### ISSUE TITLE
Using ui: true the volume icon is sometimes missing

### ISSUE THREAD

**Issue by fingalo** [AlexxIT/WebRTC#103]
I have 4 cameras c200 tapo connected to my HA. All working very well and stable, really nice!

When adding the 4'th camera the volume icon is not displayed on this camera using UI:true. If I start via my duckdns link it shows up, but with my local direct ip it's mostly missing, sometimes it works.

The reason I use ui:true is that I'm experimenting with adding presets and some additional icons, all that is working very well, but the volume icon issue also occur with the original  webrtc-camera.js.

**Comment by AlexxIT** [comment]
Volume icon shows only if volume available for current codec and video mode (WebRTC/MSE). Check docs

**Comment by fingalo** [comment]
OK, I see that camera 4 most of the time connect MSE. That explains missing volume.
I'm  just a bit confused it is working sometimes and not other times, but I really have not learned very much about the technologies yet.

And thank's for a great addon!
