### ISSUE TITLE
Error in version 2021.7 "Uncaught InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffe

### ISSUE THREAD

**Issue by Gferretta** [AlexxIT/WebRTC#104]
Hi Alex

After update to 2021.7 I have this error

![WebRTC Error AppendBuffer on SourceBuffer](https://user-images.githubusercontent.com/65413059/125116740-889a7300-e0c3-11eb-9790-701545241d48.jpg)

**Comment by lukedukeus** [comment]
I'm getting this too, any fix?

**Comment by Gferretta** [comment]
> I'm getting this too, any fix?

No

**Comment by lukedukeus** [comment]
I had this some time ago, but don't remember exactly what fixed it. I think it went away when I started using a public url

**Comment by AlexxIT** [comment]
This closed because duplicate

**Comment by thefunkygibbon** [comment]
Dupe of which case #?

**Comment by lukedukeus** [comment]
#120

**Comment by thefunkygibbon** [comment]
Different error message but ok
