### ISSUE TITLE
source URL not parsed correctly

### ISSUE THREAD

**Issue by pazz** [AlexxIT/WebRTC#106]
I am trying to stream from a rtsp url that includes a user/password, similar to some examples mentioned in issues here. The url seems to be incorrectly parsed (too many colons, see below).
The url is certainly correct as I can stream from it, for example using the custom cam integration.

Installed from HACS just now, as mentioned in the README. I'm using Chromium to test this.

![2021-07-10-193415_1738x691_scrot](https://user-images.githubusercontent.com/628455/125173239-34bc8680-e1b6-11eb-947b-0e9dd1941e93.png)

any ideas? Many thanks!

**Comment by pazz** [comment]
It seems that the port must not be mentioned in the url. Luckily I'm using a standard one. Sorry for the noise!

**Comment by AlexxIT** [comment]
Colon after port shouldn't exist
