### ISSUE TITLE
Resource not added when installed via HACS

### ISSUE THREAD

**Issue by Lyr3x** [AlexxIT/WebRTC#112]
I just installed the custom component. However, I am facing multiple issues.
1. The resource is not added at all and is not installed the expected location `/hacsfiles/webrtc` but in `custom_components`. I can't add resources lying in that folder (using HA on docker) -> Results in component missing
2. Moving the resources to the correct folder the component is found.
 
I do not see errors in log but the preview says: Restarting and if I inspect the element I can see WebSocket connection failed 404. Url is correct and working fine (also for others with this component and the same camera) 

Is that component somewhat incompatible when using docker?  Most likely i am doing something wrong here :)

**Comment by calisro** [comment]
how did you fix this?

**Comment by Lyr3x** [comment]
Was totally my fault. I only installed the Vis Hacs but not added the integration (Configuration->Integrations)

**Comment by calisro** [comment]
Actually I just figured that out as well. :)
