### ISSUE TITLE
Constant Pausing and Reconnect Request

### ISSUE THREAD

**Issue by NVader2000** [AlexxIT/WebRTC#113]
Within the last week or so WebRTC has been constantly pausing and playing and eventually disconnecting altogether asking to reconnect. I am running HA core-2021.7.4 and have tried deleting the integration and reinstalling it. Below is the basic card configuration that I am using. This is a LAN to LAN connect, so I am not hopping out and coming back in. though that should not matter, and I am pulling Low (480x360) from the source.

type: custom:webrtc-camera
url: rtsp://192.168.1.1:7447/blah,blah,blah
title: Door Bell
background: true

Please advise and thank you.

**Comment by dreitakter** [comment]
Same Problem here.
Stream plays without problems in VLC but via WebRTC constantly pausing and reconnecting.
It worked very well for two days.
I think Homeassistent made an Update but i am not sure.

**Comment by EelcoBaartse** [comment]
Same problem here, except appearing only in FullyKiosk browser on amazon fire tablet.
(settings: webrtc: false mse: true)

**Comment by crozo5** [comment]
Same problem here

**Comment by NVader2000** [comment]
Not sure if this will help anyone. I decided to wipe the tablet that I was using as an HA Panel and clean install the HA app for Android. Thus far the reconnect requests and pausing have stop. I did try resetting the HA app first before the wipe but that did not help, so I went full nuclear. I do run on the 5Ghz band for WiFi and the tablet is relatively close to the AP so I should not suspect any delays in the video streams.

I will monitor this and it I see the issue returns I will chime back in here with any findings.

**Comment by zeliant** [comment]
After updating to latest version of the component and latest version of home assistant, i'm getting the frequent reconnection issue too. I have another installation running latest HA but with version 1.4 WebRTC, it takes longer to connect but after connect it is stable

**Comment by NVader2000** [comment]
It appears that this issue has returned. Did another full wipe and this time this issue remained where before it seemed to have resolve the issue for a period of time. HA does not let me go back to version 1.4 of WebRTC, can only go back to 2.0.0.

zeliant, would mind sharing your WebRTC tile configuration? Mine is below.

type: custom:webrtc-camera
url: rtsp://192.168.1.1:7447/blahblahblahblah
title: Doorbell
background: true 
mse: false

**Comment by zeliant** [comment]
> zeliant, would mind sharing your WebRTC tile configuration? Mine is below.

My config is the same as yours.

You can go back to 1.4 by manually downloading the component and put inside custom_components folder.

I have since switched back to the latest version 2.1.1. I narrowed my problem down to local and external access. Somehow WebRTC cannot connect when i'm in local but I am able to connect farily quickly using WebRTC when i'm using external connection on my mobile. I gonna do a whole network reset of my router and all the switches to see if I can solve my problem.

**Comment by NVader2000** [comment]
I cannot seem to find WebRTC 1.4. Do you have a link?

**Comment by NVader2000** [comment]
NVM found it.

**Comment by harambe88** [comment]
FYI only: Same problem here, but only on PC client with chrome or Edge. No problem on Raspi4 where HA is running. Here the live video is perfectly stable. 

I'm running also Frigate NVR. When I stop the NVR part of Frigate (only live view remaining) everything is stable. So I think its a Frigate NVR problem.

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc

**Comment by AlexxIT** [comment]
Should be fixed in v3
