### ISSUE TITLE
custom Element does't exist

### ISSUE THREAD

**Issue by dietlman** [AlexxIT/WebRTC#117]
I have installed the plugin and everything looks fine. It is copied/installed to the proper folder. I can't see it in Lovelace integration, but when I try to use it with manual card then I get an error that the custom element doesn't exist: webrtc-camera

When I look in lovelace resources then I see this entry:
URL: /webrtc/webrtc-camera.js?v2.0.2
JavaScriptModule

Thanks for any advise.

**Comment by AlexxIT** [comment]
Have you installed the integration?

**Comment by dietlman** [comment]
Hi,

yes I have installed the integration. In the meantime I have removed HACS
and reinstalled HACS again , after that I have reinstalled WEBRTC and since
this morning it works. So you can close this case, thank you very much, The
integration works fine now.

Manfred DIETL
phone: +43 664 8497777
***@***.***
www.dietl.us
