### ISSUE TITLE
tap/hold actions support

### ISSUE THREAD

**Issue by luzik** [AlexxIT/WebRTC#119]
I do believe that WebRTC Lovelace card should support tap/hold actions

https://www.home-assistant.io/lovelace/actions/

My personal use case is to use WebRTC as "panel: true" and I switch to this tab when someone ring doorbell. I got full screen video, and want to connect tap action with door lock opening service

**Comment by direx1** [comment]
I'm after this too. I have it pop up in a new window when motion detected and would like to tap to close. Tried using with browser mod Popup but the webRTC stream takes forever to load this way.

**Comment by AlexxIT** [comment]
#77
