### ISSUE TITLE
Failed to execute 'appendBuffer' on 'SourceBuffer'

### ISSUE THREAD

**Issue by serlinGi** [AlexxIT/WebRTC#120]
given that I'm really very satisfied with this integration and that I don't have serious problems, I have often noticed errors related to the buffer in my log.  tonight more than 3,000 were counted in a few minutes.  what can it depend on?  what suggestions can you give me?  

this is my log:

Logger: frontend.js.latest.202108090
Source: components/system_log/__init__.py:190
First occurred: 8:30:36 PM (3179 occurrences)
Last logged: 8:48:15 PM

https://yyyyyyy.xxxxxxx.org/webrtc/webrtc-camera.js?v2.0.2:88:34 Uncaught InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.

Thanks

**Comment by Murder3D** [comment]
Having a similar issue:

https://github.com/AlexxIT/WebRTC/issues/164

Did you resolve this?

**Comment by redpizza69** [comment]
I'm also getting this error (16 times in the space of 3 seconds).

**Comment by AlexxIT** [comment]
@redpizza69 do you use latest version?

**Comment by redpizza69** [comment]
Thanks - just seen 2.2.0 is out with a fix for it. Instralling now.

**Comment by bobloadmire** [comment]
Did this resolve for anyone else? Updated still having the same issue.

**Comment by thefunkygibbon** [comment]
I updated and it is no longer complaining and works fine

**Comment by redpizza69** [comment]
WebRTC failed to load after upgrading to 2.2.0 in HA 2021.11. Upgraded to HA 2021.12.2 and all good.

**Comment by AlexxIT** [comment]
@bobloadmire cache

**Comment by bobloadmire** [comment]
> 

what?

**Comment by AlexxIT** [comment]
Should be fixed in v3
