### ISSUE TITLE
Problem with one EZVIZ C6CN Camera

### ISSUE THREAD

**Issue by Gferretta** [AlexxIT/WebRTC#123]
Hi Alex
I own of two similar cameras, same brand, same model.
But with one of them, no video is show and error is appears.

My config is similar in two cameras.

ffmpeg:
stream:
camera:
  - platform: ffmpeg
    name: Comedor
    input: !secret WebRTC_CAM1
  - platform: ffmpeg
    name: Dormitorio
    input: !secret WebRTC_CAM2

and config of cameras is:
WebRTC_CAM1/2: rtsp://user:passw@ip:554/H264

Any idea?
Regards

![Camera C6CN](https://user-images.githubusercontent.com/65413059/131177719-265b5f8f-b310-4b00-b385-829c94d5342d.jpg)

**Comment by AlexxIT** [comment]
HVC1 is H265 - unsupported

**Comment by Gferretta** [comment]
Hi
I leave the solution for those who have the same problem.
Using the **"EzViz Studio" software** and setting it to **"advanced settings"**, you can modify the codec used by the camera and set it to _H264_.
Thanks and Regards.

https://support.ezvizlife.com/faq/171

**Comment by brunokelo** [comment]
> HVC1 is H265 - unsupported

any predictions to support?
thanks.

**Comment by AlexxIT** [comment]
You can ask Google and other browser developers...
