### ISSUE TITLE
Foscon VD1 Doorbell Camera

### ISSUE THREAD

**Issue by salopette** [AlexxIT/WebRTC#124]
Hello Alex, I have Foscon VD1 Doorbell, this has the rtsp port 88, unfortunately I can't get the stream to run.

rtsp://user:pass@192.168.178.44:88/videoMain

In VLC the video works

https://www.foscam.com/faqs/view.html?id=81

**Comment by salopette** [comment]
![sshot-4](https://user-images.githubusercontent.com/32480002/131539769-91266a98-9d6b-4e98-a9f9-81d3f4f3dbb0.jpg)

**Comment by AlexxIT** [comment]
HVC1 = H.265 - unsupported by WebRTC technology
