### ISSUE TITLE
No rounded corners for custome plugin on IOS

### ISSUE THREAD

**Issue by CloudWolf99** [AlexxIT/WebRTC#126]
I'm using my Ipad as wallboard to stream the cameras. But on ios i can't see rounded corners for the webrtc plugin on lovelace. When i open the same site on my pc browser i can see the rounded corners.

![20210829_161601000_iOS](https://user-images.githubusercontent.com/63864674/131723432-857875c6-a493-4d3e-b334-86c6d13a84fa.jpg)

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/WebRTC/pull/8
