### ISSUE TITLE
Video in Firefox not working

### ISSUE THREAD

**Issue by devbis** [AlexxIT/WebRTC#13]
You've mentioned that FF is not supported due to the limitations of the browser.
On the other hand, I cannot say that WebRTC is completely broken in FF.
Other apps, e.g. jit.si video conference tool, works perfectly in this browser.

What is the problem with the implementation of webrtc in FF? Is there any way to add limited support for it?

**Comment by AlexxIT** [comment]
Check this
https://github.com/AlexxIT/WebRTC/releases/tag/v1.0.5

**Comment by devbis** [comment]
@AlexxIT Why don't you support both directions depending on the userAgent?

```js
const direction = (window.navigator.userAgent.toLowerCase().indexOf('firefox') > -1) ? 'sendrecv': 'recvonly';
```

**Comment by AlexxIT** [comment]
Ok, I will fix as you suggest
