### ISSUE TITLE
Permission Denied on rtsp2webrtc_v4_armv7

### ISSUE THREAD

**Issue by thiagobucca** [AlexxIT/WebRTC#131]
Hi, i'm trying to use this component in it's latest version, installed from HACS, but i'm getting Permission Denied error and can't get the stream to work.

My Setup:

HA Docker Container running on a Raspberry Pi 4 Model B
I'm testing the readme bunny stream on lovelace, running on my local network, not external access.

Any clues on why i'm getting Permission Denied error?

`2021-09-11 23:00:47 ERROR (webrtc) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/config/custom_components/webrtc/utils.py", line 172, in run
    self.process = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/config/rtsp2webrtc_v4_armv7'`

**Comment by MrQYX** [comment]
how to solve it

**Comment by thiagobucca** [comment]
@AlexxIT i'm afraid that's not the case, here's the output of lscpu

pi@rasp:~ $ lscpu
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               3
Model name:          Cortex-A72
Stepping:            r0p3
CPU max MHz:         1500.0000
CPU min MHz:         600.0000
BogoMIPS:            108.00
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32

**Comment by thiagobucca** [comment]
hey guys, just figured it out, nothing wrong with the integration, my configuration was on a mount that didn't got permissions to execute binaries, when i move it and gave the necessary permissions, everything worked like a charm. Closing this now.
