### ISSUE TITLE
Improvement more entities available in the frame as the picture glace

### ISSUE THREAD

**Issue by MiAutomations** [AlexxIT/WebRTC#132]
Hello

Sorry this is not a issue or a bug is a question or a improvement suggestion. 

Once the new IP camera device have more and more information/entities  available like motion sensores, etc ...

Can we have a possibility to integrate like the picture glace the other entities in this lovelace card WebRTC? 

![image](https://user-images.githubusercontent.com/47602733/134250116-b5946af4-a733-4b6a-aa3d-a1d1f21a1747.png)

Thank you for your work and support, best regards

**Comment by MiAutomations** [comment]
Any news about this ?

**Comment by AlexxIT** [comment]
Check my new project. It support default lovelace card
https://github.com/AlexxIT/go2rtc
