### ISSUE TITLE
Custom element does not exist - Tried all methods

### ISSUE THREAD

**Issue by Tokn59** [AlexxIT/WebRTC#134]
Hi, I'd love to use this add-on but can't get it to work. I have several custom components running without issues but this one seems hard to crack for me. I first installed it using the HACS method and then also using the manual method. In HACS - Integrations it does show up but it does not show up in Lovelace - Resources. I have the folder webrtc in /config/www/community/webrtc as well.

Any idea what I might try next ? Thanks for your support !

**Comment by SvenHamers** [comment]
Same issue since core-2021.9.7

**Comment by FrnchFrgg** [comment]
You need to also add the `WebRTC` integration to home assistant via the configuration page.

**Comment by Tokn59** [comment]
Correct ! Now it works. Thank You !!!!
