### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Tyrian81** [AlexxIT/WebRTC#135]
When trying to connect via custom:frigate-card webrtc live view it says ERROR: WebRTC server not available, it worked flawlessly before I had a power outage and all devices got rebooted...

Removed hacs integration and webRTC integration , reinstalled both now this :
![frigatecard](https://user-images.githubusercontent.com/31477524/136509118-213e21c2-22da-4bf3-bce6-3d2b1da6c7e2.jpg)

**Comment by benedikt-bartscher** [comment]
check your /etc/hosts for localhost and try "ping localhost"

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc

**Comment by AlexxIT** [comment]
Closed because no response
