### ISSUE TITLE
NotSupportedError

### ISSUE THREAD

**Issue by airens** [AlexxIT/WebRTC#137]
Hello, I can't get my Imou Ranger 2-a camera working with your integration. The error is:

``` 
ERROR: NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="hvc1.014000") is unsupported
```

Can I try some options to make it work?

**Comment by Nakebod** [comment]
Was searching for that HVC1 message, found another issue where the author said that HVC isn't supported (yet) in WebRTC.

For my IMOU G26 I can use: rtsp://<user:pass>@<IP>/cam/realmonitor?channel=1&subtype=1
If you are now using &subtype=0, and your device supports it, try &subtype=1. It is much lower quality, but at least it does work.

**Comment by airens** [comment]
> Was searching for that HVC1 message, found another issue where the author said that HVC isn't supported (yet) in WebRTC.
> 
> For my IMOU G26 I can use: rtsp://user:pass@/cam/realmonitor?channel=1&subtype=1 If you are now using &subtype=0, and your device supports it, try &subtype=1. It is much lower quality, but at least it does work.

Yeah, that's worked for me to! The quality is awful, but certainly better, than nothing, thanks!
