### ISSUE TITLE
iOS cant view livestream

### ISSUE THREAD

**Issue by dpomnean** [AlexxIT/WebRTC#139]
Not able to view livestream through iOS, it stops at the 'starting connection (WebRTC)' phase and never loads. I also get this error when following the logs.

```
2021-10-11 14:30:09 ERROR (MainThread) [frontend.js.latest.202106030] homeurl.home.com/webrtc/webrtc-camera.js:675:22 NotSupportedError: Cannot define multiple custom elements with the same tag name
```

This only happens on iOS through the mobile app and via browser. I do not have this issue on Android or web browser through a laptop.

**Comment by blvermeu** [comment]
Same issue here,  iphone 12, with latest IOS (15) and fully up to date.
'starting connection (WebRTC)' icon keeps on the screen, both on chrome (ios) and the native HA app.

thanks!

**Comment by fouram** [comment]
Confirmed here on iOS 15.1 and iPhone 13 Pro. Both wifi and cellular. Was having this issue as well on an older device before upgrading (iOS 12, iPhone 6)

**Comment by shablagu** [comment]
having the same issue on my ios devices on LAN and WAN, using either the home assistant app or safari. No issue on laptop or android devices. Running home assistant core in a docker.

**Comment by dpomnean** [comment]
Upgraded home assistant to 2021.11.5. Still same issue

**Comment by dpomnean** [comment]
My issue was the VPN that was enabled on my iphone (it's a work phone). Once I disabled that, it started working. Not sure if it was a combination of my Hass update or a combination of the two.

I will close this.
