### ISSUE TITLE
my hass run in docker occur this problem

### ISSUE THREAD

**Issue by MrQYX** [AlexxIT/WebRTC#141]
```
2021-10-13 11:43:34 ERROR (webrtc) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/config/custom_components/webrtc/utils.py", line 172, in run
self.process = subprocess.Popen(
File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/config/rtsp2webrtc_v5_amd64'
```

**Comment by andriy7811** [comment]
hi - I do have exactly same error 
PermissionError: [Errno 13] Permission denied: '/config/rtsp2webrtc_v5_amd64'

Also running Hassio on docker on Debian 10 mini pc

Any lead to solve this?

**Comment by MrQYX** [comment]
I haven't found a solution yet

**Comment by MrQYX** [comment]
> hi - I do have exactly same error PermissionError: [Errno 13] Permission denied: '/config/rtsp2webrtc_v5_amd64'
> 
> Also running Hassio on docker on Debian 10 mini pc
> 
> Any lead to solve this?

I haven't found a solution yet

**Comment by thiagobucca** [comment]
Check this: https://github.com/AlexxIT/WebRTC/issues/131 

Maybe your problem is the same, make sure you can run binary rtsp2webrtc_v5_amd64 through terminal, if you have "permission denied" error, maybe your mount point doesn't have permission to run binaries.

To clarify:

When my usb hdd that stores homeassistant config was on /mnt/myhdd/homeassistant/config i get Permission Denied error

When i moved to /home/myuser/homeassistant/config the problem was solved.

hope it helps.

**Comment by andriy7811** [comment]
> Check this: #131
> 
> Maybe your problem is the same, make sure you can run binary rtsp2webrtc_v5_amd64 through terminal, if you have "permission denied" error, maybe your mount point doesn't have permission to run binaries.
> 
> To clarify:
> 
> When my usb hdd that stores homeassistant config was mounted on /mnt/myhdd/homeassistant/config i get Permission Denied error
> 
> When i moved to /home/myuser/homeassistant/config the problem was solved.
> 
> hope it helps.

Hi this was really helpful. 

It was indeed a permission issue and running 
sudo chmod -R 0755 <folder including rtso2webrtc binary> 
fixed the problem after restarting HA

Thanks a lot

**Comment by MrQYX** [comment]
> Check this: #131
> 
> Maybe your problem is the same, make sure you can run binary rtsp2webrtc_v5_amd64 through terminal, if you have "permission denied" error, maybe your mount point doesn't have permission to run binaries.
> 
> To clarify:
> 
> When my usb hdd that stores homeassistant config was mounted on /mnt/myhdd/homeassistant/config i get Permission Denied error
> 
> When i moved to /home/myuser/homeassistant/config the problem was solved.
> 
> hope it helps.

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       43 bits physical, 48 bits virtual
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           4
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6

I run docker on my x86 Linux. Can't I use this component? Must it be an arm device?

**Comment by AlexxIT** [comment]
Component support different architectures

**Comment by thiagobucca** [comment]
> 
> 
> > Check this: #131
> > Maybe your problem is the same, make sure you can run binary rtsp2webrtc_v5_amd64 through terminal, if you have "permission denied" error, maybe your mount point doesn't have permission to run binaries.
> > To clarify:
> > When my usb hdd that stores homeassistant config was mounted on /mnt/myhdd/homeassistant/config i get Permission Denied error
> > When i moved to /home/myuser/homeassistant/config the problem was solved.
> > hope it helps.
> 
> Architecture: x86_64 CPU op-mode(s): 32-bit, 64-bit Byte Order: Little Endian Address sizes: 43 bits physical, 48 bits virtual CPU(s): 4 On-line CPU(s) list: 0-3 Thread(s) per core: 1 Core(s) per socket: 1 Socket(s): 4 NUMA node(s): 1 Vendor ID: GenuineIntel CPU family: 6
> 
> I have modified the permissions, but the component still doesn't work I run docker on my x86 Linux. Can't I use this component? Must it be an arm device?

What happens if you run ./rtsp2webrtc_v5_amd64 directly on bash?

**Comment by MrQYX** [comment]
> > > Check this: #131
> > > Maybe your problem is the same, make sure you can run binary rtsp2webrtc_v5_amd64 through terminal, if you have "permission denied" error, maybe your mount point doesn't have permission to run binaries.
> > > To clarify:
> > > When my usb hdd that stores homeassistant config was mounted on /mnt/myhdd/homeassistant/config i get Permission Denied error
> > > When i moved to /home/myuser/homeassistant/config the problem was solved.
> > > hope it helps.
> > 
> > 
> > Architecture: x86_64 CPU op-mode(s): 32-bit, 64-bit Byte Order: Little Endian Address sizes: 43 bits physical, 48 bits virtual CPU(s): 4 On-line CPU(s) list: 0-3 Thread(s) per core: 1 Core(s) per socket: 1 Socket(s): 4 NUMA node(s): 1 Vendor ID: GenuineIntel CPU family: 6
> > I have modified the permissions, but the component still doesn't work I run docker on my x86 Linux. Can't I use this component? Must it be an arm device?
> 
> What happens if you run ./rtsp2webrtc_v5_amd64 directly on bash?

You woke me up! I found the problem. The hard disk I mounted in Linux does not have the permission to execute files. I modified / etc / fstab, changed noexec to exec, and the problem was solved! Thank you for your help!
