### ISSUE TITLE
Does this integration support "Codec: H264 - MPEG-4 AVC (part 10) (h264)"?

### ISSUE THREAD

**Issue by TomHart** [AlexxIT/WebRTC#143]
I'm trying to add a feed for a RTSP stream, which when I view in VLC gives me the codec of "Codec: H264 - MPEG-4 AVC (part 10) (h264)" but when I add a card for the stream, it says unsupportederror, for type "video/mp4, codecs: avc1.000000", and just checking if that should be supported or not

**Comment by sneakythr0ws** [comment]
+1

**Comment by AlexxIT** [comment]
Maybe the same problem #155

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc

**Comment by AlexxIT** [comment]
Closed because no response
