### ISSUE TITLE
Sonoff cam displays 1970-01-01 as date

### ISSUE THREAD

**Issue by Stooovie** [AlexxIT/WebRTC#146]
Any idea why my Sonoff GK-200MP2-B displays 1970-01-01 (and wrong time) as date in the watermark? It was fine with the default eWelink app. Thanks! HA 2021.10.6 with WebRTC addon 2.1.1, Sonoff camera fw 27620201103, used with SonoffLAN 2.4.6. 

Thanks.

**Comment by AlexxIT** [comment]
This is camera software problem. You can check stream in VLC
