### ISSUE TITLE
Ошибка при выделении порта сервису (+1 к self.port)

### ISSUE THREAD

**Issue by insound** [AlexxIT/WebRTC#148]
Тк, например nginx и прочие веб серверы, могут грузиться дольше (или перезагружаться, после инициализации HA), то решение использовать self.port + 1 не лучшее, тк может занять сервисные порты 80**, которые необходимы по дефолту php-fpm, nginx и другие возможные причины. Предлагаю все же захардкодить начало отсчета хотя бы с 8200, и потому уже плюсовать в случае занятости.

**Comment by AlexxIT** [comment]
Fixed in new project. You can select any port via YAML config
https://github.com/AlexxIT/go2rtc
