### ISSUE TITLE
QuotaExceededError error flooding log but stream ok 

### ISSUE THREAD

**Issue by GGI1982** [AlexxIT/WebRTC#149]
Hello, I have an error repeating **each second**: 

`webrtc/webrtc-camera.js?v2.0.2:88:34 Uncaught QuotaExceededError: Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.
`

But your addon is f***g great since it's the only solution I found that allows me to have a very high response time on my Foscam R2M. I really want to thank you for your hard work ! 👍 🥇  

It seeems to be linked to high resolution stream and someone might have found a workaround  : 

https://github.com/videojs/videojs-contrib-hls/pull/1242

Maybe you could try the same approach ...

**Comment by GaryOkie** [comment]
just encountered the same error.    getting about 10 of these errors every second.

Just a single camera using webrtc (a 2K Dahua), in a small lovelace window that was live with no delay while errors occurring.

Restarted HASS, and all is well for now.

Guess if it repeats, I'll have to change logging level for webrtc to critical to keep log file reasonable unless someone knows of another fix.

**Comment by bobloadmire** [comment]
yes I have this same issue streaming from my Wyze cams with the RTSP firmware. It's so bad, if I watch 4 cams at once it will actually bork my network until I restart HA. Viewing the cams from my PC everything is fine, but from within HA it gets fuky very quickly.

**Comment by AlexxIT** [comment]
Should be fixed in v3

**Comment by GGI1982** [comment]
Came late but ok ....
