### ISSUE TITLE
How to correctly add resources?

### ISSUE THREAD

**Issue by Klagio** [AlexxIT/WebRTC#154]
I have the file
ui-lovelace.yaml

How to add resources? Like below?
```

  - url: /custom_components/webrtc/www/webrtc-camera.js
    type: module
```

my HACS installation installed  webrtc-camera.js   under 

X:\custom_components\webrtc\www

but I receive custom element doesn't exist error

this my lovelace configuration
```

      - id: 7c608881aeasdds7f4f8198e0953dc7asdasdf83541  # Automatically created id
        type: custom:webrtc-camera
        url: rtsp://admin:xxxx@192.168.1.42:554/Streaming/Channels/101
```

**Comment by sygys** [comment]
im having the same question. Its nice the documentation tells me i need to add something like:

type: 'custom:webrtc-camera'
url: 'rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov'

But where? Why are all these integrations written by people so minimal explained. not everyone reading this stuff is a rocket scientist. Please explain step by step where to add which code...

**Comment by dandanarsk** [comment]
HACS - Integrations - Explore and download repositories - search webrtc - install master branch
restart home assistant and check you have the webrtc card on HACS integrations
Configuration - Integrations - add integration - search webrtc - install
Restart, the card webrtc should show in integration (main home assistant)
Edit dashboard - click on the 3 dots menu on the top right, make sure the webrtc resources are installed in resources menu
Back to edit dashboard - add card - at the bottom you should have the webrtc card where you set the name and rtsp feed

**Comment by jamestowers** [comment]
I'm also struggling with this, every item apart from the list above is OK apart from the last - there's no webrtc card when adding a card to the dashboard

**Comment by AlexxIT** [comment]
Read this #260
