### ISSUE TITLE
NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource'

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/WebRTC#155]
I'm receiving this error very oftenly:

```
NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4;codecs="avc1.000000") is unsupported.
```

![image](https://user-images.githubusercontent.com/29582865/140663992-b504d40f-69c9-49f7-b417-9725e565410a.png)

But after a minute it starts working normally:

![image](https://user-images.githubusercontent.com/29582865/140664077-1073d6b7-5ccd-44bb-892d-76934f02ee95.png)

So, I wonder if there is anything I can do to solve this issue.

This is the media information about the RTSP link I'm using in WebRTC card:
![image](https://user-images.githubusercontent.com/29582865/140664119-4b3e7be7-c192-4128-88c4-d7bcdb6461a6.png)

**Comment by babelhoo** [comment]
Same happens to me only with 1 (of 3) cameras, sometimes it shows the same error, others it works with no issues.

**Comment by lvluat** [comment]
I got the same error with both 2 Ezviz C6N cameras. The error shown for few seconds and then the cameras work normally.
![image](https://user-images.githubusercontent.com/9134827/141073330-e749fbda-fe02-434f-9e2d-72b97b68f9a2.png)

**Comment by AlexxIT** [comment]
Disable MSE as described in readme

**Comment by felipecrs** [comment]
But in this report I was always using the local network, not external. Should not WebRTC always use webrtc rather than MSE in that case?

If I disable MSE, then it won't work outside of my home.

**Comment by AlexxIT** [comment]
Component starts MSE and WebRTC simultaneously. If second can stars - MSE will stop

**Comment by felipecrs** [comment]
I ended up by disabling MSE with:

```yaml
webrtc: true
mse: false
```

And using another technique for allowing webrtc outside of my network: https://github.com/AlexxIT/WebRTC/issues/151#issuecomment-997405236

**Comment by DIYtechie** [comment]
Had the same issue. Disabling mse also worked for me. Thanks.

**Comment by dkitz** [comment]
I have exactly the same problem as mention in this threat. Have 2 older Foscam cams, they work fine, but the Foscam D4Z, has most of the times errors. 
NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4;codecs="avc1.000000") is unsupported.
Disabling MSE did not the trick.

Hope this will be fixed, because the WebRTC normaly works great!!

**Comment by rbray89** [comment]
> I have exactly the same problem as mention in this threat. Have 2 older Foscam cams, they work fine, but the Foscam D4Z, has most of the times errors. NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4;codecs="avc1.000000") is unsupported. Disabling MSE did not the trick.
> 
> Hope this will be fixed, because the WebRTC normaly works great!!

@dkitz disable NAA. I had the same issue, and it seems their "Network adaptive something" was the culprit. You can do this on their desktop software.

**Comment by RIKWEBB** [comment]
> I got the same error with both 2 Ezviz C6N cameras. The error shown for few seconds and then the cameras work normally. ![image](https://user-images.githubusercontent.com/9134827/141073330-e749fbda-fe02-434f-9e2d-72b97b68f9a2.png)

Try disabling 'Image Encryption' in the Ezviz App for your camera's --- seemed to work for me!

**Comment by cvladan** [comment]
> Disable MSE as described in readme

Where is that described? Searching for half an hour!

**Comment by AlexxIT** [comment]
Readme for old version (latest release):

https://github.com/AlexxIT/WebRTC/tree/v2.3.1
