### ISSUE TITLE
Direct camera connection ?

### ISSUE THREAD

**Issue by r00nster** [AlexxIT/WebRTC#158]
This isn’t an issue but more a question, can the card be configured so the device displaying it connects directly to the camera to get the stream and not via HA?

I setup the card in Lovelace to test but when in view it from a tablet the HA IP address connecting to the camera and not the IP of the tablet. I know this also as it wouldn’t work till I allow the HA IP to connect to the camera. HA seems to proxy the streams.

Is there somehow a way to config direct connections from the tablet ??

**Comment by AlexxIT** [comment]
Browser can't handle RTSP stream directly. You can you VLC on your tablet
