### ISSUE TITLE
Custom element doesn’t exist: ‘webrtc-camera

### ISSUE THREAD

**Issue by serjefazo2010** [AlexxIT/WebRTC#159]
I got “Custom element doesn’t exist: ‘webrtc-camera’” on lovelace dashboard. 

Installed from HASC and verified that the webrtc-camera.js file is in custom_component.

I have rebooted multiple times and reinstalled multiple times without success.

Intel NUC
HomeAssistant OS 6.6
supervisor-2021 10.8
core-2021.11.2
CPU x86_64

**Comment by NapalmCandy** [comment]
I have exact same problem. Don't know why it is marked as duplicate, because the other topic it is iOS related

Any solution?

**Comment by AlexxIT** [comment]
Because there are already 10 (ten) issues about this problem

**Comment by NapalmCandy** [comment]
I found the solution, simply reset cache.

There are other HACS Integrations that ask to clear cache after installation, maybe would be a good idea to do it here also
