### ISSUE TITLE
Cast doesn't work at all

### ISSUE THREAD

**Issue by PilaScat** [AlexxIT/WebRTC#161]
Trying to cast on Nest Hub 4 webrtc cameras using ha cast and dash cast, it doesn't work neither on the hub neither on android tv, it start but soon crashes

**Comment by PilaScat** [comment]
?

**Comment by AlexxIT** [comment]
If you run a lot of cameras on Nest, it really crashes. Very bad hardware. Can't be fixed.
The same problem on my Nest.
