### ISSUE TITLE
Revisiting - Custom element doesn't exist: webrtc-camera

### ISSUE THREAD

**Issue by boctok** [AlexxIT/WebRTC#162]
I am having issues with a newly setup integration. I do have the integration installed from the Configuration page. I do have debug logging set. I do not see any error messages in the logs, but I am still getting "Custom element doesn't exist: webrtc-camera" messages when I try to add a card.

This is the yaml:
`type: custom:webrtc-camera
 entity: camera.doorbell`

and attached is what I see on the dashboard after saving the card.
![Web-RTC](https://user-images.githubusercontent.com/5306739/142478913-44f4f92a-a937-4adb-9a96-d0321b49c539.png)

I reinstalled a couple of times and eventually achieved a little progress, I think. It now shows a blank video window with the message "ERROR: Can;t get URL for camera"

**Comment by Yonny24** [comment]
Same issue here. I thought I could use just the entity.
Possibly need the url and entire rtsp config?

**Comment by boctok** [comment]
I can get it to work using the entire rtsp url, but unfortunately, in setting things up I found that not all my cameras support rtsp.
