### ISSUE TITLE
No audio in Iphone

### ISSUE THREAD

**Issue by va77** [AlexxIT/WebRTC#163]
Hi.
I faced with rather strange behaviour, I have Tapo C200 camera which I successfuly added to HA via current integration.
Via PC (Win, Chrome) I can see video and also hear audio.
Via Iphone HA app I see mute/unmute pic, but no sound at all (same for safari browser). At the same time, if I connect earphones (bluetooth headset), audio become available.
What is that? Audio codec which doesn't support by Iphone, but supported by my headset?

upd.
Wife’s iPhone (also XR) have audio from camera. I found only one difference - ios 14.2 and 14.7 on my phone.
Any idea?

**Comment by AlexxIT** [comment]
Check status icon on both phones https://github.com/AlexxIT/WebRTC#status-icons
Check if you using HA app or Safari in both phones

**Comment by va77** [comment]
> Check status icon on both phones https://github.com/AlexxIT/WebRTC#status-icons Check if you using HA app or Safari in both phones

Hi AlexxIT.

Icon is "stream is played with WebRTC" in APP and safari too.
I updated ios to latest 15.1, audio appeared, but it always breaks, like too loud, or poor network connection. At the same time via bluetooth headset audio plays as it should be.

**Comment by danieldabate** [comment]
Same issue here. 

Sound is ok with Airpods but broken when played through the phone (iPhone XR here with iOS 15.2.1).

Have you solved it yet?

**Comment by acoffman87** [comment]
Hello,

I am also experiencing the same issue, audio is distorted when coming through the iPhone on safari, the HA app but clear on a Bluetooth connection

is there any updates?

**Comment by Hisokaah** [comment]
Hello,

Same issue with my iPhone X and my iPhone XR.

Is there any updates ?

Thank you in advance.

**Comment by johnfredrik** [comment]
I also have the same issue on IPhone 11 pro, IOS 15.3.1

**Comment by danieldabate** [comment]
This issue is fixed for me since iOS 15.4.1 (including the latest iOS 15.5). Seems like it was an iOS issue, so I'd close this issue if others confirm the same.

**Comment by johnfredrik** [comment]
This issue is also fixed for me

**Comment by AlexxIT** [comment]
Looks like fixed by Apple
