### ISSUE TITLE
No Audio via HA Android App

### ISSUE THREAD

**Issue by EmAnzi3** [AlexxIT/WebRTC#165]
Hello,
I successfully integrated my Reolink E1 Pro in HA and via browser everything works fine, however, via HA Android app audio seems to be deactivated, no option to turn it on. Status icon is "stream is played with WebRTC".

**Comment by trabogano** [comment]
Hi, unfortunately same here. :(
There is something that we can do for resolve?

**Comment by niahane** [comment]
Hello, I have the same configuration, if I open home assistant from chrome for android or from its companion app the result does not change the audio does not work. If I open it from a PC browser the audio works.

**Comment by rbray89** [comment]
Audio is only supported if the audio codec from the RTSP stream is OPUS or G.711 PCM. This is a limitation of the WebRTC spec https://developer.mozilla.org/en-US/docs/Web/Media/Formats/WebRTC_codecs

**Comment by AlexxIT** [comment]
Check my new project. It can handle any codec situation with your help...
https://github.com/AlexxIT/go2rtc
