### ISSUE TITLE
Cant get URL for ... error

### ISSUE THREAD

**Issue by pergolafabio** [AlexxIT/WebRTC#166]
Hey, i was trying out this on my foscam C1 model

but i receive error below on lovelace?

        - type: custom:webrtc-camera
          entity: 'rtsp://admin:xxxx@192.168.0.43:93/videoMain'

(port 553 is changed to 93 , this is normal) , above url tested in VLC works

![image](https://user-images.githubusercontent.com/43251136/142848933-de46d6b4-2996-4efb-90b2-bd0c462d68d4.png)

![image](https://user-images.githubusercontent.com/43251136/142849088-a27daaa2-637e-453a-b65d-f498f945f158.png)

**Comment by Barma-lej** [comment]
Change `entity:` to `url:`

**Comment by pergolafabio** [comment]
omg, terribly sorry
