### ISSUE TITLE
Small request ability to set title

### ISSUE THREAD

**Issue by mcc05** [AlexxIT/WebRTC#17]
Hi brilliant component!!, I have a small feature request could you allow setting of the lovelace title please if specified

I'm doing this in the code card.header = this.config.title;  to allow naming of each camera feed panel I have.

Thank you again for a great component.

**Comment by AlexxIT** [comment]
It looks very ugly. Need to make custom design for video title.

**Comment by AlexxIT** [comment]
Added to latest release
