### ISSUE TITLE
Add support for RTSPS 

### ISSUE THREAD

**Issue by Haloooch** [AlexxIT/WebRTC#171]
Unifi seem to be removing the RTPS feed from their Unifi Protect solution, instead forcing the use of RTSPS feeds. This kind of feed doesn't appear to be supported in the current WebRTC component. Not sure if that's a functionality or technical limitation?

If functionality would be great for this to be added so I can go back to having near instant feeds on Lovelace from these cameras.

**Comment by AlexxIT** [comment]
Added in latest version
https://github.com/AlexxIT/WebRTC/releases/tag/v2.3.0
