### ISSUE TITLE
[FEATURE REQUEST] Add button like picture glance

### ISSUE THREAD

**Issue by PilaScat** [AlexxIT/WebRTC#172]
![image](https://user-images.githubusercontent.com/12989749/143920319-165f85fe-8cce-43a7-9970-72b02280dda9.png)
Very useful for opening gates, switch lights or tts

**Comment by andiukas** [comment]
Try
type: entities
entities:
  - type: custom:webrtc-camera
    entity: camera.nvt_mainstream
  - type: buttons
    entities:
      - entity: cript.1622924076355
        icon: mdi:arrow-left-drop-circle-outline
        tap_action:
          action: toggle
      - entity: script.1622967856260
        icon: mdi:arrow-right-drop-circle-outline
        tap_action:
          action: toggle

**Comment by PilaScat** [comment]
Thanks, but was better directly in webrtc ui

**Comment by AlexxIT** [comment]
You can check this in latest master version:
https://github.com/AlexxIT/WebRTC/pull/169

**Comment by AlexxIT** [comment]
No. Only in master version

**Comment by andiukas** [comment]
Not works

**Comment by dmamontov** [comment]
> Not works
> 021-12-08 07:50:45 ERROR (MainThread) [frontend.js.latest.202112060] https://xxxxxxxxxxxxxxxxxxxxxxxxxx:8123/webrtc/webrtc-camera.js?v2.0.2:332:22 Uncaught TypeError: Cannot read properties of undefined (reading 'callService')

Settings and file content please. So what version of hass do you have?

**Comment by andiukas** [comment]
> > Not works
> > 021-12-08 07:50:45 ERROR (MainThread) [frontend.js.latest.202112060] https://xxxxxxxxxxxxxxxxxxxxxxxxxx:8123/webrtc/webrtc-camera.js?v2.0.2:332:22 Uncaught TypeError: Cannot read properties of undefined (reading 'callService')
> 
> Settings and file content please. So what version of hass do you have?

Everything is fine, I didn't add a feature: ui: true

**Comment by dmamontov** [comment]
through card-mod you can do

example:
```
type: custom:webrtc-camera
style: |
  .shortcuts > .shortcut-0 {
    color: {% if is_state('switch.xiaomi_dafang_record', 'on') %}
              #df4d1d
           {% else %}
              white
           {% endif %};
    animation: {% if is_state('switch.xiaomi_dafang_record', 'on') %}
                  1s ease 0s infinite normal none running pulse;
               {% else %}
                  none
               {% endif %};
  }
  .shortcuts > .shortcut-1 {
    color: {% if is_state('switch.dafang_night_mode_2', 'on') %}
              var(--paper-item-icon-active-color, #fdd835)
           {% else %}
              white
           {% endif %};
  }
entity: camera.dafang3
ui: true
shortcuts:
  - name: Запись
    icon: mdi:record-circle-outline
    service: switch.toggle
    service_data:
      entity_id: switch.xiaomi_dafang_record
  - name: Ночной режим
    icon: mdi:theme-light-dark
    service: switch.toggle
    service_data:
      entity_id: switch.dafang_night_mode_2
  - name: Перезагрузить
    icon: mdi:refresh-circle
    service: switch.toggle
    service_data:
      entity_id: switch.xiaomi_dafang_power

```

**Comment by PilaScat** [comment]
Thanks

**Comment by mash2k3** [comment]
Does the shortcuts also support entity states where icons change color for example the cameras motion?

**Comment by dmamontov** [comment]
> Does the shortcuts also support entity states where icons change color for example the cameras motion?

o wrote above. you can use card_mode

**Comment by PilaScat** [comment]
But with that I can't see other status, like images for plex or light color

**Comment by mash2k3** [comment]
Thought it would be easier and cleaner if it was built in since the function already exists in HA instead of adding custom CSS

**Comment by nkgiovannivl** [comment]
Hi, I'm trying to add my presets ONVIF, but how can chage position (bottom center) and text (white) and background (black) to my shortcuts? Thanks!

![image](https://user-images.githubusercontent.com/48342344/147687580-399b8ac2-82a4-4be1-bf77-c1cb5edea832.png)

**Comment by dmamontov** [comment]
> Hi, I'm trying to add my presets ONVIF, but how can chage position (bottom center) and text (white) and background (black) to my shortcuts? Thanks!

first, you need the version from the wizard. secondly, the card-mod component is required.

**Comment by nkgiovannivl** [comment]
> > Hi, I'm trying to add my presets ONVIF, but how can chage position (bottom center) and text (white) and background (black) to my shortcuts? Thanks!
> 
> first, you need the version from the wizard. secondly, the card-mod component is required.

Thanks! I did not know about card mod!

![image](https://user-images.githubusercontent.com/48342344/147714853-13b79679-f50a-403b-bb87-e1f9cdf4567f.png)

**Comment by fgonza2** [comment]
can you do somehow picture-elements, so you have an overlay of say a temperature sensor icon and value on the camera image?

**Comment by Liam-Whiteside** [comment]
Is there any way to put sensor icons overlayed on the webrtc-camera card eg change an icon (ideally the icon and colour) when there's motion detected?

I haven't been able to get things like this to work:

```
title: Drive Cam via WebRTC
type: custom:webrtc-camera
entity: camera.drive_camera
muted: true
ui: true
shortcuts:
  top: 25
  left: 5
  services:
    - name: Motion
      icon: >
        {% if is_state('binary_sensor.drive_camera_motion', 'Detected') return
        'mdi:motion-sensor'; else return 'mdi:motion-sensor-off'; %}
```

**Comment by dmamontov** [comment]
@Liam-Whiteside I think you can solve it with template sensor

**Comment by AlexxIT** [comment]
`style` settings supported from v3
