### ISSUE TITLE
After migration to SSD no video on Android tablets anymore

### ISSUE THREAD

**Issue by skeal** [AlexxIT/WebRTC#173]
Hello!

thanks for this addon.

I used it with the newest Home Assistant version for a few weeks without problems.
No I moved my installation to SSD (New install, backup restore).

After that only on my Windows PC with Chrome the RTSP streams are shown. Not on any of the Android tablets anymore. Only sometimes one or two frames are shown from several cameras and then it show the static picture again.

It happened exactly with the move so it's no general problem. I also reinstalled the HACS and integration without success.

This now is in the log:

```
Logger: frontend.js.latest.202111090
Source: components/system_log/__init__.py:190
First occurred: 08:49:46 (149 occurrences)
Last logged: 08:49:54

http://192.168.10.14:8123/webrtc/webrtc-camera.js?v2.0.2:88:34 Uncaught InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.
```

Any ideas?

**Comment by AlexxIT** [comment]
Do you have problems with latest version?
https://github.com/AlexxIT/WebRTC/releases/tag/v2.3.0

**Comment by AlexxIT** [comment]
No answer...
