### ISSUE TITLE
error installing integration 

### ISSUE THREAD

**Issue by esnet146** [AlexxIT/WebRTC#18]
GUI. Configuration > Integration > Add Integration > WebRTC Camera.
![rtc](https://user-images.githubusercontent.com/64173457/115017790-b8205180-9ebf-11eb-9a65-9d3dcacc9036.PNG)
mouse click  end
![rtc2](https://user-images.githubusercontent.com/64173457/115017955-edc53a80-9ebf-11eb-9a44-fbe7d5c2fce2.PNG)
core-2021.4.4
What is missing?

**Comment by AlexxIT** [comment]
Server architecture doesn't supported. Windows or Linux 32 bit?

**Comment by esnet146** [comment]
linux 32. Thank you update ver 1.1.1! fixed.

**Comment by sgrzys** [comment]
I've got the same problem on:
![image](https://user-images.githubusercontent.com/17645379/115850610-56636880-a426-11eb-9b46-ed56ae7fa5bb.png)
Is this possible to run webRTC with this ?

**Comment by AlexxIT** [comment]
@sgrzys run `python -c 'import os; print(os.uname())'`

**Comment by sgrzys** [comment]
```
~ $ python -c 'import os; print(os.uname())'
posix.uname_result(sysname='Linux', nodename='localhost', release='3.14.29', version='#1 SMP PREEMPT Tue Jan 23 04:07:38 CST 2018', machine='armv8l')
```

**Comment by AlexxIT** [comment]
What is your device? Some orange***?

**Comment by sgrzys** [comment]
its Amlogic S905 device with Android 7.1.2

**Comment by AlexxIT** [comment]
@sgrzys try to run `rtsp2webrtc_aarch64` on your device
https://github.com/AlexxIT/RTSPtoWebRTC/releases/tag/v2

**Comment by sgrzys** [comment]
armv7 is better choice:
![image](https://user-images.githubusercontent.com/17645379/116002544-7ea3c080-a5fa-11eb-9ad9-91997b3c2ba1.png)

**Comment by AlexxIT** [comment]
@sgrzys added in v1.4.0

**Comment by sgrzys** [comment]
Great - installed - THX
![image](https://user-images.githubusercontent.com/17645379/116387425-17b12200-a81b-11eb-8235-02dd6c5bb31c.png)

**Comment by AlexxIT** [comment]
Is it works? Can you see stream with Bunny?

**Comment by sgrzys** [comment]
Installation is OK, but stream still not working:
![image](https://user-images.githubusercontent.com/17645379/116394371-213e8800-a823-11eb-8e33-a82237553b26.png)
even with my local camera (connected but all time buffering):
![image](https://user-images.githubusercontent.com/17645379/116394546-5945cb00-a823-11eb-99f5-c6bc0b292ade.png)

**Comment by AlexxIT** [comment]
Seems like some network problems. I don't know if it depends on arch.

**Comment by sgrzys** [comment]
Thx, for pointing this out - seems that my router filter UDP comunication.
It works on different WLAN:
![image](https://user-images.githubusercontent.com/17645379/116397848-61a00500-a827-11eb-9e6e-5d5857d67993.png)
Great work - :beer:  for you ;)
