### ISSUE TITLE
WebRTC appears to grab more and more CPU over time

### ISSUE THREAD

**Issue by Moondevil-ha** [AlexxIT/WebRTC#180]
As described, I'm using WebRTC as the live preview using substream from Reolink cameras, and the CPU usage appears to start low, and slowly consume more and more over time. Attached is a snapshot of my processes, about 6 hours from last reboot. 

My lovelace card code is also attached, anythign else you would need?

Hass OS on NUC i3-6100U 16GB Ram

<img width="622" alt="image" src="https://user-images.githubusercontent.com/72937989/145075321-236d5f5b-1d21-4128-acac-68e505dbfbf6.png">

<img width="604" alt="image" src="https://user-images.githubusercontent.com/72937989/145072840-e512b823-9ca8-4aea-9fcd-4ea8802cff69.png">

**Comment by AlexxIT** [comment]
Duplicate #64
