### ISSUE TITLE
Refuses to Setup in HA 

### ISSUE THREAD

**Issue by thorrrr** [AlexxIT/WebRTC#181]
I followed the direction in docs and used HACs.
Restarted HA then went to add WebRTC but it refuses to install.
But I can see all the files in custom components

See error log [here](https://0bin.net/paste/oUIj-9Ck#W+3nuFHY4ibn0zb2XFGYFXVyOTc5d178ZGnQRhSieqO)
Also warning
Logger: homeassistant.setup
Source: /usr/local/lib/python3.9/asyncio/events.py:80
First occurred: 17:15:22 (1 occurrences)
Last logged: 17:15:22

Setup of webrtc is taking over 10 seconds.

I have tried re downloading same error every time

**Comment by AlexxIT** [comment]
I think you block internet for Hass. Because component trying to load server binary

**Comment by thorrrr** [comment]
PiHole :)
