### ISSUE TITLE
Taking long time (more than 1 minute) to load streams on iDevice

### ISSUE THREAD

**Issue by weitheng** [AlexxIT/WebRTC#19]
Am trying to load 2 streams on my iDevice, but they are taking taking quite long before the video appears. For my iPhone, it took about 1 minute for the streams to appear, while for my Mac, the streams doesn't seem to load no matter how long I waited. I have tried using Safari, Mozilla Firefox, Chrome on my Mac, but with no luck.

On my Android phone, on the other hand, the streams appear almost immediate.

I have allowed port forwarding on the following UDP ports on my router (50000 -> 50009), there are no error logs generated.

**Comment by AlexxIT** [comment]
Try to increase port range to 50000-60000. No need to port forward it on router. And try latest master version

**Comment by weitheng** [comment]
Reinstalled with latest master version, but streams still taking a long time to appear on iDevices. Tried with the bunny sample video, have the same latency

**Comment by weitheng** [comment]
![IMG_2378](https://user-images.githubusercontent.com/34220268/115124441-28ab9900-9fba-11eb-9efb-9a06e9b987f3.jpg)
Now streams seem to have completely stopped working on my iPhone but work flawlessly on the Android app. The streams seem to be stuck at some stage "... Connection", can't see the first word (attached in the photo). Force closed, restarted device, and rested frontend cache but that message didn't go away.

Checked debug logs on the integration, but no logs were generated. Connected my android phone to the streams, logs were immediately generated.

**Comment by weitheng** [comment]
Got to see the message/error displayed on the video stream.
![IMG_2380](https://user-images.githubusercontent.com/34220268/115134695-53254280-a00a-11eb-9b63-37a39d6ebd11.jpg)

**Comment by weitheng** [comment]
I managed to get it working on my Mac, apparently my adblocker (Adguard) is blocking the connection. Once I whitelist the website, the streams load immediately.

I tried with my other iOS devices, some worked some didn't. Not sure why. On those that didn't work, I disabled all content blockers, VPN and cleared History and Website Data on Safari. But still stuck on `init connection`

What could be the problem?

**Comment by AlexxIT** [comment]
Try latest master

**Comment by weitheng** [comment]
That worked! Just wondering what was the issue?

**Comment by AlexxIT** [comment]
Apple makes a lot of trouble for web developers :)
