### ISSUE TITLE
No feed/"Unsupported browser" message on webrtc card using FF95.0 since switching WebRTC to "master"

### ISSUE THREAD

**Issue by pem884** [AlexxIT/WebRTC#190]
### Description of issue:
Card no longer shows my camera feed; instead shows in an error state (red background) the card yaml:

```
Unsupported browser
type: custom:webrtc-camera
url: rtsp://redacted:redacted@redacted/h264Preview_01_sub
```

Link to image of message: https://imgur.com/a/QPYORk5

### What changed / when did the issue begin?

1. Card had been working fine earlier today;
2. Then I upgraded Home Assistant (OS) to 2021.12.0 and began seeing the error described in #182: `Error during setup of component webrtc` (...) `KeyError: 'allow_cors'`
3. As a result I changed WebRTC version to "master" through HACS, as I read in #182 - this made it work in my mobile devices but not my desktop PC.

### Further thoughts on troubleshooting:
I could go back and try with a different PC tomorrow if no one else seems to be getting the error. I can pull more information from this PC and/or another (hopefully working) PC if desired. Any other details that may help?

### Browser information (hopefully relevant)
```
Information about my browser (again, the webrtc card looks fine in Edge and also in Home Assistant mobile app):
Name 	Firefox
Version 	95.0
Build ID 	20211129150630
```
(...)
```
Update Channel 	release
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
OS 	Windows_NT 10.0 19044
```

**Comment by AlexxIT** [comment]
There is simple check for supported browser: `'RTCPeerConnection' in window`. You can run it in browser console on any page

**Comment by pem884** [comment]
Thank you so much. I'm new at browser debugging but think I got it:
```
'RTCPeerConnection' in window
false
```
(I did that in this GitHub Firefox tab, I believe it doesn't matter but happy to try other things)

**Comment by AlexxIT** [comment]
It's very strange. Because in my Firefox for macOS - WebRTC supported...

**Comment by pem884** [comment]
Agreed! I am slightly inclined to think it is something especially related to my own Firefox (Windows x64), but I myself lack the tools to plan debugging/troubleshooting. I will try on another Windows 10 x64 PC, hopefully today, assuming we don't think of anything else to try.

I noticed this but do not strongly feel it is related after reading it. Perhaps someone more knowledgeable may think otherwise, though:
[Bug 1690367 - [Experiment] Staged Rollout: Moving webRTC networking functionality into it's own process Fx 87.0 to 100.0 Release](https://bugzilla.mozilla.org/show_bug.cgi?id=1690367)

**Comment by pem884** [comment]
Interesting, I found that Firefox offers a page which seems like it might offer some tools to research but I am not sure what to do with them. I hope I am not burdening you with something that turns out to be a Firefox issue, but perhaps Firefox offers us some tools to find out.

![image](https://user-images.githubusercontent.com/50749285/145727031-ac887270-f78c-4cfd-acb7-3d58781be655.png)

**Comment by AlexxIT** [comment]
In the address bar or your Mozilla Firefox browser, type about:config and press Enter.
Click I accept the risk! on the warning screen that shows up.
Type media.peerconnection.enabled in the search bar beneath the address bar.
Double-click the search result to change the Value column to true.

**Comment by pem884** [comment]
Thank you so much! That fixed it... so there was clearly an issue with my settings in Firefox. I am not sure how it changed and will follow up if I find out, in case anyone experiences this again.

Again, thank you very much, I am loving the low latency access to the camera feed that this integration allows!
