### ISSUE TITLE
Webrtc stopped working after update 12/12/2021

### ISSUE THREAD

**Issue by samios88** [AlexxIT/WebRTC#193]
It worked perfectly with previous version but since new update it's broken I tried to set it up again but no luck here is log error
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: webrtc (documentation, issues)
First occurred: 4:11:07 PM (1 occurrences)
Last logged: 4:11:07 PM

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by AlexandreUSA** [comment]
Same here with the same log entry.

**Comment by idoaflalo** [comment]
> It worked perfectly with previous version but since new update it's broken I tried to set it up again but no luck here is log error This error originated from a custom integration.
> 
> Logger: homeassistant.setup Source: custom_components/webrtc/utils.py:74 Integration: webrtc (documentation, issues) First occurred: 4:11:07 PM (1 occurrences) Last logged: 4:11:07 PM
> 
> Error during setup of component webrtc Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component result = await task File "/config/custom_components/webrtc/**init**.py", line 75, in async_setup utils.register_static_path(hass.http.app, url_path, path) File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path app['allow_cors'](route) File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in **getitem** return self._state[key] KeyError: 'allow_cors'

For now, you can comment out line 75 in the init.py file of this custom component (by adding # to the start of the line) and restart home assistant to solve the problem (Chromecast will stop working with webrtc).

**Comment by shlomosv1** [comment]
yap, same with me "Webrtc stopped working after update 12/12/2021"

**Comment by Farmer-Eds-Shed** [comment]
Reinstalled from Hacs using Master as version and is working for me now

**Comment by idoaflalo** [comment]
#179 Duplicate

**Comment by phptanker** [comment]
> Reinstalled from Hacs using Master as version and is working for me now

This worked for me aswell.

**Comment by tbone004** [comment]
> > It worked perfectly with previous version but since new update it's broken I tried to set it up again but no luck here is log error This error originated from a custom integration.
> > Logger: homeassistant.setup Source: custom_components/webrtc/utils.py:74 Integration: webrtc (documentation, issues) First occurred: 4:11:07 PM (1 occurrences) Last logged: 4:11:07 PM
> > Error during setup of component webrtc Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component result = await task File "/config/custom_components/webrtc/**init**.py", line 75, in async_setup utils.register_static_path(hass.http.app, url_path, path) File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path app['allow_cors'](route) File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in **getitem** return self._state[key] KeyError: 'allow_cors'
> 
> For now, you can comment out line 75 and 85 in the init.py file of this custom component (by adding # to the start of the line) and restart home assistant to solve the problem (Chromecast will stop working with webrtc).

Thanks, that worked for me.

**Comment by shlomosv1** [comment]
> > Reinstalled from Hacs using Master as version and is working for me now
> 
Reinstalleddid not work for me ...)-:

**Comment by AlexxIT** [comment]
#156
