### ISSUE TITLE
errOR: NotSupportedError: Failed to execute addSourceBuffer' on 'MediaSource': The type provided (video/mp4; godecs= "hvc1.016000") unsupported.

### ISSUE THREAD

**Issue by savinct** [AlexxIT/WebRTC#196]
Hello,
    I created an rtsp link from the surveillance camera DAHUA, a link that works correctly in VLC.
    When I wanted to display in HA also through "webrtc-camera" it displays this error to me.

    Does anyone know what I can do?
    
![vlc](https://user-images.githubusercontent.com/48353342/145729207-4af047c8-4634-4b3d-a4f8-84652e3796a0.png)

   
![cam](https://user-images.githubusercontent.com/48353342/145729217-aeaf1a93-51af-4d0e-8488-47da0a2a295d.png)

**Comment by AlexxIT** [comment]
Check this issue #71

**Comment by pergolafabio** [comment]
I have the same issue , and sometimes it's gone after a minute, then I can see it, mine are h264, also exposed RTSP stream coming from Synology

Do you still have issue?

**Comment by savinct** [comment]
I created a template for the camera, the url is not good for me and I didn't find it in the camera documentation

After creating the item, I displayed it in the Image Item in live mode

He only shows me the picture when I enter it

It hasn't worked for me in a week
  
  - platform: generic
    name: Camera2
    still_image_url: "http://1234@192.168.1.150:80/"
    stream_source: "rtsp://user:password@192.168.1.150:554/cam/realmonitor?channel=2&subtype=1"
    username: user
    password: password
    authentication: basic

**Comment by pergolafabio** [comment]
For me error is gone, seems when I was streaming to other clinets, probably to less Bandwith, this error occurs... Turned off streaming to other clients and  ow it's gone
