### ISSUE TITLE
Autoplay stream

### ISSUE THREAD

**Issue by weitheng** [AlexxIT/WebRTC#20]
The streams doesn't seem to autoplay on my iPhone until I press the play icon, is there any way to get it to autoplay stream? It did for the first few times, but now it requires me to click play before it starts playing.

**Comment by AlexxIT** [comment]
What do you mean about first few times? What versions: component, iPhone, iOS, browser/app do you just?

**Comment by weitheng** [comment]
The streams did autoplay when I just updated to the last master version. But after a while, it starts requiring me to press the play icon to play stream on the HA app. I am using iPhone 11 and iPhone 8 on (iOS 14.5 and iOS 14.4.2 respectively), running the streams on HA app

**Comment by weitheng** [comment]
Now the streams seem to be autoplaying again. Not sure what happened there

**Comment by weitheng** [comment]
It still doesn't autoplay on my iPhone 8

**Comment by weitheng** [comment]
It seems to autoplay intermittently, now the streams don't autoplay on my iPhone 11 as well

**Comment by weitheng** [comment]
Would adding` <video autoplay></video>` in `index.html` fix this issue?
https://flaviocopes.com/webrtc/

**Comment by AlexxIT** [comment]
Already [there](https://github.com/AlexxIT/WebRTC/blob/64f43747ebffeb93ead8655a75a93461baa99ecb/custom_components/webrtc/www/webrtc-camera.js#L444). I don't know why autoplay doesn't works for you.

**Comment by weitheng** [comment]
I have figured out why autoplay sometimes works and sometimes doesn't. Autoplay doesn't work when my device is in low power mode, but works when not in low power mode. 

Not sure if this article https://shaktisinghcheema.com/how-to-autoplay-video-on-mobile-devices-on-low-power-mode/ would be able to get around the problem. If not, perhaps it's not something we could do about it, since it's implemented on the OS side.

**Comment by AlexxIT** [comment]
He is advising to play video with any screen click. I don't think it is good idea. Apple, as usual, decided everything for its users.
