### ISSUE TITLE
No shortcuts showing

### ISSUE THREAD

**Issue by direx1** [AlexxIT/WebRTC#201]
Just this. No shortcut shown even though configured as per documentation.

**Comment by AlexxIT** [comment]
Any details?

**Comment by baggein** [comment]
Не стал создавать новую тему - интеграция перестала работать на последнем обновлении HA.

`Уровень: ОШИБКА
Эта ошибка возникла в кастомной интеграции.

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera (documentation, issues)
First occurred: 20:58:28 (1 occurrences)
Last logged: 20:58:28

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'
`

**Comment by zvldz** [comment]
> Не стал создавать новую тему - интеграция перестала работать на последнем обновлении HA.

**Comment by baggein** [comment]
> хорошо что не стали создавать, следующим этапом надо научится читать те что есть

Что именно есть?

**Comment by zvldz** [comment]
воспользуйтесь поиском, вы 100500 кто описывает такую проблему

**Comment by baggein** [comment]
> воспользуйтесь поиском, вы 100500 кто описывает такую проблему
Понял вас, спасибо за подсказку - думал, это из-за новой версии HA что-то приключилось, но как понял такое уже было ранее.

**Comment by zvldz** [comment]
Алекс уже устал закрывать дубликаты )

**Comment by baggein** [comment]
> Алекс уже устал закрывать дубликаты ) тут уже есть ответ в других issue

PS: Вообщем поставил master-версию - всё работает.

**Comment by direx1** [comment]
> Any details?
Nothing shows up on the feed
![Screenshot_20211213-183550_Chrome](https://user-images.githubusercontent.com/77240604/145868916-78aab3f0-b2fd-4b35-a257-028f494164a5.jpg)

**Comment by AlexxIT** [comment]
It's better to discuss in this issue #172
I think you don't enable `ui: true`
