### ISSUE TITLE
Unable to load the integration in the last Home Assistant Version

### ISSUE THREAD

**Issue by MiAutomations** [AlexxIT/WebRTC#202]
Hello 

After the update core-2021.12.1 I'm unable to load the this integration

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: webrtc (documentation, issues)
First occurred: 4:15:57 PM (1 occurrences)
Last logged: 4:15:57 PM

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

Can you please check ?

Thank you

**Comment by alonbendavid** [comment]
I have the same issue since the update of core-2021-12-*
looks like this part of the code is for use with Chromcast, so I commented the line out (custom_components/webrtc/utils.py:74) and it's working.
Will remove and update once a patch will be provided.

**Comment by benek984** [comment]
Hi, I have the same issue after upgrading to core-2021-12-x

**Comment by htmltiger** [comment]
HACS > Integrations > WebRTC ... > Redownload > select version > master

**Comment by AlexxIT** [comment]
#156
