### ISSUE TITLE
ERROR: Support only RTSP-stream

### ISSUE THREAD

**Issue by NVader2000** [AlexxIT/WebRTC#206]
Fresh install of HA OS 7.0. What am I missing?

![image](https://user-images.githubusercontent.com/34590572/145998614-674072ee-94dd-4d8f-ae8a-d52a850d69ba.png)

**Comment by aotd1** [comment]
Attach some technical details? =)
Logs, configurations...

**Comment by NVader2000** [comment]
No errors in the logs.

![image](https://user-images.githubusercontent.com/34590572/146003675-3746d1f1-dcd4-41fa-a142-78cba77efe52.png)

**Comment by NVader2000** [comment]
BUMP?

**Comment by rainman369** [comment]
> No errors in the logs. FYI: This was happening in HA OS 6.6 as well. This error at some point start, but not sure when. I did have this working previously but some has changed since.
> 
> ![image](https://user-images.githubusercontent.com/34590572/146003675-3746d1f1-dcd4-41fa-a142-78cba77efe52.png)

should be rtsp, not rtsps right?

**Comment by hardy-yan** [comment]
> No errors in the logs. FYI: This was happening in HA OS 6.6 as well. This error at some point start, but not sure when. I did have this working previously but some has changed since.
> 
> ![image](https://user-images.githubusercontent.com/34590572/146003675-3746d1f1-dcd4-41fa-a142-78cba77efe52.png)

The error message says it all, the plugin only supports RTSP stream, not RTSPS.
Since I noticed your URL looked like UniFi's camera, just wanted to say that the default streaming URL on UniFi Protect is now RTSPS after v1.20, and if you want to switch back to RTSP just change it to rtsp:// and change the port number to 7447.

**Comment by NVader2000** [comment]
Yeah, tried that and got this.

![image](https://user-images.githubusercontent.com/34590572/146623551-56efdcb4-fb6f-456d-b883-1273eec1907d.png)

**Comment by hardy-yan** [comment]
> Yeah, I tried that and got this.
> 
> ![image](https://user-images.githubusercontent.com/34590572/146623567-84fe4c38-5395-45d0-b574-3593cf0b0fba.png)

did you remove the ?enableSrtp at the end of the URL?

**Comment by InvisCo** [comment]
> > Yeah, I tried that and got this.
> > ![image](https://user-images.githubusercontent.com/34590572/146623567-84fe4c38-5395-45d0-b574-3593cf0b0fba.png)
> 
> did you remove the ?enableSrtp at the end of the URL?

I managed to get this working with the following URL: `rtsp://<camera-ip>:7447/plWTzeWJss3q6BSv`

**Comment by ibanmda** [comment]
I have the same issue. No log error showed.

`ERROR: Support only RTSP-stream`

![Captura de pantalla de 2021-12-28 23-37-55](https://user-images.githubusercontent.com/37747906/147612218-8efdf524-ed14-4701-b896-dee7b6e8bd06.png)

I tried with `url: rtsp://192.168.X.XX/ch0_0.h264` not succefuly

![Captura de pantalla de 2021-12-28 23-47-08](https://user-images.githubusercontent.com/37747906/147612719-bdb772ef-d4f7-4ba9-a5b0-68fe01f5cca0.png)

**Template config:**

`type: custom:webrtc-camera`
`url: camera.yi_hack_xx_xxxxxx_cam`

**My system:**

**Home Assistant OS 7.0
core-2021.12.6
yi-hack
Firmware: 0.1.9 
Yi 1080p Dome *FUS
Base Version | 9.0.05.33_202009251856**


Best Regards!

**Comment by ibanmda** [comment]
> I have the same issue. No log error showed.
> 
> `ERROR: Support only RTSP-stream`
> 
> ![Captura de pantalla de 2021-12-28 23-37-55](https://user-images.githubusercontent.com/37747906/147612218-8efdf524-ed14-4701-b896-dee7b6e8bd06.png)
> 
> I tried with `url: rtsp://192.168.X.XX/ch0_0.h264` not succefuly
> 
> ![Captura de pantalla de 2021-12-28 23-47-08](https://user-images.githubusercontent.com/37747906/147612719-bdb772ef-d4f7-4ba9-a5b0-68fe01f5cca0.png)
> 
> **Template config:**
> 
> `type: custom:webrtc-camera` `url: camera.yi_hack_xx_xxxxxx_cam`
> 
> **My system:**
> 
> *_Home Assistant OS 7.0 core-2021.12.6 yi-hack Firmware: 0.1.9 Yi 1080p Dome _FUS Base Version | 9.0.05.33_202009251856__
> 
> Best Regards!

Worked with **lowres** `url: rtsp://192.168.X.XX/ch0_1.h264` , but not with highres (through VLC work without problem)

Regards

**Comment by nkgiovannivl** [comment]
I have same issue, but with picture-entity works ok

```
type: picture-entity
entity: camera.ipcam_sala_gatos_360_rtsp
show_name: true
show_state: false
camera_view: live
```

Same entity using webrtc-camera does not work

```
type: custom:webrtc-camera
url: camera.ipcam_sala_gatos_360_rtsp
```
configuration.yaml

```
  - platform: generic
    name: IPCam_Sala_Gatos_360_RTSP
    still_image_url: https://www.google.com/logos/doodles/2017/colombia-national-day-2017-5750822263586816-2xa.gif
    stream_source: rtsp://myuser:mypass@192.168.1.23:5523/11 
```

Am I using in a good way an entity as a parameter in url option on webrtc-camera? Thanks

**Comment by AlexxIT** [comment]
RTSPS is not RTSP #171
