### ISSUE TITLE
[FEATURE REQUEST] Add the Ability to Load/Unload Cameras On-Demand

### ISSUE THREAD

**Issue by eroc1990** [AlexxIT/WebRTC#209]
It would be awesome if we were able to trigger the camera to turn on and otherwise leave it idle. I've got a handful of battery-powered Eufy cameras I've configured to work over RTSP, but leaving the feeds on 24/7 would drain their batteries far too quickly to make using WebRTC to pull them into HA feasible. If there was a way to trigger the camera to activate/deactivate, that would allow me to take an on-LAN look at my cameras and be able to remove my dependency on the Eufy Security app.

**Comment by AlexxIT** [comment]
You can use shortcuts and call service that enable/disable streaming from your cameras
