### ISSUE TITLE
Correct Camera Stream to 16:9

### ISSUE THREAD

**Issue by sumur1au** [AlexxIT/WebRTC#21]
The stream is displayed in 4:3 when the camera records in 16:9 is it possible to correct the aspect ratio in the configuration card?

**Comment by AlexxIT** [comment]
iPhone?

**Comment by sumur1au** [comment]
Chrome on Windows and Android

**Comment by AlexxIT** [comment]
Please show screen. You may blur image.

**Comment by sumur1au** [comment]
![Camera Stream](https://user-images.githubusercontent.com/65957586/115853978-1b385800-a46d-11eb-9c4d-11a771701582.jpg)

**Comment by AlexxIT** [comment]
It seems to be displayed correctly. Or is the picture compressed horizontally?

**Comment by sumur1au** [comment]
The picture is compressed, it should be spread vertically.

**Comment by giggo** [comment]
I have the same with a RTSP stream from a Reolink camera.

**Comment by kp-bit** [comment]
Does the stream out of the camera have the right aspect ratio? I had to adjust my substream from 640x480 to 640x360 to get 16:9 aspect ratio...

**Comment by brianewman** [comment]
I'm using a hikvision camera and WebRTC stretches the image to 4:3.  The same rtsp URL shows the correct aspect ratio in VLC.

**Comment by brianewman** [comment]
Here is the same camera feed in a picture-entity card (top) and a WebRTC card (bottom).
![Screenshot 2021-05-20 180027](https://user-images.githubusercontent.com/45852375/119059257-95d59400-b995-11eb-848c-8d397efd7590.png)

**Comment by majdzik84** [comment]
I have the same problem

**Comment by AlexxIT** [comment]
Is size same in VLC desktop player?

**Comment by majdzik84** [comment]
Any ideas how to get the correct 16: 9 format?

**Comment by JaCoLJcL** [comment]
Same Here :( Add option to change Resolutions of source image!

**Comment by majdzik84** [comment]
@AlexxIT Will this help with the scaling problem? 

https://www.home-assistant.io/blog/2021/09/01/release-20219/
![image](https://user-images.githubusercontent.com/31352476/131738618-b41b7dc2-e36c-4785-b44b-d30bb32893af.png)

**Comment by mckochan** [comment]
Have this problem with my Amcrest camera too.
I've tried various card-mod CSS styles to no avail. Anyone else try Card mod?
      padding-top 56.25% !important;
and
aspect-ratio: 1.77 !important;

**Comment by AlexxIT** [comment]
Can someone provide public access to their RTSP-stream? You can send link in private message in Telegram @AlexxIT or [Hass community](https://community.home-assistant.io/u/alexxit/)

**Comment by majdzik84** [comment]
Can anyone share the stream? I've been struggling with it for 3 hours but unfortunately something is wrong with me. (My network is shared and I have some limitations).
If someone sends a stream to Alex, please let me know so I don't get tired :)

**Comment by AlexxIT** [comment]
Thanks to @majdzik84 - I found the problem
```
Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 640x480 [SAR 4:3 DAR 16:9], 15 fps, 100 tbr, 90k tbn, 30 tbc
```
Component doesn't supported [display aspect ratio](https://en.wikipedia.org/wiki/Pixel_aspect_ratio). And shows picture in original size. I will try to find a solution.

**Comment by majdzik84** [comment]
I keep my fingers crossed for it to succeed :)

**Comment by AlexxIT** [comment]
Seems like WebRTC doesn't support pixel aspect ratio. Need a JavaScript developer who can stretch the video manually in the browser.

https://chromium.googlesource.com/external/webrtc/+/HEAD/common_video/h264/sps_parser.cc#222

**Comment by mckochan** [comment]
Should be a way to just force an aspect ratio for the card and the video will follow, or are you saying then the video will just crop?
Default picture_entity card has aspect_ratio setting as does https://github.com/custom-cards/button-card#aspect-ratio

**Comment by saxopwn** [comment]
> Should be a way to just force an aspect ratio for the card and the video will follow, or are you saying then the video will just crop? Default picture_entity card has aspect_ratio setting as does https://github.com/custom-cards/button-card#aspect-ratio

Would love to see something like this. I have a few WebRTC cards within a swipe card to flip through my security cameras. One of the cameras is a 4:3 doorbell while the rest are 16:9. I'm being nitpicky but being able to force 16:9 would fix the spacing on my dashboard. :)

**Comment by kspearrin** [comment]
I recently opened #227, but it seems like it might be related to this. Is anyone that experiences this problem see the video frame being cropped on the HomeAssistant iOS app? It shows fine on the desktop (albeit with the wrong aspect ratio), but on iOS part of the video is actually cropped off the sides which makes the card unusable.

**Comment by nagyrobi** [comment]
Found [here](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/187), needs [lovelace-card-mod](https://github.com/thomasloven/lovelace-card-mod) to set ratio to 16:9:
```
style: |
  ha-card {
    --height-cctv: calc(28vh - 40px);
    --width-cctv: calc(var(--height-cctv) / 9 * 16);
    height: var(--height-cctv);
    width: var(--width-cctv);
  }
```
Has two issues:
- sets the card size static
- renders the full screen incorrect

**Comment by davros123** [comment]
@AlexxIT what was the solution? Are we still awaiting a JavaScript developer?

**Comment by nagyrobi** [comment]
With the PR above, and config like below, it will show nice:
```
  - type: custom:webrtc-camera
    url: >-
      rtsp://user:pass@192.168.2.20:554/Streaming/Channels/202
    poster: http://192.168.2.10:8123/local/pub/HA_cam_poster3.png
    style: |
      ha-card {
        --height-cctv: calc(32vh - 40px);
        --width-cctv: calc(var(--height-cctv) / 9 * 16);
        height: var(--height-cctv);
        width: var(--width-cctv);
      }
    shortcuts:
      - name: Camera Light Switch
        icon: mdi:track-light
        service: switch.toggle
        service_data:
          entity_id: switch.camera_lights
```

**Comment by felipecrs** [comment]
I would make it even simpler for the final user to customize. Something like the Frigate Hass Card do:

```yaml
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:9'
```

**Comment by jodyalbritton** [comment]
> With the PR above, and config like below, it will show nice (tested on Hikvision secondary streams):
> 
> ```
>   - type: custom:webrtc-camera
>     url: >-
>       rtsp://user:pass@192.168.2.20:554/Streaming/Channels/202
>     poster: http://192.168.2.10:8123/local/pub/HA_cam_poster3.png
>     style: |
>       ha-card {
>         --height-cctv: calc(32vh - 40px);
>         --width-cctv: calc(var(--height-cctv) / 9 * 16);
>         height: var(--height-cctv);
>         width: var(--width-cctv);
>       }
>     shortcuts:
>       - name: Camera Light Switch
>         icon: mdi:track-light
>         service: switch.toggle
>         service_data:
>           entity_id: switch.camera_lights
> ```

does this still work for you? I made the changes and it is still a 4:3 stream using the rtc card

**Comment by nagyrobi** [comment]
Yes it works fine here.
Clear cache, restart browser.

**Comment by AlexxIT** [comment]
Supported from v3:
```
style: "video {aspect-ratio: 16/9; object-fit: fill;}"
```

**Comment by AlexxIT** [comment]
Should be fixed in v3

**Comment by felipecrs** [comment]
@AlexxIT is it possible to zoom/center the video rather than just stretching it?

**Comment by felipecrs** [comment]
Actually found my answer:

```
style: "video {aspect-ratio: 16/9; object-fit: cover;}"
```

https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

**Comment by Smosia** [comment]
Update 3.2.1 broke rotation of video.
`style: 'video {transform: rotate(90deg); aspect-ratio: 1}'`
Don't work

**Comment by AlexxIT** [comment]
@dbuezas can you check rotation feature with CSS?

**Comment by dbuezas** [comment]
Please try with `digital_ptz: false`.
That feature also uses transforms for zoom and pan so it is probably overwriting the style

**Comment by AlexxIT** [comment]
I have solution for rotate MSE and MP4 (not WebRTC). But it work only in Chrome and Firefox. Maybe will be in next versions.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/releases/tag/v3.3.0

**Comment by IronicRebound77** [comment]
> Actually found my answer:
> 
> ```
> style: "video {aspect-ratio: 16/9; object-fit: cover; object-position: left top;}"
> ```
> 
> https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit https://css-tricks.com/almanac/properties/o/object-position/

thanks, this really helped me adjust the frame size, was messing with it for hours!
