### ISSUE TITLE
How to disable intersection

### ISSUE THREAD

**Issue by PilaScat** [AlexxIT/WebRTC#210]
I would like to make that when I change the page on chrome and then go back to home assistant the cameras do not reload
How?

**Comment by AlexxIT** [comment]
What you mean about "do not reload"

**Comment by PilaScat** [comment]
Them come back black with a spinning circleFilippo ScatignaOn 15 Dec 2021 13:52, Alex X ***@***.***> wrote:
What you mean about "do not reload"?

**Comment by reef-actor** [comment]
`background: true` will keep the stream going in the background I think

**Comment by AlexxIT** [comment]
Should be fixed in v3
