### ISSUE TITLE
Password with ^ and/or ! doesn't work

### ISSUE THREAD

**Issue by vdbrink** [AlexxIT/WebRTC#211]
I had a password with a `^` and a `!` in it which didn't work if I use the username and password not as seperated defined fields but in the url.

I knew the url was correct because I tested it with VLC media player with this description: https://support.reolink.com/hc/en-us/articles/360007010473-How-to-Live-View-Reolink-Cameras-via-VLC-Media-Player

After I removed these characters from the url and camera password it works. Something with escaping the characters.
I tried with single and double quotes around the rtsp url but that doesn't make any difference.

I used version 2.1.1

**Comment by nh-mike** [comment]
Hi @vdbrink can you try substituting ^ for %5e and ! for %21

**Comment by AlexxIT** [comment]
These characters are not allowed in the password without encoding
https://datatracker.ietf.org/doc/html/rfc3986.html
