### ISSUE TITLE
Enhancement Request: Enlarged View similar or identical to the LoveLace standard card

### ISSUE THREAD

**Issue by fouram** [AlexxIT/WebRTC#215]
I would like the ability to configure this card so that when clicked, it enlarges to an overlaid, simulated-dialog-box type view in the way that the standard Lovelace Picture Card (instead of just full-screen); with a title bar, an X to close it, and a gear to look a the related entities/etc.

It would be nice if this was configurable, alongside the fullscreen button at the bottom left being toggleable

**Comment by timdonovanuk** [comment]
It would fantastic if it reached feature parity with the default Lovelace card. It's missing this enlarged view and also picture in picture, which is extremely handy for things like baby cams.

Cheers!

**Comment by markfrancisonly** [comment]
Currently using a picture glance card's hold action to call browser_mod popup with an webrtc card, however, broswer_mod is heavy and provides a ton of functionality I don't use

**Comment by AlexxIT** [comment]
Check my new project. It has support default lovelace card
https://github.com/AlexxIT/go2rtc
