### ISSUE TITLE
Any chance to go fullscreen from small sized card in lovelace?

### ISSUE THREAD

**Issue by guciopl** [AlexxIT/WebRTC#216]
I have my main camera presented on dashboard with this integration and it works just awesome. Below I wanted to have 3 other cameras in horizontal stack, they are not so important but nice to take a look there from time to time. Problem is that in HA android app I am unable to enlarge those three. They are too small to show fullscreen option, only pause is visible after clicking them. Any chance to apply there some "onclick" action so it will automaticaly go fullscreen once clicked (instead of pausing which is practicaly useless)? Or it uses some external system player and there is no way to intefere with it?
![Screenshot_20211216-185654_Home Assistant](https://user-images.githubusercontent.com/61185430/146438567-693173d2-c6ad-4773-a0ed-86c91ba34fd0.jpg)

On PC it works well, I can see three dots with fullscreen option available on dropdown menu.
![2](https://user-images.githubusercontent.com/61185430/146438618-2878b74e-cd3c-41f7-bfe0-add13a6af1dc.PNG)

**Comment by AlexxIT** [comment]
Try to use `ui: true` setting

**Comment by guciopl** [comment]
Actually it already works ok for me for quite long time. No idea when exactly it has changed but I can click triple dots and pick fullscreen even on those small thumbnails on my mobile.

**Comment by koganei** [comment]
It actually turned out to be a wallpanel issue: https://github.com/thecowan/wallpanel-android/issues/302
It works with the home assistant app or the browser.

**Comment by AlexxIT** [comment]
Check my new project. It has support default lovelace card
https://github.com/AlexxIT/go2rtc
