### ISSUE TITLE
Stuck on "Init Connection" Safari Desktop

### ISSUE THREAD

**Issue by weitheng** [AlexxIT/WebRTC#22]
Updated to latest master version which does not require specifying ports, streams are stuck on` init connection` when using Safari Desktop. Tried specifying ports from 50000-59999,  but did not work. Working well with other browsers (Chrome, Firefox) on the same laptop even when not specifying ports

**Comment by AlexxIT** [comment]
Try clear cache

**Comment by weitheng** [comment]
Cleared cache and tried on incognito, both didn't work. Went onto JS console, got this message `Blocked *URL* from asking for credentials because it is a cross-origin request.`

Looks like url has been blocked

**Comment by AlexxIT** [comment]
This is not about component. Because it doesn't do any requests.

**Comment by AlexxIT** [comment]
I think this is browser cache problem.

**Comment by weitheng** [comment]
> This is not about component. Because it doesn't do any requests.

Could the request be from my RTSP stream? Because the RTSP url contains the username and password to access the stream.

I have tried clearing the cache and gone onto incognito mode again, but with no luck. :(

I also tried disabling the Cross-Origin Restrictions on Safari, but I am immediately redirected to the IP address of the camera upon refreshing the page, prompting me to enter the username and password (even though they are already included in the RTSP url, and works fine on my other devices). But after entering the correct credentials, I am redirected back to my HA domain, with the following message `Failed to load resource: the server responded with a status of 401 (Unauthorized)` on the JS console.

**Comment by AlexxIT** [comment]
You can use camera entity instead of url in latest version. For example, if the camera is configured as Generic.

**Comment by weitheng** [comment]
> You can use camera entity instead of url in latest version. For example, if the camera is configured as Generic.

Tried that, still getting the same error on JS console. :(

Really unsure what's causing the issue, I kept refreshing the page and sometimes I managed to get it working temporarily, but another refresh will bring it down again.

I managed to have a try on my other MacBook, and it works flawlessly on Safari. You could be right that it's the browser problem specifically the cache or website date. But I did clear both of them.

**Comment by AlexxIT** [comment]
This error not from component. You can remove card from page and check.

**Comment by weitheng** [comment]
> This error not from component. You can remove card from page and check.
> 
> I hope you didn't set up the card poster?

Nope, no card poster. I created a new page and try adding the entity one by one, it seems that it works fine when there's only 1 or 2 WebRTC entities on the page. Once there's more than 2, it struggles to initialise connection.

**Comment by weitheng** [comment]
I will keep on trying to see what's the issue, it should be a problem with my browser. Thanks for your help!

**Comment by AlexxIT** [comment]
I have tested on Safari Version 14.0 (15610.1.28.1.9, 15610).
What version do you have?

**Comment by weitheng** [comment]
I am using Version 14.0.3

**Comment by weitheng** [comment]
Somehow the streams are working again now, I will continue to monitor the issue. Thanks!

**Comment by AlexxIT** [comment]
Reopen if there's a problem
