### ISSUE TITLE
WEBRTC card - Display problem on iphone 12

### ISSUE THREAD

**Issue by SmartM-ui** [AlexxIT/WebRTC#224]
Hi @AlexxIT ,
the card in the home assistant for viewing my two cameras, of different brands, are not displayed on iphone 12 with ios 15, while it works perfectly on iphone X (ios 15) and iphone 7 (ios 14) and Android.

How can I solve the problem? 

Thanks

![WebRTC_Error](https://user-images.githubusercontent.com/63554131/146764453-7488dcce-13a6-4b69-a33a-0ecf28fe9103.jpg)

**Comment by noorbertt** [comment]
I have a similar issue. It's working on lan but not from mobile network. 

All good with android

**Comment by AlexxIT** [comment]
@SmartM-ui you using it in same LAN with same network settings?

**Comment by SmartM-ui** [comment]
> @SmartM-ui you using it in same LAN with same network settings?

Hi @AlexxIT ,
Thanks for the reply. The problem occurs when the phones are using data from the SIM and not under the same LAN.

**Comment by mckochan** [comment]
Sam here, even though I'm using wireguard VPN, the cams will not display when off of wifi.

**Comment by chudystg** [comment]
Hi @AlexxIT,
I tested. The problem appeared after updating iOS 15.2 -> 15.3. No preview is available only when connected to an external network.

**Comment by AlexxIT** [comment]
Should be fixed in v3
