### ISSUE TITLE
iOS App Clips Video Frame

### ISSUE THREAD

**Issue by kspearrin** [AlexxIT/WebRTC#227]
Sorry if this is a duplicate, I was not able to find the same issue posted already.

I have the WebRTC camera card running on my home assistant install. Everything seems to be working well when viewing from my desktop PC:

```
type: custom:webrtc-camera
url: >-
  rtsp://username:password@amcrest_camera_name.local:554/cam/realmonitor?channel=1&subtype=1
```

I am using substream 1 with my Amcrest (Dahua) IP cameras, configured with a 704x480 (D1) resolution and frame rate of 10.

![image](https://user-images.githubusercontent.com/1190944/147131758-c141d0b5-4dad-4290-8941-86b68782a7e9.png)

![image](https://user-images.githubusercontent.com/1190944/147130609-fb2d0191-a166-4f52-9100-9e9adab640af.png)

However, when viewing these cards from the Home Assistant iOS app, the videos are clipped and I cannot see the entire area. It appears that the clipping is only along the width (x) of the frame.

![image](https://user-images.githubusercontent.com/1190944/147131670-b7053cb9-afc4-464e-a539-3ad713300318.png)

Even when viewing the stream in full screen, it is clipped the same.

![image](https://user-images.githubusercontent.com/1190944/147131494-fbffd0e0-bab3-4fec-bd6f-ec9afe6a8193.png)

If I change the resolution to something that is 16:9, it seems to display correctly on both platforms, however, I need this lower resolution to save on bandwidth for live viewing of 10 cameras.

**Comment by AlexxIT** [comment]
I think problem the same #21

**Comment by kspearrin** [comment]
@AlexxIT I reviewed #21, but this seems like it might be different. #21 discusses the wrong aspect ratio (4:3 instead of 16:9), however, the entire frame is still visible (just squished). Here, the frame is actually trimmed down and part of the image is missing. I did not see any part of the image missing in #21 like I am experiencing.

**Comment by AlexxIT** [comment]
You can check this stream in another software. Example VLC

**Comment by kspearrin** [comment]
Aspect ratio is correct and the full frame is visible in VLC.

![image](https://user-images.githubusercontent.com/1190944/147258722-580dcd2c-15b4-4fab-b984-e66e6eab46b7.png)

**Comment by kspearrin** [comment]
Looking at the screenshots again, it appears that on desktop (Chrome) the aspect ratio is changed and the image is squished, however, the full frame is still visible. On iOS, it appears that is is trying to keep the correct aspect ratio, however, that results in the frame being trimmed.

**Comment by AlexxIT** [comment]
I think is same problem as 21. Camera sends wrong pixel size. VLC can read it. WebRTC don't support wrong pixel size
