### ISSUE TITLE
Plays/Streams even when hidden?

### ISSUE THREAD

**Issue by tunerooster** [AlexxIT/WebRTC#23]
_Love your new WebRTC card!!!!_

It appears, however, that the stream is playing even when the card/view is not visible (i.e., when a completely different view is showing).  The cpu does not change when navigating away.  This causes the CPU to increase quite a bit for each camera.

I have 6 cameras, so far I have only tested two simultaneously, and the cpu is at 70% for the process `rtsp2webrtc_v1_amd64`.  With one camera, the cpu was at 50%.  Haven't tried 6 yet.

Is it possible to stop streaming when the card/view is not visible?  Or disconnect and reconnect when visible?

Great work though!  _I had all but given up on live streaming with HA!_

**Comment by AlexxIT** [comment]
Known bug. Will be fixed in v2

**Comment by tunerooster** [comment]
Outstanding!

**Comment by tunerooster** [comment]
I installed 1.3...  (I am running an Intel NUC equivalent machine.)

The CPU is down to 10%-25% (for the process `rtsp2webrtc_v2_amd64`) for 3 cameras, which is very good.   After a little while, the CPU went down to below 10% when nothing was viewed.  So it looks like closing views *does* lower the load now.  Plus the load is quite low, and does not go up much for each camera.  I will be able to display all 6 camera with no problem!  Very impressive!

However, when I revisit each camera, the *seek duration* (in the lower left of the video nav bar) appears that it is still playing from the initial viewing.  I.e., instead of restarting at 0:00, it displays 6:17.  If I completely close the browser and reopen, it restarts at 0:00.  It seems like on for example a permanently running dashboard, which is my case, that it could/would run for days/weeks etc... building up quite a duration.

I'm not saying this is a problem, I am just pointing it out.  It makes it appear that is it still streaming even when not viewed.

Maybe you can explain what it is doing (or supposed to do)...  Is there a way (other than closing the HA instance) to reset it to zero?  When you say in the release notes:
```
. Fixed stream stopping if no one is watching #23
```
It sounds like continuing the duration counter might be by design, so I'm a little confused.

In any case, **thanks** and great work (it is very smooth)!

**Comment by AlexxIT** [comment]
I think that's just how your browser works. And I don't know why you still have a 10% download.

```
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  208   205 root     S    3207m  19%   0   1% python3 -m homeassistant --config /config
 3569   208 root     S     700m   4%   1   0% /config/rtsp2webrtc_v2_amd64 --ice_server stun:stun.l.google.com:19302 --
   ```

**Comment by tunerooster** [comment]
It's not the browser I was referring to, it is the HA server (running Linux)...  What machine is your `rtsp2webrtc_v2_amd64` running on?  If it is more powerful than a NUC, that would explain the 10% to 4% difference.

**Comment by tunerooster** [comment]
P.S.  Just thinking about you saying it is likely the way the browser works...

I'll bet if you unset <video src=...> and restore it (src) on each connection, that it would reset the duration counter.  Just a thought...  Thanks!

**Comment by AlexxIT** [comment]
Nuc i3 gen 10
