### ISSUE TITLE
Too many colons in address

### ISSUE THREAD

**Issue by crpgbogor** [AlexxIT/WebRTC#230]
My rtsp camera entity is working fine, but the web rtc card is getting this error:

![image](https://user-images.githubusercontent.com/14017328/147720564-dd56c381-c797-401c-ba98-7c95d91a561c.png)

**Comment by AlexxIT** [comment]
So. The problem's been described pretty well. Too many colons in the address.

**Comment by crpgbogor** [comment]
Thanks. This is my config, is there anything I am missing?

Config.yaml

  - platform: generic
    name: camerartsp
    still_image_url: http://xx.xx.xx.xxx:xxxx/stream/snapshot.jpg
    stream_source: rtsp://username:password@10.10.10.111:554/h264_vga.sdp
    verify_ssl: false
    username: "username"
    password: "password"
    authentication: digest
    
    

Card:

type: custom:webrtc-camera
entity: camera.camerartsp

**Comment by AlexxIT** [comment]
You have hidden the URL, in a WebRTC error. Is it similar to the URL in your generic config?

**Comment by crpgbogor** [comment]
yes, they are both the same url, just different path and port

**Comment by AlexxIT** [comment]
Try remove port from URL. Because it is default port

**Comment by crpgbogor** [comment]
still the same response (too many colon in address). I also tried removing the username and password but it gets invalid authentication

**Comment by crpgbogor** [comment]
The problem is probably with my camera. I use tp link nc220. https://github.com/reald/nc220
I changed user to admin and now receive this error...

![image](https://user-images.githubusercontent.com/14017328/147750124-ee694be8-306c-4ed5-aa15-713f952ade33.png)

**Comment by AlexxIT** [comment]
Is your link work in VLC player?

**Comment by ra-pha** [comment]
Just to chime in here as I had the same issue with my Reolink NVR.

Changing the password of the NVR to something simpler (without special chars) did the trick for me. It was a long struggle to get to that point. 😅 Also left out the port since 554 is the default port for the protocol.

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc
