### ISSUE TITLE
Aspect ratio set

### ISSUE THREAD

**Issue by nagyrobi** [AlexxIT/WebRTC#232]
Please add an option to enforce card's aspect ratio, similar to HA's picture entity card.

My Hikvision camera's substream has an aspect ratio of 4:3 while the video itself is actually 16:9, and it appears vertically stretched. 

If we could set the card height not to reszize automatically to video's aspect, but instead, with optional parameter allow setting a custom card aspect ratio (for 16:9 this is 1.78) it would be great.

VLC displays the stream correctly but I'm sure there's a glitch in the stream itself. No way to fix it in the camera (could use the main stream of 2K resolution, that has the correct ratio, but it's too much for Lovelace, useless here. Substream is enough.)

**Comment by nagyrobi** [comment]
I've got partial results with:
- set `object-fit: fill;` in the CSS of the video (I think [here](https://github.com/AlexxIT/WebRTC/blob/7085fb4c737eb7a348418d1ff23aba2e3529db04/custom_components/webrtc/www/webrtc-camera.js#L455))
- set `width: 100%;` for `ha-card`

**Comment by AlexxIT** [comment]
Same as #21 
If you know JS enough, you can propose the fix

**Comment by nagyrobi** [comment]
Me neither. The problem is that the two changes above do the correct ratio, but in Lovelace bottom of the card remains black.

**Comment by AlexxIT** [comment]
So we waiting some JS guru :)

**Comment by nagyrobi** [comment]
Posted something to https://github.com/AlexxIT/WebRTC/issues/21#issuecomment-1008124553
