### ISSUE TITLE
Request Status Icon to be optional

### ISSUE THREAD

**Issue by tzeryin1981** [AlexxIT/WebRTC#233]
Request to hide the status icon.
Status icon over lapping when intergrate into custom:button card 
![Screenshot_20220106-224327_Home Assistant](https://user-images.githubusercontent.com/96242882/148400456-0a77768f-d06f-4c9b-8d09-cbc6e5c17062.jpg)

**Comment by AlexxIT** [comment]
The status icon shouldn't be so big

**Comment by AlexxIT** [comment]
Should be fixed in v3
