### ISSUE TITLE
How to initiate a desktop stream from VLC?

### ISSUE THREAD

**Issue by chilman408** [AlexxIT/WebRTC#235]
I'm trying to stream a desktop from an Ubuntu Box using VLC and this command:
`cvlc screen:// :screen-fps=15 :live-caching=450 :sout='#transcode{vcodec=h264,venc=x264{qp=21},acodec=none,scodec=none}:rtp{sdp=rtsp://:8554/ch0.h264}' :no-sout-all :sout-keep`

This stream fine to the Picture-Entity card.

But when using Webrtc-camera card, I'm getting this error:
`ERROR: Camera send statusRTSP/1.0.461 Client error`

Can anyone tell what I should change to make this work with WebRTC?

**Comment by chilman408** [comment]
Hi, wondering if anyone could help out with this.  I'm trying to get a VLC stream working, let me know if there is anything from the commandline perspective that I can change to make this work.

**Comment by AlexxIT** [comment]
VLC seems to have incorrect support for the RTSP specification

**Comment by chilman408** [comment]
Thanks, Do you have specifics on which part is not correct?  I can connect with VLC to see if I can get something resolved.

The odd thing is that the regular camera card in HA support the VLC RTSP stream but not this.

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc

**Comment by AlexxIT** [comment]
Closed because no response
