### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by atv2016** [AlexxIT/WebRTC#237]
1. What does the webrtc create link exactly do ?
2. I can cast great with Sansco CCTV RTSP streams if i lower the codec to non 1080P for a firs generation chrome cast. If i try to do the same with eufy it will display some message about codec. 

Is there any way of having eufy2c/indoor/pan&tilt be casted as well ? It should work as if i cast it from google home assistant it displays fine. Is this something in webrtc ?
3. Can the dash cast startup logo be removed? I feel it adds to the general startup time of the cast. At the very least it looks like product placement.

Many thanks for a cool piece of software!

**Comment by AlexxIT** [comment]
1. Create permanent link to camera for access without auth
2. I don't know
3. This is 3rd party app. I can't change its behavior
