### ISSUE TITLE
Working Cameras

### ISSUE THREAD

**Issue by tunerooster** [AlexxIT/WebRTC#24]
If you want, you can add:
```
Yi 1080p Outdoor Hi3518e Chipset (with hack)
Yi 1080p Indoor (9FUS) (with hack)
```
To the list of known working cameras.

**Comment by AlexxIT** [comment]
Thanks, they already there

**Comment by tunerooster** [comment]
Ah...  My rendering of: `https://github.com/AlexxIT/WebRTC` shows only:
```
Yi 1080p Dome Hi3518e Chipset with hack
Yi 1080p Dome MStar Infinity Chipset with hack
```
Or are you meaning Domes covers Outdoor?  No need to answer.  Just wanted
to let you know.

Best...

**Comment by AlexxIT** [comment]
I think all cameras with Hi3518e and MStar chipset supported. No need to list them separately

**Comment by tunerooster** [comment]
I would take off "Dome" then, as the Dome is a specific camera.
