### ISSUE TITLE
Question on how to troubleshoot 

### ISSUE THREAD

**Issue by KendallStauffer** [AlexxIT/WebRTC#240]
I have a home assistant on a raspberry pi 4 b 8g and less than 30 devices, only 2 cameras.  When I install the webrtc camera component the system becomes very slow. it is a very vanilla installation.  I tried enabling system monitor and cpu and swap look fine. I am wondering how I can troubleshoot and and find out what I might be doing wrong.

**Comment by KendallStauffer** [comment]
Update - I installed latest homeassistant update, 2021 12 10 and it seems to work now!! Let me know if you have any ideas about troubleshooting if anything like that happens again.

**Comment by AlexxIT** [comment]
I think this is just a coincidence and has no connection to webrtc
