### ISSUE TITLE
 Problems loading the image

### ISSUE THREAD

**Issue by marcinwrobel** [AlexxIT/WebRTC#241]
On one of my cameras I get this error, after a few seconds the image is loaded.

ERROR. NotSupportedErrror: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="avc1.000000") is unsupported.

![image](https://user-images.githubusercontent.com/7246779/149902570-6230f6b5-fa15-45bc-b0de-9afac8a68163.png)

**Comment by AlexxIT** [comment]
#155
