### ISSUE TITLE
Unable to see stream on iPhone externally via nabu casa

### ISSUE THREAD

**Issue by julet85** [AlexxIT/WebRTC#246]
RTSP stream works fine on iPhone while connected to LAN. Also works fine in browser while connected externally. It appears that just iPhone is unable to see stream. I am using nabu casa for external connection. No errors in the logs.

Any idea how to resolve this issue? Apologies if this has already been answered somewhere. I did have a look at the FAQs but did not find anything that specifically resolves my problem.

**Comment by AlexxIT** [comment]
> Also works fine in browser while connected externally

Works fine in iPhone browser? Or PC?

**Comment by chudystg** [comment]
I have the same problem on iOS 15.4 App HA and Safari external network stream not working. Local on LAN is ok. Older iPhone with iOS 12 works ok locally and externally. I noticed the problem from updating to iOS 15.3

**Comment by AlexxIT** [comment]
@chudystg you need to check external access in exact same conditions. Same WiFi network or same mobile operator.

**Comment by robsalasco** [comment]
same problem here only local works I'm on the latest ios

**Comment by thinkjk** [comment]
I'm running into the same issue with my iPhone going through nabu casa. It works fine on Wi-Fi and doesn't work on mobile.

**Comment by dabm-git** [comment]
The bug is still there, it seems to be an iOS issue as the streaming works on Android devices.

**Comment by chudystg** [comment]
For me, the Orange operator turned out to be the problem. The problem was solved by activating the Orange VPN service for my Orange phone.

**Comment by julet85** [comment]
Took a while to figure this out but in my case it was the carrier, tried a SIM card from another carrier and was able to stream video externally via Nabu Casa.

**Comment by thinkjk** [comment]
@AlexxIT I'm happy to send any logs over. I'm on Verizon Wireless

**Comment by AlexxIT** [comment]
Check my new project. It has solution for external access
https://github.com/AlexxIT/go2rtc

**Comment by thinkjk** [comment]
> Check my new project. It has solution for external access https://github.com/AlexxIT/go2rtc

Thanks! Does this mean that WebRTC development will stop? Unfortunately it looks like go2rtc isn't supported yet in the Frigate Lovelace card

**Comment by AlexxIT** [comment]
go2rtc is next version. It will replace this integration backend in the future. And it can be used with default Lovelace card without this integration card.
