### ISSUE TITLE
Issue with buffering every second

### ISSUE THREAD

**Issue by SeBsZ** [AlexxIT/WebRTC#249]
First of all thanks for this integration.

I have two unifi RTSP streams in my Home Assistant UI. When I enable webrtc on them, they stream perfectly but without any sound. If I disable webrtc, I get sound but every second or so I see a spinning circle and after a few seconds of spinning I see a few new frames. This is on my OnePlus Android phone with the Home Assistant app. On my desktop Chrome this mode works perfectly, there is sound and no spinning circle (buffering). I require audio though...

Is there a way maybe to increase the buffer size to prevent this? Or could something else be causing this?

**Comment by maxi1134** [comment]
I tried several tablets over the last few days;
Samsung Tab A8
Samsung S6 Lite
Samsung S7 FE
and Samsung S8 
(They looked at me funny at bestbuy)

All have this bug for me.
The streams all work flawlessly on Android VLC.

Does anyone have an idea?

**Comment by nsuresh81** [comment]
OK, I finally resolved my problem.
My Fire HD 10 9th generation was running an older version of webview.
All you have to do is to check for latest updates and update your OS, this will also install the latest version of the webview.
After doing that I have smooth video playback and I'm very happy.
Hope this solution works for others. 
Update your OS and this will also update the webview.

**Comment by maxi1134** [comment]
> OK, I finally resolved my problem. Fully Kiosk Browser on my Fire HD 10 9th generation was using an older version of webview. All you have to do is to check for latest updates and update your Fire OS (or any OS your tablet uses), this will also install the latest version of the webview. After doing that I have smooth video playback running on fully kiosk browser and I'm very happy. Hope this solution works for others. Update your OS and this will also update the webview.

Could you share your webview version? Mine is updated and I get this problem on both a S8 and a S7FE, which should be able to run this I assume

**Comment by AlexxIT** [comment]
When you disabling WebRTC - you using MSE. **MSE Cons: jumps over frames**. I don't know if this can be fixed

**Comment by cliffjao** [comment]
I'm running into this issue too. What's interesting to me is that I don't see the same issue with RTSPtoWeb library when using MSE on the same stream. Any idea why that might be the case? @AlexxIT

**Comment by nsuresh81** [comment]
The webview version on my Amazon firetab was very old. I updated the OS and it's OK now. The OS update updated the webview.

Sent from Yahoo Mail on Android 
 
  On Thu, 14 Apr 2022 at 5:52, ***@***.***> wrote:   


I'm running into this issue too. What's interesting to me is that I don't see the same issue with RTSPtoWeb library when using MSE on the same stream. Any idea why that might be the case? @AlexxIT

**Comment by AlexxIT** [comment]
RTSPtoWeb may have some fixes and new library versions
