### ISSUE TITLE
Feature request: HEVC/H265 support

### ISSUE THREAD

**Issue by vampywiz17** [AlexxIT/WebRTC#252]
Hello there,

I found two of repos, that (if i understand correctly) able to use h265 in webrtc.

https://github.com/metartc/metaRTC

https://github.com/metartc/yangwebrtc

What do you think, it possible to use it in your app?

Also i found this chrome version(it also avaliable on Windows: https://github.com/macchrome/winchrome), that support h265/hevc playing. (i tested it with h265 sec. cam, and works well)

https://github.com/macchrome/linchrome/

**Comment by rbray89** [comment]
The stream uses whatever the RTSP stream does. There is no transcoding, so it just depends on what the camera is setup for.

**Comment by vampywiz17** [comment]
@rbray89 Yes, but if i set camera to HEVC and open it in a browser that support HEVC (like Edge, or above chromium) this addon say that is not supported codec. In this browsers, other HEVC streams play it without any problem.

**Comment by gfduszynski** [comment]
The fact that browser can handle HVEC in video playback does not mean that it will work with WebRTC.

Repos that you linked to are to WebRTC implementations that look like they can support HVEC, however browsers such as Edge/Chrome/FF have their own implementation that we have no influence over.

If your camera allows it, I would recommend to use secondary stream with H264 and primary with H265.

**Comment by AlexxIT** [comment]
You sent link to MetaRTC. This is some kind of 3rd party technology. I think this requires development of separate component.

**Comment by vampywiz17** [comment]
@AlexxIT 

Sorry to open these issue again, but now chrome support webRTC (with experimental flag)

https://chris.hiszpanski.name/posts/is-webrtc-hevc-supported/

I tested it with chrome 130 and seems work. but if i set your module to a hevc stream, it can not switch to RTC.

**Comment by AlexxIT** [comment]
@vampywiz17 Thanks! Nice news. I will check this https://github.com/AlexxIT/go2rtc/issues/1439
