### ISSUE TITLE
Question my rtsp play flawless in HA but not in WebRTC but other users can (same cameras)

### ISSUE THREAD

**Issue by thorrrr** [AlexxIT/WebRTC#253]
HI Alex
I have followed the docs and I know you say it may not work. But other users with same setup do use WebRTC so i am confused.
I have tried the direct rtsp direct link config in which i get this error see [here](https://xbackbone.daddycloud.co.uk/Piqa4/xAweduGu51.jpg). I have also tried with camera entity which just gives blank page.
Would love to get it working, if possible, my only thought is i do run behind a reverse proxy. But when trying this out it was over local network. As mentioned, my direct rtsp stream no issue so would appreciate some guidance to get it working if it is possible

My Cameras are Hik Vision DS-2CE72HFT-F28 & DS-2DE3A400BW

I can see Bunny video with message it ends in Jan 2022 :)

Log
2022-02-07 09:34:38 ERROR (MainThread) [frontend.js.latest.202202030] http://192.168.23.137:8123/frontend_latest/38188e47.js:2:308 Uncaught TypeError: Cannot convert undefined or null to object

**Comment by AlexxIT** [comment]
hvc1 is H265 - unsupported #71
