### ISSUE TITLE
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry'

### ISSUE THREAD

**Issue by pergolafabio** [AlexxIT/WebRTC#254]
Hi,

creating a new issue, it looks like this one : https://github.com/AlexxIT/WebRTC/issues/30

But the error is different, it also happens when i clear cache or incognito mode... 

```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "webrtc-camera" has already been used with this registry
    at https://xxx8123/hacsfiles/webrtc/webrtc-camera.js:692:16
```

**Comment by pergolafabio** [comment]
hey @AlexxIT , any idea what could cause this? on every refresh of the page, i see those events in my log file

**Comment by AlexxIT** [comment]
`/hacsfiles/webrtc/webrtc-camera.js` this is not from my repo

**Comment by pergolafabio** [comment]
hey @AlexxIT  , how do ypu mean?

its this file : 

https://github.com/AlexxIT/WebRTC/blob/master/custom_components/webrtc/www/webrtc-camera.js

**Comment by pergolafabio** [comment]
can you open issue again?

**Comment by AlexxIT** [comment]
My component don't put this file to `/hacsfiles/`

**Comment by pergolafabio** [comment]
Yeah, I moved it manually :-)

**Comment by AlexxIT** [comment]
So you made this bug with your own hands

**Comment by pergolafabio** [comment]
How do you mean? I just copied that file manually, like I do with other resources?

**Comment by pergolafabio** [comment]
i also use yaml method, so if i install your component, it doesnt add it to resources, i need to do it manually in my resources.yaml file

**Comment by AlexxIT** [comment]
The error means that the component is initialized twice

**Comment by pergolafabio** [comment]
Ok , that's strange... In your readme, you say it's added to resources... But since i use yaml method I can only add it that way...

Gonna look into it tomorrow, thnx for pointing me to the direction

**Comment by AlexxIT** [comment]
You need to add it manually only if you have some problems.
The right url: `/webrtc/webrtc-camera.js?v2.3.0`

**Comment by pergolafabio** [comment]
If i install your component, the .js file isnt copied to my \config\www folder, its still present in the custom_component folder
thats why i copy it over to the community folder in www, and then i add it manually to the resources

**Comment by pergolafabio** [comment]
Hmm, i still see the issue, i have it now in resources.yaml like below

```
  - url: /hacsfiles/webrtc/webrtc-camera.js?v2.3.0
    type: module   
```

It needs to be there, otherwise the custom lovelace card doesnt load at all
you said earlier, it might be causing be because its intiliaized twice ... i have indeed 2 webrtc cameras on one view, so i disabled one card, but it still orrcurs, but only when i do a refresh of the page

**Comment by AlexxIT** [comment]
Mine JS file hosted from component folder. You don't need to copy it anywhere.

**Comment by pergolafabio** [comment]
Ah ok, do it doesn't need to be in resources either?

**Comment by AlexxIT** [comment]
Component can add it to resources automatically. But sometimes it not work with Lovelace mode yaml.

**Comment by pergolafabio** [comment]
Yes, I use yaml mode... If I don't add it to resources manually, card doesn't load at all, doesnt mather in what directory...
