### ISSUE TITLE
Dashcast no longer seems to work on Google Nest Hub

### ISSUE THREAD

**Issue by tbrausch** [AlexxIT/WebRTC#255]
Up until a few months ago, I was able to use DashCast to display a camera on the Google Nest Hub whenever a motion event occurred.  Since then, the camera is displayed, but only as a single frame (no video).  A current snapshot of the camera is displayed, and theere is a Play button on the bottom left of the screen.  However, pressing the play button doess not do anything.

If a try to cast a view containing a WebRTC camera, the view comes up but continually displays "Waiting for WebRTC Card to Load".  Anyone else seeing this behavior?

**Comment by pergolafabio** [comment]
yes, known issue

https://github.com/AlexxIT/WebRTC/issues/88 , you can close this one

**Comment by AlexxIT** [comment]
@pergolafabio thanks. Hope to find time to fix it
