### ISSUE TITLE
Intermittent: fails to play

### ISSUE THREAD

**Issue by tunerooster** [AlexxIT/WebRTC#257]
First, I have been highly impressed and satisfied with this plugin. Before this, all options were totally inadequate. Thank you for this!

I have, however, encountered an intermittent failure where the video fails to play (says: no video). In trying to troubleshoot this I encountered the following:

Running netstat -l displayed over 900 of the following lines:
udp 0 0 0.0.0.0:5353 0.0.0.0:*
Running lsof -p <pid of rtsp2webrtc> similarly displayed > 900 lines of this:
rtsp2webr 14132 root 174u IPv4 94851035 0t0 UDP *:mdns
After killing rtsp2webrtc (it restarts automatically), netstat shows only 4 listeners and lsof shows only 2 open fd's.

I don't have any additional data at present, but I can run any additional diagnostics you would like, when it re-occurs.

Please advise...

P.S. I am running HA 2021.12.8
I couldn't find how to display the rtps2webrtv version, but a ps shows rtsp2webrtc_v5_amd64

UPDATE:
Feb 09 2022:  It has happened again... Almost 500 repeating lines of:

rtsp2webr 22578 root  410u     IPv4 142154278      0t0       UDP *:mdns 
rtsp2webr 22578 root  411u     IPv4 142158064      0t0       UDP *:mdns 
rtsp2webr 22578 root  412u     IPv4 142156263      0t0       UDP *:mdns 
rtsp2webr 22578 root  413u     IPv4 142158911      0t0       UDP *:mdns 
rtsp2webr 22578 root  414u     IPv4 142159415      0t0       UDP *:mdns 
rtsp2webr 22578 root  415u     IPv4 142158525      0t0       UDP *:mdns 
rtsp2webr 22578 root  416u     IPv4 142160927      0t0       UDP *:mdns 
...

When it is working, I see one of the above lines for each video I have open and streaming.
So perhaps, when it fails, it is not closing down an open FD or something.  But of course, you will know better than I...

Please advise...

**Comment by AlexxIT** [comment]
**no video** means your camera don't send keyframe during 10 seconds.

**Comment by tunerooster** [comment]
The issue I was reporting was the over 500 instances...  Not the "no
video", which may or may not be the cause of the issue.

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc

**Comment by AlexxIT** [comment]
Closed because no response
