### ISSUE TITLE
Just wanted share what worked for me.

### ISSUE THREAD

**Issue by matt-desmarais** [AlexxIT/WebRTC#261]
I am using a raspberry pi zero 2 and 5mp picam
I used this software [v4l2rtspserver](https://github.com/mpromonet/v4l2rtspserver)
I followed most of this [tutorial](https://siytek.com/raspberry-pi-rtsp-to-home-assistant/)
there was way too much of a delay for my taste using the ffmpeg camera integration so I went searching and found WebRTC. My camera works great minimal delay, it also works remotely through nabucasa.

Thank you!

**Comment by AlexxIT** [comment]
Thanks!
