### ISSUE TITLE
Does the stream goes to the ICE server and back?

### ISSUE THREAD

**Issue by fgonza2** [AlexxIT/WebRTC#262]
What is the role of the ICE server? will this work locally w/o internet connection?

**Comment by gfduszynski** [comment]
It's role is to help with NAT traversal - there 2 types of servers:
- STUN
- TURN

see [this](https://developer.signalwire.com/apis/docs/stun-vs-turn-vs-ice) for explanation.

In any case, it's possible host your own turn/stun server.
It's possible to run [WebRTC without internet connection](https://stackoverflow.com/questions/30742431/webrtc-on-isolated-lan-without-ice-stun-turn-server).

**Comment by fgonza2** [comment]
thanks so much for the link and the explanation
