### ISSUE TITLE
ERROR: RTSP Client Unauthorized 401

### ISSUE THREAD

**Issue by sharonoren1** [AlexxIT/WebRTC#265]
Hi, 
I got error message "ERROR: RTSP Client Unauthorized 401"
The same URL works well with VLC
![image](https://user-images.githubusercontent.com/77583793/154854391-5582e511-1c6e-4673-85e9-736b3b2b02c9.png)

Regards,
Oren

**Comment by AlexxIT** [comment]
Do you have auth in your camera url? Maybe you have special characters there...

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc

**Comment by AlexxIT** [comment]
Closed because no response
