### ISSUE TITLE
[Feature Request] Add option for persistent server

### ISSUE THREAD

**Issue by rbray89** [AlexxIT/WebRTC#266]
I have a couple of Foscam cameras that are very finicky using this integration, but work great using the RTSPtoWebRTC integration.

The difference is that the RTSPtoWebRTC maintains the RTSP stream and WebRTC sever binary persistently rather than spinning it up once viwed. I think there may be a race condition. At any rate, having the option to preload or persistently run the webRTC backend would be greatly appreciated.

**Comment by AlexxIT** [comment]
There may be a problem with key frames. Ideally, their value should be no more than 2 seconds. Can you check your camera config?

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc

**Comment by rbray89** [comment]
Hmmm... So I'm seeing *worse* behavior unfortunately. The image only seems to render on the i-frames, so framerate is absolutely terrible. 

My hikvision Cameras work better with go2rtc though.

Trying to figure out if it is just these cameras or if this is a more systemic issue.

**Comment by AlexxIT** [comment]
Should be fixed in v3
