### ISSUE TITLE
Invalid URL escape '%'

### ISSUE THREAD

**Issue by gvillo** [AlexxIT/WebRTC#267]
Facing an issue `entity` because my camera's password has a '%' on it, and it's throwing an error while trying to parse the URL, e.g. 'rtsp://username:passwordwith%@192.168.0.22:554/video'

**Comment by AlexxIT** [comment]
The advice to use a percent-encoded equivalent is correct

**Comment by jokerigno** [comment]
I was facing same issue and using @AlexxIT  advice now the stream works.
