### ISSUE TITLE
Error: InvalidStateError Failed to execute 'addSourceBuffer' on  'MediaSource': the MediaSource's readyState is not 'open'

### ISSUE THREAD

**Issue by drkshen** [AlexxIT/WebRTC#268]
First of all thanks for this integration again.

I m getting this error message:

Error: InvalidStateError Failed to execute 'addSourceBuffer' on 
'MediaSource': the MediaSource's readyState is not 'open'

the video shows w/ green image, but after few seconds or few reload the video shows.
how do i fix this loading problem. thx advance!!

**Comment by AlexxIT** [comment]
All fixes in latest release https://github.com/AlexxIT/WebRTC/releases/tag/v2.3.0
Please reopen issue if it still actual

**Comment by Aviv943** [comment]
@AlexxIT looks like it still happens. I'm on 2022.5.5, WebRTC 2.3.0 and the issue is happening on chromuim browsers.
