### ISSUE TITLE
Port Forwarding Question

### ISSUE THREAD

**Issue by maxi1134** [AlexxIT/WebRTC#269]
I see that I can forward ports 50000<->51000 to get webRTC to work on my external access.

My question is, should this be forwarded toward my NGINX reverse proxy, or my HASS instance directly?

**Comment by chasinmytail** [comment]
Any update on this? I’m having similar issues I th8nk.
 I’m using HA Proxy and OpnSense but for the life of me I can’t get it to work with iOS app from external connection

**Comment by gfduszynski** [comment]
I would say to your HASS instance directly, that's how I have mine setup.

**Comment by AlexxIT** [comment]
This should be forwarded on your router
