### ISSUE TITLE
KeyError: 'allow_cors' (github releases bug)

### ISSUE THREAD

**Issue by kyledong** [AlexxIT/WebRTC#270]
can't  load WebRTC with latest homeAssistant 2022.3.2 , Error message blow ? any hlep ?thanks.
Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera ([documentation](https://github.com/AlexxIT/WebRTC), [issues](https://github.com/AlexxIT/WebRTC/issues))
First occurred: 12:12:42 (1 occurrences)
Last logged: 12:12:42

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by xrays72** [comment]
Hi
Download https://github.com/AlexxIT/WebRTC/releases/tag/v2.2.0, extract archive and replace all files from folder custom_components/webrtc

**Comment by andorardo** [comment]
I using `master` from HACS, and it seems to be working. What's the reason the 2.2.0 isn't showing up in HACS yet?

**Comment by AlexxIT** [comment]
It's a github bug. Some repositories are missing the latest release.

This problem fixed in latest component release
https://github.com/AlexxIT/WebRTC/releases/tag/v2.2.0

But this release has disappeared from the github API.

I hope the next release will fix this situation. And hope to find time for it.

**Comment by Mark612** [comment]
v2,2.0 works, most of the time. However the mobile app and sometimes the web interface fails to load webrtc. Restarting and refreshing the browser will usually solve it.

**Comment by marcoahp** [comment]
I can't install WebRTC v2.2.0 only v2.1.0. Master version don't help. I get 'allow_cors' error too.

**Comment by savikko** [comment]
Latest version works great.

Problem is that latest version is not visible on releases on github page.

Just download current repo from github and then extract webrtc -folder to your `custom_components` directory and then proceed with installing the integration.

**Comment by Hobbit44** [comment]
You can create the release manually from the tag that exists. That should close this ticket.
