### ISSUE TITLE
Wyze Cam Configuration

### ISSUE THREAD

**Issue by parthmodi** [AlexxIT/WebRTC#275]
How do you get the Wyze cam configured using this for homeassistant? I'm using docker-wyze-bridge and can get the signaling URL and token from there. Not sure how to apply it here.

**Comment by crocobau** [comment]
You must install Rtsp firmware on Wyze camera.
Search on official Wyze site how to proceed.
(Wyze cloud mode is working in same time with Rtsp but have limited AI features)

**Comment by skynet01** [comment]
With RTSP firmware Wyze and this Integration work great you'll have a url like rtsp://user:pass@172.16.3.111/live

**Comment by AlexxIT** [comment]
Maybe this link helps
https://support.wyze.com/hc/en-us/articles/360026245231-Wyze-Cam-RTSP
