### ISSUE TITLE
Cannot disable or hide the play/pause button 

### ISSUE THREAD

**Issue by ONBET** [AlexxIT/WebRTC#276]
I have one RTSP H264 camera connected to webrtc card but I doesn't able to hide the media control
![image](https://user-images.githubusercontent.com/95070936/158835143-2f4427cf-d73c-466a-b74c-300c62139b8c.png)

Basically I just want to display the camera live feed and block user tap/hold the card, only live feed 

I tried set tap_action, double tap action and hold action to false but no luck no work

**Comment by AlexxIT** [comment]
Use `ui: true` setting
