### ISSUE TITLE
Can't setup after install

### ISSUE THREAD

**Issue by Harvsch** [AlexxIT/WebRTC#280]
core-2022.3.5
supervisor-2022.03.5
Home Assistant OS 7.5
Hardware odroid XU4
```
`Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera (documentation, issues)
First occurred: 20:58:50 (1 occurrences)
Last logged: 20:58:50

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'<!--`
```

**Comment by howelljiang** [comment]
## System Health

version | core-2022.3.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.92-v8
arch | aarch64
timezone | Asia/Shanghai

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | failed to load: unreachable
GitHub Web | ok
GitHub API Calls Remaining | 4390
Installed Version | 1.23.0
Stage | running
Available Repositories | 1080
Downloaded Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.5
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.5
docker_version | 20.10.9
disk_total | 118.3 GB
disk_used | 6.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Samba share (9.5.1), Node-RED (11.1.0), Mosquitto broker (6.0.1), Terminal & SSH (9.3.0), Zigbee2mqtt (1.23.0-1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 6
views | 2
mode | storage

</details>

<details><summary>Xiaomi MIoT</summary>

logged_in | true
-- | --
can_reach_micloud_server | ok
accounts_count | 1
account_devices_count | 12
added_devices | 6

</details>

此错误来自自定义集成。

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera (documentation, issues)
First occurred: 19:56:56 (1 occurrences)
Last logged: 19:56:56

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by tgerardot** [comment]
Having same issue as above.

**Comment by 02987440** [comment]
here to

**Comment by pimp1310** [comment]
yeah the integration dont work anymore with the newest Homeassistant, is the developer not here anymore?

**Comment by mplogas** [comment]
@pimp1310  wow, please consider rephrasing your comment. the dev is still doing this on his spare time. a quick check of his profile would have revealed why he isn't exactly able to support any of his projects rn.

**Comment by blalor** [comment]
dupe: https://github.com/AlexxIT/WebRTC/issues/156

**Comment by Sarunas88** [comment]
yea doesn't work for me too anymore

**Comment by savikko** [comment]
Latest version works great.

Problem is that latest version is not visible on releases on github page.

Just download current repo from github and then extract webrtc -folder to your `custom_components` directory and then proceed with installing the integration.

**Comment by NoMacSec** [comment]
> Latest version works great.
> 
> Problem is that latest version is not visible on releases on github page.
> 
> Just download current repo from github and then extract webrtc -folder to your `custom_components` directory and then proceed with installing the integration.

Can confirm this workaround got it working for me. Thanks @savikko

**Comment by K3str3l** [comment]
Thanks @savikko back up and running!

**Comment by Sarunas88** [comment]
RTSPtoWebRTC-Server 

*RTSPtoWebRTC Server URL z.B. https://example.com*

i am a bit confused, to install it it is requiring a server ? what am i missing ? sorry cant find this step anywhere

**Comment by jopvanraaij** [comment]
Had the same issue, but Solved!

Could not select v2.2.0 (only v2.1.0) in HACS. Solved it by using 'master' instead of a specific version.

**Comment by FirstRulez** [comment]
I am still having issues with the add-on. As I installed using HACS I swapped the download channel to master as recommended above, and updated, but having done so the version number in manifest.json shows as  "version": "v2.0.2", and the same error message appears in my HASS logs.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/issues/270#issuecomment-1064862905

**Comment by jopvanraaij** [comment]
@FirstRulez Might need to do a HA restart and/or hard refresh of the UI. I remember doing that quite a few times (not sure it really helped).

**Comment by FirstRulez** [comment]
Thank you all. v2.3.0 is now showing in HACS and has sorted the problem
