### ISSUE TITLE
Sound issues on iPad iOS 15+

### ISSUE THREAD

**Issue by besiktas97** [AlexxIT/WebRTC#285]
I am using WebRTC for a long time now. The main reason I am started using it was the lag issue and the no sound issue of my Foscam camera with Home Assistant.
Lately I am having issues with the sound on our wallmounted iPad, that the sound is doing crazy. I hear a lot of noises but not the sound of my son for example. I already re-downloaded the master version or deleted the integration from hacs and reinstalled it. Also used the add-on in HA, but the problem didn't solved my issue. On my mobile with the dedicated HA app I don't have the problem. Anyone can help with it?

**Comment by besiktas97** [comment]
Any response someone?

**Comment by AlexxIT** [comment]
The stream is WebRTC or MSE?

**Comment by besiktas97** [comment]
Streaming is webrtc. I am using the config of webrtc with the rtsp path. What do you mean with MSE?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC#status-icons

**Comment by besiktas97** [comment]
I am using the webrtc on the dedicated app on iOS.

**Comment by AlexxIT** [comment]
What version of OS is on your mobile phone? What is your camera model?

**Comment by besiktas97** [comment]
On my phone is 15.4.1 and on the wallmounted ipad is 15.3.1.
Model of camera is: Foscam C1

**Comment by AlexxIT** [comment]
Sound problems seem to be quite common with Apple devices
https://github.com/AlexxIT/WebRTC/issues/163

I don't know solution yet. You can try the built-in HA component. Maybe it don't have this problems
https://www.home-assistant.io/integrations/rtsp_to_webrtc/

**Comment by besiktas97** [comment]
It also have the same issue 😩. I already try that one out. It worked for almost a year perfectly. Then I will check it out myself thanks Alex.

**Comment by besiktas97** [comment]
Its working with the new iOS firmware 15.4.1. Thanks for the effort Alex!
