### ISSUE TITLE
Option to restrict ICE candidates

### ISSUE THREAD

**Issue by gfduszynski** [AlexxIT/WebRTC#286]
I would be great if it was possible to restrict list of ICE candidates.
Currently my home assistant instance is hosted as docker container and is connected through 2 networks:
- IoT vlan
- nginx reverse proxy network

As a result 3 candidates are presented to the browser (about:webrtc in  firefox)
- IoT vlan (ok)
- nginx reverse proxy (not ok)
- public ip (ok)

This is probably a reason why sometimes I have issue with the video, but refreshing the page often helps.

**Comment by gfduszynski** [comment]
I can see you have a code on JS side that is supposed to remove docker IP's. 
However it does not work for my IP of 172.16.0.15 (IP is not static in this subnet)

**Comment by AlexxIT** [comment]
I don't understand what you mean about "nginx reverse proxy network". Nginx proxies only HTTP(S) port. WebRTC uses other UDP ports for transmit video data.

It's not a problem when you have "wrong" ICE candidates. The WebRTC will check all of them.

**Comment by gfduszynski** [comment]
nginx reverse proxy network - refereed to docker network that only purpose is to connect [nginx container](https://hub.docker.com/r/jwilder/nginx-proxy) with other containers requiring proxy.

You are right that this is not critical. I'm trying to solve this minor annoyance on the asterisk side.

**Comment by AlexxIT** [comment]
You Hass container should use network host mode (whole network access without proxing).

**Comment by gfduszynski** [comment]
Probably should add, that it already works/ed (without host network). I've migrated to [rtsp to webrtc](https://www.home-assistant.io/integrations/rtsp_to_webrtc/) due to the fact that it allows me to neatly avoid some other issues with SIP card ;)

Feel free to close this issue, and thank you for your work!
