### ISSUE TITLE
"Cannot get url of stream..."

### ISSUE THREAD

**Issue by robertoleonardo** [AlexxIT/WebRTC#288]
HASS 2022.4 seems to break this integration - all of my cameras say "cannot get url of stream [camera name]..." over a black box instead of the video. a few minutes after a restart, it changes to "restart connection. have re installed master version but no luck. don't seem to have any errors in my logs relating to this.

**Comment by AlexxIT** [comment]
I checked the latest version. It's working.
I think you using `entity: camera.xxx` in your config. Via which integration is the camera connected?

**Comment by robertoleonardo** [comment]
i figured it out - something changed in 2022.4 such that if you have your cameras configured via yaml, it no longer ignores a bad still image url (which apparently mine were bad). previously i guess it just ignored it but as of 2022.4 it won't load them. so if anyone else has this issue -- it can be fixed by just removing the still image url from your yaml or, alternatively, just adding them via the generic camera integration in the UI (leaving the field for still image url blank). thanks for everything alex!
