### ISSUE TITLE
iOS black screen

### ISSUE THREAD

**Issue by peledzius** [AlexxIT/WebRTC#289]
When stream is loaded in iOS, it often shows black screen. When you press pause and play button, video reappears and plays fine. 

I think it has something to do with custom video player UI, because I never noticed this behaviour with `ui: false`. 

![IMG_E1584](https://user-images.githubusercontent.com/24360494/162558104-1f198222-4916-409e-b140-3a8cb650777c.JPG)

```
type: custom:webrtc-camera
entity: camera.living_room
mse: false
ui: true
```

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc

**Comment by AlexxIT** [comment]
Should be fixed in v3
