### ISSUE TITLE
iOS unable to pause video anymore

### ISSUE THREAD

**Issue by peledzius** [AlexxIT/WebRTC#292]
With `ui: true`, if you press pause video button in iOS, video pauses for a moment and then continues to play. 

This behaviour started after I updated to **v2.3.0**

**Comment by AlexxIT** [comment]
What version iOS do you have?

**Comment by peledzius** [comment]
15.3.1

**Comment by AlexxIT** [comment]
Pause option deprecated from v3. Because it is useless. Data continues to transfer from the server to the browser
