### ISSUE TITLE
Richiesta PTZ per Ezviz C6TC

### ISSUE THREAD

**Issue by Alex230177** [AlexxIT/WebRTC#293]
Hi, your integration is great, I was able to integrate both my Foscam C2 and ezviz C6TC perfectly.
The only thing I can't get is Ezviz's PTZ control I've tried all the examples and above but it doesn't work. could you give me a tip with some examples.
Thanks.

**Comment by srodighiero** [comment]
Up, I'm also interested

**Comment by srodighiero** [comment]
Found how directly via the card, without a script.

ptz:
  service: ezviz.ptz
  data_up:
    direction: up
    speed: 7
    entity_id: camera.ezviz_webcam_soggiorno
  data_down:
    direction: down
    speed: 7
    entity_id: camera.ezviz_webcam_soggiorno
  data_left:
    direction: left
    speed: 7
    entity_id: camera.ezviz_webcam_soggiorno
  data_right:
    direction: right
    speed: 7
    entity_id: camera.ezviz_webcam_soggiorno

**Comment by AlexxIT** [comment]
@srodighiero thanks. Also here #329
