### ISSUE TITLE
CPU spikes after installing April core-2022.4.X

### ISSUE THREAD

**Issue by besiktas97** [AlexxIT/WebRTC#295]
Since the installation of the core version 2022.4.X I have got huge CPU spikes while using this integration.
I even thought yesterday that my SD card was broken and replaced it with a SSD and still got the same issue.
After removing the integration from HACS it solved my issue and the Core CPU usage went back to normal.
I couldn't find anything in the logs that I can show you. I read a lot about the same issue from other users with the same problems and almost all of them have the same integration installed.

See this link please: https://github.com/home-assistant/core/issues/66389
The only difference is that this wasn't the core version 2022.4.X but version 2022.2.X.
Looks like it was started on that version, because my issue with webrtc was also started around january from this year.

Maybe you can check it out please why your integration is causing this issue ?

**Comment by besiktas97** [comment]
This issue is playing for a long time if I read this:

https://github.com/AlexxIT/WebRTC/issues/64

**Comment by AlexxIT** [comment]
Duplicate #64
