### ISSUE TITLE
Codec not supported for eufy camera to chromecast

### ISSUE THREAD

**Issue by atv2016** [AlexxIT/WebRTC#296]
It runs fine within HA as webrtc but once I use dashcast I get this on the chromecast.

woukd be great to get a fix for this if possible, I would be eternally grateful.
![9FA87A27-02D2-4784-85E2-C4B6668375B5](https://user-images.githubusercontent.com/16917203/164681718-cb0d922f-403e-42bf-bf3f-8be5be1a02e4.jpeg)

**Comment by atv2016** [comment]
Which is weird as the Google chromecast page says it supports it:


H.264 level 4.0 | high | AAC | aac_he | video/mp4; codecs="avc1.640028, mp4a.40.5"
-- | -- | -- | -- | --
aac_lc | video/mp4; codecs="avc1.640028, mp4a.40

https://developers.google.com/cast/docs/media

**Comment by atv2016** [comment]
Maybe this should be posted in Dashcast repo as well.

**Comment by AlexxIT** [comment]
What Chromecast model do you have? `avc1.64002a` => H.264 level 4.2 => Chromecast 1st and 2nd Gen up to level 4.1...

**Comment by TimpP-Spb** [comment]
Hello AlexxIT, i have similar problem with codec for camer. screnshot is attacehd
![error_cam](https://user-images.githubusercontent.com/64695580/169987401-189bafe5-3842-414f-944e-51c4069f1f74.jpg)

**Comment by AlexxIT** [comment]
@TimpP-Spb check #155

**Comment by AlexxIT** [comment]
@atv2016 so your camera has a very high H264 profile. Old Chromecasts doesn't support it

**Comment by AlexxIT** [comment]
You can use transcoding feature from go2rtc app. This component use it from v3

**Comment by austinliuu** [comment]
I noticed the issue after upgrading from v5.x, any solution? I put the` MSE:false` to my card but it looks like it is not working for me Nest Home Hub

**Comment by AlexxIT** [comment]
Integration v3 support video transcoding

**Comment by atv2016** [comment]
So how do I transcode? My rtsp streams to chromecast are not showing, I suppose I have to transcode from h265 to 264?
________________________________

**Comment by AlexxIT** [comment]
You can read go2rtc docs

**Comment by atv2016** [comment]
So do I install this go2rtc separately in HA?
________________________________

**Comment by AlexxIT** [comment]
You can try with built-in go2rtc. But I don't know if hardware acceleration will work.
