### ISSUE TITLE
continously reloading during streaming with Android app

### ISSUE THREAD

**Issue by Claudio1L** [AlexxIT/WebRTC#299]
HI, thank you for this great integration.

I'm not sure if duplicate of #298. But when forcing MSE (webrtc: false) I get continous reloading on Android app.
Video is showing correctly, but reload animation is contious
Integration v2.3.0

Home Assistant 2022.4.7

**Comment by AlexxIT** [comment]
This is how MSE works...

**Comment by Beylie** [comment]
Claudio1L, after the latest update of O/S, 8.2, my cameras now work with WebRTC every time. Perhaps check if yours work now?
