### ISSUE TITLE
Two sets of controls in the UI

### ISSUE THREAD

**Issue by krystiancharubin** [AlexxIT/WebRTC#3]
UI displays two sets of controls, one for video and another for audio. Is there a way to have unified controls? The audio icon on the on the main video controls seems disabled.

![WebRTC-Camera-UI](https://user-images.githubusercontent.com/17775600/114377421-a4d65480-9b54-11eb-90fe-4f8e208cca82.PNG)
![WebRTC-Camera-Code](https://user-images.githubusercontent.com/17775600/114377600-d5b68980-9b54-11eb-8892-9656ad7da2c1.PNG)

**Comment by AlexxIT** [comment]
Fixed in latest version

**Comment by timdonovanuk** [comment]
The audio icon is still disable for me?

**Comment by AlexxIT** [comment]
Because your camera audio codec doesn't supported. Check FAQ
