### ISSUE TITLE
HikVision Camera issue

### ISSUE THREAD

**Issue by ntienminh62** [AlexxIT/WebRTC#301]
Hello, I have trouble adding my HikVision cameras. I have confirm the rtsp url is working; however, I still get ERROR : dial tcp my_camera_ip: 554: i/o timeout. I have my camera on a seperate vlans. Did I do something wrong or do I have to configure my HikVision camera a certain way for this to work? I have my Home Assistant in a docker container on my nas. Please let me know. Thank you.

**Comment by AlexxIT** [comment]
Is your camera works with Generic camera integration?

**Comment by AlexxIT** [comment]
No answer...

**Comment by kakawaite44** [comment]
Hello, I have the same problem and i use a webRTC integration
