### ISSUE TITLE
What is the BEST camera to use with webrtc and gives near-realtime video in homeassistant?

### ISSUE THREAD

**Issue by atv2016** [AlexxIT/WebRTC#303]
Looking for realtime or near-realtime stream. Ideally i'd like to use it with Frigate in the future so should give a good frame rate.

**Comment by timmeh87** [comment]
im pretty sure this plugin can take any rtsp stream and make it near realtime. i just bought random cheap rtsp cameras and they all work fine

**Comment by atv2016** [comment]
Nope, doesn't work. I tried using webrtc: dash cast to cast a stream from eufy to chromecast, way to much lag. What brand did you buy ?

**Comment by shadow7412** [comment]
Do you have the same issue when looking at the dashboard directly?

**Comment by AlexxIT** [comment]
Often the quality of the camera is related to its price. The cheapest cameras, produce poor quality and implement poor standards. Usually it's cameras around $25.

Fine cameras start at $50-100. It is better to choose a camera of some well-known brand.
I had a positive experience with Dahua and Aqara cameras.
Negative experience with Realink and Sonoff cameras.
Neutral experience with Ezviz and Hikvision cameras.
Negative experience with any custom firmware on cameras.
Negative experience with noname cameras from Ali.

**Comment by timmeh87** [comment]
Hey I just noticed the bump to this thread (of closing it), after a year or so of using I would say ..

several v380 cameras seem to work "okay" (neutral), even for pt (no support for "z")
other cheap ali cams were total crap, one random one that looked like a big white UFO could not handle two streams without crashing
a rasperry pi "3b" with two cameras, (one is a USB web cam) running custom software was too hard to configure, still technically 'works'
there is a camera on ali that looks like a tiny 40x40mm black square, I have been using the 8mp version and im pretty happy with the size and performance, I just ordered one more. It does not seem to have a brand and random people sell it in random configurations so YMMV. 

![image](https://user-images.githubusercontent.com/31858838/210395739-063e2f53-f4fa-43d2-bd12-d4f7b0bb0947.png)

I started switching from wifi to PoE for better signal, so far its not really been that hard to hide those flat flimsy network cables from amazon, you can get them in white and just tape them to a wall
