### ISSUE TITLE
Why is it realtime on the lovelace card but not when casting a RTSP stream using dash cast

### ISSUE THREAD

**Issue by atv2016** [AlexxIT/WebRTC#304]
If i use a camera entity or a direct RTSP url there is a lag of 15 seconds or so. If i use the webrtc card instead it's near realtime.

**Comment by timmeh87** [comment]
Webrtc is designed for video calls so they fixed the 15 second delay thing that many other protocols have. The actual delay depends on the encoding and also how close to the next I-frame you join the stream

**Comment by AlexxIT** [comment]
Maybe you casting not webrtc card with dashcast
