### ISSUE TITLE
External access not working

### ISSUE THREAD

**Issue by frantathefranta** [AlexxIT/WebRTC#306]
Hey, I'm having issues with getting external access for the WebRTC protocol. I've tried both of the ways of getting external access but neither has been successful. I've opened ports to my OPNSense router, as well as the address where my HASS instance lives. I can't get WebRTC to load on either when outside of my LAN. 
I've also tried to run a TURN server (coturn) on a AWS EC2 VPS. I've opened all the necessary ports on it and I can test it [here](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) successfully, but it doesn't seem to work for the integration. My turnserver config is this:
```
realm={external-ip}
server-name=mydomain.com
fingerprint
listening-ip={internal-ip}
external-ip={external-ip}/{internal-ip}
listening-port=3478
min-port=49152
max-port=65535
log-file=/var/log/turnserver.log
user=test:test123
lt-cred-mech
verbose
```
I'm also not sure about if this is the right behavior, but I can test the turnserver using the turnutils_client command successfully, but only when it's TCP. When I use UDP I get channel bind: error 403 (Forbidden IP)

The HASS logs only show this when my ice_servers are specified (I've tried all combinations of google stun server, my own ice server as well as stun server):

```
2022-05-27 16:45:03 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/05/27 16:45:03 websocket.JSON.Receive EOF
2022-05-27 16:45:03 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2022/05/27 - 16:45:03 | 200 |  3.841934293s |       127.0.0.1 | GET      "/ws?url=rtsp://username:password@camera-ip:554/h264Preview_01_main"
```

If I leave out the ice_server config out of the card yaml, I see this in the logs repeated over and over, but no external access:
```
2022-05-27 16:41:43 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/05/27 16:41:43 Set ICEServers [stun:stun.l.google.com:19302]
2022-05-27 16:41:43 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/05/27 16:41:43 Set UDP ports to 49152 .. 50152
```

I am running HASS in a docker container in an LXC on a Proxmox host, no firewall rules changed or applied. 
If anyone has any advice on what I'm doing wrong, please let me know.

**Comment by timmeh87** [comment]
You say you are using docker, do you forward the ports out of docker or try setting network=host on your docker? I thought you had to be listening on high udp ports like around 50000 or 60000 for webrtc access. For my setup on hyperv without docker im pretty sure i just forwarded it on my router and it worked right away, if your ip is public you shouldnt need all this extra turn and ice setup, at least, i didnt

**Comment by frantathefranta** [comment]
> You say you are using docker, do you forward the ports out of docker or try setting network=host on your docker? I thought you had to be listening on high udp ports like around 50000 or 60000 for webrtc access. For my setup on hyperv without docker im pretty sure i just forwarded it on my router and it worked right away, if your ip is public you shouldnt need all this extra turn and ice setup, at least, i didnt

I'm using docker for HASS, coturn is ran as a binary on my EC2 instance.

**Comment by AlexxIT** [comment]
Check my new project. It has solution for external access
https://github.com/AlexxIT/go2rtc

**Comment by AlexxIT** [comment]
Should be fixed in v3
