### ISSUE TITLE
Ptz motions repeated twice

### ISSUE THREAD

**Issue by timmeh87** [AlexxIT/WebRTC#307]
Hey I have a few v380 ptz cameras and things are working good but it seems like after some recent update all pan actions are repeated twice when i use the overlay of this component to move them. Other integrations still move normally. I can tell the motion is sent twice because the camera moves twice as far as it used to and also it discretely moves in two bursts

**Comment by AlexxIT** [comment]
You need to log problem somehow. You can check browser developer console

**Comment by AlexxIT** [comment]
I think the problem same #312
