### ISSUE TITLE
Feature: add rotate camera image

### ISSUE THREAD

**Issue by Trevsweb** [AlexxIT/WebRTC#308]
please can you add a function to rotate the image of the camera
similar to 

style: |
  ha-card {
    transform: rotate(90deg);
  }

**Comment by sepodele** [comment]
Yes, please. That would be awesome.

**Comment by AlexxIT** [comment]
Is your code works? Do you check it?

**Comment by sepodele** [comment]
His code kinda works with the lovelace-card-mod: https://github.com/thomasloven/lovelace-card-mod

But the user experience is horrible. What we want is a rotation of the video feed itself, not the entire card. For instance, if I use the Tapo: Cameras Control integration and set 'Extra arguments for ffpmeg' to '-vf "transpose=1"' and untick 'Use Stream from Home Assistant', the picture-entity card will show the video feed as rotated. Unfortunately the same thing does not happen in your webrtc-camera card.

**Comment by AlexxIT** [comment]
ffmpeg not good idea because it use unnecessary transcoding with high CPU activity

**Comment by sepodele** [comment]
Yeah, I don't want to use ffmpeg. Can you ad an option for rotation in webrtc instead? I have cameras on the beds of my children so it's much more convenient if the video was portrait mode instead of landscape.

**Comment by AlexxIT** [comment]
I'm not so good with JS. It should be some browser feature.

**Comment by sresam89** [comment]
Any option to rotate will be awesome

**Comment by AlexxIT** [comment]
Should be fixed in v3

**Comment by sepodele** [comment]
What's the syntax to do this in v3? I tried `style: 'video {rotate: -90deg;}'` and it rotates, but the image is then cropped at top and bottom. There's also a large black bar on left and right side.

**Comment by AlexxIT** [comment]
I'll try to write example

**Comment by quack3d** [comment]
This works: 

style: 'video {transform: rotate(-90deg); aspect-ratio: 1}'

**Comment by brettinternet** [comment]
It doesn't appear possible to flip the video as transpose does.
