### ISSUE TITLE
Keep connection alive while switching tabs on desktop

### ISSUE THREAD

**Issue by mortenmoulder** [AlexxIT/WebRTC#309]
I just gave this integration a shot and I am very, very impressed. It works very well!

I used to use a different software (Shinobi) to monitor my cams while I'm at my desk. I've now switched to Home Assistant with the cameras in a tab instead, and it works very well. However, when I take a screenshot using a software called ShareX, the cams reconnect (which fortunately happens quickly). It's rather annoying, because it makes it flicker for a second, which makes me lose my focus.

It also happens when I change into a different tab and change back again.

I tried searching for the same issue, but couldn't really find one. Thanks

**Comment by AlexxIT** [comment]
background setting
