### ISSUE TITLE
Also working: QNAP QUSBCam2

### ISSUE THREAD

**Issue by dloeckx** [AlexxIT/WebRTC#310]
The integration also works with (USB) cameras exposed by QNAP QUSBCam2, with the following URL

`rtps://username:password@[QNAP NAS ip address]:554/channel[QUSBCam2 channel number]`

Example: `rtsp://username:password@192.168.1.101:554/channel1`

See also https://www.qnap.com/en/how-to/faq/article/what-is-the-qusbcam2-rtsp-url-format

**Comment by AlexxIT** [comment]
Thanks!
