### ISSUE TITLE
rtsp stream not loading - error: no video

### ISSUE THREAD

**Issue by jffz** [AlexxIT/WebRTC#313]
Whenever I try to integrate an rtsp stream, it report `ERROR: no video`. This is from hacked yi cams (using 3 differents hacks related to their models).
Integrating using surveillance station entity (based on the same rtsp stream) just works.
No logs

**Comment by igor-epam** [comment]
Same issue occurs from time to time.

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc

**Comment by Beer17HWAM** [comment]
Check if port 8554 is not already used on same system. I had it too, port conflict. Changed it to 8555 in g2rtc.yaml.

**Comment by AlexxIT** [comment]
Should be fixed in v3

**Comment by igor-epam** [comment]
@AlexxIT With the v3 I've got the following error always:
ERROR: NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="undefined") is unsupported.

So, it doesn't work at all. instead of some random video stoppage.

**Comment by AlexxIT** [comment]
@igor-epam you need to run go2rtc on any computer you have. Enable log level trace. Any try to watch MSE stream in go2rtc WebUI.
