### ISSUE TITLE
WebRTC performance issues

### ISSUE THREAD

**Issue by der71** [AlexxIT/WebRTC#314]
The WebRTC card loads the stream just fine, but it gets stuck every 0.5 seconds.
It does show it swapped to the WebRTC protocol.
See [gif](https://gyazo.com/3fdd7548d373dd438a727ba135d72f5e)

I tested the stream in vlc and it played without the stuttering 
Looking at the documentation it tells you to forward UDP ports for users running a docker installation.
I got stuck trying to do this.

Home Assistant Core 2022.6.2
Home Assistant Supervisor 2022.05.3
WebRTC v2.3.0
Tested in Chrome/Firefox and android app to exclude client side

**Comment by der71** [comment]
Forgot to mention I tried on both WAN and LAN

**Comment by gerardsyd** [comment]
I'm getting exactly the same issue as well. Lot of stuttering, nothing in the logs (have set up debug). Running on docker with homeassistant running network_mode: host so don't think it is the port issue (this is on WAN). 

Home Assistant Core 2022.6.7
WebRTC v2.3.0

**Comment by gerardsyd** [comment]
Thanks! Yes this solved the issue on my desktop. I had PureVPN which was blocking WebRTC. Disabling the add-in solved the issue. 
On mobile, it required update of android webview for the home assistant app and it now works! 
Hopefully this helps others!

**Comment by AlexxIT** [comment]
@der71 Is the problem only with bunny video? Because this is buggy stream

**Comment by der71** [comment]
Sorry for the long wait.
I changed my OS from ubuntu 18.04 to debian 11.
So it took a little before I could test it. 

It seems indeed to be the buggy stream as it works fine with my camera now. 
Because of the chrome extension I used the bunny stream as a trouble shooting step not knowing it can be laggy.

Thx for your help and the great integration.
