### ISSUE TITLE
How to setup two cameras both with audio?

### ISSUE THREAD

**Issue by srodighiero** [AlexxIT/WebRTC#315]
I have two Ezviz cameras setup with WebRTC, both working fine.

What I noticed is that the audio button is visible or on one camera, or in the other, but never on both.

Am I maybe doing something wrong?

Thank you for any help

**Comment by AlexxIT** [comment]
Check status icon https://github.com/AlexxIT/WebRTC#status-icons

**Comment by AlexxIT** [comment]
Availability of audio depends on the stream codec and selected streaming technology
