### ISSUE TITLE
WebRTC stops working on HA 2022.7.0b0

### ISSUE THREAD

**Issue by tkdrob** [AlexxIT/WebRTC#318]
The next Home Assistant release drops Python 3.9. This may be the cause?

https://rc.home-assistant.io/blog/2022/06/29/release-20227/

No error logs are visibile.

**Comment by kamil382** [comment]
:(
I confirm it does not work

**Comment by dermotduffy** [comment]
Same. Even the stock WebRTC card configuration will not work:

```
type: custom:webrtc-camera
url: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
```

Nothing of note getting logged in the HA logs with default logging.

**Comment by miit86** [comment]
Hi,

Same Issue

**Comment by skrobul** [comment]
Upgraded recently, it broke too. This is what's showing up on the javascript console

```
WebSocket connection to 'wss://hass.skrobul.com/api/webrtc/ws?authSig=REDACTEDREDACTED-V4CPlNcR5_Zzaeh4uaoehKB237YgV6ZsGYk4&url=rtsp%3A%2F%2Fmyuser%3Akamera%40192.168.1.111%2Flive0' failed: 
initMSE @ webrtc-camera.js?v2.3.0:75
```

**Comment by skrobul** [comment]
Reverting changes made in https://github.com/home-assistant/core/pull/73829 fixed it for me. Not sure if that's permanent, but just in case paging @AngellusMortis and @bdraco

**Comment by AngellusMortis** [comment]
HA has a similar [out of the box replacement for this custom integration](https://www.home-assistant.io/integrations/rtsp_to_webrtc/). I would recommend migrating.

**Comment by skrobul** [comment]
> HA has a similar [out of the box replacement for this custom integration](https://community.home-assistant.io/t/add-on-rtsptoweb-and-rtsptowebrtc/387846). I would recommend migrating.

Thanks @AngellusMortis, it seems like a good idea but it's not really "out of the box" replacement - it looks more like alpha quality extension that is poorly documented and does not provide external connectivity through NAT, which is absolutely needed for things like cameras.
 
I've tried setting it up and it simply spins forever when connecting from remote network, even with TURN server configured for the occasion. Works OK when on local, but I don't really want to watch cameras when I'm in the same room...

**Comment by Delta1977** [comment]
@AlexxIT can you have a look? Today is release of ha 2022.7

**Comment by skrobul** [comment]
> @AlexxIT can you have a look? Today is release of ha 2022.7

@Delta1977 : AlexxIT is marked 'on vacation' and I'm hoping he is having great time ;-) I took a stab at fixing this in #320, seems to work for me, so feel free to try this on your setup.

**Comment by Delta1977** [comment]
> > @AlexxIT can you have a look? Today is release of ha 2022.7
> 
> 
> 
> @Delta1977 : AlexxIT is marked 'on vacation' and I'm hoping he is having great time ;-) I took a stab at fixing this in #320, seems to work for me, so feel free to try this on your setup.

I try your fix with current released 2022.07 and it didn't work.

**Comment by skrobul** [comment]
> I try your fix with current released 2022.07 and it didn't work.
Did you replace the `.gz` version of the javascript?

**Comment by Delta1977** [comment]
> > I try your fix with current released 2022.07 and it didn't work.
> 
> Did you replace the `.gz` version of the javascript?

now i got it working. at first i delete the .gz and add your code to .js file . then Restart.

the curios thing is as i had  "  ip_ban_enabled: true" in configuration.yaml then my devices imideatly get blocked as i open the webrtc card. Clear browsercache and Mobile-APP Cache didnt help, but i see in Chrome the new code. 
 i need to disable ipban, then open the WeRTC Card one time on each device, wait for stream. the i can enable ipban without problem.

Crazy Thing :-)

**Comment by skrobul** [comment]
> now i got it working.

:+1: 

> the curios thing is as i had " ip_ban_enabled: true" in configuration.yaml then my devices imideatly get blocked as i open the webrtc card. Clear browsercache and Mobile-APP Cache didnt help, but i see in Chrome the new code.
i need to disable ipban, then open the WeRTC Card one time on each device, wait for stream. the i can enable ipban without problem.

Good stuff - I have the ipban disabled for now, but wonder if there is anything else that may be issuing requests that cause bans. Try enabling debug on `homeassistant.components.http.view` and it should at least show you which IP is responsible for the failing requests. If it turns out to be your browser, then use devtools to identify which part of code is sending the request

**Comment by tkdrob** [comment]
Works for me, too. Only chrome is having issues though. Incognito works. Clearing cache and cookies has yet to fix my regular chrome profile.

**Comment by MMachor** [comment]
This appears to fix local usage, but when viewing from an external ip address it still gives the same error.  

Login attempt or request with invalid authentication from 192.168.0.1 (192.168.0.1). (Mozilla/5.0 (Linux; Android 12; SM-N975U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.70 Mobile Safari/537.36 Home Assistant/2022.6.0-2398 (Android 12; SM-N975U))

**Comment by tkdrob** [comment]
In clearing browsing data, I had to remove hosted app data in the advanced tab in chrome. Things are all looking good now.

**Comment by calisro** [comment]
Doesn't seem to work here.  hmm.

**Comment by 8OND007** [comment]
> > > I try your fix with current released 2022.07 and it didn't work.
> > 
> > 
> > Did you replace the `.gz` version of the javascript?
> 
> now i got it working. at first i delete the .gz and add your code to .js file . then Restart.
> 
> the curios thing is as i had " ip_ban_enabled: true" in configuration.yaml then my devices imideatly get blocked as i open the webrtc card. Clear browsercache and Mobile-APP Cache didnt help, but i see in Chrome the new code. i need to disable ipban, then open the WeRTC Card one time on each device, wait for stream. the i can enable ipban without problem.
> 
> Crazy Thing :-)

Have the same problem not being able to open the WebRTC stream and getting IP banned by HA.
Deleted that .GZ file, rebooting & clearing cache did not fix at all.
I hope the WebRTC custom integration owner will fix this problem and make his addon HA 2022.7.x proof again.

**Comment by mariusnauj** [comment]
@Borcon good step list.  Now it's working. Thank you

**Comment by aubhi89** [comment]
@borcon @mariusnauj How to check if ipban is enabled?

**Comment by dreimer1986** [comment]
Pull confirmed working fine. I am on 2022.7.1 now.

**Comment by harambe88** [comment]
I'm on core-2022.7.1 too, but WebRTC problem persists. Followed Borcons steps. Checked twice.

**Comment by 8OND007** [comment]
Borcon tip works! I'm on 2022.7.1.
But only local URL/connections of homeassistant, if used remotely (external URL) it does not work.

**Comment by dreimer1986** [comment]
Here both internal and external work fine after full cache cleanup. Chrome on Windows 11 btw

**Comment by harambe88** [comment]
2022.7.2 is out - and didn't help!

**Comment by dreimer1986** [comment]
The standard Chrome way. F12 to open devtools and then right clickon the refresh button. in the menu the very lowest selection and all was fine.

**Comment by andregoncalvespires** [comment]
It's work. Thank you!

**Comment by harambe88** [comment]
Went back to 2.6.7 and webRTC is working!

**Comment by Tyrian81** [comment]
[Borcon](https://github.com/Borcon) steps worked THANKS !!!

**Comment by calisro** [comment]
The pull partially fixed things.  I still am having trouble with the service: webrtc.create_link working.

**Comment by skrobul** [comment]
> https://github.com/AlexxIT/WebRTC/pull/320#issuecomment-1180888344

[responded](https://github.com/AlexxIT/WebRTC/pull/320#issuecomment-1180888344) in the PR, let's continue discussion there
