### ISSUE TITLE
On my Home Assistant android app, sometimes the stream tries to connect to LAN when I am on WAN or tries WAN when I am on LAN

### ISSUE THREAD

**Issue by ZainAjam** [AlexxIT/WebRTC#32]
The webrtc lovelace card seems to confuse when I am on local wifi vs mobile data, and sometimes it tries to connect to LAN when I am not on the local network, resulting in an infinite spinning of the progress circle, with no camera feed ever showing up

**Comment by AlexxIT** [comment]
Duplicate #26
