### ISSUE TITLE
Stream will not auto play on IOS device?

### ISSUE THREAD

**Issue by totalitarian** [AlexxIT/WebRTC#322]
Hi, WebRTC stream start immediately on my windows desktop but on my mobile (iPhone) I have to lick the play button. Is there an option override this behaviour?

**Comment by Gymnae** [comment]
This is not an issue or bug really, but an iOS behavior.

**Comment by AlexxIT** [comment]
Yes. Problem with iOS. But I have seen fix somewhere. Will try to test it someday

**Comment by woempiej** [comment]
Did you select the option "auto play video" in the app?

**Comment by AlexxIT** [comment]
Can't be fixed because Apple knows better what's best for you
https://developer.apple.com/documentation/webkit/delivering_video_content_for_safari
