### ISSUE TITLE
Stream no longer working in HA

### ISSUE THREAD

**Issue by dietlman** [AlexxIT/WebRTC#325]
Since a couple of weeks Webrtc camera stream is no longer workging in my HA. I have tried to rtsp link with the test movie, but that one is also not working, however, when I try to open the stream in VLC it works, also my camera stream works in VLC, but in Homeassistant using Webrtc it does not work. Have there been any changes recently? Like I said, it was working fine for a long time, but now it stopped working and I am not sure where to start with troubleshooting since nothing has changed in my configuration.
Thanks a lot for helping.

**Comment by zdzichu6969** [comment]
same here

**Comment by Jacquedebie** [comment]
Ditto, worked for about 4 Months and just stopped Friday morning...
In VLC I can also see my cameras with the same rtsp link as in HA.

**Comment by fanuch** [comment]
>  Have there been any changes recently? 

Yes. Look at the active issues before posting.

https://github.com/AlexxIT/WebRTC/issues/321

**Comment by AlexxIT** [comment]
#321
