### ISSUE TITLE
WebRTC causing incompatible cameras in media?

### ISSUE THREAD

**Issue by Vards0** [AlexxIT/WebRTC#327]
Greetings all.

After the incompatibility between HA release 2022.7 and WebRTC, I carried out the steps suggested by [freirejc](https://github.com/freirejc) below which resolved the issue for me.

`

    File Browser, change the file custom_components\webrtc\www[webrtc-camera.js]
    replace all content to below RAW code:
    https://raw.githubusercontent.com/skrobul/WebRTC/38c77b400f86f20a42e0b8103bb01f6a0a7377eb/custom_components/webrtc/www/webrtc-camera.js

    Delete the .gz file located in custom_components\webrtc\www

    Delete all files located in custom_components\webrtc_pycache_

    Remove IP Ban (in case you have it)

    Restart you HA and in the meantime you clear all the cash from your browser. Do not forget to clear the cash in your mobile phone app as well.

    Try to see your cameras in your browser and in your mobile app.

    If everything is working fine, turn on IP Ban again.
`

I also noticed that after doing the above, my cameras started appearing again under media (player).

However when I updated to the latest WebRTC release yesterday (2.3.1), the cameras had disappeared and were showing as 7 **incompatible items hidden**.

Is there something in the code that could be causing them to no longer be compatible with HA media?

**Comment by AlexxIT** [comment]
May be you broke something when you apply fix manually

**Comment by Vards0** [comment]
Hi Alex

I don't think I broke something because the cameras started appearing as they should under media.

It is only after I installed the latest WebRTC that they disappeared again and were showing as incompatible.

Cheers

**Comment by AlexxIT** [comment]
I don't understand what's going on in this issue. If the problem is still relevant - you need to provide more data
