### ISSUE TITLE
Ability to change ratio of the card

### ISSUE THREAD

**Issue by GregoryKowalik** [AlexxIT/WebRTC#328]
Hi,

I would love to see an option allowing me to change the ratio of displayed video on the card so I can adjust the card to small screens like tablet.

Thanks
Greg

**Comment by AlexxIT** [comment]
Card width will be always same as others cards. Card height will be computed automatically base on video size

**Comment by GregoryKowalik** [comment]
Agree, but if we manipulate the video size and change  width to height ratio the card will adjust to it like it works for standard Picture Entity card, am I wrong?

**Comment by nagyrobi** [comment]
@GregoryKowalik see [here](https://github.com/AlexxIT/WebRTC/issues/21).

**Comment by AlexxIT** [comment]
Card width controlled by dashboard and can't be changed by card
