### ISSUE TITLE
Port forwarding set up for 50000 to 50019 but webrtc sometimes picks ports outside of that range

### ISSUE THREAD

**Issue by ZainAjam** [AlexxIT/WebRTC#33]
i am using duckdns with nginx for reverse dns lookup. Without port forwarding, i get no camera stream when off my local network. I have to port forward. I have 2 cameras, so i use 50000 to 50019 as my ports that I forward to my home assistant raspberry pi. I noticed, however, that the webrtc card uses random port that isn't between the range i've setup for the integration and port forwarded, so i get a connection error

**Comment by AlexxIT** [comment]
Have you set this range in integration options?

**Comment by ZainAjam** [comment]
I have yes. It is set minimum 50000 and 50019 in the integration options. I
have also port forwarded this same range.

**Comment by AlexxIT** [comment]
Duplicate #26
