### ISSUE TITLE
Feature request: picture-glance like integration

### ISSUE THREAD

**Issue by Stormrage-DJ** [AlexxIT/WebRTC#330]
Hi!

It would be very nice if WebRTC could be somehow put into picture-glance card or the WebRTC card could have some features like the picture-glance.

The usecase i'm looking for is switching between 2 stream with different quality/resolution (1).
So on my dashboard I have a low quality 4fps stream that goes my tablet as a central display for it 0-24h, of couse just to take a quick look you don't need 4k resolution or so, however It would be nice to have an alternate button/option to open a different stream in fullscreen, preferably with the ability to use with WebRTC and default stream (for full screen in 4k resolution i may make compromise with 5-6s delay of default stream, because some devices may not play 4k fluently)

I also really love the instant full screen button of the actual stream (2) :)

I will keep an eye on this addon as it is really promissing!

![image](https://user-images.githubusercontent.com/83466158/179345984-dc66832e-ff4b-4b6c-9b55-0a0870d48102.png)

**Comment by AlexxIT** [comment]
Check my new project. It has support default lovelace card
https://github.com/AlexxIT/go2rtc
