### ISSUE TITLE
maximum 1 camera view per page, camera some time not loaded until page refresh.

### ISSUE THREAD

**Issue by xeonlee** [AlexxIT/WebRTC#332]
HA under Docker
Home Assistant Core 2022.6.7

if i add more than 1 camera to lovelace in same page, only one of the camera successful loaded, and its was randomly.
i also have issue with camera loading stuck until i tab to other page, than goes back camera will successfully loaded. chance was 50:50.
it was frustrating when every time i open app or browser to check out camera event .
some one have this issue ?
![Capture](https://user-images.githubusercontent.com/72093392/181167720-5b28935f-300e-47ad-b077-5b10c34d0773.JPG)

**Comment by woempiej** [comment]
Yes I have the same issue and have tested it out with the same conclusion.
1 camera = oké
2 or 3 is an issue!

I'm on a military class 3 system with no further loading issues with other integrations.
I decreased the video stream quality, but no effect.

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc

**Comment by woempiej** [comment]
> Yes I have the same issue and have tested it out with the same conclusion. 1 camera = oké 2 or 3 is an issue!
> 
> I'm on a military class 3 system with no further loading issues with other integrations. I decreased the video stream quality, but no effect.

I have no issues anymore since Unifi update. Sorry for the "to fast" conclusion. Works perfect (3 camera's on 1 page)

**Comment by woempiej** [comment]
> Check my new project. Maybe it handle this situation https://github.com/AlexxIT/go2rtc

Nice project but I stick to this one because it is well implemented in HA and easy to use.
The only thing I miss is a simple click on the camera dashboard card to get fullscreen :)

**Comment by mercenaruss** [comment]
> Check my new project. Maybe it handle this situation https://github.com/AlexxIT/go2rtc

Nice one. Integration to HA via web page iframe?
or is another way to view video in HA using go2rtc?

**Comment by AlexxIT** [comment]
@mercenaruss do you read docs?

**Comment by AlexxIT** [comment]
Should be fixed in v3
