### ISSUE TITLE
WebRTC stop working after Hassio Core 2022.7.7 update

### ISSUE THREAD

**Issue by AntoBB** [AlexxIT/WebRTC#334]
The WebRTC integration worked fine in my Hassio OS (Pi3 b+), Core version 2021.12.4.
As soon as I updated to version 2022.7.7, the webrtc-camera cards in my dashboard stopped working and the rtsp stream of the cams are no longer visible.
I tried to restore the Core 2021.12.4 version and the cards started working again.

**Comment by madeddie** [comment]
This is probably a dupe of #321
