### ISSUE TITLE
Camera send statusRTSP/1.0 406 Not Acceptable

### ISSUE THREAD

**Issue by RomchikL** [AlexxIT/WebRTC#343]
Hello!

I have the following error.
<details>
<summary>Log</summary>
 2022-08-20 20:02:01.285 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/08/20 20:02:01 Stream Try Connect rtsp://USER:PASS@IP/Streaming/Channels/101

2022-08-20 20:02:02.357 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/08/20 20:02:02 Camera send statusRTSP/1.0 406 Not Acceptable

2022-08-20 20:02:02.358 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/08/20 20:02:02 Stream Exit On Demand No Viewer

2022-08-20 20:02:06.319 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/08/20 20:02:06 Stream Codec Not Found

2022-08-20 20:02:06.321 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2022/08/20 - 20:02:06 | 200 | 5.034433566s | 127.0.0.1 | GET "/ws?url=rtsp://USER:PASS@IP/Streaming/Channels/101"
</details>

The rtsp stream is available in VLC and other integrations in Home Assistant.
Bunny video works.

My HA is configured in docker.
I forwarded 10 udp ports (50000-50010) and selected the same min-max ports in the integration settings.

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc

**Comment by RomchikL** [comment]
I tried to use go2rtc in and without docker, but I still get an error.
E.g., in win version Bunny video works with mse. With my camera I have the following log.

1. webtrc:
```
19:55:47.935 INF [streams] create new stream url=rtsp://user:pass@IP:PORT/Streaming/Channels/101
19:58:30.475 ERR [streams] probe producer error="wrong response on DESCRIBE" url=rtsp://user:pass@IP:PORT/Streaming/Channels/101
19:58:30.518 ERR [streams] probe producer error="wrong response on DESCRIBE" `url=rtsp://user:pass@IP:PORT/Streaming/Channels/101
```
2. info --- "null"
3. frame.mp4 --- as in 1/
4. mse:
```
20:05:55.102 ERR [streams] probe producer error="wrong response on DESCRIBE" url=rtsp://user:pass@IP:PORT/Streaming/Channels/101
20:05:55.134 ERR [streams] probe producer error="wrong response on DESCRIBE" url=rtsp://user:pass@IP:PORT/Streaming/Channels/101
2022/08/21 23:05:55 http: panic serving [::1]:57319: runtime error: invalid memory address or nil pointer dereference
goroutine 51 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1802 +0xb9
panic({0xabc000, 0xf9d2a0})
        runtime/panic.go:1047 +0x266
github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).stop(0xc0003ac120)
        github.com/AlexxIT/go2rtc/cmd/streams/producer.go:77 +0x72
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).RemoveConsumer(0xc0003843f0, {0xc1b238, 0xc0001ca000})
        github.com/AlexxIT/go2rtc/cmd/streams/stream.go:114 +0x115
github.com/AlexxIT/go2rtc/cmd/mse.handler.func2()
        github.com/AlexxIT/go2rtc/cmd/mse/mse.go:38 +0x28
github.com/AlexxIT/go2rtc/cmd/api.(*Context).Close(0xc0003941c0)
        github.com/AlexxIT/go2rtc/cmd/api/ws.go:34 +0x42
panic({0xb197a0, 0xc0003922d0})
        runtime/panic.go:1038 +0x215
github.com/deepch/vdk/format/mp4f.(*Muxer).GetInit(0xc000382230, {0x0, 0xc0003a41b0, 0x1})
        github.com/deepch/vdk@v0.0.19/format/mp4f/muxer.go:280 +0x83a
github.com/AlexxIT/go2rtc/pkg/mse.(*Consumer).Init(0xc0001ca000)
        github.com/AlexxIT/go2rtc/pkg/mse/consumer.go:113 +0x85
github.com/AlexxIT/go2rtc/cmd/mse.handler(0xc0003941c0, 0xa7c180)
        github.com/AlexxIT/go2rtc/cmd/mse/mse.go:41 +0x335
github.com/AlexxIT/go2rtc/cmd/api.apiWS({0xc1bef8, 0xc00039a540}, 0xc00019e200)
        github.com/AlexxIT/go2rtc/cmd/api/api.go:129 +0x1bc
net/http.HandlerFunc.ServeHTTP(0x0, {0xc1bef8, 0xc00039a540}, 0x0)
        net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00039823c, {0xc1bef8, 0xc00039a540}, 0xc00019e200)
        net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0xc000184300}, {0xc1bef8, 0xc00039a540}, 0xc00019e200)
        net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0001ba000, {0xc20c60, 0xc0001840c0})
        net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        net/http/server.go:3034 +0x4e8
```

Maybe it depends on the camera. I have Laxihub M3-TY with root by [guino](https://github.com/guino)

**Comment by AlexxIT** [comment]
@RomchikL please show logs and create issue in go2rtc project

`go2rtc.yaml` config:

```
log:
  rtsp: trace
```

**Comment by RomchikL** [comment]
@AlexxIT done, see [issue 7](https://github.com/AlexxIT/go2rtc/issues/7#issue-1345883224).

**Comment by AlexxIT** [comment]
Fixed in `go2rtc`
