### ISSUE TITLE
Mac App

### ISSUE THREAD

**Issue by kaystrobach** [AlexxIT/WebRTC#344]
Hello WebRTC devs,

thank you for all the effort you put into the card.
It works in most cases, but not in the Mac App, while this is similar (visually) to the iOS one.

![grafik](https://user-images.githubusercontent.com/1185776/186104011-c94c3f2b-808c-4ae4-b962-f1c677bacf38.png)

* Is there any plan to support the MacApp?
* Is there an option to detect the problem and maybe fall back to the still image of the video?

PS: This integration is relatively popular in due to the [fuatugan/eufy_security](https://github.com/fuatakgun/eufy_security) plugin, which integrates eufy cameras and encourages the installation of this card to render the stream.

Thank you.

**Comment by AlexxIT** [comment]
Support only depends on the guys from Cupertino #76 #248

**Comment by kaystrobach** [comment]
Thank you for pointing that out, will try to check if there is a workaround. It works perfectly on the iOS App. So it seems like a rather dumb limitation by apple. 👍
