### ISSUE TITLE
Can't find integration In HACS

### ISSUE THREAD

**Issue by Rupp3r** [AlexxIT/WebRTC#345]
Hi there

Trying to add the integration, but can't seem to find it?
https://hacs.xyz/docs/repositories/integration/alexxit_webrtc also says "Page Not Found"

**Comment by markus-seidl** [comment]
Make sure you are on the Integration page - I have just installed it and found it in HACS. (Maybe the HACS indexes are still populating?)

**Comment by Rupp3r** [comment]
Don't know if it was me in the wrong tab or HACS being a bit busy...
No matter what I found and successfully installed the integration.

- Thanks Markus🙏🏼:)
