### ISSUE TITLE
No sound on HA with Eufy indoor cam 2k pan & tilt

### ISSUE THREAD

**Issue by AreHoyland** [AlexxIT/WebRTC#347]
Hi Alex

I have a Eufy indoor cam 2k pan & tilt connected to HA and the video is great but i cant seem to get audio from it.
Have I forgotten something or is it not possible with that specific camera?
![Eufy HA code](https://user-images.githubusercontent.com/112121923/186979639-b9e8c065-1e72-4a95-8fc5-710d80d9adf4.JPG)

**Comment by AlexxIT** [comment]
Switch to this addon and check your camera supported codecs. Use transcoding if it needed.
https://github.com/AlexxIT/go2rtc
