### ISSUE TITLE
Remote Access Issues

### ISSUE THREAD

**Issue by ItsJamesMurray** [AlexxIT/WebRTC#349]
Ahoy!

I am able to view my cameras in my home-assistant instance perfectly fine from my home network.  However, any time I connect to a different network or use mobile data to view my dashboards I am no longer able to see the livestream.  Is there a toggle I need to change or something in my config file to allow remote viewing?

Thank ya!!

edit:  fwiw I am running on a raspberry pi and using homeassistant container.

**Comment by AlexxIT** [comment]
Try this https://github.com/AlexxIT/go2rtc

**Comment by ItsJamesMurray** [comment]
Thank you!  Hate to be a bug but I added an issue to the go2rtc since I am getting errors not shown in the documentation.  Since it is a different repo I'll close this one here.

You rock!
