### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by gajpchapo** [AlexxIT/WebRTC#35]
Hi Alex,

Really great work here.

I have a couple of sound issues on Sonoff Cam. 

1. There's a clicking under the sound
2. If I open the stream 3 or 4 times the sound is lost and I have to reboot HA to reinstate.

Thanks in advance

**Comment by AlexxIT** [comment]
Strange. I don't have this problems with Sonoff Cam

**Comment by gajpchapo** [comment]
I have a second Sonoff Cam arriving.  I will check that one and come back to you.  The sound is fine through the app, but there's a clicking sound when played through HA.  If I still have the problem I will upload sound files in and out of HA.

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc
