### ISSUE TITLE
i'm getting always restart connection

### ISSUE THREAD

**Issue by morpheus8888** [AlexxIT/WebRTC#350]
![image](https://user-images.githubusercontent.com/49568239/190988068-61f5ac96-b3c8-41e8-be8c-33b2bc852c8d.png)

until a few days ago everything was working correctly, now it keeps restarting connection, even the video demo bunny does the same thing, I checked the rtsp stream on vlc and it works. Any suggestions?

**Comment by saxopwn** [comment]
Same thing here

**Comment by AlexxIT** [comment]
Try this https://github.com/AlexxIT/go2rtc

**Comment by fribse** [comment]
same here @AlexxIT use that INSTEAD of this?

**Comment by AlexxIT** [comment]
The latest fixes are made in the go2rtc project. When it will be finished, it will be embedded in this component. But now it can be used on its own.

**Comment by AlexxIT** [comment]
Should be fixed in v3
