### ISSUE TITLE
Constant Buffering

### ISSUE THREAD

**Issue by Maxcodesthings** [AlexxIT/WebRTC#352]
I am having constant buffering with this frontend component. I have tried different ways of hosting the RTSP stream all with the same buffering issue, so I am left suspecting something on the browser side weith this component. Today I am using the `go2rtc` integration, thanks to AlexxIT once again for that, but it is lagging and buffering in Home Assistant
![chrome_YS2UxlZKlZ](https://user-images.githubusercontent.com/85802950/196332196-42e7084c-8627-43f6-b4b4-104a4cb1d155.gif)

I have also tried different RTSP capable cameras in my house, two are Amcrest and one is Wyze, with the same behavior. I know my throughput is good because VLC playback is flawless when accessing the RTSP stream and same with the apps

My configuration:

```
- type: 'custom:webrtc-camera'
   title: Front Door go2rtc
   url: rtsp://go2rtc:8554/doorbell_camera
   ui: false
```
I have also tried accessing the RTSP hosted by the camera and not with go2rtc proxy with same exact behavior
```
- type: 'custom:webrtc-camera'
  title: Front Door
  url: rtsp://admin:password@127.0.0.1:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
  ui: false
```

**Comment by AlexxIT** [comment]
Check this #249

Also you can try this project https://github.com/AlexxIT/go2rtc
