### ISSUE TITLE
Home Assistant App for MacOS, unsupported browser

### ISSUE THREAD

**Issue by Salsalove** [AlexxIT/WebRTC#355]
The card is not loaded in the MacOS Home Assistant App. Unsupported browser. Any fix?

<img width="284" alt="Screenshot 2022-11-07 alle 09 51 41" src="https://user-images.githubusercontent.com/44812056/200266690-f2cabc14-158f-4f10-bfff-b358e07a9520.png">

**Comment by AlexxIT** [comment]
#5 #76 #248 #344
