### ISSUE TITLE
PTZ

### ISSUE THREAD

**Issue by masumehboluree** [AlexxIT/WebRTC#363]
Hi
I install latest SonoffLAN and webrtc on home assistant. I add a card and connect to sonoff GK-200MP2-B camera and it work properly but although sonoff.send_command service exist but PTZ control not work. do you have any idea for solve this problem?
I call manually this service from services tab in developer tools section but did not see any reaction in camera!
Thanks a lot

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/issues/67#issuecomment-1284179929
