### ISSUE TITLE
Casting to Google Cast with low latency but with audio

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/WebRTC#369]
- If I use HA native casting, stream is HLS: very high latency, but audio works
- If I cast the lovelace card: low latency, but no audio
- If I cast with DashCast: low latency, but no audio

Were you able to achieve something better than I did?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/issues/129#issuecomment-1368925814
