### ISSUE TITLE
RTMP

### ISSUE THREAD

**Issue by debsahu** [AlexxIT/WebRTC#37]
I have a rebroadcast of RTSP via RTMP. When I try to add RTMP it ways only RTSP stream is allowed. Can you point me to where to make modifications that would allow such RTMP streams.

**Comment by AlexxIT** [comment]
I'm not a video specialist and I don't write video software. I used the binary from project:
https://github.com/deepch/RTSPtoWebRTC

**Comment by gigabyteservice** [comment]
Does [this](https://github.com/Sean-Der/rtmp-to-webrtc) help ?

**Comment by AlexxIT** [comment]
@gigabyteservice maybe. I don't promise anything. Very big and specific feature

**Comment by mk-mrshll** [comment]
I'll add a +1 to RTMP support!

**Comment by lobetaa** [comment]
Maybe this will help?🤞

https://github.com/pion/example-webrtc-applications/tree/master/rtmp-to-webrtc

**Comment by AlexxIT** [comment]
Check my new project. It has RTMP support
https://github.com/AlexxIT/go2rtc
