### ISSUE TITLE
Is there a way to specify different go2rtc server for the Lovelace card?

### ISSUE THREAD

**Issue by skynet01** [AlexxIT/WebRTC#372]
I am currently using go2rtc as an add-on (that way HA entity cameras use it through HA's RTSPtoWebRTC integration). I also have some cameras that are not in HA (and I want to keep it that way) and I pull their streams directly through url using this integration. 

Now with v3 almost out I assume this will result in me having 2 go2rtc servers running along side (one as an add-on and another that comes with this integration).

 Is there any way to have the webrtc Lovelace card use my go2rtc  add-on server and not run its own additional server? Would be cool if there is a integration config option to specify go2rtc url, and if that's not used only then start up its own go2rtc server instance?

**Comment by AlexxIT** [comment]
If the component sees that go2rtc is already running on the same server (e.g. addon or Frigate) - it will not run the built-in go2rtc, but will use an external one. When installing the component, you can directly specify which go2rtc to use.

**Comment by AlexxIT** [comment]
Just run top on your server.
Anyway, two go2rtc can't be run on same server, because them will use same ports by default and second go2rtc will fail.
