### ISSUE TITLE
Removed WebRTC still "exists in store'

### ISSUE THREAD

**Issue by AndySymons** [AlexxIT/WebRTC#374]
I installed WebRTC successfully on one environment and liked it a lot, so I installed it on another. 
In the second case the custom card did not appear. I guess I had set it up wrongly somehow and wanted to reinstall it.  
I removed it from HACS and rebooted twice, it does not appear in the HACS UI and cannot be added as an integration, but if I try to install it I get the message "exists in store". 

So I am stuck in a quandry: I cannot install it because it is allegedly already there, but I cannot find it to either delete it or reconfigure it.

**Comment by AlexxIT** [comment]
You can't remove the integration from HACS because it is there "by default"
