### ISSUE TITLE
No stream on cellular network, but working on wifi

### ISSUE THREAD

**Issue by matthieup240** [AlexxIT/WebRTC#375]
I'm displaying my camera streams on my Home Assistant lovelace.
On wifi, all is working as expected.
But when I try to disconnect to the wifi network, the webRtc is trying to load the stream with MP4 and I only have black picture.

I'm using a reverse proxy to access to my server outside of the local network.
Is their something to do ?

PS: I have an iPhone, didn't test on Android.

**Comment by AlexxIT** [comment]
The iPhone has the most retarded browser in terms of modern technologies.
It does not support MSE technology, so you need to learn how to set up external access for WebRTC technology.
This can be difficult if you don't have IT skills.
https://github.com/AlexxIT/go2rtc
