### ISSUE TITLE
webrtc not showing v3.0-beta.4 + Uncaught TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by avico78** [AlexxIT/WebRTC#376]
all cameras (Dahua 4mp) using generic camera with rtsp from go2rtc

1.previous webrtc folder from custom_components deleted
2.Install v3.0-beta.4 + go2rtc  0.1-rc.7(docker)
3.On local network using Chrome browser-> Open HA  : 
delete previous webrtc integration -> restart -> install  WEBRTC integration -> define go2rtc url http://192.168.1.113:1984 

 card:
```
type: custom:webrtc-camera
entity: camera.intercom_camera
muted: false
background: false
webrtc: true
```
Some camera show as:

![image](https://user-images.githubusercontent.com/9049952/211263664-40e5fa80-8aff-4090-a279-bc048fb18b36.png)
![image](https://user-images.githubusercontent.com/9049952/211263954-965725d0-54d1-4cba-abcd-1346f7beffdc.png)

With error in log:
```

2023-01-09 10:01:11.000 ERROR (MainThread) [frontend.js.latest.202301040] http://192.168.1.113:8123/webrtc/video-rtc.js:509:31 Uncaught TypeError: Cannot read properties of null (reading 'connectionState')
```
also:
```
2023-01-09 10:12:09.378 ERROR (MainThread) [homeassistant.components.camera] Timeout handling WebRTC offer
```

some cameras show MSE icon - webrtc not showing

On go2rtc webUi : 
webrtc streams is working and running without audio - i think it is a bug as on latest Frigate beta webrtc stream audio is working
while on HA cameras screen open(5 cameras) - maybe it's expected but "online" column show 4/5 , not sure what it means 
![image](https://user-images.githubusercontent.com/9049952/211266322-6d1f6726-198b-4acb-8516-242dae80325b.png)

**Comment by AlexxIT** [comment]
`Timeout handling WebRTC offer` error from RTSPtoWebRTC integration.

**Comment by avico78** [comment]
webrtc intergation doesn't relay on RTSPtoWebRTC ,
as it connecting to go2rtc directly right?
not sure I see the relation that webrtc doesn't work

**Comment by AlexxIT** [comment]
- Hass default card > RTSPtoWebRTC integration > go2rtc
- WebRTC Camera card > WebRTC Camera integration > go2rtc

**Comment by avico78** [comment]
Thanks Alex , as mention in first post i do use webrtc card 
and this post related to webrtc integration only 
WebRTC Camera card > WebRTC Camera integration > go2rtc
```
type: custom:webrtc-camera
entity: camera.intercom_camera
muted: false
background: false
webrtc: true
```
So the errors and issues i share related only to:

please ignore the other error related to RTSPtoWebRTC as i also doing tests to new go2rtc version working with RTSPtoWebRTC .

**Comment by AlexxIT** [comment]
I hope this issue fixed with release v3. You can reopen it if not.
