### ISSUE TITLE
WebRTC Camera card doesnt play audio in WebRTC stream on iOS 16.2 (iPhone 13) 

### ISSUE THREAD

**Issue by cris1410** [AlexxIT/WebRTC#382]
Hi there.
I got problem with custom dasboard card **WebRTC Camera v3.0-beta.5**.
It doesnt play audio on webrtc stream on iPhone (iOS 16.2) companion app.
If I try the same card with same config on PC (Chrome) - it works without any problems.

Weird is that problem is only in WebRTC Camera card on companion app.
If I play the same stream on iPhone directly from Go2RTC app ( http://192.168.0.168:1984/stream.html?src=camera_vzadu_webrtc&mode=webrtc,mse,mp4,mjpeg ) it works fluently.

WebRTC Camera config:
`type: custom:webrtc-camera`
`url: 'camera_vzadu_webrtc'`

I tried also `ui:true` without any success.

Thanks.
Adam

**Comment by AlexxIT** [comment]
Check codecs from your stream. You can get them in the go2rtc Web UI, info link for **active** stream.

**Comment by cris1410** [comment]
I am not sure what you mean.
This is my go2rtc config:
`rtsp:
  listen: ":8553"  # RTSP Server TCP port, default - 8554

streams:
  camera_vzadu_webrtc:
    - rtsp://xxx:yyy@192.168.0.199:554/h264Preview_01
    - ffmpeg:camera_vzadu_webrtc#audio=opus `

**Comment by NickM-27** [comment]
@cris1410 go to the go2rtc frontend and press the `info` button, paste the output here

**Comment by cris1410** [comment]
Sorry, never used that function before 🤷‍♂️

`{
  "producers": [
    {
      "url": "rtsp://adam:NAA0807@192.168.0.115:554/h264Preview_01_main"
    },
    {
      "url": "ffmpeg:camera_vzadu_webrtc#audio=opus"
    }
  ],
  "consumers": null
} `

**Comment by cris1410** [comment]
Sorry, never used that function before 🤷‍♂️

`{
  "producers": [
    {
      "url": "rtsp://xxx:yyy@192.168.0.115:554/h264Preview_01_main"
    },
    {
      "url": "ffmpeg:camera_vzadu_webrtc#audio=opus"
    }
  ],
  "consumers": null
} `

**Comment by AlexxIT** [comment]
Stream should be viewed by someone when you check info link

**Comment by AlexxIT** [comment]
You still haven't provided information on your stream.

**Comment by cris1410** [comment]
Sorry Alexx, I didnt get it again :/

**This is info from iPhone Safari stream (audio work well)**:
```
{
  "producers": [
    {
      "type": "RTSP source",
      "url": "rtsp://192.168.0.115/h264Preview_01_main/",
      "remote_addr": "192.168.0.115:554",
      "user_agent": "go2rtc/0.1-rc.9",
      "medias": [
        "video, sendonly, 96 H264/90000",
        "audio, sendonly, 97 MPEG4-GENERIC/16000"
      ],
      "tracks": [
        "96 H264/90000, sinks=1",
        "97 MPEG4-GENERIC/16000, sinks=1"
      ],
      "recv": 6392416
    },
    {
      "type": "RTSP source",
      "url": "rtsp://localhost:8553/xxxxxxxxxxxxxxxxxxxx",
      "remote_addr": "127.0.0.1:41276",
      "user_agent": "ffmpeg/go2rtc",
      "medias": [
        "audio, sendonly, 96 OPUS/48000/2"
      ],
      "tracks": [
        "96 OPUS/48000/2, sinks=1"
      ],
      "recv": 162476
    }
  ],
  "consumers": [
    {
      "type": "RTSP client",
      "url": "rtsp://localhost:8553/camera_vzadu_webrtc?audio",
      "remote_addr": "127.0.0.1:41262",
      "user_agent": "go2rtc/ffmpeg",
      "medias": [
        "audio, recvonly, 96 MPEG4-GENERIC/16000"
      ],
      "tracks": [
        "96 MPEG4-GENERIC/16000, sinks=1"
      ],
      "send": 124080
    },
    {
      "type": "WebRTC client",
      "remote_addr": "tcp4 prflx 172.19.0.2:53635 related :0",
      "user_agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Mobile/15E148 Safari/604.1",
      "send": 6489747
    }
  ]
}
```

**This is info from iPhone companion app stream (audio doesnt work)**:
```
{
  "producers": [
    {
      "type": "RTSP source",
      "url": "rtsp://192.168.0.115/h264Preview_01_main/",
      "remote_addr": "192.168.0.115:554",
      "user_agent": "go2rtc/0.1-rc.9",
      "medias": [
        "video, sendonly, 96 H264/90000",
        "audio, sendonly, 97 MPEG4-GENERIC/16000"
      ],
      "tracks": [
        "96 H264/90000, sinks=1",
        "97 MPEG4-GENERIC/16000, sinks=1"
      ],
      "recv": 5542821
    },
    {
      "type": "RTSP source",
      "url": "rtsp://localhost:8553/xxxxxxxxxxxxxxxxxxxx",
      "remote_addr": "127.0.0.1:50040",
      "user_agent": "ffmpeg/go2rtc",
      "medias": [
        "audio, sendonly, 96 OPUS/48000/2"
      ],
      "tracks": [
        "96 OPUS/48000/2, sinks=1"
      ],
      "recv": 134731
    }
  ],
  "consumers": [
    {
      "type": "RTSP client",
      "url": "rtsp://localhost:8553/camera_vzadu_webrtc?audio",
      "remote_addr": "127.0.0.1:50026",
      "user_agent": "go2rtc/ffmpeg",
      "medias": [
        "audio, recvonly, 96 MPEG4-GENERIC/16000"
      ],
      "tracks": [
        "96 MPEG4-GENERIC/16000, sinks=1"
      ],
      "send": 103488
    },
    {
      "type": "WebRTC client",
      "remote_addr": "tcp4 prflx 172.19.0.2:53669 related :0",
      "user_agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2022.10.1 (io.robbie.HomeAssistant; build:2022.424; iOS 16.2.0) Mobile/HomeAssistant, like Safari",
      "send": 5625539
    }
  ]
}
```

**Comment by AlexxIT** [comment]
Ok, Thanks. I'll try to reproduce this situation on my hardware.

**Comment by cris1410** [comment]
go2rtc is installed on Docker (Linux Ubuntu core) on my IntelNUC.

I sent you that info when I connected to stream from external access (VPN - WireGuard).

But problem is very same also when I connect from local network.

**Comment by AlexxIT** [comment]
Well. I can't test it on iOS 16. My wife doesn't wont to update iOS version. But sound works fine in iOS 15 version.
Exact your case exept TCP. Can you test in LAN with UDP?
Do you have other cameras with sound? You can setup local file from media folder as stream. You also needs audio transcoding.

**Comment by cris1410** [comment]
You gotta be kidding me.
Sound is back for all my cameras.
I dont know why, I dont know how but I changed literally NOTHING.
And sound works in UDP and also in TCP connection.
I swear I did not touch any setup, i didnt update nothing.
