### ISSUE TITLE
Unsupported browser in MacOS app (safari browser works fine)

### ISSUE THREAD

**Issue by keeema** [AlexxIT/WebRTC#384]
When I open dashboard with webrtc cards in MacOS app, then I get error:

_Unsupported browser_

There is no such issue in Safari MacOS browser (the default system browser). Only in app.

![image](https://user-images.githubusercontent.com/8296695/213167548-3b9b16d1-db59-4b1a-b7f9-573a0c4d846c.png)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/issues?q=is%3Aissue+macos+app
