### ISSUE TITLE
UI Not working on iPhone

### ISSUE THREAD

**Issue by bm55** [AlexxIT/WebRTC#385]
The UI is working on laptop browser within Home Assistant but not showing on iPhone HA app. Is there any tricks?

```
type: custom:webrtc-camera
url: rtsp://srv.home.com:8554/garage
background: true
ui: true
```

WebRTC Camera
Version: 3.0.0

**Comment by AlexxIT** [comment]
What iOS version do you have?
Have you clear cache in you browser?
It's technology label shown in top right corner for you when you not using ui true?

**Comment by thiagobucca** [comment]
it's not working for me also. I'm on latest version and technology shows "RTC" in top right corner.

**Comment by AlexxIT** [comment]
@thiagobucca this issue about UI on iPhone. You also has this problem?

**Comment by bm55** [comment]
> What iOS version do you have?
> Have you clear cache in you browser?
> It's technology label shown in top right corner for you when you not using ui true?

I have iOS 16.2 and it shows RTC on the top right. 

I spent more time today and found that it does work if I open HA in Safari browser even without the “ui: true”. The ui doesn’t work on Edge browser and the iOS HA app

**Comment by AlexxIT** [comment]
I think it's just a cache inside your Hass app.
What you mean about Edge browser? iOS has only one browser - Safari. Any others it's just webview with a lot a limitations.

**Comment by bm55** [comment]
I wasn’t aware of the cache option in HA app. After deleting the cache, the ui works but with strange behavior - sometimes it launches the stream in full screen without any input. Ui disappears after exiting the full screen

**Comment by thiagobucca** [comment]
@AlexxIT yes, after some time testing and clearing the cache, the behavior is exactly like bm55 in the comment above.

**Comment by AlexxIT** [comment]
Auto full screen error is another issue #388
