### ISSUE TITLE
Security for WebRTC with external port 8555

### ISSUE THREAD

**Issue by dm82m** [AlexxIT/WebRTC#390]
hey guys,

I switched to version 3.x and moved from 5000 udp ports to stun:8555 in go2rtc.yaml and port forward of 8555 in my router.

my question is now: is that port secured via home assistant or is it possible for people out there to connect to my public_ip:8555 and consume my outdoor video stream?

best
Dirk’

**Comment by AlexxIT** [comment]
I cannot guarantee that there are no bugs or vulnerabilities in the [pion library](https://github.com/pion):
https://github.com/AlexxIT/go2rtc/blob/f0def68482dad3a2f1e78d364a5099f580c32f4a/pkg/webrtc/api.go#L43-L51

But this port is only used to transmit encrypted [SRTP packets](https://en.wikipedia.org/wiki/Secure_Real-time_Transport_Protocol). This port is not a control port and cannot be used to request or start a stream.

The SRTP packet encryption key is transmitted through the Home Assistant API. Therefore, if you use HTTPS, it cannot be intercepted.

**Comment by dm82m** [comment]
Okay thanks, sounds good. Last question: why is it then possible to set a user and password for external ports? I guess mainly for the webui?

and one side nose: regarding “change your yaml” maybe you can make it more clear that go2rtc.yaml is meant, I was modifying configuration.yaml and wondering why nothing changes 😬

**Comment by AlexxIT** [comment]
Where you read about "change your yaml"?

Read more here: https://github.com/AlexxIT/go2rtc#security

You can set user/pass for go2rtc WebUI and RTSP ports. It's for you LAN. You shouldn't open this ports to WAN, even with auth. You also can close LAN access to this ports if you want. Component will continue to work without problems. But WebUI and RTSP Server can be useful for you.

**Comment by dm82m** [comment]
Ahhh user/pass is for 8554 and 1984, got it. Thanks for clarification.

I was just reading here: https://github.com/AlexxIT/go2rtc#module-webrtc

and interpreted “you can change the port in YAML config:” as configuration.yaml - maybe it’s just me but something like “you can change the port in YAML config file ‘go2rtc.yaml’”

**Comment by AlexxIT** [comment]
go2rtc is separated standalone application. It's not related and not depends on Home Assistant

**Comment by dm82m** [comment]
This is know also clear to me. But it was not when migrating the 2.x integration to 3.x in home Assistant. Anyways. I am fine know. Was only mentioning it cause it could help other users aswell. Or maybe it’s just my own inability.
