### ISSUE TITLE
3.0 update , black screen MSE

### ISSUE THREAD

**Issue by LilCritical** [AlexxIT/WebRTC#392]
hello ,
before this update my chinese ip camera's worked fine using rstp://username:password@ip:554/live/ch00_1
with this update i now get a black screen and MSE on the top right corner .. no video feeds 
am i doing something wrong ? i got the go2rtc addon installed etc

thanks in advance

**Comment by AlexxIT** [comment]
Try to get stream in go2rtc WebUI. Try only WebRTC mode and only MSE mode.

**Comment by LilCritical** [comment]
> Try to get stream in go2rtc WebUI. Try only WebRTC mode and only MSE mode.

 thank you for the reply ,
unfortunatelly none of them give any feeds just black screen for webrtc mode it says loading instad of MSE

**Comment by AlexxIT** [comment]
Increase go2rtc log level to trace and provide logs. You can run go2rtc on any PC. You can send logs in private msg. Check contracts in GitHub profile.

**Comment by LilCritical** [comment]
> Increase go2rtc log level to trace and provide logs. You can run go2rtc on any PC. You can send logs in private msg. Check contracts in GitHub profile.

hello im getting this error 
![log](https://user-images.githubusercontent.com/95590442/213927679-0d8fa01d-1ab7-485c-8a40-5735078e7e4c.png)

**Comment by AlexxIT** [comment]
This is trace level message. Not important error

**Comment by LilCritical** [comment]
> This is trace level message. Not important error

how can i pm you on github to show the full log

**Comment by AlexxIT** [comment]
Check github profile

**Comment by LilCritical** [comment]
> Check github profile

i really cant find it anywhere how to send dm's , google says its not possible anymore ..
do you have discord ? LilCritical#0983

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT#contacts

**Comment by majkers** [comment]
Same happens for me. My reolink MSE streams do not work anymore. Either from custom card or go2rtc web UI. Sometimes it starts with an image but then freezes. RTC works for them without any problems. I will try trace some logs.

**Comment by majkers** [comment]
```
RTSP/1.0 401 Unauthorized
Cseq: 1
Date: Tue, Jan 24 2023 10:52:15 GMT
Www-Authenticate: Digest realm="LIVE555 Streaming Media", nonce="45de1447ae3dec8fe7a9c7cddc6d4b22"

11:52:14.684 TRC [rtsp] client request:
DESCRIBE rtsp://CAMERA_IP_ADDRESS:554/h264Preview_01_sub RTSP/1.0
CSeq: 2
Authorization: Digest username="MY_USERNAME", realm="LIVE555 Streaming Media", nonce="45de1447ae3dec8fe7a9c7cddc6d4b22", uri="/h264Preview_01_sub", response="f50275770a9314ea89960f0d73663f1b"
Accept: application/sdp
Require: www.onvif.org/ver20/backchannel

11:52:14.723 TRC [rtsp] client response:
RTSP/1.0 200 OK
Date: Tue, Jan 24 2023 10:52:15 GMT
Content-Type: application/sdp
Content-Base: rtsp://CAMERA_IP_ADDRESS/h264Preview_01_sub/
Cseq: 2
Content-Length: 695

v=0
o=- 1674349224548930 1 IN IP4 CAMERA_IP_ADDRESS
s=Session streamed by "preview"
i=h264Preview_01_sub
t=0 0
a=tool:LIVE555 Streaming Media v2020.08.12
a=type:broadcast
a=control:*
a=range:npt=0-
a=x-qt-text-nam:Session streamed by "preview"
a=x-qt-text-inf:h264Preview_01_sub
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:500
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKCgPZA=,aO48sA==
a=control:track1
m=audio 0 RTP/AVP 97
c=IN IP4 0.0.0.0
b=AS:256
a=rtpmap:97 MPEG4-GENERIC/16000
a=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408
a=control:track2
11:52:14.724 TRC [streams] producer=0 candidate=0 media="video, sendonly, 96 H264/90000"
11:52:14.724 TRC [streams] match producer:0:0 => consumer:0:0 codec="96 H264/90000"
11:52:14.724 TRC [rtsp] client request:
SETUP rtsp://CAMERA_IP_ADDRESS/h264Preview_01_sub/track1 RTSP/1.0
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
CSeq: 3
Authorization: Digest username="MY_USERNAME", realm="LIVE555 Streaming Media", nonce="45de1447ae3dec8fe7a9c7cddc6d4b22", uri="/h264Preview_01_sub/track1", response="572add6d29642491c2c966e4463ab959"

11:52:14.748 TRC [rtsp] client response:
RTSP/1.0 200 OK
Cseq: 3
Date: Tue, Jan 24 2023 10:52:15 GMT
Transport: RTP/AVP/TCP;unicast;destination=HA_IP_ADDRESS;source=CAMERA_IP_ADDRESS;interleaved=0-1
Session: 7F67B808;timeout=65

11:52:14.749 TRC [streams] consumer=0 candidate=1 media="audio, recvonly, 0 MPEG4-GENERIC/0"
11:52:14.749 TRC [streams] producer=0 candidate=0 media="video, sendonly, 96 H264/90000"
11:52:14.750 TRC [streams] producer=0 candidate=1 media="audio, sendonly, 97 MPEG4-GENERIC/16000"
11:52:14.750 TRC [streams] match producer:0:1 => consumer:0:1 codec="97 MPEG4-GENERIC/16000"
11:52:14.750 TRC [rtsp] client request:
SETUP rtsp://CAMERA_IP_ADDRESS/h264Preview_01_sub/track2 RTSP/1.0
Transport: RTP/AVP/TCP;unicast;interleaved=2-3
CSeq: 4
Authorization: Digest username="MY_USERNAME", realm="LIVE555 Streaming Media", nonce="45de1447ae3dec8fe7a9c7cddc6d4b22", uri="/h264Preview_01_sub/track2", response="73528b9de65dd8e6963e4965625d254e"
Session: 7F67B808

11:52:14.755 TRC [rtsp] client response:
RTSP/1.0 200 OK
Cseq: 4
Date: Tue, Jan 24 2023 10:52:15 GMT
Transport: RTP/AVP/TCP;unicast;destination=HA_IP_ADDRESS;source=CAMERA_IP_ADDRESS;interleaved=2-3
Session: 7F67B808;timeout=65

11:52:14.755 DBG [streams] start producer url=rtsp://MY_USERNAME:MY_P@SSWORD@CAMERA_IP_ADDRESS:554/h264Preview_01_sub
11:52:14.755 TRC [rtsp] client request:
PLAY rtsp://CAMERA_IP_ADDRESS/h264Preview_01_sub/ RTSP/1.0
CSeq: 5
Authorization: Digest username="MY_USERNAME", realm="LIVE555 Streaming Media", nonce="45de1447ae3dec8fe7a9c7cddc6d4b22", uri="/h264Preview_01_sub/", response="aa0b4f6befdfc66c07c6eebdc235b474"
Session: 7F67B808

11:52:14.808 TRC [rtsp] client response:
RTSP/1.0 200 OK
Cseq: 5
Date: Tue, Jan 24 2023 10:52:15 GMT
Range: npt=0.000-
Session: 7F67B808
Rtp-Info: url=rtsp://CAMERA_IP_ADDRESS/h264Preview_01_sub/track1;seq=57986;rtptime=266586945,url=rtsp://CAMERA_IP_ADDRESS/h264Preview_01_sub/track2;seq=54205;rtptime=1157383615
```

**Comment by majkers** [comment]
Is it possible that special chars like @#$ in password might cause an issue? Besides reolink, I have also yi camera with hack and MSE is working just fine for them.

**Comment by AlexxIT** [comment]
Password not a problem if your WebRTC stream starts.
MSE selected because AAC codec. Because Video+Audio better than just Video.

**Comment by majkers** [comment]
Ohhh I see now. Seems like that was it. When I added new stream as ffmpeg like _ffmpeg:camera1#video=copy_ all problems are gone. Selecting mode is OK and MSE stream from this new stream works as well. Strange that I had to do such things to make it work.

**Comment by AlexxIT** [comment]
Fixed in v3.0.1

**Comment by AlexxIT** [comment]
Looks like some Reolink cameras has problem AAC codec. Thats why `ffmpeg:camera1#video=copy` helps for MSE.

**Comment by jakes-it** [comment]
Where must we include the ffmpeg:camera1#video=copy in HA(PS I'm not running frigate or any go2rtc server). MSE stream does not work at all, the RTC mode does not always start it defaults a lot back to MSE. The MP4 mode works but it is very laggy

**Comment by AlexxIT** [comment]
Reolink MSE fixed in go2rtc addon master version. You can install it or wait next release
