### ISSUE TITLE
NotsupportedError: video/mp4, codecs=undefined

### ISSUE THREAD

**Issue by pergolafabio** [AlexxIT/WebRTC#393]
Hi, after updating to 3.0 , i receive error:

NotsupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource" : The type provided (video/mp4, codecs=undefined) is unsupported

I only receive this on HA Android companion app, clearing cache, restarting HA / APP doesnt work
Chrome browser doesnt give any error, 

i have a simple setup, like:

```
          - type: custom:webrtc-camera
            #entity: camera.buiten
            url: rtsp://xxxxx@192.168.0.14:554/Sms=18.unicast#backchannel=0
```

Before i used the entity camera card, but in other threads they speak about adding #backchannel=0 , but that doesnt help either

**Comment by AlexxIT** [comment]
Try to get stream in go2rtc WebUI. Try only WebRTC mode and only MSE mode.

**Comment by pergolafabio** [comment]
yes, that works on chrome browser, when i click on "stream" it shows me the stream when i access this page : http://192.168.0.17:1984/

But when i open HA Companion app, i still receive the error

i dont have any port open in firewall for 1984  or anything else

**Comment by pergolafabio** [comment]
ahh i need to add the urls there, but without mp4/mjpeg selected?  ok ...

but how can i delete/manage the existing ones? it doenst delete or save them it seems

**Comment by pergolafabio** [comment]
Its not 100% clear how i can check only MSE/WEBRTC mode here? Seems i cant save or edit anything on this page?

![image](https://user-images.githubusercontent.com/43251136/213926385-10af6d30-096b-4638-81e1-be356521e316.png)

**Comment by AlexxIT** [comment]
Select stream row, select only one technology, click stream

**Comment by pergolafabio** [comment]
yes, the stream opens (chrome) but afterwards, all checkboxes are still selected, and stream still fails on compantion app

**Comment by dennyreiter** [comment]
I'm seeing this also, using Chrome:

```
type: 'custom:webrtc-camera'
url: 'rtsp://daddy:xxxxxxxxx@172.16.2.69:554/videoMain'
mode: webrtc
```
Setting the mode does not make a difference. I receive the same error if I try and use the entity provided by Frigate.
It does stream from the go2rtc page selecting only webrtc (but not mse.)

**Comment by pergolafabio** [comment]
I have it defined like below, stream works on chrome, but not on HA  android companion

```
          - type: custom:webrtc-camera
            entity: camera.buiten
            mode: webrtc,mse
```

on the go2rtc webpage i still see all checkbox and option selected, maybe thats the issue ?

**Comment by AlexxIT** [comment]
@pergolafabio you need to confirm with what technologies work you stream in go2rtc WebUI. And with what doesn't work

**Comment by pergolafabio** [comment]
Well, they all work when I open then on chrome browser, but the HA android Companion app gives issues

**Comment by AlexxIT** [comment]
They all work on same Android phone?

**Comment by pergolafabio** [comment]
Yes, on android browser and on notebook I tried , stream, two way audio, MP4 , they all work...

But on companion app, I see the issue

**Comment by pergolafabio** [comment]
Rtsp and mpjeg, don't work... The others do on Android chrome browser

**Comment by AlexxIT** [comment]
Ok. This is Companion cache problem. It using old custom card

**Comment by pergolafabio** [comment]
No, I already cleared cache on companion app several times...?

**Comment by AlexxIT** [comment]
Can you show screen with error?

**Comment by pergolafabio** [comment]
![Uploading Screenshot_20230122-201512.jpg…]()

**Comment by pergolafabio** [comment]
![Screenshot_20230122-201512](https://user-images.githubusercontent.com/43251136/213935446-3f972242-f31f-49b8-9454-7ba61ba5f334.jpg)

**Comment by AlexxIT** [comment]
This is old card! New card doesn't has icon in corner.

**Comment by pergolafabio** [comment]
Hmm, but what can I do more then clearing cache?

**Comment by pickonedev** [comment]
I was watching your discussion having the same problem, but after I clean cache, data storage and reopened the card, it started to work. But still, I have a question which pergolafabio had it as well.. How can I delete the wrong/bad streams from webui? As far as I see, when you put the mouse pointer on "delete" button, there is no link, it is only "http://IP:1984/#"

**Comment by pergolafabio** [comment]
See, I clear cache... I didn't delete storage, it will delete all settings, normally cache is always enough for custom cards...

![Screenshot_20230122-204219](https://user-images.githubusercontent.com/43251136/213936715-a30188db-aefc-45aa-a0eb-de31f44de599.jpg)

**Comment by pickonedev** [comment]
I use Fully Kiosk Browser, not Companion...

**Comment by AlexxIT** [comment]
@pickonedev it seems to be a bug with the deletion of a stream that was added from the HA. I'll fix it. 
Don't worry, this list is not persistent. It will be deleted when you restart the integration/go2rtc
Permanent list of streams only from config `go2rtc.yaml`.

**Comment by pergolafabio** [comment]
Hi @AlexxIT , seems i had in resources indeed an reference to old version, probably from an older readme copy/pasted...

```
  - url: /hacsfiles/webrtc/webrtc-camera.js?v2.3.0
    type: js   
```

Still strange that it was working in chrome browser?
Anyway, i tried removing, since it doesnt mention anymore that it needs to be added manually, but then i have on HA companion app, custom card not found

Then changed back to:

```
  - url: /hacsfiles/webrtc/webrtc-camera.js?v3.0.0
    type: js   
```

But still after clearing cache, still custom card not found, allthough still working on chrome browsers... also after clearing cache
Seems there is another issue ongoing, with users having the same issue on companion app

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/issues/260#issuecomment-1288676091

**Comment by pergolafabio** [comment]
tried all steps, also tried readding the integration
still dont get why it works on chrome, but not on companion

I use yaml method, what is the best method to load it manually?

i copy pasted the webrtc-camera.js file from the custom components folder to "www\community\webrtc"

then loaded with:
```

  - url: /hacsfiles/webrtc/webrtc-camera.js?v3.0.0
    type: module  
```

still doesnt work :-(

**Comment by pergolafabio** [comment]
started clean, removed it also from my resources, readded integration, cleared cache on chrome, card still loads, even without a reference to resource
cleared cache on companion, still a issue about card not found

**Comment by pickonedev** [comment]
I tested with companion as well and yes, there was a problem with not deleting the cache, but I have uninstalled companion and after I reinstalled, it started to  work. Seems that companion does not delete cache so easy :-) Have you tried to reinstall?

**Comment by pergolafabio** [comment]
ok, got it to work now, i was missing the "=" before the 3.0.0

```
  - url: /hacsfiles/webrtc/webrtc-camera.js?v=3.0.0
    type: module  
```

thnx for all help here!!

**Comment by pergolafabio** [comment]
i still need to copy/pasted the webrtic files manyally, shoudl this not be mentioned in readme? especially for yaml users?

**Comment by AlexxIT** [comment]
I think YAML users are causing problems for themselves and for me. How much time you and I have wasted.

I have never used YAML and I don't recommend it to anyone. And the HA developers would not recommend using it either.

**Comment by pergolafabio** [comment]
> I think YAML users are causing problems for themselves and for me. How much time you and I have wasted.
> 
> I have never used YAML and I don't recommend it to anyone. And the HA developers would not recommend using it either.

true, but still lots of users are using it :-) µ
and should work too, not? :-)

**Comment by AlexxIT** [comment]
I think when users choose the "hard way," they should know how to use it

**Comment by pergolafabio** [comment]
100% correct, i was just indeed missing the "="  :-)

**Comment by AlexxIT** [comment]
`?v=3.0.0` really means nothing. It's just for passing cache. You can write anything after question mark.

**Comment by pergolafabio** [comment]
ah, yeah its still strange, maybe its indeed an companion cache issue, allthough i cleared it several times
but anyway, it works now, and i'm happy

thnx again for support!!! appreciated

**Comment by AlexxIT** [comment]
Users said that logout helps with clear cache for companion.

**Comment by pergolafabio** [comment]
Ah , something to try next time

**Comment by mortenmoulder** [comment]
Hi @AlexxIT I have a similar issue to this. I am using latest 3.2.1 version of WebRTC Camera (verified by checking the JS file getting loaded in browser) and 1.6.2 of go2rtc as a separate Docker container.

After updating Home Assistant today to 2023.8.0 (from 2023.3.5), I got the same error when trying with this config:

```
type: custom:webrtc-camera
url: rtsp://192.168.1.123:8554/camera
```

Here is how it looks on the screen:

![image](https://github.com/AlexxIT/WebRTC/assets/1304665/2b73462d-7945-4190-a29a-39b5214f4864)

iOS and Android apps report the same error. If I go to http://192.168.1.123:1984/webrtc.html?src=camera&media=video+audio it works perfectly.

The cameras are Dahuas and a few Sonoff GK-200MP2 as well.

I tried everything I can think of. Any clues?

**Comment by AlexxIT** [comment]
This is old card. From v2. Because you have icon in top right corner.

**Comment by mortenmoulder** [comment]
@AlexxIT Okay yep you're right. I apparently have this installed two places:

\home-assistant\www\community\webrtc
and
\home-assistant\custom_components\webrtc\www

The first one is the one I actually reference, where the other is the one installed via HACS. I copied the files from the HACS folder into the actual folder, then refreshed the cache by changing the version number to 3.2.11 under resources. Works again now :-)
