### ISSUE TITLE
Custom card missing

### ISSUE THREAD

**Issue by zarevskaya** [AlexxIT/WebRTC#394]
Hey!

I don't find the "custom card".

Cache clear, reboot, I had try on Chrome, Firefox, Brave.

Since 4 day's, impossible to find this card for do this thing:

type: 'custom:webrtc-camera'
url: 'rtsp://rtsp:12345678@192.168.1.123:554/av_stream/ch0'

Thank you in advance :)

PS: I use the version 3.

**Comment by AlexxIT** [comment]
#260 probably you use Lovelace more YAML

**Comment by zarevskaya** [comment]
I don't use YAML.

What can I do?

**Comment by AlexxIT** [comment]
Maybe you haven't install integration. You can also check errors in Hass logs

**Comment by zarevskaya** [comment]
I use integration. But I don't see anything ^^

I will check logs.

Thank you and have a noce day Alexx

**Comment by zarevskaya** [comment]
![Capture d’écran 2023-01-23 144654](https://user-images.githubusercontent.com/60230221/214055557-2aa73335-26a3-4761-aa85-e5ca6a36637b.png)

Very weird oO

**Comment by AlexxIT** [comment]
What is wired for you? If this window is displayed - the integration is not configured. If integration is not configured - there is no card.
