### ISSUE TITLE
D-Link camera - Invalid port bug

### ISSUE THREAD

**Issue by djungelola** [AlexxIT/WebRTC#395]
After upgrade to 3.0 my dlin dcs-8302LH camera stopped working.

Config:
type: custom:webrtc-camera
url: rtsp://admin:xxxxxx@192.168.1.63:554/onvif/profile.0

Pasting the rtsp url to VLC works just fine

Error:
2023-01-23 12:56:38.318 DEBUG (webrtc) [custom_components.webrtc.utils] 12:56:38.318 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="parse \"rtsp://::ffff:192.168.1.63/onvif/profile.0/\": invalid port \":192.168.1.63\" after host" url=rtsp://admin:xxxxx6@192.168.1.63:554/onvif/profile.0

Cant understand the parsing error!

Br Ola

**Comment by AlexxIT** [comment]
Do you have special symbols in password? Is your username just `admin`?

**Comment by djungelola** [comment]
> Do you have special symbols in password? Is your username just `admin`?

No, just admin and psw is just digits (123456)

/Ola

**Comment by AlexxIT** [comment]
You can increate log level to trace for go2rtc. To check exact place of error.

**Comment by djungelola** [comment]
Not really sure where to do that. Please advice.

**Comment by AlexxIT** [comment]
You need to read go2rtc docs

**Comment by djungelola** [comment]
[go2rtc.log](https://github.com/AlexxIT/WebRTC/files/10480514/go2rtc.log)

**Comment by AlexxIT** [comment]
Thanks. It's helpful. Stupid camera. I wonder how it works in VLC. I'll fix it

**Comment by AlexxIT** [comment]
Fix should be in master version of go2rtc addon. If you want - you can install it. Or wait next release. I need to collect other issues for next release.

**Comment by djungelola** [comment]
> Fix should be in master version of go2rtc addon. If you want - you can install it. Or wait next release. I need to collect other issues for next release.

Thanks AlexxIT!

/Ola

**Comment by AlexxIT** [comment]
Fixed in v3.0.1

**Comment by djungelola** [comment]
Worked just fine! And a camera that was just black before came alive also. Great fix!!
