### ISSUE TITLE
Port forwarding is breaking my ability to access my network remotely

### ISSUE THREAD

**Issue by ZainAjam** [AlexxIT/WebRTC#40]
I have 2 sonoff cameras and i've port forwarded 50000 to 50019, and i've set the same range in the WebRTC integration. For some reason, when I do this, it breaks my ability to access my entire home assistant instance remotely. I have to disable the port forwarding to get back the ability to access my home assistant instance, but then I cannot see the cameras when accessing remotely.

**Comment by ZainAjam** [comment]
This could be an issue on my ISP side and just co-incidence that when i removed the port forwarding, access was restored to home assistant. I did a few restarts of devices and everything seems fine now. I will keep an eye on this, and report back in a few days if everything is still fine or not.

**Comment by AlexxIT** [comment]
Port forward will work only if you have public IP address. Port forward with private IP address may break external access
