### ISSUE TITLE
Error: NotSupportedError: MediaSource.add.SourceBuffer: Can't play type

### ISSUE THREAD

**Issue by MarcoCITA** [AlexxIT/WebRTC#400]
After 3.0 update an error pops up.
Error: NotSupportedError: MediaSource.add.SourceBuffer: Can't play type

**Comment by AlexxIT** [comment]
Please show screen

**Comment by MarcoCITA** [comment]
![immagine](https://user-images.githubusercontent.com/53432302/214376058-994a24dd-a587-451f-bb2a-72d1b1819cc2.png)

**Comment by AlexxIT** [comment]
This is old version. Browser cache
