### ISSUE TITLE
MP4 Stream Playing at <1FPS

### ISSUE THREAD

**Issue by PablaV** [AlexxIT/WebRTC#402]
When on LAN my streams start using RTC and the FPS is fine. When I am on WAN and connect, the streams use MP4 to play. The picture comes up but the live stream plays at less than 1FPS, almost like its playing a time lapse. After a few minutes of viewing, I cannot reconnect to HA on LAN or even through Nabu Casa until I force close the app and wait a minute or two (not sure if this is related to my issue though). This only happens when I am not on LAN. I am using WebRTC v3.0.1, and Go2RTC v1.0. Here is the info from when the stream starts:

Edit: Even on LAN this happens, the reason why its not noticeable is  because most of the times the streams play using RTC and occasionally MP4. 

```
{
  "producers": [
    {
      "type": "RTSP source",
      "url": "rtsp://192.168.8.20:554/cam/realmonitor?channel=7\u0026subtype=0/",
      "remote_addr": "192.168.8.20:554",
      "user_agent": "go2rtc/1.0.0",
      "medias": [
        "video, sendonly, 96 H264/90000"
      ],
      "tracks": [
        "96 H264/90000, sinks=1"
      ],
      "recv": 69020318
    }
  ],
  "consumers": [
    {
      "type": "WS/MP4 client",
      "remote_addr": "192.168.8.85:45168",
      "user_agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2022.10.1 (io.robbie.HomeAssistant; build:2022.424; iOS 16.3.0) Mobile/HomeAssistant, like Safari",
      "send": 17414164
    }
  ]
}
```

**Comment by g1za** [comment]
I'm experiencing lags with MP4 stream too

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC#faq

**Comment by g1za** [comment]
Thank you. I'll read that carefully. Just a question: with version 2.3.1 the stream was fluid on iPhone as well and the stream was ("is" if I download the previous version) the one with the flower-like icon (sorry I can't find the section with the explanation of the icons anymore).
Is this because of the switch to go2rct?
Thanks

**Comment by AlexxIT** [comment]
Flower means WebRTC. Now it named RTC.
This technology works on iPhones.
But sometimes it needs additional settings for external access.

**Comment by PablaV** [comment]
If I am understanding this correctly, the only way to gain external access is through MP4? Since the iPhone can play RTC, could external access work that way?

**Comment by AlexxIT** [comment]
MP4 is a helper for iPhone owners who couldn't manage to setup external access for WebRTC.
Seeing a stream of keyframes is better than seeing nothing.

**Comment by PablaV** [comment]
Ah I see, I think I got things working. I re-setup external access for WebRTC now I see RTC streams when connecting externally.
