### ISSUE TITLE
WebRTC Custom Card uses url string instead of entityid for stream

### ISSUE THREAD

**Issue by kidhasmoxy** [AlexxIT/WebRTC#404]
I'm using the go2RTC addon and want to transcode AAC to Opus so I get audio on iOS device. The Picture Entity card sends the entity id as the stream name so it's easy to set transcoding in the go2rtc config. The WebRTC Custom Card is setup to use the entity ID, but it registers the stream using the URL. This means I can't reuse the connection strings and also limits my ability to transcode a custom stream. 

Is it possible to have the WebRTC card respect the config and register the stream with url if it was supplied, and entity_id if that was supplied?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/releases/tag/v3.0.2
