### ISSUE TITLE
Configure label position

### ISSUE THREAD

**Issue by addrum** [AlexxIT/WebRTC#406]
Annoyingly the Amcrest AD410 has no way to move the timestamp which always sits in the top right corner...the same place as the WebRTC labels (RTC, MP4 etc). Would be nice if the card allow configuring the location of the label (all 4 corners as options maybe?)

**Comment by AlexxIT** [comment]
Bottom left
```
type: custom:webrtc-camera
url: sonoff1
style: |
  .header {bottom: 6px}
  .mode {position: absolute; left: 0px; bottom: 0px}
```
