### ISSUE TITLE
No image being displayed on android device when connected on 3G/LTE via nabu casa

### ISSUE THREAD

**Issue by majkers** [AlexxIT/WebRTC#41]
As mentioned in #30 I do not see any image from camera nor a default cartoon video when using android device connected with 3G/LTE to my HA via nabu casa. 

PC/Android + Localhost + Wi-Fi/LAN = works
PC + NabuCasa + Wi-Fi/WAN = works
Android + NabuCasa + 3G/LTE = doesn't work

**Comment by AlexxIT** [comment]
Duplicate #26 - all problems about outside connection there

**Comment by majkers** [comment]
Ok but not exactly. I can access it from outside LAN but only on PC not on Android

**Comment by majkers** [comment]
> Duplicate #26 - all problems about outside connection there

Ok but not exactly. I can access it from outside LAN but only on PC not on Android

**Comment by AlexxIT** [comment]
Have you tried: Android + NabuCasa + Wi-Fi/WAN ?

Because Wi-Fi/WAN and 3G/LTE/WAN are different cases.

**Comment by majkers** [comment]
> Have you tried: Android + NabuCasa + Wi-Fi/WAN ?
> 
> Because Wi-Fi/WAN and 3G/LTE/WAN are different cases.

Android+Nabu Casa+WiFi/WAN works

**Comment by AlexxIT** [comment]
Well it is problem not with Android. If you have public IP, forward ports as it described in readme

**Comment by majkers** [comment]
But why this default cartoon video is not working? It does require public ip to work? And why do I have to forward ports when I can still access all videos for example from PC? The one and only config not working is android through LTE/3G connection.

**Comment by AlexxIT** [comment]
There is a lot of information about private IPs, symmetric NAT, STUN and UDP hole. You can find all the links in the FAQ.
