### ISSUE TITLE
No autoplay when switching back from other lovelace tab

### ISSUE THREAD

**Issue by Stormrage-DJ** [AlexxIT/WebRTC#411]
Hi there!

My use-case is that I have 1 front screen on tablet with cameras which plays in rtc mode and with 3.x.x (with 2.x it was working fine) that started to broke or behave differently: automatically pauses, won't play video stream when navigating back from other tab/lovelace.

How to reproduce:

0. Create a lovelace page with camera stream and start there
1. navigate to any other lovelace page
2. navigate back to lovelace page where your camera stream is and instead of playing, it will be paused.

Expected behavior:
When I switch back to camera page it should continue playing without manually pressing the play button.

![2023-01-31 12_54_43-Settings](https://user-images.githubusercontent.com/83466158/215753631-18011c57-01e5-4bcd-bcc4-81b80ffbe99e.png)
![2023-01-31 12_55_01-Settings](https://user-images.githubusercontent.com/83466158/215753646-d5b14cf5-6b35-425c-a17f-6a5c0c3d9c0a.png)

**Comment by AlexxIT** [comment]
OS/Browser?

**Comment by Stormrage-DJ** [comment]
Same happens on:
Win11 and 10 64 bit chrome 109.0.5414.120 (Official Build) (64-bit)
Also same happens on Android companion app 2022.12.10-full (Android 9)
And on Kiosk Browser on a different android tablettablet. (Android 10)

I believe it is more-or-less browser independent issue

**Comment by bigjme93** [comment]
I can confirm i have this issue as well on the android companion app but have never seen it on a browser. My companion apps (2 of them) are  the same so i will just include one below:

Fire HD 10 tablet (2021), Android 9, Version 2023.1.1-full
Home Assistant 2023.1.5
Frontend 20230110.0 - latest

It does not always happen for me however. If i navigate away for 30+ seconds its fine when i return
The issue seems to happen if i navigate away and then back quickly like turning a light on and going back
Once paused, it remains paused until you manually un-pause it

**Comment by reijorland** [comment]
Same issue for me on all my devices. I noticed this when updated from 2.x to 3.0

- Google Chrome browser.
- HA App on iPad, iPhone, and Samsung Galaxy 10 Plus
- Fully Kiosk on Fire HD 10 Plus 2021.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/releases/tag/v3.0.2

**Comment by reijorland** [comment]
3.0.2 did not fix the issue for me.
I restarted the HA and rebooted my hardware. I don't know what else to try.

**Comment by S-Przybylski** [comment]
I had similar issues using the Frigate-custom card which itself uses this card to display RTC. 
As a workaround I have configured the Frigate custom card in the following way (maybe this helps). It's not perfect but it limits the traffic in that way, that the video is streamed only when the card is displayed:
````
type: custom:frigate-card
cameras:
  - webrtc_card:
      entity: camera.cam
live:
  webrtc_card:
    background: false
  preload: false

````
If I understand the logic of the card correctly, 'background: false' is bypassed to this card.

**Comment by reijorland** [comment]
> 3.0.2 did not fix the issue for me. I restarted the HA and rebooted my hardware. I don't know what else to try.

After restarting HA a couple more times, it looks like my card is fixed. 
I have this typical card...

type: custom:webrtc-camera
entity: camera.mycamera1


Will update you again if needed.

**Comment by TitjyDev** [comment]
I'm experiencing similar issues too. 

- Setting `background:true` won't play the stream automatically. I need to click on the play button. I don't know if this behavior is normal.
- Switching back from other tabs won't let me watch the stream: it won't start automatically and clicking the play button does nothing. I need to refresh the page to it works again.

**WebRTC v3.6.0**

```
type: custom:webrtc-camera
url: Camera-Room
server: http://localhost:11984
media: video,audio
title: Camera Room 1
muted: true
ui: true
background: true
```
