### ISSUE TITLE
Tablet gets very laggy after a while with the cameras loaded

### ISSUE THREAD

**Issue by bigjme93** [AlexxIT/WebRTC#412]
I think this may be a home assistant issue rather than anything else but want to mention it anyway

I have 2 android tablets running the companion app, details are as follows

Fire HD 10 tablet (2021), Android 9, Version 2023.1.1-full
Home Assistant 2023.1.5
Frontend 20230110.0 - latest
Go2RTC v1.0.1
WebRTC Camera v3.0.1

Before switching, my dashboards contained mjpeg streams in picture cards with no issues.
Now i have go2rtc in a separate docker, and the WebRTC Camera cards being used which work great

These camera feeds stay loaded almost 24/7 (just one per lovelace and set to auto pause) but I've noticed after a week or so, the tablets start to get slower and slower, to the point where even alexa alarms refuse to work properly on them

This has only started since switching and it works flawlessly until this starts to happen.
It feels like a memory issue but I think its likely to be with the home assistant web socket that everything is streaming through holding onto too much over time

Has anyone else run into this issue?

Regards,
Jamie

**Comment by AlexxIT** [comment]
How many cameras you have? What type of stream you using (WebRTC, MSE, etc)?

**Comment by bigjme93** [comment]
Sorry, i completely forgot they would be useful

Here are the full info details for the streams from go2rtc:
```
{
  "producers": [
    {
      "type": "RTSP source",
      "url": "rtsp://192.168.x.x:554/Streaming/Channels/102/",
      "remote_addr": "192.168.x.x:554",
      "user_agent": "go2rtc/1.1.0",
      "medias": [
        "video, sendonly, 96 H264/90000"
      ],
      "tracks": [
        "96 H264/90000, sinks=2"
      ],
      "recv": 2521409408
    }
  ],
  "consumers": [
    {
      "type": "WebRTC client",
      "remote_addr": "udp4 prflx 192.168.x.x:36242 related :0",
      "user_agent": "Mozilla/5.0 (Linux; Android 9; KFTRWI Build/PS7326.3178N; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.170 Safari/537.36 Home Assistant/2023.1.1-3124 (Android 9; KFTRWI)",
      "send": 95966569
    },
    {
      "type": "WebRTC client",
      "remote_addr": "udp4 host 192.168.x.x:45636",
      "user_agent": "Mozilla/5.0 (Linux; Android 9; KFMAWI Build/PS7326.3178N; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.114 Safari/537.36 Home Assistant/2023.1.1-3124 (Android 9; KFMAWI)",
      "send": 56827911
    }
  ]
}
```

I have updated just in case since posting.

In home assistant i have 2 lovelace pages, each with a single camera as above, the camera entity is created as follows:
```
type: custom:webrtc-camera
url: front_trendnet_sub
mode: webrtc
```

All streams are in webrtc and are from 2 identical cameras via rtsp camera streams
The camera streams are h264, with a resolution of 640x360 and use roughly 370kbps of bandwidth

We leave the tablets on at least 1 of the camera streams 24/7 besides when we switch to turn lights on so its pretty much streaming all the time

Regards,
Jamie

**Comment by AlexxIT** [comment]
WebRTC technology is implemented completely by the browser. There are no places to optimize anything.
Have you interact with tablets during the day? It is important whether you stay on the same lovelace tab with the video the whole time or switch between tabs so the video is constantly stopped and restarted.

**Comment by bigjme93** [comment]
I had a feeling that was the case to be honest but wanted to check

The one tablet gets interacted with maybe twice a day for a few minutes and that's all
The other gets interacted with randomly through the day but maybe 12 to 15 times

Honestly i think this may just be the webrtc connection in home assistance causing it but as you say, thats handled by the webview on the device anyway

Sometimes the streams can be running 20+ hours with no interaction so it is a long stream

My only thought was if there was a way to reconnect automatically after 12 hours or so to see if that would help but as i say, each stream is stopped due to navigation at least once per day, and the issue doesn't happen until around a week after the last reboot of the device so the issue builds over time

**Comment by AlexxIT** [comment]
I don't think reconnecting will help. Rebooting the browser may help free up resources. But the question is about the implementation of the browser and the operating system itself.

**Comment by bigjme93** [comment]
I completely agree, i will close this now as i do think its a home assistant/web view issue rather than anything you can sort but thank you for confirming. Is there another format you'd recommend to try that keeps the low latency? We don't use 2 way on these specific cameras anyway but need them as real time as possible

**Comment by AlexxIT** [comment]
You can try mse or even mp4.

**Comment by germanotero** [comment]
I have the same issue, plus video halts after 20 or so minutes, mp4 doesn’t work mse doesn’t fix it :(
