### ISSUE TITLE
Multiple Instances of WebRTC card in same view inherit setting from one another

### ISSUE THREAD

**Issue by haforme** [AlexxIT/WebRTC#415]
Multiple Instances of WebRTC card for version 3.0.2 configured in the same view inherit setting from one another. An example is if I disable the viewing of the WebRTC mode via the style command "style: .mode {display: none}" on one webRTC card it disables them for both cards.  This seems to occur for anything that is related to "style:"

Home Assistant 2023.2.0
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230201.0 - latest

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/WebRTC/releases/tag/v3.1.0

**Comment by haforme** [comment]
Same problem with the latest version of v3.1.0

**Comment by AlexxIT** [comment]
It's just browser cache. I think I forgot to update version in the code.
