### ISSUE TITLE
sonoff/send_command. Service not found.

### ISSUE THREAD

**Issue by igorglazkow** [AlexxIT/WebRTC#42]
When i paste Full component code to GUI entites, have this problem.

May i can install any Sonof Plugin?

**Comment by AlexxIT** [comment]
If you have Sonoff camera, you need to install and setup
https://github.com/AlexxIT/SonoffLAN

**Comment by igorglazkow** [comment]
> If you have Sonoff camera, you need to install and setup
> https://github.com/AlexxIT/SonoffLAN

I use original Dafang Camera

**Comment by AlexxIT** [comment]
With custom firmware?

**Comment by masumehboluree** [comment]
Hi 
I install latest SonoffLAN and webrtc on home assistant. I add a card and connect to sonoff GK-200MP2-B camera and it work properly but although sonoff.send_command service exist but PTZ control not work. do you have any idea for solve this problem?
I call manually this service from services tab in developer tools section but did not see any reaction in camera!
Thanks a lot
