### ISSUE TITLE
Service "webrtc.create_link" generates error

### ISSUE THREAD

**Issue by alex-savin** [AlexxIT/WebRTC#421]
I was trying to use webrtc.create_link, but all of the times it spits out error. When I tried to lower down number of generated numbers to 10 it did work

```
Event is not JSON serializable: <Event call_service[L]: domain=webrtc, service=create_link, service_data=link_id=6791675154841193000960657897340062294605, url=rtsp://IP-ADDRESS:8554/doorbell, open_limit=1, time_to_live=60>: Integer exceeds 64-bit range
```

**Comment by AlexxIT** [comment]
Looks like link_id not string but integer. You need to use quotes.

**Comment by alex-savin** [comment]
Thank you!

**Comment by kloodhu** [comment]
hello, same problem here. use quotes where? when generating or when using? ' or "?
sorry for the lame question...
