### ISSUE TITLE
url with base_path in go2rtc not working

### ISSUE THREAD

**Issue by luzik** [AlexxIT/WebRTC#422]
As I am able to  add WebRTC extension to HA using https://my.ha.public.domain:8123/go2rtc/ (go2rtc using api: base_path: '/go2rtc') - WebRTC seams to try opening wss://my.ha.public.domain:8123/api/websocket and I got 404

**Comment by luzik** [comment]
One more thing! I am trying to use entity - not url in custom:webrtc-camera card

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/WebRTC/releases/tag/v3.1.0
