### ISSUE TITLE
WebRTC doesnt load every time on mobile app

### ISSUE THREAD

**Issue by HAuser1234** [AlexxIT/WebRTC#428]
In the HA mobile app for some reason not all streams load, but in the desktop Browser all streams work fine.
Example: I have 3 cameras. every time I opten the camera tab in HA, only one or even no camera-streams load. It hangs on Loading2.
Wehn I open the same Tab on the desktop it takes a second and all strems are there. Form there on the streams are instantly available.
Card code:

```
type: custom:webrtc-camera
muted: true
ui: true
background: false
entity: camera.XYZ
style: 'video {aspect-ratio: 16/9; object-fit: fill;}'
mode: webrtc
```

I have set the mode to webrtc, because only then I can get some streams to work, or else it loads a MSE stream and a black picture.

This is with webRTC V3.0.2

Is there any reason for that?

**Comment by AlexxIT** [comment]
Have you read docs and FAQ?

**Comment by HAuser1234** [comment]
yes it should work according to the FAQs. Apperently the problem only is one one phone. Other android devices seem to show all streams

**Comment by AlexxIT** [comment]
Are you doing this on a local network?
Do streams sometimes load and sometimes not on just one phone?

**Comment by HAuser1234** [comment]
It does seem to be specific to one Phone. I just switched to frigate and the frigate card seems to work. So I think we can close this issue
