### ISSUE TITLE
Two Way Audio with Hikvision doorbell ds-kb6003-wip ?

### ISSUE THREAD

**Issue by pickonedev** [AlexxIT/WebRTC#432]
Hi!

Anyone knows if the most recent version of this addon, works two way audio on Hivision DS-KB6003-WIP?

If yes, can you please share extra info in how to achieve this?

Thank you in advance!

**Comment by pergolafabio** [comment]
no, it doesnt work in Hikvsion intercom, they are based on two wau audio with isapi

**Comment by pergolafabio** [comment]
https://github.com/AlexxIT/go2rtc/commit/5846cbd9899383a07ff30b902e90bb0a3a9b566c
