### ISSUE TITLE
Zoom video stream (not via PTZ)

### ISSUE THREAD

**Issue by zelo66** [AlexxIT/WebRTC#438]
Hey,

Is there an option to add a camera zoom (not via PTZ) by using a gesture on the phone or by mouse scroll on the computer?
It would also be useful to have a button to restore the default view (not zoomed in).

My camera is quite far from the gate and in the app I normally use (QVR PRO) it is normally possible to do this and it is very useful.

The add-on works very well.
Great job, thank you for your work.
Regards.

**Comment by Gymnae** [comment]
+1

**Comment by dbuezas** [comment]
There's now an open PR for that: https://github.com/AlexxIT/WebRTC/pull/491
For the adventurous, you can copy the contents of that branch to your custom_components and use it already.
It adds:
* pinch to zoom
* one-finger drag to pan
* two-fingers drag to pan
* tap+drag for one finger zoom
* double tap to zoom in and out 
* and the same with the mouse too!

The controls are pretty much the same as google maps.

**Comment by dbuezas** [comment]
This issue can be closed now
