### ISSUE TITLE
WebRTC stuck after switching to beta image HA2023.3.0b2+ (docker)

### ISSUE THREAD

**Issue by S-Przybylski** [AlexxIT/WebRTC#441]
After moving the to HA betachannel, my dashboard, which worked since weeks, no longer shows Webrtc streams using the this custom card... on non of my devices. It indicates 'webrtc/offer: stream not found'. The logs do not show any error, either the Frigate go2rtc log (tracing enabled) and also the HA log (same enabled here for custom_card).

My first idea was to undo OS updates i made just before - without success; also tried to disable IPv6 - nop...
Then I deleted the integration (but leave it installed as a custom component in HACS) and installed the native WebRTC plugin: Then by surprise picture-elements start streaming Frigate cameras (go2rtc configured) using WebRTC (native integration). This do not worked before. Also the Frigate custom-card worked with minor changes (use HAnative) again. But indeed the usage of this custom card - I realy like two features of it (1. Feedback, which Stream type is used; 2. no network bandwith consumation if not in focus) - no longer work in that configuration....

Initial config:
Frigate 12b8 with go2rtc enabled - works like a charm (webrtc is running on several browsers) - Container on Intel PC / Ubuntu
HA 2023.3.0b3 on docker container (Synology NAS) with AlexxITWebRTC integration installed and configured (pointing to dedicated Frigate)

In general I prefer to stay using the native integration together with Frigate 12 and the Custom_card from this repo (if possible). Could this in future be an option (maybe to separate the custom_card)?

Has anyone got also problems using the current beta? Any thoughts how to deal with that differently?

**Comment by n0012** [comment]
Same issue for me which started today

**Comment by semack** [comment]
The same here

**Comment by S-Przybylski** [comment]
I moved to native plug in. Works well
