### ISSUE TITLE
WebRTC: ICE failed, add a TURN server and see about:webrtc for more details

### ISSUE THREAD

**Issue by olijouve** [AlexxIT/WebRTC#45]
Hi,

I've got that error while trying to start stream. I'm on my local network, using Firefox or Safari desktop.

On IOS companion app still on local network i sometimes got connected staus but no video is loading and after few secondes i lost connexion and got stucked in an new trying to start stream step.

Any idea ? Can ICE/TURN be disabled if usage is only on local network ?

**Comment by AlexxIT** [comment]
Have you read FAQ?

**Comment by olijouve** [comment]
Yes I did, but not sure to understand everythings. I've made forwarding ports, Bunny sample work like a charme.
Maybe my issue is on the docker part, i'm using HA Supervised distribution but i have no idea on how to allow more port forwarding on supervisor...

**Comment by olijouve** [comment]
I don't have that issue with https://github.com/olijouve/webrtc-streamer-card but i would prefer to use your integration.

**Comment by AlexxIT** [comment]
Bunny works in Firefox, Safari and iOS?

**Comment by olijouve** [comment]
I just restarted HA and now it worked on firefox, IOS...
I restart also earlier but maybe there where something wrong with google stun server.

I don't have sound, is it supposed to work also or only video at the moment ?

Great integration and card, many thanks !
