### ISSUE TITLE
Add camera time stamp base.

### ISSUE THREAD

**Issue by dobl1** [AlexxIT/WebRTC#451]
Hi,

It would be great to add the time of the displayed frame.
Useful in case of latency on the video or even if the image is frozen (on a scene with little movement you may not notice that something is wrong)

Thanks !

**Comment by AlexxIT** [comment]
You can do it with ffmpeg. But it will be very CPU heavy operation.
https://github.com/AlexxIT/go2rtc/issues/127

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.0
