### ISSUE TITLE
Preset Points on Reolink E1 Pro / E1 Zoom

### ISSUE THREAD

**Issue by criticallimit** [AlexxIT/WebRTC#453]
I have two Redolink E1 Pro and one E1 Zoom succesfully working in HA.
But Preset Points in one Cam is working fine with shortcuts, but in the other cams it´s not.

Is it possible that Reolink cams dont´t use  preset: '001' .... preset: '006' for all cams in the network?

But why is it working in one cam, in the others not. The E1 Pro´s are both exactly same Hard- and Firmware Versions.

Or is there something missing with onvif Protocoll not working?
How can I find out how the presets are named in the cams for the onvif_protocol? In Reolink app all is working fine.

Maybe someone has same fault or a way to get it working for all Reolink cams?

Thanx for help.

cheers 
Dirk

**Comment by AlexxIT** [comment]
Your question not related to this integration
