### ISSUE TITLE
Display shortcuts in full screen mode?

### ISSUE THREAD

**Issue by timothybuchanan** [AlexxIT/WebRTC#454]
I use this code to display shortcuts on my WebRTC cameras:

style: >-
  .shortcuts {left: 40px; top: 10px; right: unset; display: flex;
  flex-direction: line}
  .mode {display: none}

but they don't show if I click the card to display the camera full screen. Is there a way to make the shortcuts show on full screen, or could that be added? Thanks.

**Comment by AlexxIT** [comment]
You need to enable option `ui: true`
