### ISSUE TITLE
Camera ezviz c3w not working on Webrtc

### ISSUE THREAD

**Issue by muckob** [AlexxIT/WebRTC#455]
Hi, 

i have Ezviz c3w camera as Generic Camera (rtsp://admin:pass@192.168.#.#:554/h264_stream)) and it doesn't work in custom:webrtc-camera. 

Logs:
.../webrtc/video-rtc.js?v3.0.1:390:27 Uncaught NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="avc1.010101,mp4a.40.2"') is unsupported.

.../webrtc/video-rtc.js?v3.0.1:314:22 Uncaught TypeError: this.ondata is not a function

**Comment by AlexxIT** [comment]
Looks like latest Ezviz models has awful RTSP implementation. You can increase go2rtc log level for rtsp module to trace.

**Comment by muckob** [comment]
How do I do that?

**Comment by Isengo1989** [comment]
EZVIZ LC3 as well, it is a disgrace... Sadly I got lead into buying it by a comment that it does support ONVIF.

**Comment by AlexxIT** [comment]
Please reopen issue when you get more debug info
https://github.com/AlexxIT/go2rtc#module-log
