### ISSUE TITLE
"WebRTC server not available"

### ISSUE THREAD

**Issue by Shivy011** [AlexxIT/WebRTC#456]
Hi

I am getting the above error
The RTSP streams work fine in VLC on multiple computers. IT was also working fine on my raspberry pi, I have now swapped to an ubuntu based VM
They are hikvision cameras through an NVR

**Comment by Shivy011** [comment]
Also working through camera & stream component within HA

**Comment by AlexxIT** [comment]
Try to remove go2rtc binary from your Hass config folder and restart Hass

**Comment by Shivy011** [comment]
> Try to remove go2rtc binary from your Hass config folder and restart Hass

Thanks tried and stream is semi working . However I have to keep restarting gortc add on as the stream just stops loading on dashboards, any tips?

**Comment by jonasf21** [comment]
Had the same problem after i migrated from a rpi 4 to a intel nuc (w/proxmox). The go2rtc binary was for aarch64 (rpi) and thus did no longer work, causing the "webrtc server not available" message. I tried removing and reinstalling webrtc but it didnt help - i manually had to remove the go2rtc binary, restart HA and it apparently downloaded the correct binary.

@AlexxIT Maybe add some check at startup to see if the arch has changed to prevent this?

**Comment by AlexxIT** [comment]
Perhaps there was an error when downloading go2rtc binary. And you need to delete it manually, so that it can be downloaded again.

I'll think about some validation after download.

**Comment by luxmoel** [comment]
> Had the same problem after i migrated from a rpi 4 to a intel nuc (w/proxmox). The go2rtc binary was for aarch64 (rpi) and thus did no longer work, causing the "webrtc server not available" message. I tried removing and reinstalling webrtc but it didnt help - i manually had to remove the go2rtc binary, restart HA and it apparently downloaded the correct binary.
> 
> @AlexxIT Maybe add some check at startup to see if the arch has changed to prevent this?

I have exactly this problem => how can I remove the go2rtc binary? => for beginners please

**Comment by jonasf21** [comment]
Its in /config. Open HA in your browser and choose terminal. 
cd /config
rm go2rtc
Thats it.

**Comment by luxmoel** [comment]
> Its in /config. Open HA in your browser and choose terminal. cd /config rm go2rtc Thats it.

thanks a lot, it works. Thanks so much!!!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/releases/tag/v3.6.0
