### ISSUE TITLE
Closing card do not kill stream

### ISSUE THREAD

**Issue by luzik** [AlexxIT/WebRTC#458]
I have tablet on wall with HA companion app on it. When someone is near my doors, I am using browser_mod.popup to show custom:webrtc-camera card. After timeout popup disappear, but go2rtc keep showing, that stream is active and sending data. More popups over time giving more streams online, and eventually it crashing my companion app.
While I am not sure this issue is related to WebRTC, go2rtc or browser_mod.popup, problem is there.

**Comment by AlexxIT** [comment]
I think this problem related to `browser_mod`. Because `webrtc-camera` can handle: lovelace view switch, browser tab switch and browser minimize. You can check all this features without browser_mod.
