### ISSUE TITLE
How to organize the indentation of icons (shortcuts)

### ISSUE THREAD

**Issue by sashakozlov86** [AlexxIT/WebRTC#460]
Good afternoon  Thank you so much for developing such a useful integration!  I created a custom-card, added shortcuts, assigned icons to them, added a style command: style: '.shortcuts {left: 6px;  top: 15px;  right: 5px;  distance: 10px}' and I have very close icons (shown in the attached screenshot).  Can you please tell me how to set the indentation command between the shortcuts icons?  Thank you very much!
![Screenshot_2023-03-30-23-37-17-38_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/93244850/228960160-7d9e9e6a-608a-43e8-8b3a-380d03bdc79a.jpg)

**Comment by stplatt** [comment]
Use gap: in style section. Example below

```
style: >-
  .header {top: 6px; right: 5px} .mode {position: absolute; top: 0px; right:
  5px} .shortcuts {left: 6px: top: 6px; right: unset; display: flex;
  flex-direction: row; gap: 10px; opacity: 0.7; background: rgba(0, 0, 0, 0.25);
  border-radius: 5px}
```

**Comment by sashakozlov86** [comment]
Thank you, very much!
