### ISSUE TITLE
Mode on screen display 

### ISSUE THREAD

**Issue by direx1** [AlexxIT/WebRTC#461]
Is there not an option to disable the mode osd in top right corner as it overlaps my camera's time and date?

**Comment by AlexxIT** [comment]
Example right in the docs

**Comment by direx1** [comment]
Sorry but where?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC#custom-card

**Comment by direx1** [comment]
Hide Mode label, missed this reading through. Thanks
