### ISSUE TITLE
Is this needed if already using Frigate 0.12/bundled go2rtc?

### ISSUE THREAD

**Issue by Iceman248** [AlexxIT/WebRTC#468]
Looking at the v3 of this, had been on v2, it seems to suggest that this includes go2rtc and that it can be had in Frigate 0.12, which is how I have both Frigate/go2rtc, so I removed this integration from HA, but now I can't use WebRTC cards in HA. Am I misinterpreting this? What do I need to use WebRTC inside of HA?

**Comment by AlexxIT** [comment]
Custom WebRTC Card provided only by this integration.
go2rtc does not provide cards. It is server software for streaming video.

**Comment by Iceman248** [comment]
Thanks, understand it now.
