### ISSUE TITLE
Config option for stream to be paused by default

### ISSUE THREAD

**Issue by Haloooch** [AlexxIT/WebRTC#47]
Not an issue an enhancement request, sorry if this is the incorrect place to log it!

The frontend card is really good at last zero lag videos from my Unifi cameras. It would however be much more flexible if there was a config option to set the stream to be either playing or paused on page load. If that's even possible?

**Comment by AlexxIT** [comment]
Do you want to save traffic?

1. The camera can transmit, but the picture is paused
2. The camera will start transmitting data only when the user clicks

**Comment by johnvanl** [comment]
I would like join in this request. 
For me the reason is that I would like to have a more calm view when on the screen; I have 8 camera's and the general reason to go view the camera's is after an "alarm". In my point of view the user will look for the relevant camera and by clicking starts the live camera. 
I am not sure but sense that it will consume also less performance if it starts with 8 paused camera's in stead of 8 live camera's. And if this also saves traffic, that would be another welcome asset.  
Of course I am open for your advices. Thanks in advance!

**Comment by Haloooch** [comment]
AlexxIT, when you asked me that question I needed to stand back and think. Most of my cameras are Arlo, I use a custom component for them which by default shows the last snapshot rather than a live feed. You then need to press play to show the feed. This is what I have been use to and my request came from that familiarity.

When you asked me 'why' I needed to think was familiarity a good reason? It's not, but what is a good reason is what John has said. I have one page with 10 cameras on it, if they were all paying the page would have too much going on. I prefer just selecting the one feed I want to watch.

More importantly choice is good. Not suggesting pause is the default setting, rather the card has the flexibility to select pause if that's what you want.

Side note I'm moving my cameras over to Unifi, hense why I'm moving over to this card :)

**Comment by Haloooch** [comment]
AlexxIT, when you asked me that question I needed to stand back and think. Most of my cameras are Arlo, I use a custom component for them which by default shows the last snapshot rather than a live feed. You then need to press play to show the feed. This is what I have been use to and my request came from that familiarity.

When you asked me 'why' I needed to think was familiarity a good reason? It's not, but what is a good reason is what John has said. I have one page with 10 cameras on it, if they were all paying the page would have too much going on. I prefer just selecting the one feed I want to watch.

More importantly choice is good. Not suggesting pause is the default setting, rather the card has the flexibility to select pause if that's what you want.

Side note I'm moving my cameras over to Unifi, hense why I'm moving over to this card :)

**Comment by GaryOkie** [comment]
Yes!  This option is needed for all the reasons stated above, plus it can avoid the spinning circle inside multiple webrtc streams when bandwidth is limited.     "Click to play"  would be a great new feature.

```
paused:  true    #  start stream paused.  (default false)  
ui: true         #  custom video controls, default false, unless paused option is true
```

**Comment by juliandsp91** [comment]
Hi guys! is it any advance in this? would like to have the "pause" by default when open the dashboard. Thanks!

**Comment by AlexxIT** [comment]
In development...

**Comment by juliandsp91** [comment]
Nice! Thanks

**Comment by retepz** [comment]
Bump? 👀

**Comment by xiaolei0125** [comment]
Thank you for providing such a nice tool.  this feature is very useful,  Are there any updates?

**Comment by AlexxIT** [comment]
Done https://github.com/AlexxIT/WebRTC/releases/tag/v3.5.0
