### ISSUE TITLE
Disable autoplay rtsp stream custom:webrtc-camera

### ISSUE THREAD

**Issue by hugst** [AlexxIT/WebRTC#470]
Hey, probably dumb question from a newbie ...
I'm using card type: custom:webrtc-camera with an rtsp stream.
Perfectly working so far.
I would like to get the video paused by default on  the dashboard (or a still picture) 
It's always playing on the dashboard consuming ressources.
Is there any control to not display the video running on the dashboard ?
Thx

**Comment by AlexxIT** [comment]
#47
