### ISSUE TITLE
webRTC video/security camera prevents monitor sleep 

### ISSUE THREAD

**Issue by vajonam** [AlexxIT/WebRTC#474]
When I run a HA dashboard with security cameras, it prevents the monitor from sleeping because it detects a video is playing and send a dbus inhibit PowerSaveMode message on linux. 

```
method call time=1682343217.664731 sender=:1.84 -> destination=:1.46 serial=1517 path=/org/gnome/Mutter/DisplayConfig; interface=org.freedesktop.DBus.Properties; member=Set
   string "org.gnome.Mutter.DisplayConfig"
   string "PowerSaveMode"
   variant       int32 0
```

This is as designed on Chrome, to prevent sleeping when a video is playing. However just curious if there is / can be option to disable this and allow the monitor the sleep when HA is open and WebRTC is playing maybe in non full screen mode.

**Comment by AlexxIT** [comment]
I don't know how to get around that. There have already been users with this problem, but I can't find this issue.
