### ISSUE TITLE
Use existing streams in go2rtc

### ISSUE THREAD

**Issue by erunaheru** [AlexxIT/WebRTC#475]
I'm using the go2rtc in Frigate. Frigate creates a number of named streams, and my WebRTC cards are using these as sources. This results in go2rtc restreaming itself. Is there any way to use the existing named streams instead?

**Comment by AlexxIT** [comment]
Don't understand what you mean.

https://github.com/AlexxIT/WebRTC#custom-card

```
As a url you can use any protocol supported in go2rtc or specify the stream name from the go2rtc config.
```

**Comment by erunaheru** [comment]
Ah, I missed the "specify the stream name from the go2rtc config". An example of that use would definitely be nice, but this is mostly down to my own reading comprehension.
