### ISSUE TITLE
Feature request: Option to hide video controls and add "pointer-events: none;"

### ISSUE THREAD

**Issue by jack5mikemotown** [AlexxIT/WebRTC#476]
Hi, apologies if this is possible already. I'm not aware of any way to change card html and am not super familiar with css. I would love if these 2 features were available, they would make for a much nicer viewing experience. Thank you!

**Comment by MacLeod92** [comment]
Adding `style: 'video {pointer-events: none;}'` to your ha card config should get you to where you want to be.

**Comment by jack5mikemotown** [comment]
hi, thanks, that solves the second problem, is there any way to hide video controls?

**Comment by MacLeod92** [comment]
A few seconds after the initial load the controls should fade away and because of pointer events none won't come back. Is it crucial for your use case that you don't see the controls for those few seconds?

**Comment by AlexxIT** [comment]
```
style: '.ui {display: none}'
ui: true
``
