### ISSUE TITLE
How to update go2rtc that is bundled inside WebRTC?

### ISSUE THREAD

**Issue by andrew-lemon** [AlexxIT/WebRTC#481]
I installed WebRTC via the HACS integration in my Home Assistant RPi4. When I check the version, it shows v3.1.0 so this is the latest stable version. When I go to '''http://localhost:1984''' however it shows that I have go2rtc v1.2.0. I believe the current version of go2rtc is v1.4.0. How do I upgrade go2rtc to v1.4.0?

**Comment by AlexxIT** [comment]
Just use external go2rtc. Or download binary and put it in Hass config folded with exact name like old one.
