### ISSUE TITLE
Please tell me if there is an interface card with support for two-way audio ???

### ISSUE THREAD

**Issue by TokarevSergey** [AlexxIT/WebRTC#486]
Please tell me if there is an interface card with support for two-way audio ???

**Comment by AlexxIT** [comment]
I saw someone make one, but I don't have a link to it. Look it up on GitHub.

**Comment by pergolafabio** [comment]
@TokarevSergey  , have you found it?

**Comment by TokarevSergey** [comment]
> @TokarevSergey , вы нашли его?

No, I didn't.
 I am using web torrent links.

**Comment by pergolafabio** [comment]
Web torrent links?

**Comment by TokarevSergey** [comment]
> Ссылки на веб-торренты?

https://github.com/AlexxIT/go2rtc#module-webtorrent

**Comment by TokarevSergey** [comment]
> Ссылки на веб-торренты?


You can open the page in any browser with two-way audio.
