### ISSUE TITLE
Docker Wyze Bridge vs WebRTC Camera integration load order

### ISSUE THREAD

**Issue by pythonchris1** [AlexxIT/WebRTC#488]
When HA starts, it looks like it's loading the WebRTC Camera integration first, it reserves ports, and then Docker Wyze Bridge cannot start because it wants to use those reserved ports.

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/128749295/236996240-318b595f-e69b-423b-b7d3-a575b88d9c15.png">

<img width="787" alt="image" src="https://user-images.githubusercontent.com/128749295/236995217-fb6d06ad-0ce1-4e96-9af0-175220a7b92f.png">

If I then disable the WebRTC Camera integration, then start the Docker Wyze Bridge it starts fine. Then I re-enable WebRTC Camera and the camera feeds work fine.

Is there a way to have HA load Docker Wyze Bridge first and THEN load the WebRTC Camera integration so I don't have to do this shuffle every time I restart HA?

I'm running HA on a Linux Oracle VirtualBox on my tower, and my tower has an Intel network adapter.  I put my system into hibernation each night and when I wake up my system it shows a network error in the VirtualBox terminal so I have to restart the VM for the VMs network connectivity to start working again.  It's apparently a known issue with Intel NICs. So I'm dealing with the load order thing on a daily basis as I'm having to restart the HA VM daily.

**Comment by AlexxIT** [comment]
You can change 8554 port or even disable it if you don't need it. Read go2rtc docs.
This integration can works fine without RTSP server if you don't need FFmpeg source.

**Comment by pythonchris1** [comment]
I actually did need it. I changed the RTSP port defined in Docker Wyze Bridge to 8556 then updated the Generic Camera definition string for each camera to use the new port, just in case this ever comes up for anyone else.

<img width="793" alt="image" src="https://github.com/AlexxIT/WebRTC/assets/128749295/7cefc58d-6412-468b-9f81-8e9ad0df36bb">

<img width="301" alt="image" src="https://github.com/AlexxIT/WebRTC/assets/128749295/7693f0f3-3ceb-46e9-8a9f-f82d9621a48e">

<img width="434" alt="image" src="https://github.com/AlexxIT/WebRTC/assets/128749295/72804161-af75-4db7-9ce4-fbef9c44e36a">

**Comment by AlexxIT** [comment]
I was talking about 8554 port from go2rtc
