### ISSUE TITLE
enhancement request: unifi camera - certificate doesn't contain IP SAN

### ISSUE THREAD

**Issue by fribse** [AlexxIT/WebRTC#493]
I have a unifi protect system set up. I've added a lets encrypt certificate to the box, but of course that doesn't contain an IP address as that is not doable by LE.
So when webrtc goes to fetch the stream it shows:
mse: source 0 error: x509: cannot validate certificate for a.b.c.d because it doesn't contain any IP SANs.

I can go and activate the unencrypted stream, but could I somehow disable the certificate verification?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc#source-rtsp
