### ISSUE TITLE
ERROR: Passing coroutines is forbidden, use tasks explicitly.

### ISSUE THREAD

**Issue by hoanglongutc** [AlexxIT/WebRTC#498]
After upgrading the version Home Assistant 2023.6.0 I got the following error: "ERROR: Passing coroutines is forbidden, use tasks explicitly."
![image](https://github.com/AlexxIT/WebRTC/assets/35026043/d71ef985-e68e-4276-8556-3077e1ad2282)
/config/custom_components/webrtc/__init__.py:214: RuntimeWarning: coroutine '_websocket_forward' was never awaited await ws_server.send_json({"error": str(e)})

**Comment by brainmaitai** [comment]
I can confirm this is happening with me on 2023.6.0 and 2023.6.1 of Home Assistant.
The error is present in v2.3.1 in as well as in v3.1.0.

**Comment by kijuz** [comment]
Also for me, after upgrade to the latest version of home assistent. 
i guess the problem is the python version upgrade.
hope in a fix

**Comment by 1966pjrl** [comment]
Same problem...  Using webrtc-camera
ERROR: Passing coroutines is forbidden, use tasks explicitly

**Comment by Petramuzammel88** [comment]
I can confirm as im also facing the issue.

**Comment by hoanglongutc** [comment]
I installed go2rtc add-on and everything worked again
