### ISSUE TITLE
No Mac version 

### ISSUE THREAD

**Issue by niceboygithub** [AlexxIT/WebRTC#5]
Not work on Mac cause there is no RTSP2webrtc for mac

**Comment by smokecustom** [comment]
> Not work on Mac cause there is no RTSP2webrtc for mac

Either you do use Mac Mini, or what's this for? Anyway, just use Raspberry, it easier.

**Comment by niceboygithub** [comment]
My HA is running on Mac Mini

there is no any error logs related WebRTC.
It just pop up ‘Aborted’.
After checked the code, I think it was aborted cause no RTSP2WebRTC.
![2369C34E-6221-4F7E-A3F9-CA3F829858C7](https://user-images.githubusercontent.com/74046071/114475715-5647b980-9c2b-11eb-97dc-60460bd87a31.png)

**Comment by niceboygithub** [comment]
Thanks for update
Tested static binary for MacOS.

https://1drv.ms/u/s!AitCBpqMIxNsgfM6IMimcZ3bJi9vkQ?e=FpsffQ

**Comment by AlexxIT** [comment]
It should install and run automatically

**Comment by niceboygithub** [comment]
Yes.
Thanks for support. Let’s close this issue.
