### ISSUE TITLE
Sound chopped/crackled on Tapo C200

### ISSUE THREAD

**Issue by dsimop** [AlexxIT/WebRTC#500]
Home Assistant 2023.6.1 on RPi 4B 8GB.

The WebRTC 2.x version was working like a charm.
Recently, I updated to the latest WebRTC 3.x version, as the older one was no longer compatible with the latest HAOS version. I am using the add-on (the simplest installation method), which includes the go2rtc server.

The video works as expected, but unfortunately the sound is now crackled - meaning you can hear it but not understanding what is said.  I am not sure what changed since the version 2.x.

Here are the respective camera audio codecs of the sub-stream from VLC:
<img width="487" alt="Screenshot 2023-06-12 at 11 05 03" src="https://github.com/AlexxIT/WebRTC/assets/8091329/f68ea01f-7e1d-4e9a-bbc7-46e6988a2c9c">

**Comment by sqrg** [comment]
Having the same issue with the same camera. Did you find any fix?

**Comment by dsimop** [comment]
Unfortunately not. Still waiting for a response, a minor info is that the hardware of my camera is V2.

**Comment by sqrg** [comment]
Do you know which go2rtc server are you using? I have 1.2.0 installed on mine, so I'm going to try updating that to 1.5.0 https://github.com/AlexxIT/go2rtc/releases to see if it helps

**Comment by dsimop** [comment]
Same here, it is the 1.2.0. Please give a feedback if you test it with the newest go2rtc version.

**Comment by sqrg** [comment]
Does not seems to work on latest release, same crackling audio

**Comment by dsimop** [comment]
Thanks for the feedback. Pretty weird, as it used to work. Also, the Tapo C200 is a widely-used model. Additionally, as said rolling back to WebRTC 2.x is not possible since the latest HA version.

**Comment by sqrg** [comment]
Yes, go2rtc seems to be the problem (since that was what change between 2.x and 3.x)

I don't know much about this stuff, but I think https://github.com/bluenviron/mediamtx could be a solution for us, because seems to have a proper implementation for the audio codec. I think we can create an RTSP server with that, and then use the RTSPtoWebRTC integration from HA. I'll try to investigate further and give feedback over the weekend

**Comment by AlexxIT** [comment]
You can try your luck with addons RTSPtoXXX
https://www.home-assistant.io/integrations/rtsp_to_webrtc/

**Comment by dsimop** [comment]
> You can try your luck with addons RTSPtoXXX
> https://www.home-assistant.io/integrations/rtsp_to_webrtc/

Probably this won't do much, since a WebRTC Server is needed anyway and we would probably use the same go2rtc server. The aforementioned add-on from HA is only for displaying/providing the stream from the server, as far as I know - which is similar to the implementation of the current WebRTC.

**Comment by AlexxIT** [comment]
When I write "addon" and "integration", I understand the difference

**Comment by sqrg** [comment]
> When I write "addon" and "integration", I understand the difference

Really helpful and insightful comment. Thanks for nothing

**Comment by AlexxIT** [comment]
If you follow the link. You can find RTSPtoWeb or RTSPtoWebRTC addons there.
And RTSPtoWebRTC integration can be connected to any of this addons. Also it can be connected to go2rtc.
WebRTC integration 2.0 used RTSPtoWebRTC as server before go2rtc.

**Comment by sqrg** [comment]
Sorry, I'm a bit new to all this. To use an add-on I have to install HA operating system, right? I can't do it from Docker

**Comment by dsimop** [comment]
I assume you can run the Docker image standalone and the connect to it by giving the respective IP address and the port. The downside with that though is that it does not work when using HA with external access (only internally)

**Comment by sqrg** [comment]
I reinstalled HA using Proxmox so I can use addons. Everything is working fine now, thanks :)

**Comment by dsimop** [comment]
So, after a lot of experimentation I found out that the sound problem **disappears** when replacing the `rtsp` url with the `tapo` url as described in the [_go2rtc_ repo](https://github.com/AlexxIT/go2rtc#source-tapo). Personally I tested it with the following format:
`camera: tapo://admin:MD5-PASSWORD-HASH@192.168.1.123`

However on iPhone devices, the video stream with the `tapo` url config cannot be played (black screen), while the `rtsp` one is displayed normally. I have also hardcoded in both cases the line `mode: webrtc`, without any luck for the _tapo_ config video stream. 

Probably it would be wise to open a discrete ticket in the `go2rtc` repo for the iPhone devices that cannot play the video stream which is configured using the `tapo` url instead of the camera's `rtsp` url.

**Comment by sqrg** [comment]
Nice find, will try later. Do you experience some kind of latency or delay using go2rtc?

**Comment by dsimop** [comment]
Not at all, it is working as expected.

**Comment by dsimop** [comment]
This ticket is closed after the last update.
