### ISSUE TITLE
WebRTC stopped working after upgrade to Home Assistant 2023.6

### ISSUE THREAD

**Issue by stalakerob** [AlexxIT/WebRTC#503]
Since upgrading to HA 2023.6 my WebRTC camera streams stopped working and I get the following errors:
`Logger: frontend.js.latest.202306080

Source: components/system_log/__init__.py:257

First occurred: 17:31:29 (10478 occurrences)
Last logged: 17:35:47
http://192.168.1.200:8123/webrtc/video-rtc.js?v3.0.1:158:26 Uncaught TypeError: Cannot read properties of undefined (reading 'catch')
http://192.168.1.200:8123/webrtc/video-rtc.js?v3.0.1:314:22 Uncaught TypeError: this.ondata is not a function`

**Comment by AlexxIT** [comment]
#501
