### ISSUE TITLE
Tap action to open fullscreen

### ISSUE THREAD

**Issue by tomas-cs** [AlexxIT/WebRTC#504]
Is it possible to add something like normal tap_action to this card? Ideally, we would be able to define what happens when user clicks on the card - play/pause, open full screen, navigate to page... I use this card as tiny preview of door camera, and having it play/pause when I click on it doesn't make much sense, opening full screen (or at least navigating to cam dashboard) would be much better. Thank you

**Comment by AlexxIT** [comment]
#251
