### ISSUE TITLE
Amplifier sound

### ISSUE THREAD

**Issue by TokarevSergey** [AlexxIT/WebRTC#508]
Tell me if it's possible to add a sound booster to the card so that the sound is a little louder. Thank you.

**Comment by AlexxIT** [comment]
Here an example
https://github.com/AlexxIT/go2rtc/issues/447

**Comment by TokarevSergey** [comment]
> Вот пример [AlexxIT/go2rtc#447](https://github.com/AlexxIT/go2rtc/issues/447)


Thank you
