### ISSUE TITLE
Fix stream playing stops when exit from fullscreen mode on iOS

### ISSUE THREAD

**Issue by Spirituss** [AlexxIT/WebRTC#51]
When you open full screen mode then exit from it, you see just still picture but not streaming video. In order to start stream again you "play" button should be pressed.

**Comment by AlexxIT** [comment]
Do you use `ui: true`?

**Comment by weitheng** [comment]
Having the same problem as well with `ui: false`.

When I include `ui: true`, I can't see the fullscreen icon which is supposed to be on the lower left corner of the stream. 

Running on iOS HA App, OS: iOS 14.6

**Comment by AlexxIT** [comment]
iOS doesn't support fullscreen with custom UI

**Comment by weitheng** [comment]
I see, then the only problem is the stream will pause when exiting from full-screen

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/releases/tag/v3.5.0
