### ISSUE TITLE
Stream starts paused after UI reload, requires PLAY button to be pressed

### ISSUE THREAD

**Issue by psmiejabh42** [AlexxIT/WebRTC#513]
In some circumstances (not sure what triggers this behaviour) the dashboard will refresh, forcing the stream to reload.
This can also be triggered by changing windows or tabs in the browser and returning to the tab with the dashboard.

Observed behaviour:
This will sometimes cause the stream to load up paused, requiring the user to click a play button (just next to the mute/unmute button) that would not be present otherwise. This requires monitoring playback state, which is extremely inconvenient in for example baby monitoring.

Expected behaviour:
In case of a dashboard refresh, the stream restarts in playback.

**Comment by AlexxIT** [comment]
`backgroud` option, read in the readme

**Comment by psmiejabh42** [comment]
In fact I did use `backgroud`. This was the issue, as the option is `background`, with an `n`.

Confirmed as solved ;) Thanks for the patience!
