### ISSUE TITLE
WebRTC Stream as Source

### ISSUE THREAD

**Issue by gtxaspec** [AlexxIT/WebRTC#515]
does WebRTC card or go2rtc support webrtc as source?  I could not find anything in the docs.  

Currently when I add a webrtc http camera url, , error:

`webrtc/offer: unknown format 3c21444f43545950`

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc#source-webrtc

**Comment by AlexxIT** [comment]
What source you tried to use here?

**Comment by gtxaspec** [comment]
@AlexxIT sent PM on telegram.
