### ISSUE TITLE
How to place PTZ in a different place?

### ISSUE THREAD

**Issue by mguilherme** [AlexxIT/WebRTC#516]
Is there a way to change the PTZ controls placement?

Unfortunately the Picture-in-Picture mode control is in the same place of the zoom controls, it would be nice if I could move the zoom to a different place

<img width="504" alt="SCR-20230701-ropq" src="https://github.com/AlexxIT/WebRTC/assets/699510/ba5d8cb5-fe06-48b4-8f28-977637e4d815">

**Comment by AlexxIT** [comment]
```
.ptz {right: unset; left: 10px}
```
