### ISSUE TITLE
Feature request: Save snapshot button

### ISSUE THREAD

**Issue by dbuezas** [AlexxIT/WebRTC#524]
Parts of this snippet may be handy
https://gist.github.com/lukejacksonn/a5dd4bb03dc8dad3d489379fd5d26339

**Comment by AlexxIT** [comment]
VideoRTC has similar code
https://github.com/AlexxIT/WebRTC/blob/359e3ecea9ddbda100c248b812b7f16a05e3732d/custom_components/webrtc/www/video-rtc.js#L581

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/releases/tag/v3.3.0
