### ISSUE TITLE
Any solution for iPhone.

### ISSUE THREAD

**Issue by Jaguaza** [AlexxIT/WebRTC#528]
First of all, thank you @AlexxIT for your work. It works perfectly on my PC.

And I can only view it locally In iPhone.

But on the iPhone I can't find a way to do it, or hls, or anything. Any solution in sight.

**Comment by AlexxIT** [comment]
I don't understand the question

**Comment by Jaguaza** [comment]
@AlexxIT I can see the cameras locally, but I can't see them outdoors with 4G.

My installation is Ha in Proxmox.

**Comment by AlexxIT** [comment]
#378

**Comment by Jaguaza** [comment]
Thank you, I will consult both to see if I can get anything.

Thanks for your time.

**Comment by AlexxIT** [comment]
Latest integration version should support HLS technology. It's awful, but should works on iPhones.

**Comment by Jaguaza** [comment]
> Latest integration version should support HLS technology. It's awful, but should works on iPhones.

I added to my card:

mode: hls

And I got no positive result. It didn't even play locally.

No mode: played in local RTC.

**Comment by AlexxIT** [comment]
It doesn't work on bad cameras.

**Comment by Jaguaza** [comment]
> It doesn't work on bad cameras.

VStarcam. I'm sure that's it.

**Comment by AlexxIT** [comment]
You can try to setup ffmpeg source for your camera in the go2rtc config.
