### ISSUE TITLE
custom elemement doesn't exist

### ISSUE THREAD

**Issue by bigsem89** [AlexxIT/WebRTC#531]
![image](https://github.com/AlexxIT/WebRTC/assets/63959082/2be40056-0263-424d-bfa4-170beebd4151)
![image](https://github.com/AlexxIT/WebRTC/assets/63959082/02ddc5d3-c378-41b6-9107-f8e8562c45ed)

HA version - 2023.7.2

i have tried to install and reinstall integration.

**Comment by ArcziHA** [comment]
+1
The same.

**Comment by androdlang** [comment]
The same

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/issues/260#issuecomment-1643524820
