### ISSUE TITLE
Using go2rtc add-on with WebRTC card

### ISSUE THREAD

**Issue by oNaiPs** [AlexxIT/WebRTC#533]
I have tried to use the go2rtc add-on with the WebRTC card with mixed success. It seems that the integrated go2rtc and the add-on go2rtc will race to listen to the port, and whomever starts first, will be the one working.

Is there a way to disable the integrated go2rtc so that the add-on will always start successfully? Would be nice to add this to the README as well.

Thanks

**Comment by AlexxIT** [comment]
You can only customize the go2rtc URL when configuring the integration. Delete it and add again.

**Comment by oNaiPs** [comment]
Thank you it works!
