### ISSUE TITLE
How to crop camera feed by default without doing manually

### ISSUE THREAD

**Issue by sewershagger** [AlexxIT/WebRTC#538]
Is there a way to have the camera feed cropped by default within the webrtc card?

I have a camera feed and each time I view it, I need to zoom in manually to focus an enlarge a specific part of the image. 

I'm talking about cropping and zooming in via the webrtc lovelace card, not via the camera settings itself.

I can do it manually with the card which is great, but I would be better if I could set the parameters for the crop so it can stay cropped by default.

**Comment by xuniversus** [comment]
Did you find a solution? @sewershagger
