### ISSUE TITLE
FR: Support adding/configuring multiple go2rtc server(URL)

### ISSUE THREAD

**Issue by xiaolei0125** [AlexxIT/WebRTC#542]
* I have a few IP cameras in various locations (my parents' house, my home, and the studio). 

* I'm hoping to run multiple go2rtc server in both of these places, and accessing them directly from Home Assistant Fronted would have better network performance.

* It is hoped that this WebRTC component can support configuring multiple servers, or can run multiple WebRTC components in Home Assistant.  Thanks!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/releases/tag/v3.3.0
