### ISSUE TITLE
FR:  webrtc-camera card directly connect to go2rtc server in MSE mode, no HA websocket relay

### ISSUE THREAD

**Issue by xiaolei0125** [AlexxIT/WebRTC#543]
* My home assistant and go2rtc server are running in different places.  In MSE mode,  I found that webrtc-camera card（in HA front-end） is connected to go2rtc server through the home assistant's websocket, which causes a network delay and high CPU usage for home assistant server.
  
* In MSE mode,  Can webrtc-camera card in HA front-end directly connect to go2rtc server?  Thanks!

**Comment by AlexxIT** [comment]
No. Use iframe and go2rtc WebUI.
