### ISSUE TITLE
How to run custom go2rtc

### ISSUE THREAD

**Issue by dbuezas** [AlexxIT/WebRTC#546]
What is the easiest way to run a custom go2rtc inside home assistant?

I built it locally using `env GOOS=linux GOARCH=amd64 go build main.go` and then copied the result to `~/config/go2rtc-1.6.0` as [this](https://github.com/AlexxIT/WebRTC/blob/359e3ecea9ddbda100c248b812b7f16a05e3732d/custom_components/webrtc/utils.py#L66) part of the code suggests. Then I restarted HomeAssistant with the add on removed.

I expected the WebRTC integration to run that binary but it didn't, what could I be doing wrong?

**Comment by dbuezas** [comment]
I removed it and restarted. I was able to run my custom go2rtc manually from ssh, so the binary is fine and the ports available

**Comment by AlexxIT** [comment]
Is problem still relevant?

**Comment by dbuezas** [comment]
I never managed to replace the executable but it looks like no one needed to do this, and it can be worked around by running it manually via ssh, so not important
