### ISSUE TITLE
TP lin tl-ipc45aw plus cannot achieve bidirectional voice and bridge homekit

### ISSUE THREAD

**Issue by love768952693** [AlexxIT/WebRTC#547]
Thank you for the tool provided by the developer. I have connected the tp lin tl-ipc45aw plus.

Now there are two questions

1. Is it impossible for a local area network to achieve bidirectional communication? If bidirectional communication can be achieved, can the device be bridged into the homekit and can be used to make out calls through Apple Home without SSL.

2. Since the device has not created an entity, how can it be bridged into a homekit?

**Comment by AlexxIT** [comment]
Two way audio supported only for some Tapo cameras.
Use another integrations for create entities.
