### ISSUE TITLE
How to dashcast a rtsp camera to a chromecast that is musted

### ISSUE THREAD

**Issue by jemershaw** [AlexxIT/WebRTC#555]
When trying to run the service in hass the dashcast service doesn't provide the ability to unmute the stream. Is it possible to add the ability to unmute via the service?

I'm willing to do this myself but I was guessing this setting would need to be passed down to the generated link that it sends to the chromecast device?

**Comment by jemershaw** [comment]
Hmm it seems like it is [here](https://github.com/AlexxIT/WebRTC/blob/master/custom_components/webrtc/www/video-rtc.js#L161) that is causing the problem. I don't think there is an easy way to do it

**Comment by AlexxIT** [comment]
You right. This is not possible.
