### ISSUE TITLE
No image in external connexion (Nabu Casa)

### ISSUE THREAD

**Issue by herveaurel** [AlexxIT/WebRTC#556]
Good morning,
When I am connected with Nabu Casa (external link), there is no image. But locally I have no problem.
I see "HLS" at the top right.
Camera Sonoff Slim
```
Logger: frontend.js.latest.202308021
Source: components/system_log/__init__.py:270 
First occurred: 14:17:50 (1 occurrences) 
Last logged: 14:17:50

https://0dxe4xszmztwdf5c93uik2ggn97whwm6.ui.nabu.casa/webrtc/video-rtc.js?v=1.6.2:321:16 TypeError: null is not an object (evaluating 'this.ws.addEventListener')
```
![IMG_E7970D464299-1](https://github.com/AlexxIT/WebRTC/assets/64784541/2b9861dc-8cc3-4e1a-9dae-0f682eeb479c)

**Comment by AlexxIT** [comment]
What you see in the corner when you at home? Try to set `mode: hls` and check if it works when you at home.

**Comment by herveaurel** [comment]
> What you see in the corner when you at home?
> Try to set `mode: hls` and check if it works when you at home.
> Whats your OS version?
> Is this app companion or browser?

I see "RTC" at home, image perfect. 
i use Safari (MacOS), and app HA for iOS
;) 
How to set this HLS mode?

THANKS !

<img width="171" alt="image" src="https://github.com/AlexxIT/WebRTC/assets/64784541/a401e707-be6a-422c-824a-8b3b84f2568a">

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC#custom-card

**Comment by herveaurel** [comment]
> https://github.com/AlexxIT/WebRTC#custom-card

In external connection, mse mode and hls mode do not work either. I have a black screen.

**Comment by AlexxIT** [comment]
MSE mode shouldn't work for iPhones
What about HLS mode locally?

**Comment by herveaurel** [comment]
> MSE mode shouldn't work for iPhones.
> What about HLS mode locally? (lower case in card settings).
> And what's your OS version on the phone?

On my iPhone 13 everything is up to date, iOS, HA app, webrtc...
HLS mode locally does not work.
Locally I have no problem, and externally the HLS mode works very rarely, often a black screen.
Sorry for my very bad English.

**Comment by pridi** [comment]
The same issue for me. Writing here to be updated.
