### ISSUE TITLE
Feature request: full screen on iOS (mobile?)

### ISSUE THREAD

**Issue by g1za** [AlexxIT/WebRTC#558]
Hello,
It would be nice to have the possibility to go full screen on iOS (maybe on Android as well?) likewise we can on desktops.
But the full screen icon is not available (only the "take snapshot" is).
I checked and this is not currently implemented both on Safari for mobile neither on the HA mobile app.
Cheers!

----------------
I did my research among open/closed tickets as I thought somebody could have already asked for it, as quite obvious... but I didn't find anything. Sorry if I missed it.

**Comment by AlexxIT** [comment]
Apple devices has some problems with this JS AIP

**Comment by g1za** [comment]
Closing this as after upgrading to v 3.5.0 and iOS 17 the feature is supported (opening a new bug as it goes full screen but in landscape mode it's black - feel free to reply in the same way ;) )
