### ISSUE TITLE
New models supported

### ISSUE THREAD

**Issue by roleoroleo** [AlexxIT/WebRTC#56]
I can confirm that this component works with the following cams:
- Yi with hack https://github.com/roleoroleo/yi-hack-Allwinner
- Yi with hack https://github.com/roleoroleo/yi-hack-Allwinner-v2
- Sonoff GK-200MP2B with or without hack https://github.com/roleoroleo/sonoff-hack

All models with alaw/ulaw audio.

Thanks for your work.

**Comment by stripeyhorse** [comment]
Ive test this with Unifi G3 Flex and G3 Bullet and Dome.

**Comment by Ailme** [comment]
Reolink E1
MISECU from https://aliexpress.ru/item/32950759885.html?spm=a2g0s.9042311.0.0.264d33ed1xk5Wl&_ga=2.47597605.364037802.1621967416-919761677.1598814968

Techage from https://aliexpress.ru/item/4000601510379.html?spm=a2g0s.9042311.0.0.264d33ed1xk5Wl&_ga=2.47597605.364037802.1621967416-919761677.1598814968

url: 'rtsp://192.168.1.10/user=admin&password=&channel=1&stream=0.sdp?'

**Comment by AlexxIT** [comment]
Thanks!
