### ISSUE TITLE
iPhone companion app with no streaming

### ISSUE THREAD

**Issue by pridi** [AlexxIT/WebRTC#569]
Before writing I've searched everywhere; there are similar conditions but actually not really what I'm experiencing.
Premise: 
- Companion app: version 2023.4
- go2rtc: version 1.6.2 

Conditions:
- Safari on macOS: Working "perfectly" (with MSE) inside and outside internal LAN.
- Chrome on macOS: Working "perfectly" (with MSE)  inside and outside internal LAN.
- iPhone companion app: 
-- when I'm inside the internal LAN: everything works smoothly, in RTC MODE 
![IMG_89AF5348CB71-1](https://github.com/AlexxIT/WebRTC/assets/36031754/721056d3-5028-4da4-a42c-240dce6e8376)
-- when I'm outside, the card automatically tries to use HLS but **NO streaming** at all. Even forcing all the other modes.
![IMG_FC9C3D4782C8-1](https://github.com/AlexxIT/WebRTC/assets/36031754/36489e8c-eb2d-4bde-84eb-9334f73739ae)

What am I missing? Thank you!

**Comment by pridi** [comment]
Another info: if I use the companion app (iOS) but connected with a WiFi **OUTSIDE** my home (my company WiFi for ex.), everything is working (with HLS)...really strange

**Comment by Isuru-rana** [comment]
Have you added STUN server address to RTSPtoWebRTC integration? 
![Screenshot 2023-09-19 143314](https://github.com/AlexxIT/WebRTC/assets/68464572/fbee33f0-4f8b-48aa-bd0c-2174fd187227)

**Comment by AlexxIT** [comment]
You missing: 
1. https://github.com/AlexxIT/go2rtc#codecs-madness
2. https://github.com/AlexxIT/WebRTC/issues/378
