### ISSUE TITLE
Custom element doesn't exist: webrtc-camera.

### ISSUE THREAD

**Issue by vit-um** [AlexxIT/WebRTC#57]
Hi Alexx!
Why custom element doesn't exist: webrtc-camera?
Please see picture for details.
![image](https://user-images.githubusercontent.com/74271908/117552262-e9211b80-b052-11eb-8a18-f59d70594d0b.png)

**Comment by AlexxIT** [comment]
It happens when you didn't setup integration

**Comment by vit-um** [comment]
Thank you. That helped.

**Comment by NVader2000** [comment]
When browsing in Edge (Chromium) this works fine. However, on my Android tablet (Android 10) running the Home Assistant app, I get the same error. Please advise.

**Comment by Mechotronic** [comment]
I just bumped against this even after installing the integration. Make sure you flush your browser cache. ctrl-f5 in Firefox. It worked after that.
