### ISSUE TITLE
Feature request: add support for custom label

### ISSUE THREAD

**Issue by amaximus** [AlexxIT/WebRTC#570]
Thanks for this awesome integration.

It would be nice to have support for a CSS stylable custom label that supports Jinja templating.

Use case: I have sensors for each of my cameras on their mode in my chosen NVR (Shinobi), something like sensor.tapo_street_mode whose state is `watching` or `recording`. I'd like to display this information on the card.

I tried to use the title for this with `title: "{{ states['sensor.tapo_street_mode'].state }}"` but title accepts only a fixed string.

**Comment by AlexxIT** [comment]
Jinja can be calculated only on server side

**Comment by amaximus** [comment]
Thanks, you're right.
