### ISSUE TITLE
Support for new iOS Safari 17 ManagedMediaSource for MSE support

### ISSUE THREAD

**Issue by duro** [AlexxIT/WebRTC#573]
As detailed [here](https://bitmovin.com/managed-media-source/#migration-from-mse-to-mms-ed4921d7-725c-4010-b3d0-d32af2f44964), iOS Safari 17, which was released with the new iOS 17, now has support for an MSE compatible API called `ManagedMediaSource`. That article I linked to details that it is backwards compatible with the MediaSource API, but also has some additional new features.

It appears the feature may still be behind a feature flag in Safari (see screen below), but I would love to see us get support for it.

According to the article above, it should be a minimal code change, and I may even be able to submit a PR myself, I will just have to come up to speed on how to setup the dev and test environments for this repo.

**Comment by duro** [comment]
https://github.com/AlexxIT/WebRTC/assets/17632/83811d05-566d-48bf-a87e-46f6a1812209

**Comment by AlexxIT** [comment]
Added to latest master version
https://github.com/AlexxIT/go2rtc/commit/037970a4ea10a1f78cc7a931a154385bb150dd0f

**Comment by AlexxIT** [comment]
Looks like this is not supported before iOS 17.1
https://github.com/w3c/media-source/issues/320#issuecomment-1752703789

**Comment by AlexxIT** [comment]
Supported https://github.com/AlexxIT/WebRTC/releases/tag/v3.5.0
