### ISSUE TITLE
Name in card does nothing.

### ISSUE THREAD

**Issue by jimz011** [AlexxIT/WebRTC#574]
When adding multiple streams to a card you can configure the mode and name. The name however does nothing.
As it currently stands the name is pointless as nothing changes when changing the name.

The mode button however does work fine and changes the stream (though I'd wish it would show the name instead of the streaming protocol).

**Comment by AlexxIT** [comment]
You need to use `ui: true`

**Comment by jimz011** [comment]
My apologies, that wasn't really clear to me in the UI. Thanks this worked out great (though I can't scroll through video anymore, but honestly this is better imho).

Thanks
