### ISSUE TITLE
Feature request: microphone manual control (enable/disable) in custom card

### ISSUE THREAD

**Issue by blackie333** [AlexxIT/WebRTC#584]
Hello, 
I have 3 different cameras all of which support 2-way audio on 1 HA dashboard.
If I enable microphone in webrtc-camera card configuration (media section) it's always enabled so the other side can always hear me (on all cameras). This is usually not necessary/required and I prefer manual control of my microphone output for each camera.

Some onscreen button to quickly toggle enable/disable microphone output in 'custom:webrtc-camera' card would be perfect.
Control source could be a HA entity (template switch, button, helper,...) or 'custom:webrtc-camera' GUI element.
Thanks a lot for considering such a feature for the future.

**Comment by AlexxIT** [comment]
Just use the docs example. It has toggle.

**Comment by blackie333** [comment]
I'm sorry but not sure which toggle you mean, can only see a button for muting cameras mic.
But in 2-way audio mode I want to mute my PC's microphone signal to selected(multiple) cameras speakers.
Now the speakers on all 3 cameras play my voice simultaneously when I want to speak to only 1 camera.

**Comment by Suxsem** [comment]
@AlexxIT i think you mean using two streams, one with mic and one without. I agree with @blackie333, a microphone toggle would be much better in my opinion

**Comment by AlexxIT** [comment]
Current solution can be mic toggle. If you want icons - just use emoji

**Comment by rodolfomachado** [comment]
> Current solution can be mic toggle. If you want icons - just use emoji.

Mic toggle would be two streams?
And how can I choose which icon for each streams?

Tks in advance
