### ISSUE TITLE
{FEATURE} openwakeword support / wyoming protocol

### ISSUE THREAD

**Issue by TRusselo** [AlexxIT/WebRTC#592]
using 2 way audio, please add support for Home Assistant new plugin OpenWakeWord for the Wyoming Protocol.
This would allow cameras with mics to listen for WakeWords and commands, and cameras with speakers to play back the voice assistant.

When enabled on Esp32 and other devices, you get an on/off toggle to enable WakeWord Detection on compatible devices.
Of course you would only want this enabled on indoor cameras normally, but maybe enabled on demand for outdoor camera when working in the driveway....  dont want people talking to your assistant from outside when not home.

**Comment by AlexxIT** [comment]
This is not related to this integration
