### ISSUE TITLE
H265 CTRONICS IPCAM HOME ASSISTANT NO IMAGE 3.5.0

### ISSUE THREAD

**Issue by Cryinman82** [AlexxIT/WebRTC#593]
On HAOS i can't have any image on my ctronics
Here is my card webrtc
```
type: custom:webrtc-camera
url: rtsp://user:password@IP:554/11
title: PORTAL
muted: true
ui: true
mode: webrtc,mse,mp4,mjpeg
intersection: 0.75
```
I have no errors on logs.
On the web onvif camera interface i have the log telling IP HAOS is connected.

When i change H265 for my cam to H264, it work, but my bandwidth is bad to stay on H264. (Wifi).

Is there something to do ?
on my configuration.yaml i put the log webrtc on debug and nothing to show.

I tried mode: one by one and only webrtc and mse connect without error, i tried hls and error occured with H265 => PCMA

What's wrong for me ?

Ty for help !

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc#codecs-madness

**Comment by Cryinman82** [comment]
Ok, it mean "It's all about patents and money, you can't do anything about it." ?
the way to make it work is 
"Now you have stream with two sources - RTSP and FFmpeg:

streams:
  dahua:
    - rtsp://admin:password@192.168.1.123/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    - ffmpeg:rtsp://admin:password@192.168.1.123/cam/realmonitor?channel=1&subtype=0#audio=opus
go2rtc automatically match codecs for you browser and all your stream sources. This called multi-source 2-way codecs negotiation. And this is one of the main features of this app." ?
