### ISSUE TITLE
Stream doesn't load on iOS devices (Loading...)

### ISSUE THREAD

**Issue by g1za** [AlexxIT/WebRTC#594]
Hello,
starting with version 3.4.0 the stream is not loading anymore on iOS devices.
I tested both HA companion app (latest version) and Safari (iOS 17.0) but it just says "Loading..." on black stream.
I tried on Firefox desktop and it works properly (PIP, full screen, ...  as well).

In HA log I see this (looks related), which seems to be logged only when I access the dashboard containing the stream card from iPhone:
`Uncaught error from WebKit 605.1.15 on iOS 17.0.3 TypeError: Can only call HTMLMediaElement.canPlayType on instances of HTMLMediaElement canPlayType ([native code]::) filter ([native code]::) codecs (/webrtc/video-rtc.js:188:20) onmp4 (/webrtc/video-rtc.js:650:51) onopen (/webrtc/video-rtc.js:355:23) onopen (/webrtc/webrtc-camera.js:178:36)`

Regards

**Comment by g1za** [comment]
Closing this for the moment as after upgrading to iOS 17.1 it seems to work again properly and no error is logged anymore.
Regards

**Comment by AlexxIT** [comment]
Yes. `canPlayType` was fixed earlier.
