### ISSUE TITLE
Fix poster with relative path

### ISSUE THREAD

**Issue by rdlmn** [AlexxIT/WebRTC#598]
After recent update relative URL path in "poster" property stopped working.  It used to - see example below.  No errors in the browser console, does not seem to even attempt to load.  If i put full path, it works.

  - type: custom:webrtc-camera
    url: rtsp://192.168.1.1:XXX/camera
    mode: webrtc
    **poster: /local/images/poster.jpg**

Having relative path is very useful because I have dashboards for devices outside of my network and have devices inside of the network, but disabled from internet.  Having relative path works for both cases based on how HA is accessed (internally/externally).  Please fix this.

**Comment by jymorel** [comment]
same issue here. And systematically a warning in the log and a persistant notification when displaying card in the browser.

![card](https://github.com/AlexxIT/WebRTC/assets/96637729/f5bb6a9b-3675-4837-a7be-3028de08ede6)
![log](https://github.com/AlexxIT/WebRTC/assets/96637729/001919d9-c323-4a8c-8653-99100b777bb2)
![persistant notification](https://github.com/AlexxIT/WebRTC/assets/96637729/98a01686-7032-4e8f-b647-111fed1cf634)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/releases/tag/v3.5.1
