### ISSUE TITLE
Two-way audio. Send command from web - take 2-3 sec to play audio

### ISSUE THREAD

**Issue by antonbek89** [AlexxIT/WebRTC#599]
So I send the audio file via play audio
And it take between 2-3 sec to do action
My mp3 file host at the same server with webrtc

The camera connected via LAN and my server also

My camera is Reolink Doorbell POE

Just want to be clearly, my server work really fast except this issue

The example file very light 

`https://file-examples.com/storage/fe1734aff46541d35a76822/2017/11/file_example_MP3_700KB.mp3#audio=pcma#input=file`

What can be the problem?
I want reduce it to 1 sec maximum

**Comment by AlexxIT** [comment]
It's known problem of Reolink doorbell https://github.com/AlexxIT/go2rtc/issues/331
I don't know if this can be fixed from go2rtc side. Don't have this device. Don't have problems on my cameras.

**Comment by jairbj** [comment]
@antonbek89 I'm trying to play a custom sound on my doorbell (even with this delay).

How did you configure your "audio" under your media_player settings in home assistant?

Also, how can I play a local mp3 file in HA over this media player?
