### ISSUE TITLE
Does not install, does not work after manuall install

### ISSUE THREAD

**Issue by a-x-** [AlexxIT/WebRTC#6]
I got “Custom element doesn’t exist: ‘webrtc-camera’” on lovelace dashboard

no webrtc in custom_elements found after installation. “Add Integrations” search does not find webrtc camera
ok, I copied it manually, restarted, and added integration, but no card at lovelace present now.

**Comment by a-x-** [comment]
```
type: picture-entity
entity: camera.ffmpeg
camera_image: camera.ffmpeg
camera_view: live
show_name: true
show_state: true
```
works

**Comment by a-x-** [comment]
HA on RPI 4, Browser: padOS

**Comment by a-x-** [comment]
Error log from HA:
```
Logger: custom_components.webrtc
Source: custom_components/webrtc/__init__.py:111 
Integration: WebRTC Camera (documentation, issues) 
First occurred: 20:00:45 (2 occurrences) 
Last logged: 20:00:53

Can't start stream: rtsp://192.168.1.18:554/1/h264major, because: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain', url=URL('http://localhost:8083/stream')
```

**Comment by a-x-** [comment]
Ports are forwarded
![3C3F9B08-964D-4E5E-87F6-526C8CBD2C53](https://user-images.githubusercontent.com/6201068/114434967-48af1700-9bcc-11eb-8642-7e42269618ca.jpeg)

**Comment by NylonDiamond** [comment]
Hmm, I'm getting the same error "Attempt to decode JSON with unexpected mimetype"..

**Comment by NylonDiamond** [comment]
I tried all the recent versions and v1.0.0 is the only one that works with my tablet. I'm using a Huawei M5 Lite. Any ideas why v1.0.0 would no show the error "Attempt to decode JSON with unexpected mimetype" and the newer versions all show that message?

**Comment by AlexxIT** [comment]
@NylonDiamond check v1.0.5

**Comment by NylonDiamond** [comment]
V1.0.5 did the trick. Thanks, buddy! Great work 🎉️

**Comment by a-x-** [comment]
Ok, it’s better now. But it does not show preview. I have to press play, when it becomes full screen 
![3D0A931D-4247-42B7-8065-24D4B1560B79](https://user-images.githubusercontent.com/6201068/114601479-37ced600-9c9e-11eb-8988-7ac646985848.png)

**Comment by a-x-** [comment]
I expect it will update thumbnail preview  apprx every 10s w/o any button pressing

**Comment by a-x-** [comment]
(In full screen it staring to work)

**Comment by AlexxIT** [comment]
Is any problem still actual?

**Comment by PeterKurth130265** [comment]
Hello Having a problem ... after installation via Hacs and integration custom card is not showing up ...
I included debug ...
only entry i could find was 👍 2021-04-20 21:27:10 DEBUG (webrtc) [custom_components.webrtc.utils] 2021/04/20 21:27:10 Server Start Awaiting Signal
did i miss any point during installation ... any hint wellcome !

**Comment by PeterKurth130265** [comment]
> Hello Having a problem ... after installation via Hacs and integration custom card is not showing up ...
> I included debug ...
> only entry i could find was 👍 2021-04-20 21:27:10 DEBUG (webrtc) [custom_components.webrtc.utils] 2021/04/20 21:27:10 Server Start Awaiting Signal
> did i miss any point during installation ... any hint wellcome !

Solved ... my misstake was opening in edge ... which didnt work ... chrome works

**Comment by exotsk** [comment]
![image](https://user-images.githubusercontent.com/54969124/115870760-e8409500-a469-11eb-8d4c-0d74e30781c6.png)
что не так то ? 
![image](https://user-images.githubusercontent.com/54969124/115870842-04dccd00-a46a-11eb-92af-7519ed3d9219.png)
все прописано и перезапущено.

**Comment by AlexxIT** [comment]
@exotsk так может компонент не установлен

**Comment by exotsk** [comment]
![image](https://user-images.githubusercontent.com/54969124/115981182-3bc2f800-a5bc-11eb-931d-f3359bc3241f.png)
через HACS.

**Comment by AlexxIT** [comment]
@exotsk изображение на скрине вообще не связано с компонентом

**Comment by dukerider33** [comment]
I have installed Webrtc and can see it in integration, when I try to use it I get the error like in the screenshot below:
<img width="1102" alt="Screenshot 2021-08-17 at 20 38 31" src="https://user-images.githubusercontent.com/6003802/129783466-f30af2ef-c31a-4a22-bd98-f307b79f0f90.png">
Can you please advise what I am doing wrong?

**Comment by ondraandy** [comment]
> I have installed Webrtc and can see it in integration, when I try to use it I get the error like in the screenshot below:
> <img alt="Screenshot 2021-08-17 at 20 38 31" width="1102" src="https://user-images.githubusercontent.com/6003802/129783466-f30af2ef-c31a-4a22-bd98-f307b79f0f90.png">
> Can you please advise what I am doing wrong?

I have same trouble :(

**Comment by flaviusraicovici** [comment]
I get the same, most probably the integration is broken with the latest hass vs

**Comment by DarkPark** [comment]
the same

**Comment by imydal** [comment]
same for me

Custom element doesn't exist: webrtc-camera.

**Comment by blazejp83** [comment]
Same issue. Installed via hacs.

**Comment by AlexxIT** [comment]
Did you take this steps:
Configuration > Integrations > Add Integration > WebRTC
?

**Comment by DarkPark** [comment]
> Did you take this steps:
> Configuration > Integrations > Add Integration > WebRTC
> ?

yes

**Comment by AlexxIT** [comment]
What version of Hass do you use? Do you use lovelace mode yaml?

**Comment by DarkPark** [comment]
Home Assistant 2021.9.4 via docker
HACS 1.15.2
WebRTC Camera v2.1.1
lovelace configured in yaml file

**Comment by ht2k05** [comment]
I have the same issue in Mac

**Comment by AlexxIT** [comment]
Hass 2021.9.4

1. Configured integration
<img width="441" alt="Screenshot 2021-09-13 at 10 52 39" src="https://user-images.githubusercontent.com/511909/133045172-e1d3aa2f-c71c-4211-be18-5c7fb9cda4a6.png">

2. `configuration.yaml`
```yaml
lovelace:
  mode: yaml
```

3. `ui-lovelace.yaml`
```yaml
title: Home
views:
  - title: Example
    cards:
      - type: 'custom:webrtc-camera'
        url: 'rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov'
```

All works fine

**Comment by konradwalsh** [comment]
Im having this issue..
I uninstalled everything related to WebRTC
Then reinstalled and configured integration

Home Assistant 2021.9.6 via docker
HACS 1.15.2
WebRTC Camera v2.1.1


Still get the error

Custom element doesn't exist: webrtc-camera.
type: custom:webrtc-camera
url: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
 

![image](https://user-images.githubusercontent.com/7996482/133077255-216c924c-3edf-464d-b085-b44b99de4551.png)

**Comment by Openwrtfunboy** [comment]
Тоже самое всё. Установил, перезагрузил и Custom element doesn't exist: webrtc-camera.
