### ISSUE TITLE
Prevent starting internal go2rtc instance

### ISSUE THREAD

**Issue by widewing** [AlexxIT/WebRTC#601]
I use Home Assistant in docker container, and have go2rtc set up in another container. So I want to use that external go2rtc in the WebRTC integration.
I can use the `server` setting to point to the external instance, and it works flawlessly. But I also want the internal go2rtc be able to NOT start with the integration, as it expose several ports which conflicts with external instance, and also may have potential security risk

**Comment by AlexxIT** [comment]
Delete integration and setup it again
