### ISSUE TITLE
websocket_forward was never awaited issue on Eufy Doorbell T8203

### ISSUE THREAD

**Issue by Dmoua68** [AlexxIT/WebRTC#604]
I keep getting this error below for this integration.
```
"2023-11-13 21:21:10.834 WARNING (MainThread) [py.warnings] /config/custom_components/webrtc/__init__.py:213: RuntimeWarning: coroutine '_websocket_forward' was never awaited"

"/config/custom_components/webrtc/__init__.py:213: RuntimeWarning: coroutine '_websocket_forward' was never awaited await ws_server.send_json({'error': str(e)})"
```
I confirmed line 213 of the init.py file is set to await for the ws_server.send_json. I've uninstalled and reinstalled the WebRTC integration multiple times.
```
Home Assistant 2023.7.3
Supervisor 2023.11.0
Operating System 10.5
Frontend 20230705.1 - latest
```
Any idea about this?

TIA!

**Comment by AlexxIT** [comment]
You didn't provide the integration version

**Comment by Dmoua68** [comment]
Sorry, been a crazy week at work.

I'm on version v3.5.0 - 2023-10-27

**Comment by AlexxIT** [comment]
Line 213 is empty for this version... So I don't know what code is generating this error

https://github.com/AlexxIT/WebRTC/blob/554082f6e821139c9a2b7a14ca21e609ae1b5e17/custom_components/webrtc/__init__.py#L213

**Comment by Dmoua68** [comment]
Got it working by reinstalling HACS and then reinstalling the eufy security integration.
