### ISSUE TITLE
WebRTC service stream to Google Cast device stopped working

### ISSUE THREAD

**Issue by TheStigh** [AlexxIT/WebRTC#605]
Hi,

Using Home Assistant 2023.11.x, got Frigate running in a container and installed WebRTC Camera Integration in HACS.

Up until last week, I've been using the DashCast service to stream my front door camera upon detecting a person to my Google TV. Now it wont start the stream anymore, just switches to the menu overview on the Google TV. Did also test to a different cast device attached to my TV, here it stops with the DashCast logo.

I'm connected to NabuCasa as external URL, on my LAN HA runs https://xyz.ducdns.org for internal address (using DuckDNS). What I can see flashing at the bottom of the screen of my second cast device is that it seems the URL it tries to load is the NabCasa URL and not my internal URL??

This is the script I am running (been working for months):
```
  sequence:
    - service: webrtc.dash_cast
      entity_id: media_player.google_tv
      data:
        url: rtsp://user:pass@192.168.11.70:8554/inngang
        force: true
        extra:  
          mode: webrtc,mse
```

What I've tested :
- Testing the RTSP URL on VLC > Stream works fine
- Changing mode to webrtc only > No change
- Changing mode to mse only > No change
- Rebooted both my Google TV, sencond Cast device and HA multiple times > no change

Any suggestions?

**Comment by OlorinSledge** [comment]
I am having the exact same problem, though I am not running Frigate.

I cannot get the rtsp stream to play on my Google Nest Hub. They work perfectly fine in Home Assistant 2023.08.x.

Version 2023.08.x
- View camera in Home Assistant dashboard works. Using url rtsp://user:pass@192.168.10.40:554/h264Preview_01_sub
- View camera in VLC. Using url rtsp://user:pass@192.168.10.55:8554/doorbellsub
- View camera on my Google Nest Hub using DashCast works. Using url rtsp://user:pass@192.168.10.55:8554/doorbellsub

Version 2023.11.x
- View camera in Home Assistant dashboard works. Using url rtsp://user:pass@192.168.10.40:554/h264Preview_01_sub
- View camera in VLC works. Using url rtsp://user:pass@192.168.10.55:8554/doorbellsub
- View camera on my Google Nest Hub using DashCast **does not** work. Using url rtsp://user:pass@192.168.10.55:8554/doorbellsub or rtsp://user:pass@192.168.10.40:554/h264Preview_01_sub

Something has changed in the way WebRTC is doing the stream that has broken for DashCast using Google Nest Hub devices (in my case).

Any help would be appreciated!

**Comment by TheStigh** [comment]
> I am having the exact same problem, though I am not running Frigate.
> 
> I cannot get the rtsp stream to play on my Google Nest Hub. They work perfectly fine in Home Assistant 2023.08.x.
> 
> Version 2023.08.x
> 
>     * View camera in Home Assistant dashboard works. Using url rtsp://user:pass@192.168.10.40:554/h264Preview_01_sub
> 
>     * View camera in VLC. Using url rtsp://user:pass@192.168.10.55:8554/doorbellsub
> 
>     * View camera on my Google Nest Hub using DashCast works. Using url rtsp://user:pass@192.168.10.55:8554/doorbellsub
> 
> 
> Version 2023.11.x
> 
>     * View camera in Home Assistant dashboard works. Using url rtsp://user:pass@192.168.10.40:554/h264Preview_01_sub
> 
>     * View camera in VLC works. Using url rtsp://user:pass@192.168.10.55:8554/doorbellsub
> 
>     * View camera on my Google Nest Hub using DashCast **does not** work. Using url rtsp://user:pass@192.168.10.55:8554/doorbellsub or rtsp://user:pass@192.168.10.40:554/h264Preview_01_sub
> 
> 
> Something has changed in the way WebRTC is doing the stream that has broken for DashCast using Google Nest Hub devices (in my case).
> 
> Any help would be appreciated!

When the DashCast comes up on screen, I can see a brief message at the bottom referring to my nabucasa url - can this affect it and be the reason?

**Comment by TheStigh** [comment]
@AlexxIT  Possible to get a comment - what to look for?

- My Google TV uses Google DNS
- My NabuCasa URL works from outside (but from laptop and from HA Companion App)
- My local HA is using DuckDNS with a working certificate

When triggering the script (tested from both `HA > Services` and from a `script`) the result are always the same. DashCast logo appear, I can always see the loading of my NabuCasa URL and then nothing. Using `force: true` results that image return to the Google TV default page. WIth `force: false`, it just stop and hangs at the DashCast logo.

Updated the script to:
```
service: webrtc.dash_cast
data:
  entity_id: media_player.google_tv
  url: rtsp://user:pass@192.168.11.70:8554/inngang
  force: true
  extra:
    mode: webrtc,mse
```

The URL is an internal physical server running Frigate 12+ (currently also testing beta 13). It is not available directly from WAN.

Your WIKI `(https://github.com/AlexxIT/WebRTC/wiki/Cast-or-share-camera-stream)` is outdated as HA expect the `entity_id:` to be below `data:`.

Using the RTSP to any other viewer like VLC works fine. Also within Frigate everything is fine.

**Comment by OlorinSledge** [comment]
> 
> When the DashCast comes up on screen, I can see a brief message at the bottom referring to my nabucasa url - can this affect it and be the reason?

I am not using nabucasa but am having the same issue as you, so I don't think it's related to nabacusa.

**Comment by zorgiy** [comment]
Has anyone solved the problem?

**Comment by TheStigh** [comment]
> Has anyone solved the problem?

For me it was simply that my HA instance was locked 
`http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  server_port: 443` 

As soon as this was resolved, it all worked again. HA was working with internal IP but not through Nabu Casa, and since my external URL pointed to the Nabu Casa, stream wanted to use the external URL.

**Comment by AlexxIT** [comment]
This service using `from homeassistant.helpers.network import get_url` feature from Hass API to know what is best local/cloud Hass public link. It should prefer local link by default.

https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/network.py

I don't know why it prefer nabucasa url.
