### ISSUE TITLE
Home Assistant OS crashing after few minutes of stream

### ISSUE THREAD

**Issue by hairypotta** [AlexxIT/WebRTC#61]
Hi, I'm having some trouble with WebRTC. Looks like it makes my home assistant crash, because it becomes unresponsive after few minutes (about 2 or 3) of watching stream. I have 3 streams with resolution of 640x360 each, framerate 15fps and bitrate at 1024kbps max. I am running HASS OS, core version 2021.5.2 on my raspberry pi 3, also the webrtc is in version 2.0.2. Do you have any idea what is causing the problem? I'd be grateful for any hint.

**Comment by AlexxIT** [comment]
You find the problem?

**Comment by hairypotta** [comment]
> You find the problem?

I installed the Home Assistant in latest version once again and it worked.
