### ISSUE TITLE
Unable to view rtsps stream in HA in my production instance - works in my test instance?

### ISSUE THREAD

**Issue by AdrianGarside** [AlexxIT/WebRTC#612]
This works in my test home assistant instance:
type: custom:webrtc-camera
url: rtsps://bblp:PASSWORD@10.10.10.95:322/streaming/live/1
background: true

But in my production one I get:
![image](https://github.com/AlexxIT/WebRTC/assets/26147576/9bf47ed7-a863-422b-842b-485a7776c882)
mse: tls: failed to verify certificate: x509: cannot validate certificate for 10.10.10.95 because it doesn't contain any IP SANs

If I change to rtspx which I saw mentioned in an issue as disabling security, that also works in my test instance but fails in my production instance:
![image](https://github.com/AlexxIT/WebRTC/assets/26147576/b0733bcd-60a9-4cb8-94e8-026df499eee7)
mse: wrong response on DESCRIBE

**Comment by AdrianGarside** [comment]
And now my WebRTC install in my production HA seems to have died - I can no longer access go2rtc at <IP>:1984 where I could earlier. And the video playback error has changed:
![image](https://github.com/AlexxIT/WebRTC/assets/26147576/0f1f41c1-bacc-409a-b961-d09b7aa5b214)

**Comment by AdrianGarside** [comment]
And removing the WebRTC integration and re-adding it fixed everything. Now go2rtc is working again on IP:1984 and the video is playing successfully in the dashboard, the same as my test HA instance.

**Comment by AlexxIT** [comment]
I guess problem solved
