### ISSUE TITLE
Stream not stopping when app goes to background in Android app

### ISSUE THREAD

**Issue by abmantis** [AlexxIT/WebRTC#62]
A few days ago my phone drained from over 50% to 0% overnight (usually it drains 10% or less). The culprit, according to Android battery stats, was the Home Assistant app and this happened after adding this component and viewing the cameras on my phone. Also, it indicated that the app downloaded 18GB of data this month (I'm assuming most was on that night):
 
![image](https://user-images.githubusercontent.com/974569/118381692-6f0a0d00-b5e5-11eb-92e1-58896f604b30.png)

On another day, while I was editing the cards in lovelace (changing PTZ, options, etc), I noticed that my phone was warm while the screen was off (it was not sleeping).

**Comment by Pe-MaKer** [comment]
Same here using V2021.5.1 of the mobile App for Android.
Home Assistant uses about 30% of the total battery capacity since I use WebRTC, even when the app is running in the background.

**Comment by marcoalexpinheiro** [comment]
Same here Alex, app in background on my Android and spent 4.5GB of mobile data.

**Comment by jtregl** [comment]
I have similar issue. There is still some traffic with the app running on background when screen is on. It stopped after some time after the mobile screen is turned off and mobile is in "stand by" mode for some time. But when the mobile is turn on again and the HA app is opened (running on the background all the time), the video playback is broken.
![Screenshot_2021-05-19-13-37-44-975_io homeassistant companion android](https://user-images.githubusercontent.com/77359947/118806884-e66ec380-b8a7-11eb-990a-11b23d29f736.jpg)
I have to shut down the app and open it again. Then the video is shown correctly.

**Comment by abmantis** [comment]
@jtregl I think you should open another issue, since this one is about the stream not stopping when HA is in the background and the phone enters standby. 
Your problem may be related, but it may also be unrelated and it is better to focus the discussions on one single problem IMO.

**Comment by jtregl** [comment]
I can confirm more battery drain on mobile when using the WebRTC card in Lovelace even HA application is running on background. Also more data transfer is happening, around 50kB/s with single camera with 640*360 stream resolution.

**Comment by Murder3D** [comment]
I can confirm the same behavior on Fully Kiosk Browser.

I have Home Assistant exposed via Fully Kiosk Browser on a Galaxy Tab A7 and when I tap the "camera" dashboard the WebRTC live stream of my TP-Link Tapo C200 camera starts correctly, but when I change to another dashboard or when I simply park Fully Kiosk Browser in background the WebRTC live stream of that camera does not stop. It continues to work.

To completely stop the stream I have to shut down Fully Kiosk Browser.

I noticed that if I try to access the same full quality stream via TP-Link Tapo application while the WebRTC stream is still running I get an error on the Tapo app, and I only have the low quality (720p) stream available.

An option to kill/stop the WebRTC live stream after "X" minutes/seconds would be great (or, even better, kill/stop the stream when another dashboard is viewed).

**Comment by rroller** [comment]
Can confirm similar impact when loading Home Assistant on my Chrome browser (windows 10).  I created a HA view with my cams and it works great. But switching away from that view I see my GPU and CPU both at high usage until I close the HA browser tab completely. I can also confirm through ethernet usage that the video feed is still being consumed even when I navigate away from the cam view to other HA views.

**Comment by idoaflalo** [comment]
> lso confirm through ethernet usage that the video feed is still being consumed even when I navigate away from the cam view to other HA views.

I experience the same thing. The stream never closed until I restart my Chrome.

**Comment by idoaflalo** [comment]
> > lso confirm through ethernet usage that the video feed is still being consumed even when I navigate away from the cam view to other HA views.
> 
> I experience the same thing. The stream never closed until I restart my Chrome.

I think the custom element is missing the `disconnectedCallback` function to clean up the connections to the server when the element is deatched from the DOM.

**Comment by idoaflalo** [comment]
#81 I created a branch which might fix this bug as well

**Comment by k-korn** [comment]
> #81 I created a branch which might fix this bug as well

Tested it with official Android app.
Streaming indeed now stops if you switch to another tab in the Home Assistant (which does not contain video element).

However, if you switch away from Home Assistant app to something else, stream continues to run.

**Comment by idoaflalo** [comment]
> > #81 I created a branch which might fix this bug as well
> 
> Tested it with official Android app.
> Streaming indeed now stops if you switch to another tab in the Home Assistant (which does not contain video element).
> 
> However, if you switch away from Home Assistant app to something else, stream continues to run.

What about now? can you check it?

**Comment by k-korn** [comment]
> > > #81 I created a branch which might fix this bug as well
> > 
> > 
> > Tested it with official Android app.
> > Streaming indeed now stops if you switch to another tab in the Home Assistant (which does not contain video element).
> > However, if you switch away from Home Assistant app to something else, stream continues to run.
> 
> Ok. I updated the PR :)
> Can you check it now?

Yes, now stream properly stops when app is in background - thanks!

**Comment by AlexxIT** [comment]
Great work from @idoaflalo in latest release

**Comment by karsie1994** [comment]
Found the issue to late spend 50 euro in overcharge on my data plan :(.

**Comment by mikedrawback** [comment]
I know this was closed in June, but it just started happening to me in November. 

I have set `background: false`, but I can still hear the audio for my WebRTC stream when switching tabs using Fully Kiosk Browser. When the video is visibile, I hear the audio doubled as though the video is in two places at once. I did recently make a change to the lovelace view such that it contains a conditional card, but I'm not sure if that has anything to do with it. I will try removing the conditional cards and see if it makes any difference.

**Comment by k-korn** [comment]
Same for me, the issue with Home Assistant app battery drain returned somewhere in the last month.

**Comment by mikedrawback** [comment]
OK, it has only been a few hours but ever since I removed the conditional card from the same lovelace view as my WebRTC card, it is no longer playing in the background.

There has been no update to WebRTC that I can tell would have triggered this. I did notice that there was an update to Android webview around the time it started happening, in case that helps anyone maybe it is a clue.

**Comment by idoaflalo** [comment]
> 

Just checked your problem and it looks like a problem with the 'state-switch' you are using.
As I see, this component is hiding the elements from the dom using 'display: none' (CSS) and not actually detaching the elements from the dom (In this case the WebRTC component has no way to know whether to stop the stream or not).
I suggest you to talk with the developer of 'state-switch' and ask him to detach the hidden elements from the dom when the conditional is false.

**Comment by mikedrawback** [comment]
I spoke too soon. Fully Kiosk crashed and now it is playing in the background again.

**Comment by mikedrawback** [comment]
@idoaflalo thanks for checking. I should note that WebRTC is **not** the element I'm hiding using the conditional card. It is another card adjacent to the WebRTC card. Without looking at any code I thought maybe the conditional card was somehow causing the entire tree to render twice, hence the double audio. However, it wouldn't exactly explain why I still hear the audio when navigating to other tabs.

**Comment by mikedrawback** [comment]
Further testing reveals that this only happens on one of my two tablets running Fully Kiosk browser. It only happens after reloading the fully kiosk app. Webview on the affected tablet was NOT updated recently so now I'm thinking it must have something to do with Homeassistant / Lovelace

**Comment by mikedrawback** [comment]
Sorry to flood this thread but putting it out there in case anyone else has this issue. I found that using the 'Restart App' command in the fully remote admin causes this double webrtc stream. If I turn the screen off and back on, it resolves itself. I will continue playing with some of the fully kiosk settings to see if it changes anything, ping me if interested in the results

**Comment by mikedrawback** [comment]
Still struggling with this on two tablets running fully kiosk browser. Webrtc component is still running in the background when switching Lovelace views. I hear double audio and if I mute the video I can still hear the single audio running in the background

**Comment by schol478** [comment]
Looks that i'm dealing with the same issue. 
I use the webrtc to share a stream from the ring doorbell. (webrtc.create_link) 
The stream will not stop and stays active.

The option open_limit: 1 or time_to_live: 60  doest not work.
