### ISSUE TITLE
Custom WebRTC card available after installation

### ISSUE THREAD

**Issue by MilesAheadToo** [AlexxIT/WebRTC#623]
I installed the latest version WebRTC through HACS and then through the integrations.  But I cannot see how to access the custom card.
 
![image](https://github.com/AlexxIT/WebRTC/assets/78782836/d0103e94-aed0-494b-99b3-a971b0c1d6a8)

![image](https://github.com/AlexxIT/WebRTC/assets/78782836/b804f0ac-5f0a-4c0a-b562-c34c64c84345)

![image](https://github.com/AlexxIT/WebRTC/assets/78782836/de52f8fd-5496-4186-b999-9f6a1a45e573)

![image](https://github.com/AlexxIT/WebRTC/assets/78782836/b5ba16db-ba95-4062-abc9-98762f094321)

**Comment by AlexxIT** [comment]
#260
