### ISSUE TITLE
hls: streams: wrong user/pass with eufyCam 2C

### ISSUE THREAD

**Issue by T3mplate-wow** [AlexxIT/WebRTC#627]
I want to integrate my eufycams into Home assistant using this project.

I used the HACS installation and the basic user configuration. After that I added the „webRTC Camera“ Integration. 

Now I see the „Custom WebRTC Camera“ Card and when I enter the URL everything works fine.
I see the current stream of the camera. 

the configuration is just:
`type: custom:webrtc-camera 
url: rtsp://user:pass@10.0.0.86/live1
`

So for 2 or maybe 4 or 5 minutes I can see the stream. But after that it stops showing the stream.
When I add a new WebRTC Camera Card with the same credentials it start working again. Even the card which show me the failure starts working again. 
but after a short time it stop working again.

There was an issue with some similarities:
https://github.com/AlexxIT/WebRTC/issues/499

But there was the question what the go2rtc UI shows and I don’t see that UI, because I used the basic installation.

**Comment by T3mplate-wow** [comment]
Same error when I open localhost:1984 / go2rtc when I click stream there

**Comment by AlexxIT** [comment]
1. Check RTSP from camera in some other player, for example VLC
2. Check RTSP from go2rtc in some other player, for example VLC

**Comment by T3mplate-wow** [comment]
I checked it and there was the same issue. The camera only delivers the stream, when it was activated before. I need to find out how to solve it. Sorry for the issue
