### ISSUE TITLE
Reconnect to stream after loss

### ISSUE THREAD

**Issue by popy2k14** [AlexxIT/WebRTC#631]
Using go2rtc + webrtc camera in HA to display the door cam on an magic mirror on an HA dashboard.
It's working fine most of teh time. I have done some work in HA the last days an restarted it several times.
One time the stream did'nt survive (black screen with RTC in the right corner was shown) and i had to reload the page/dashboard, which i want to prevent.

After some tests: Restart go2rtc addon, HA core, ... the stream always survived.

Is there some sort of reload/reconnect implemented? (to be sure an stzream is always shown).

thx

**Comment by ccie11827** [comment]
I am also interested in this!

**Comment by popy2k14** [comment]
Now I am doing the following as a workaround to prevent this issue:

 * Send key F5 to chromium on magic mirror
 * Delay 4 seconds
 * power on the monitor

So the dashboard gets freshly loaded everytime someone enters the room and issue doesn't pop up.

To solve this i am thinking of something like:
 It checks every minute if it has a stream, when not, reload the stream 

Is this possible?

**Comment by sigalou** [comment]
I also have flow losses after an hour and a half, I don't know why (it's since one of the last updates). I would like to be able to restart the flow if it gets stuck, like an F5 would do. THANKS

**Comment by popy2k14** [comment]
@sigalou here is my complete setup incl. refresh after 4 seconds after turning on the monitor.

HA thread: https://community.home-assistant.io/t/replaced-magicmirror-with-lovelace-dashboard/600905/11?u=popy

**Comment by AlexxIT** [comment]
What go2rtc version you using? v1.8.5 has a bug with reconnection feature

**Comment by popy2k14** [comment]
Sure I have the HA addon go2rtc version 1.8.5.

Any hints when there will be an release so we can test if the issue is fixed for us?

**Comment by AlexxIT** [comment]
Don't know about release. This problem fixed in the go2rtc latest master version

**Comment by popy2k14** [comment]
Ok, thx

**Comment by ccie11827** [comment]
My problem seems to be fixed in the  latest master version :-)

**Comment by popy2k14** [comment]
thx for the info.
Would be nice if we can get an release, so everyone with supervised HA installations can benefit from the fix.

**Comment by popy2k14** [comment]
Tested the hardware master of go2rtc and also for me it seems stable for the last few days.

Any info when next stable will be released?

thx

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/releases/tag/v3.5.2

**Comment by popy2k14** [comment]
thx for the release (with downgraded go2rtc).
Installed now and see how it goes.

**Comment by AlexxIT** [comment]
When I'll have free time for this project. Made six releases in the last three days https://t.me/AlexxIT_Releases

**Comment by popy2k14** [comment]
Wow, thx for your work.
Take your time.

**Comment by AlexxIT** [comment]
The release will be published when all planned issues will be closed.
You can install the master version at any time without waiting.

**Comment by KaelKael** [comment]
Thanks for your answer. I'm still a little new on HACS. I didn't thought to use the master branch in it. 
I'll think about it even if I usually prefer to use "fix" version.
Good luck in your work !

**Comment by popy2k14** [comment]
@AlexxIT The issue is back for me since (i think) update v3.6.0 - 2024-10-12 a few days ago.
Up until 3.6.0 it was stable.

Is it possible that the update to go2rtc 1.9.4 causes the issue for me?
How can i help you debug the issue?

I am have now downgraded to v3.5.2 - 2024-04-07 and recheck the coming days if the issue is gone.

thx

**Comment by AlexxIT** [comment]
1.9.4 don't have reconnection bug. But it may have some other bugs...
