### ISSUE TITLE
WebRTC not generating p2p stream

### ISSUE THREAD

**Issue by svanimpelen** [AlexxIT/WebRTC#632]
Trying to get a stream fro my eufy doorbell. when i setup the WebRTC integration I am not seeing e.g. camera.doorbell when i go to http://homeassistant.local:1984/. I see the following:

![image](https://github.com/AlexxIT/WebRTC/assets/22742135/667accb9-fa0b-4ffd-8db5-da52b8630d6f)

raised the issue with in the eufy community and advised me to raise a ticket as they have different behavior from the webrtc integration.

**Comment by AlexxIT** [comment]
Don't understand why this integration related to your issue.

**Comment by svanimpelen** [comment]
@AlexxIT I understood the integration should expose camera.doorbell and not the rtsp stream.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC#configuration
