### ISSUE TITLE
Hass 2025.1 warning: is using deprecated supported features values

### ISSUE THREAD

**Issue by dm82m** [AlexxIT/WebRTC#633]
> Entity None (<class 'custom_components.webrtc.media_player.WebRTCPlayer'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PLAY_MEDIA|STOP|BROWSE_MEDIA: 135680>, please create a bug report at https://github.com/AlexxIT/WebRTC/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

> Entity None (<class 'custom_components.hacs.update.HacsRepositoryUpdateEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <UpdateEntityFeature.INSTALL|PROGRESS|RELEASE_NOTES: 21>, please create a bug report at https://github.com/hacs/integration/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by klimentiy23** [comment]
2024-01-08 02:48:05.834 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.hacs.update.HacsRepositoryUpdateEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <UpdateEntityFeature.INSTALL|PROGRESS|RELEASE_NOTES: 21>, please create a bug report at https://github.com/hacs/integration/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by pcieszkowski** [comment]
+1

**Comment by scuslon** [comment]
![Screenshot 2024-01-13 143238](https://github.com/AlexxIT/WebRTC/assets/21044285/f782e23f-5cd0-4c2c-839b-1ba644fcdfa8)
![Screenshot 2024-01-13 143307](https://github.com/AlexxIT/WebRTC/assets/21044285/06aca8ec-115b-4df3-bd10-c7d169b59825)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/releases/tag/v3.5.1

**Comment by chrislail77** [comment]
WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.hacs.update.HacsRepositoryUpdateEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <UpdateEntityFeature.INSTALL|PROGRESS|RELEASE_NOTES: 21>, please create a bug report at https://github.com/hacs/integration/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

1 more?

**Comment by AlexxIT** [comment]
No. Just read what the warning says
