### ISSUE TITLE
Unable to import component: No module named 'homeassistant.components.image' (since v3.5.1)

### ISSUE THREAD

**Issue by bcutter** [AlexxIT/WebRTC#636]
Since updating to https://github.com/AlexxIT/WebRTC/releases/tag/v3.5.1 and doing the first restart of HA after the update (using HACS), I get this on every HA Core start:

![grafik](https://github.com/AlexxIT/WebRTC/assets/13799156/901b29f1-3846-4888-a1e4-0ca863c55bfd)

```
Logger: homeassistant.setup
Source: setup.py:213
First occurred: 18:42:31 (1 occurrences)
Last logged: 18:42:31

Setup failed for custom integration webrtc: Unable to import component: No module named 'homeassistant.components.image'
```

Maybe because of https://github.com/AlexxIT/WebRTC/pull/619 looking for this entity type which does not exist on older HA Core versions? If true (just a wild guess): in that case the [3.5.1 update](https://github.com/AlexxIT/WebRTC/releases/tag/v3.5.1) should have been flagged with a "breaking change" notification or listing the minimum needed HA Core version.

```
Home Assistant 2023.4.6
Supervisor 2023.12.0
Operating System 11.2
Frontend 20230411.1 - latest 
```

---

By the way there's a typo in the date of https://github.com/AlexxIT/WebRTC/releases/tag/v3.5.1.

**Comment by bcutter** [comment]
Edit: v3.5.0 works without any issues. Which HA version is needed to run v3.5.1?

**Comment by AlexxIT** [comment]
You right. Image require newer Hass version. I think this is bad idea. Will fix this in next release. You can use previous version for now.

**Comment by bcutter** [comment]
Great. Looking forward to an updated version (you'll probably implement a "if availalbe, use it, if not, don't try to implement usage of image entity" check, right?) 🎉

**Comment by bcutter** [comment]
> I think this is bad idea. Will fix this in next release.

@AlexxIT do you have any estimations for the new release containing the fix for this? Thanks.

**Comment by AlexxIT** [comment]
You can try latest master version

**Comment by bcutter** [comment]
> You can try latest master version

Is there a new release? I'm only using HACS.

**Comment by AlexxIT** [comment]
You can install it via HACS. Redownload and select master from dropdown

**Comment by AlexxIT** [comment]
It's not a release yet.

**Comment by bcutter** [comment]
So when will you make a release?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/releases/tag/v3.5.2
