### ISSUE TITLE
Aqara G4 Doorbell Homekit Integrations in HA fails. please help….

### ISSUE THREAD

**Issue by Elcapone86** [AlexxIT/WebRTC#638]
I have been trying to pair my G4 with HA via go2rtc since yesterday. Unfortunately I always get this error message when I try. (See picture)

The integration on Apple Homekit on my iPhone works without any problems. However, I would also like to use the camera in HA as an entity for automations.

![IMG_0855](https://github.com/AlexxIT/WebRTC/assets/40920098/206c71ca-a8b4-4bf5-8c72-bf22f69053de)

Here my Go2Rtc Config

![IMG_0856](https://github.com/AlexxIT/WebRTC/assets/40920098/75f4c3ba-c526-46e1-8979-fd96fc6353dc)

**Comment by AlexxIT** [comment]
1. If you trying to add go2rtc homekit module - it's only compatible with original Apple devices.
2. If you trying to add G4 camera - you should create issue in the Hass project
