### ISSUE TITLE
Reolink doorbell + Media Player

### ISSUE THREAD

**Issue by rossdargan** [AlexxIT/WebRTC#639]
I'm using frigate(.13), which has go2rtc (1.8.4) installed. All this is installed on a different server to home assistant with a different IP.

I have 2 way audio working fine, but I really want to setup the camera as a media player object so I can play TTS through it.

In my config I've added the following media player component (https://github.com/rossdargan/hass-config/blob/master/configuration/media_player/cameras.yaml):

```
  - platform: webrtc 
    name: Doorbell
    stream: doorbell
    audio: '-af "volume=10dB,adelay=2s,apad=pad_dur=6" -c:a pcm_alaw -ar:a 8000 -ac:a 1'
```

My question is what should stream be? The camera is called `camera.doorbell` inside home assistant. 

The above configuration does create the following entity:
![image](https://github.com/AlexxIT/WebRTC/assets/1276400/0d8b70d8-937d-4346-85e1-4d3c6b69bc9f)

but trying to play anything through it gives the following error:

![image](https://github.com/AlexxIT/WebRTC/assets/1276400/db7262d2-a581-4508-8a7b-6ae084ab6a78)

and it creates the following error in my home assistant logs:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:57:02 (2 occurrences)
Last logged: 13:57:23

[140308658688320]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/webrtc/media_player.py", line 74, in async_play_media
    assert r.ok
AssertionError
```

Is what I'm trying to do even possible?

**Comment by AlexxIT** [comment]
1. Stream is stream name from go2rtc config
2. I'm not sure if your audio param will work

**Comment by rossdargan** [comment]
This sounds daft, but how does webrtc know what the go2rtc config stream name is? It's on another server? Does it know I have the frigate plugin installed and does it use that? Sorry if this is a daft question!

**Comment by rossdargan** [comment]
I had moved frigate, and forgot I had entered the url when I first added the component - I needed to remove it and re-add it to update the url. Hope this helps anyone in the future!

**Comment by Iceman248** [comment]
I tried this using the stream name from my go2rtc config. This is all on the same server, but I get an error looking like the one you have. Was there something else you did to get it work?
