### ISSUE TITLE
Two way audio local network only

### ISSUE THREAD

**Issue by SusithAbeythunga** [AlexxIT/WebRTC#640]
May be this is a trivial question. I have isolated HA from internet and running completely local. But I found that the two way audio from door bell does not function without https. What's the best way to have two way audio for a HA system that runs completely local?

**Comment by AlexxIT** [comment]
1. HTTPS can also be on local sites.
2. https://stackoverflow.com/questions/52759992/how-to-access-camera-and-microphone-in-chrome-without-https
