### ISSUE TITLE
Video image is broken after app is restored

### ISSUE THREAD

**Issue by jtregl** [AlexxIT/WebRTC#65]
Hi, 
I'm using card showing the video stream from my camera (TPLink Tapo C200). 

- I put the mobile application on the background 
-- battery saver is disabled for the app 
-- automatic start is enabled 
- Left the app there for some period of time (looks like it is necessary to turn off the screen and put phone to "standby").
- After the application is opened again (restored from background), the video is screwed:
![screenshot](https://user-images.githubusercontent.com/77359947/118808772-2171f680-b8aa-11eb-8d74-1c4262ad4e94.png)
- I have to close the app and start it again completely to fix the stream.

HA is running on 64bit Pi4 4GB.

**Comment by jtregl** [comment]
After some more testing it seems to be random. Sometimes it happens even after fresh app start. Sometimes it is fixed after few seconds of playback. And sometimes it not happen even application is restored from background after some longer mobile standby.
I would give this very low prio as the workaround exists and I'm not able to test it with different camera.

**Comment by juliandsp91** [comment]
Same here, did you solve this? I just slide to different page in dashboard and come back to restart the card, is not a big problem but would be great to avoid this annoying issue, also with Tapo C200.

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc

**Comment by AlexxIT** [comment]
Should be fixed in v3
