### ISSUE TITLE
Feature Request: New Services for Mute and Mic

### ISSUE THREAD

**Issue by netsoft-ruidias** [AlexxIT/WebRTC#650]
Hey.

WebRTC card is great , it includes some really cool UI capabilities, like mute/unmute audio, toggle fullscreen, activating the microphone (through streams), digital PTZ and even the possibillity to add custom shortcuts that allow us to expand all of this... all very cool and all very well done, congrats on the work... 👍 

but...

I was wondering here, how difficult whould it be for you to include all of this features in a service?
You already have two services (`webrtc.create_link` and `webrtc.dash_cast`) could you add a few more?

I have a use case (my video intercom) in which I would prefer to have these features outside the video frame, using the normal HA buttons.

I noticed that for "the family" (wife and childrens) it is more dificult to use the WebRTC UI than to use the traditional HA buttons, as I have a wall-mounted tablet to control everything, the video intercom distracts from the usability of all other features, which makes the UX experience poorer.

What do you think?

**Comment by AlexxIT** [comment]
You should use browser mod for controlling browser from Hass
