### ISSUE TITLE
Finding Integration within HACS?

### ISSUE THREAD

**Issue by jamesphw** [AlexxIT/WebRTC#651]
I'm trying to figure out how to install this in HA. The instructions are quite straightforward:

> Method 1. HACS > Integrations > Plus > WebRTC > Install

But, WebRTC isn't available. I've added the repository https://github.com/AlexxIT/hassio-addons to the addon store, but that only adds go2rtc as an available option, not WebRTC.

What have I missed?

**Comment by jamesphw** [comment]
I should add, the installation does work by copying the files manually. But it's just not as user friendly for beginner users and it's harder to keep up-to-date!

**Comment by jamesphw** [comment]
I have also tried using the altnernative method and the files manually. This does create the WebRTC Camera in the integrations menu, but does not create the WebRTC addon in HA.

**Comment by jamesphw** [comment]
Installation did work when copying the files manually (did have to clear my browser cache to get it to work). Would still like to know how to add it via HACS store for better update management (and perhaps this can be clarified in the documentation for beginners like myself).

**Comment by AlexxIT** [comment]
This is not addon, but integration. HACS is not Home Assistant, but Home Assistant Community Store

**Comment by jamesphw** [comment]
Thanks. So stupid, it does indeed show in integrations I was clicking addons.

**Comment by nmatei** [comment]
"browse repositories" has been removed... you have to simple search it, it took me a while until i've found it :) 
had to login in incognito too see this msg
<img width="960" alt="Screenshot 2024-05-09 at 00 17 09" src="https://github.com/AlexxIT/WebRTC/assets/2863309/9559735a-5f08-45a4-80bf-80d1ad985d06">
