### ISSUE TITLE
WebRTC doesn't work in HA

### ISSUE THREAD

**Issue by Shlyakhoff** [AlexxIT/WebRTC#654]
The integration is not in the list of Integrations in Home assistant, even after cleared the browser cache and rebooting HA. Also I don't see any services like webrtc.dash_cast. However in HACS integrations I can see installed application. 

I suppose it may be related to the installed Frigate integration, but I'm not sure

I've installed ver. 3.5.1 and HA ver. 2024.2.1.

How can I fix it?

**Comment by AlexxIT** [comment]
Check custom components folder. If you have this integration there.

**Comment by Shlyakhoff** [comment]
@AlexxIT Yes, I have.
![image](https://github.com/AlexxIT/WebRTC/assets/47924237/24745cfd-a3e1-4444-a891-aa3cd3a69158)

**Comment by AlexxIT** [comment]
Try to reinstall. Maybe download is currupted.

**Comment by Shlyakhoff** [comment]
@AlexxIT I did it again - the same result, but I can't find the integration in the resources tab in HA, it seems that it doesn't add the linkc to webrtc resource automatically.

**Comment by Shlyakhoff** [comment]
I have now rebooted the server again and saw the integration, thank you so much for your help!
