### ISSUE TITLE
Feature Request: PTZ preset positions

### ISSUE THREAD

**Issue by B-double-U** [AlexxIT/WebRTC#658]
Hi, 

is it possible to add to the PTZ controls to possibility to execute the "preset" PTZ-command, to enable accessing the preconfigured positions with the camera ?

This is for example what I have used in a picture-glance card:
service: onvif.ptz
      service_data:
        entity_id: ....
        preset: Preset1
        speed: 1
        move_mode: GotoPreset

Best regards.

**Comment by AlexxIT** [comment]
Use `shortcuts` and call any services you like
