### ISSUE TITLE
IP address resolution for DashCast

### ISSUE THREAD

**Issue by ChrisRomp** [AlexxIT/WebRTC#66]
I run Home Assistant in Docker, and when using the `webrtc.dash_cast` service, the URL it tries to cast is `http://[docker internal IP]:8123/...` instead of the actual LAN IP of HA (outside of the docker network).  Is there a way to configure WebRTC to use a specific IP?

**Comment by AlexxIT** [comment]
You should config external and internal IP address manually. Read Hass docs.

**Comment by ChrisRomp** [comment]
Ah, ok: https://www.home-assistant.io/docs/configuration/basic/

Been using HA for years and never bothered with this. 😅
