### ISSUE TITLE
poster with access_token url

### ISSUE THREAD

**Issue by sdavides** [AlexxIT/WebRTC#663]
Poster doesn't work with this type, which works in notification

poster: "/api/camera_proxy/camera.camera_hub_g3_120c?token={{state_attr('camera.camera_hub_g3_120c', 'access_token') }}"

**Comment by JavanXD** [comment]
Can you take a look into the Homeassistant error log, are there warnings like this?

```
Logger: homeassistant.components.http.security_filter
Quelle: components/http/security_filter.py:65
Filtered a request with unsafe byte query string:
```

**Comment by AlexxIT** [comment]
It's not supported. It is written in the readme
