### ISSUE TITLE
hide volume icon ?

### ISSUE THREAD

**Issue by sdavides** [AlexxIT/WebRTC#666]
how to hide volume icon ?
style:   .volume {display: none} not work

**Comment by AlexxIT** [comment]
Show screenshot

**Comment by sdavides** [comment]
![immagine](https://github.com/AlexxIT/WebRTC/assets/31100253/6cd2fed6-f0d8-4c30-98be-9f24900bfc2b)

**Comment by AlexxIT** [comment]
Probably because this icon visibility changed in the code. Depends on audio track inside stream

**Comment by sdavides** [comment]
the icon appears after the play icon and the video has started, can't it be hidden?

**Comment by AlexxIT** [comment]
No. You can hide whole custom UI or disable audio track
