### ISSUE TITLE
Stream to camera. The problem is that the broadcast has stopped.

### ISSUE THREAD

**Issue by TokarevSergey** [AlexxIT/WebRTC#669]
Good evening.
After adding Hikvision camera to go2rtc

go2rtc:
  streams:
    DoorBell:
      - rtsp://admin:0000000@10.0.0.11:554/ISAPI/Streaming/Channels/101
      - isapi://admin:0000000@10.0.0.11:80/
    DoorBellCh2:
      - rtsp://admin:0000000@10.0.0.11:554/ISAPI/Streaming/Channels/102
      - isapi://admin:0000000@10.0.0.11:80/
       
And creating media_player in /homeassistant/configuration.yaml

media_player:
  - platform: webrtc
    name: PlayerDoorBell
    stream: DoorBell
    audio: pcmu

  - platform: webrtc
    name: PlayerDoorBellCh2
    stream: DoorBellCh2
    audio: pcmu

Получается такая картина:

![image](https://github.com/AlexxIT/WebRTC/assets/98225056/c4bc90c5-701c-4748-a2e1-61a6cbe54e37)

If you play audio using this button, the player will look like the image below.

![image](https://github.com/AlexxIT/WebRTC/assets/98225056/15a55f64-4471-4127-9f43-9707ac5033cc)

And if the sound is supplied through automation:
alias: Внимание обнаружена опасная активность PlayerDoorBellCh2
sequence:
  - service: media_player.media_stop
    data: {}
    target:
      entity_id:
        - media_player.playerdoorbellch2
  - service: media_player.play_media
    target:
      entity_id: media_player.playerdoorbellch2
    data:
      media_content_id: >-
        media-source://media_source/local/Vnimaniye. Obnaruzhena opasnaya
        aktivnost, informatsiya budet peredana na pult okhrany.mp3
      media_content_type: audio/mpeg
    metadata:
      title: >-
        Vnimaniye. Obnaruzhena opasnaya aktivnost, informatsiya budet peredana
        na pult okhrany.mp3
      thumbnail: null
      media_class: music
      children_media_class: null
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://media_source
mode: single
icon: mdi:alarm-light

![image](https://github.com/AlexxIT/WebRTC/assets/98225056/1686981f-cf08-4e10-b8e3-ec0529f14161)

The player is constantly working. How can I force it to turn off?

Thank you

**Comment by xraywinedrinker** [comment]
Set up an automation to stop the camera from playing.

**Comment by TokarevSergey** [comment]
Thank you.  I figured it out here.  The player works when the camera is turned on.  When is streaming broadcast?
