### ISSUE TITLE
Cards all linking to the same ip address even though they are different

### ISSUE THREAD

**Issue by ZainAjam** [AlexxIT/WebRTC#67]
![Screenshot_20210520-075327_Home Assistant](https://user-images.githubusercontent.com/32865278/118926444-a14aa000-b940-11eb-9cc3-f2f056d9f38b.jpg)

I have 6 cameras on one page and the cards are set up to link to camera entity and not rtsp link. This worked fine until I unplugged the power of two cameras and now all the cards think they are coming from the same ip address. See the error on the picture I've linked above. This is all while on the same lan.

**Comment by petramuzammel** [comment]
Any workarounds?

**Comment by AlexxIT** [comment]
Do you use entity in card config?

**Comment by ZainAjam** [comment]
That's right. Using camera entities already in my entities list

Zain Ajam
***@***.***
0845819728

**Comment by AlexxIT** [comment]
Through which integration are these cameras connected?

**Comment by ZainAjam** [comment]
Ezviz

Zain Ajam
***@***.***
0845819728

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc

**Comment by AlexxIT** [comment]
Should be fixed in v3
