### ISSUE TITLE
Possible to include nav options like the Picture Glance card?

### ISSUE THREAD

**Issue by Roachforlife** [AlexxIT/WebRTC#671]
On a stock picture glance card you can set tap and hold options for the feeds. I used this often as a way to tap a small cam window and then enlarge it or bring me to another dashboard tab with a 'sidebar' format in full screen. I tried using the same yaml from those in the webrtc custom card but didnt work. Is this possible, maybe via some other yaml?  Also since the RTC streams seem more like they are 'playing' a video, clicking it currently just brings up the seekbar, so not sure if this is just a limitation.  Or perhaps adding a custom button at the bottom, by the play/pause/seekbar somewhere? Thank you so much!

**Comment by AlexxIT** [comment]
#77
