### ISSUE TITLE
[Feature] Custom Card mode property connection order

### ISSUE THREAD

**Issue by gvillo** [AlexxIT/WebRTC#672]
I noticed that the custom card is always rendering MSE and then switching to RTC (with a black screen for a few ms), and I was wondering if we could respect the order that is given in the `mode` property to try to connect using that technology first and then connect with the following one

Example:

`mode: mse,webrtc,webrtc/tcp,hls,mjpeg`, will connect MSE first, if it fails it will fallback to webrtc and so on

Example 2:
`mode: webrtc,webrtc/tcp,mse,hls,mjpeg`, will connect webrtc first, if it fails it will fallback to webrtc/tcp and if it fails will try MSE and so on

In that case this will get rid of the black screen and I don't know if it's actually overloading my tablet when I display 6 cameras in a page (because too many connections maybe? I can't confirm that) but sometimes it's connecting all of them with RTC and sometimes some of them are just working with MSE (buffering). My network is not the issue, works ok in a notebook, PC, etc (besides that black screen when switching between MSE and RTC).

My config is:
`mode: webrtc, webrtc/tcp, mse` and it's always connecting with MSE and doing the switch to RTC after a second (with a black screen), looks like it's trying to connect to all of them in parallel and then switching to the best connection type.

**Comment by AlexxIT** [comment]
MSE will work anyway. There is no reason to use it with more priority than WebRTC.
https://github.com/AlexxIT/go2rtc/tree/master/api#javascript-api

I don't see the point of setting a manual priority.

Some tablets can play only few video on same page.

**Comment by gvillo** [comment]
Yeah @AlexxIT, it's not about how many videos a tablet can play. It's about the black blink that is doing, so that's why I cannot just set RTC to avoid that one second black screen (RTC is working on most of the scenarios, except when I am using my phone hotspot or in some WiFis). 

The actual behavior (if RTC is working) is: connects using MSE, and then switches to RTC. 

If RTC doesn't work, it just connects using MSE which is ok

**Comment by AlexxIT** [comment]
I don't understand. Is black screen constant or it shows during few seconds?

**Comment by gvillo** [comment]
@AlexxIT I recorded a video, basically it's the black blinking when the stream switches from MSE to RTC (I've refreshed the page a few times, sometimes it's very fast that you don't notice, and sometimes is really bad, specially if you have like 3 cameras on the same Home Assistant page, even for my Pixel 7 Pro)

Video: https://drive.google.com/file/d/1oHV-gwe64aTICj3iMsjsAIaKZOAFaYte/view?usp=sharing

**Comment by AlexxIT** [comment]
You can enable only webrtc mode without switching

**Comment by gvillo** [comment]
yeah, the issue of doing that, RTC is not working in some scenarios (ports forwarded correctly), such as `using mobile hotspot`, `some wifi networks using double nat`, etc, that's why I need both set.

**Comment by AlexxIT** [comment]
Well. Blinking while technology change is a "normal" behaviour...

**Comment by MrS4u** [comment]
> You can enable only webrtc mode without switching

Hello Alex, how to do this?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC?tab=readme-ov-file#custom-card
