### ISSUE TITLE
Stopped working after update to Unifi Protect 3.x.x

### ISSUE THREAD

**Issue by madAndroid** [AlexxIT/WebRTC#674]
Seems similar to: #305

Camera streams started failing directly after upgrade to Unifi Protect version: `3.0.22` from `2.x.x`

Camera stream in Home Assistant shows EOF:

<img width="508" alt="2024-03-28_08-05-57" src="https://github.com/AlexxIT/WebRTC/assets/1321437/1dc83752-28a2-42bd-bc96-5346572c5f0b">

I've enabled debug logging, but not much to go on there:

<img width="893" alt="2024-03-28_08-08-50" src="https://github.com/AlexxIT/WebRTC/assets/1321437/889bf948-e275-43b3-9d50-beaf8bf65e48">

**Comment by hunterdrayman** [comment]
Me too. 

Stream looks OK in go2rtc web interface but dash-cast call fails. HA log shows:

`This error originated from a custom integration.

Logger: custom_components.webrtc.utils
Source: custom_components/webrtc/utils.py:191
integration: WebRTC Camera (documentation, issues)
First occurred: 09:20:38 (4 occurrences)
Last logged: 09:22:26

Can't DashCast to ['media_player.den_display']
Traceback (most recent call last):
  File "/config/custom_components/webrtc/utils.py", line 191, in dash_cast
    entity.dashcast.load_url(url, force)
**TypeError: DashCastController.load_url() takes 2 positional arguments but 3 were given**

**Comment by AlexxIT** [comment]
DashCastController not related to this problem

**Comment by AlexxIT** [comment]
@madAndroid check issues in the go2rtc project. Or create new issue there
