### ISSUE TITLE
Screen is always on - WebRTC + Wallpanel

### ISSUE THREAD

**Issue by marcocunha** [AlexxIT/WebRTC#675]
Hi, I've configured go2rtc correctly and I'm using the WebRTC cards in one of my dashboards. I have this dashboard in a wall tablet loaded with WallPanel and I have Wallpanel configured to automatically turn on the screen when a face is detected and turn it off after 1 minute.

What I've noticed is that by using the 'custom:webrtc-camera' cards, the screen is always on. Do you have the same problem? I am sure it is due to this card because as soon as I remove it, everything works properly again.

Any idea why this is happening and how to fix it?

Thanks.

**Comment by AlexxIT** [comment]
This is browser / OS feature #613
