### ISSUE TITLE
Auto update poster image on change

### ISSUE THREAD

**Issue by Garulf** [AlexxIT/WebRTC#68]
Is there a way for the poster option to update and display the cameras stored proxy image ("/api/camera_proxy/camera.XXXX?token=XXXXXXXX")?

**Comment by Uriziel01** [comment]
Is this on a roadmap? What is necessary for this to happen?

**Comment by AlexxIT** [comment]
A lot of free time necessary for me. I have a lot of projects and this is only one of them.

**Comment by AlexxIT** [comment]
Check my new project. It has support default lovelace card
https://github.com/AlexxIT/go2rtc
