### ISSUE TITLE
Removed from HACS but still loads in browser?

### ISSUE THREAD

**Issue by jockebq** [AlexxIT/WebRTC#686]
I downloaded this custom component via HACS to test it out, but uninstalled it via HACS when I found another solution.

I still get this in my console when loading Home Assistant:
`GET
https://myurl.com/webrtc/webrtc-camera.js?v=v3.5.1

Loading module from "https://myurl.com/webrtc/webrtc-camera.js?v=v3.5.1" was blocked due to an illegal MIME type ("text/plain").

Loading failed for module with source “https://myurl.com/webrtc/webrtc-camera.js?v=v3.5.1”.

Uncaught (in promise) https://myurl.com/webrtc/webrtc-camera.js?v=v3.5.1`

How do I completely remove this custom component?

**Comment by AlexxIT** [comment]
Settings > Dashboards > Resources
http://xxxx:8123/config/lovelace/resources
