### ISSUE TITLE
Add support for LL-HLS

### ISSUE THREAD

**Issue by maxcanna** [AlexxIT/WebRTC#69]
Hi,
thank you for your great work. 

Could you please consider adding support for [LL-HLS](https://github.com/deepch/RTSPtoHLSLL)? It'd bring support for AAC audio and it'd be great!

**Comment by AlexxIT** [comment]
HLSLL requires mandatory HTTP2. I think it will be difficult to set up for many smart home users

**Comment by maxcanna** [comment]
Hey @AlexxIT could you please give me any feedback on this? 🙂 It could be a great tradeoff for who has AAC audio streams

**Comment by maxcanna** [comment]
@AlexxIT are you at least considering this? 🙂

**Comment by AlexxIT** [comment]
It's going to take a lot of work and tests. Definitely not going to be able to do it in the near future. I have a lot of other components.

**Comment by maxcanna** [comment]
oh ok 😞  TY for the custom component BTW 🙂

**Comment by felipecrs** [comment]
I don't know how this would relate, but there is:

https://www.home-assistant.io/integrations/stream/#ll-hls

**Comment by AlexxIT** [comment]
Check my new project. It can support AAC via realtime transcoding. WebRTC better than HLS in any situations.

https://github.com/AlexxIT/go2rtc
