### ISSUE TITLE
Question / Request: MultiStreamsMixer

### ISSUE THREAD

**Issue by RyanEwen** [AlexxIT/WebRTC#693]
I am streaming 4-6 cameras to a lovelace dashboard from wyze-bridge but the performance is pretty bad even just for 2+ cameras. 

I came across https://www.webrtc-experiment.com/MultiStreamsMixer/ which seems interesting and I was wondering if there's a way to use it with this integration, to stream a 2x2 camera grid, maybe with better performance?

Thoughts?

**Comment by AlexxIT** [comment]
You pointing to browser technology for mixing your local camera streams. Useless for your case.
You can mix streams on server via ffmpeg. But it will cost you a lot of server's resources.
