### ISSUE TITLE
how to hide 2 or more shortcuts ?

### ISSUE THREAD

**Issue by ArnolddeBolster** [AlexxIT/WebRTC#694]
Hi,

Maybe a dumb question: how can I hide 2 ore more shortcuts.

I managed to do 1 but syntax is wrong for hiding more

**Comment by AlexxIT** [comment]
I don't understand your question

**Comment by ArnolddeBolster** [comment]
What is the syntax for hiding both shortcuts (picture-in-picture and snapshot)
I sofar managed to hide one at the time.
The only shortcut I want to be left over is widescreen
![image](https://github.com/AlexxIT/WebRTC/assets/71195708/a1c9378a-743a-4b3e-8817-ba19f1f5f3b0)

**Comment by alvaromi** [comment]
just append the text below to the style entry:
.pictureinpicture {display: none} .screenshot {display: none}

**Comment by AlexxIT** [comment]
Thanks @alvaromi
