### ISSUE TITLE
Custom element doesn't exist: webrtc-camera

### ISSUE THREAD

**Issue by Scoff123** [AlexxIT/WebRTC#697]
Since updating HA Core to 2024.5.1 , I have started to see the message 'Custom element doesn't exist: webrtc-camera' when trying to play a camera stream on the dashboard on my Android Companion app. This has been working perfectly for months with my current setup, and still works correctly when viewing the camera stream on my dashboard on a web browser on PC or laptop. I enabled debug logging on the WebRTC integration, but the only error messages that are logged are:

```
2024-05-06 22:00:17.490 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from webrtc, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'webrtc' custom integration
```
```
2024-05-06 22:00:17.492 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] ServiceCallType was used from webrtc, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.ServiceCall instead, please report it to the author of the 'webrtc' custom integration
```

I am using the following card configuration on my dashboard:
```
type: picture-entity
entity: camera.front_doorbell_sub
name: Front Door
show_name: true
show_state: false
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Front Door
      timeout: 60000
      card_mod:
        style: |
          @media screen and (min-width: 1100px) {
            ha-dialog {
              --mdc-dialog-min-width: 1000px !important;
              --mdc-dialog-max-width: 1000px !important;
            }
          .content {
            width: auto !important;
          }
      content:
        type: custom:webrtc-camera
        mode: webrtc
        url: FrontDoorBell_sub
        style: ".mode {display: none}"
```

I have read through https://github.com/AlexxIT/WebRTC/issues/260 however it doesn't apply to my scenario, as I have been using this same setup for some time.

**Comment by milanov8** [comment]
I did it visa verca from this solution:
https://github.com/AlexxIT/WebRTC/issues/260#issuecomment-1537094770
removed the " v= " from "v=v3.5.2" and it worked for me.

**Comment by thekiwismarthome** [comment]
that worked for me as well
