### ISSUE TITLE
custom:webrtc-camera not available in Dashboards?

### ISSUE THREAD

**Issue by TimothyGaray** [AlexxIT/WebRTC#700]
webrtc-camera works great in the main lovelace screen but when I try to add it to a custom dashboard in Home Assistant, it complains that "custom:webrtc-camera" is not available.  If I scroll down in the list of available cards, WebRTC does not appear there.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/issues/260
