### ISSUE TITLE
Lock in persistent ptz

### ISSUE THREAD

**Issue by direx1** [AlexxIT/WebRTC#705]
Looking for a possible feature request to lock in the persistent option under ptz. Basically I'm using the same feed twice for my driveway and door but one card is zoomed in to my door. An option to lock this to prevent accidental swiping of the ptz would be great if possible. I previously tried using HA proxy but was unable to load the entity using mse or webrtc in this card. Thanks.

**Comment by AlexxIT** [comment]
I think this is same issue #714
