### ISSUE TITLE
HA Core 2025.5. Use homeassistant.core.ServiceCall instead, 'webrtc' custom integration

### ISSUE THREAD

**Issue by Walwol** [AlexxIT/WebRTC#706]
Logger: homeassistant.helpers.typing
Quelle: helpers/deprecation.py:206
Erstmals aufgetreten: 16:28:38 (2 Vorkommnisse)
Zuletzt protokolliert: 16:28:38

HomeAssistantType was used from webrtc, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'webrtc' custom integration
ServiceCallType was used from webrtc, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.ServiceCall instead, please report it to the author of the 'webrtc' custom integration

**Comment by szaman-89** [comment]
@Walwol Temporary you can edit __init__.py file with:

Line 22 from:
`from homeassistant.helpers.typing import HomeAssistantType, ConfigType, ServiceCallType`
to:
`from homeassistant.helpers.typing import ConfigType
from homeassistant.core import HomeAssistant, ServiceCall`

and rename all phrases  'HomeAssistantType' to 'HomeAssistant' and 'ServiceCallType' to: ServiceCall

It works in mycase.

**Comment by AlexxIT** [comment]
#692
