### ISSUE TITLE
No audio with Reolink E1 Pro camera

### ISSUE THREAD

**Issue by Jonny-T-cyber** [AlexxIT/WebRTC#708]
Hi,
I've tried every way but I don't get audio with my **Reolink E1 Pro** camera and **Onvif**.
Now I've instantiated another card with an elementary configuration:

```
type: custom:webrtc-camera
entity: camera.onvif_reolink_e1_pro_profile000_mainstream
```
I would like to ask 2 questions:

1. How can I enable the audio from camera?
2. Is there also the possibility of enabling 2-way audio via microphone to camera?

Thanks

**Comment by AlexxIT** [comment]
1. https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#codecs-madness
2. https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#two-way-audio
