### ISSUE TITLE
Is it possible to boost volume when sending audio files?

### ISSUE THREAD

**Issue by borgqueenx** [AlexxIT/WebRTC#709]
I am wondering if it is possible to amplify volume when sending audio files to media players created in configuration.yaml using the webrtc integration?
on quite some cameras, the volume is extremely low. i would like to artifically increase the volume to see if the sound is then acceptable.

I could make different volume mp3 files but this is also not great.

**Comment by AlexxIT** [comment]
This is wrong place for your issue. You can create feature request in the go2rtc repo. There is no such option at this time.
