### ISSUE TITLE
ERROR. NotSupportedErrror: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="hvc1.016000") is unsupported.

### ISSUE THREAD

**Issue by porok** [AlexxIT/WebRTC#71]
Getting an error on one of my camera.
ERROR. NotSupportedErrror: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="hvc1.016000") is unsupported.
Stream is accesible on PC via VLC.

<img width="687" alt="screenshot1" src="https://user-images.githubusercontent.com/6577215/119393796-17049200-bcda-11eb-8559-0e0c950ee7ce.png">
<img width="823" alt="screenshot2" src="https://user-images.githubusercontent.com/6577215/119393806-1bc94600-bcda-11eb-832b-c9b841ead8cd.png">

**Comment by AlexxIT** [comment]
hvc1 it is H265. Maybe supported only on Mac in Safari with enabled advanced option

**Comment by porok** [comment]
> hvc1 it is H265. Maybe supported only on Mac in Safari with enabled advanced option

But camera link says that stream is .h264 (second screenshot). 
Why HA want to give a H265 stream?

**Comment by porok** [comment]
This is only for this cam yi dome guard (with hack), if you have the same issue, try to read here:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/10

**Comment by porok** [comment]
This is only for this cam yi dome guard (with hack), if you have the same issue, try to read here:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/10

**Comment by pergolafabio** [comment]
I have the same issue , and sometimes it's gone after a minute, then I can see it, mine are h264, also exposed RTSP stream coming from Synology

Is this fixed?

**Comment by kdober** [comment]
Hi
I'm having a similar error on with my Reolink RLC 822. The main stream is supposed to be H265 and I'm getting the error ....codecs=hvc1.215, mp4a.40.2 is unsupported.
I'm not sure understand the previous msgs. Is this a limitation of the WebRTC? or something missing on my installation or my pc to decode that video stream?

Thanks

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/Blog/issues/5

**Comment by kdober** [comment]
Thanks :)
