### ISSUE TITLE
Trying to get Unifi cams rtsps to work with webrtc - how?

### ISSUE THREAD

**Issue by fribse** [AlexxIT/WebRTC#710]
Hi All

I've gotten my unifi cams integrated to Home Assistant lovelace by using the rtsp stream instead of the rtsps stream.
I would like to use only rtsps, but when I try to configure that, it just says 'loading'.

The Unifi Protect is v4.0.33

I've tried experimenting with gortc to test the streams, but so far no luck with rtsps...

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-rtsp

**Comment by fribse** [comment]
Thankyou @AlexxIT, the rtspx worked perfectly!
