### ISSUE TITLE
Question: infrequent but mostly slow to respond with image in HA card, missing something?

### ISSUE THREAD

**Issue by vingerha** [AlexxIT/WebRTC#711]
Hi, my setup has go2rtc docker on synology which feeds the camera streams to 
- Syno Videostation
- a tablet (wallpanel running HA)
- a page on my HA dashboard (when opened)
the rtsp itself works rather fast when e.g. using VLC but the dashboard page shows the card often (well over 50%) black and then loads in 1.5 - 2s. The tablet is a bit slower but that is probably due to network challenges.
After the first load, when paging between tabs it is OK but after refresh (or longer absence of use) the response is not really good.
One may argue that this is not bad but I have a few use-cases where I need it 'faster' 
What is your take on it or any way how to improve the HA side of things?

**Comment by AlexxIT** [comment]
The start time of a stream depends on a large number of different reasons. You cannot influence it.
Just waiting for this to be fixed in the future. For now, it's not a priority.
