### ISSUE TITLE
[Feature request] Support for Frigate cameras

### ISSUE THREAD

**Issue by Ulrar** [AlexxIT/WebRTC#72]
Hi,

This works very well (appart from some stuttering / rubberbanding sometimes), especially with a TURN server, thanks for your work !
One improvement though would be support for [Frigate](https://github.com/blakeblackshear/frigate)'s camera entities, as they don't seem to work currently. I had to add my camera a second time as RTSP using the generic platform under a separate name, not a huge deal but since Frigate is already streaming it constantly it would be great to just re-use the stream from there instead of connecting to the cameras twice. Might not be possible, not sure how Frigate re-exposes the camera to HA in practice though.

Thanks !

**Comment by AlexxIT** [comment]
As I can see, frigate integration uses RTMP stream

https://github.com/blakeblackshear/frigate-hass-integration/blob/master/custom_components/frigate/camera.py#L53

**Comment by Se7enair** [comment]
Yes, frigate restreams via rtmp.
But this would be a nice feature, because frigate is able to keep only one connection to the camera, and restream it multiple times via rtmp without any cpu load.

**Comment by stripeyhorse** [comment]
personally i just exposed the direct stream from the camera to HA.. sure i have 2 camera streams but only 1 is used for webRTC (the direct one). working perfectly with UniFi cameras.

**Comment by UmbraMalison** [comment]
@AlexxIT  - came here looking for exactly this. The ticket could be 

"[Feature request] Support for RTMP cameras"

this would enable those using Frigate NVR to use your component in HA without additional connections to each camera. This is particularly useful in my setup where my cameras are isolated with Frigate being the "gateway". 

I'll have to hack something else up to try your component out, which I'm super keen to do!

**Comment by quenthal** [comment]
Very intrested on this as well!

**Comment by mshamash** [comment]
Would be interested in this as well!

**Comment by drinfernoo** [comment]
I found this linked from the Frigate integration's GitHub today: https://github.com/dermotduffy/frigate-hass-card

Working well so far 😁

**Comment by UmbraMalison** [comment]
@drinfernoo - That's a good hint, but the webrtc support in frigate-hass-card requires webrtc entity (this component) which as it does not support RTMP, only RTSP, means you need still need to be talking directly to the cameras instead of using frigate.

in my network setup, this would significantly reduce routing intervlan vlan traffic, and also reduce the load on each camera.

**Comment by oramirite** [comment]
Yeah, what is the point of the WebRTC support on those Frigate cards? They imply that it works and it simply does not :/

**Comment by quenthal** [comment]
Does this give any help for rtmp and frigate camera support?

https://pkg.go.dev/github.com/pion/example-webrtc-applications/v3/rtmp-to-webrtc

**Comment by AlexxIT** [comment]
Check my new project. It has support RTMP
https://github.com/AlexxIT/go2rtc
