### ISSUE TITLE
Disable MSE while casting to Android TV

### ISSUE THREAD

**Issue by MrS4u** [AlexxIT/WebRTC#720]
I am using WebRTC to cast camera feed to my android TV.
-Is there a way to disable MSE (longer loading, and afterwards it switches to RTC after all)
-Is there a way to remove mode watermark (MSE, RTC)

Thanks for any help!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/wiki/Cast-or-share-camera-stream#dashcast
