### ISSUE TITLE
Running WebRTC with built in go2rtc inside Home Assistant Docker cannot find `go2rtc.yaml` config.

### ISSUE THREAD

**Issue by Ionshard** [AlexxIT/WebRTC#721]
I am running home assistant via the `linuxserver` docker image. I installed the WebRTC integration and when installing it prompted for a username and password and then created a file inside my homeassistant config directory (`/config/go2rtc.yml` inside the container) and populated it with the username and password for the `api` and `rtsp`. I then added some streams to the config.

However, when I visit the API portal (on port `1984`) it is unauthenticated and it seems to be attempting to read the config from `/run/s6-rc:s6-rc-init:cddgjJ/servicedirs/svc-homeassistant/go2rtc.yaml` (inside the container)

This appears to be the exact same issue discussed in #589 however it seems like it was incorrectly identified to be an issue with Frigate. However I am not running Frigate at all and I still have the exact same issue. I am **ONLY** running `go2rtc` via WebRTC inside the `homeassistant` docker container which is running via `host` networking.

![image](https://github.com/AlexxIT/WebRTC/assets/86419/8e09007a-c9fa-45e5-b618-18d3d112b76b)

Is there some way I can configure `go2rtc` to run with the correct configuration file?

P.S. I definitely could solve this by running `go2rtc` as it's own docker service ... however I only have a single doorbell camera, so I would really prefer to keep the simple install.

**Comment by AlexxIT** [comment]
Why you not using official Hass docker image? I don't have plans for support 3rd party images.
You'd be better off using go2rtc in a separate container to solve the problem

**Comment by Ionshard** [comment]
> Why you not using official Hass docker image? I don't have plans for support 3rd party images.
> You'd be better off using go2rtc in a separate container to solve the problem

That's fair, it was more a request to support allowing us to configure it rather than supporting the 3rd party image directly. I run the 3rd party image because my HA setup was a very old setup.

That said, it is a very rare edge case and it's very understandable that you wouldn't want to support it. Furthermore I myself no longer even run the linuxserver image and have since moved my setup over to the HomeAssistant OS on a NUC in order to explore using Frigate. 

So feel free to close this issue and thank you for your time!

**Comment by AlexxIT** [comment]
By default go2rtc will search config in the current work dir. For default Hass image and go2rtc image - it's `/config`.

**Comment by xdaniel9** [comment]
> By default go2rtc will search config in the current work dir. For default Hass image and go2rtc image - it's `/config`.

I have the same problem, only one go2rtc instance running and it's the one inside the container of ha, with webrtc camera installed
```
$ ps -ef | rg go2rtc
daniel  1043925 1043872  1 11:03 ?        00:00:00 /config/go2rtc-1.9.4
daniel  1044102  875795  0 11:04 pts/0    00:00:00 rg go2rtc
```

and `go2rtc.yaml` is in the same directory
```
$ ls -l | rg go2rtc
.rwxr--r-- daniel daniel 5.3M 2024-12-06 09:11 go2rtc-1.9.4
.rw-r--r-- daniel daniel  84B 2024-12-06 10:44 go2rtc.yaml
```

however the config is not used at all
![ss](https://github.com/user-attachments/assets/7d6ba750-4077-4fc1-86bc-86a380b01ca7)

**Comment by AlexxIT** [comment]
I think you using not original Hass docker image.
