### ISSUE TITLE
WebRTC green Box ONLY on IOS version

### ISSUE THREAD

**Issue by Basti256** [AlexxIT/WebRTC#726]
I am writing here since I am currently unable to fix this specific error that appears here. This is the first time I am writing a bug report, if I need to attach more Informations from somewhere, please feel free to ask.

Description:
I am using WebRTC to stream from a cheap 4k Camera (Simicam 4k Camera from AliExpress). The camera stream is injected to Home Assistant as Generic Camera as rtsp Stream and testwise directly to WebRTC by using the RTSP url.

When I open the Stream on my PC through the web Browser (I tried Microsoft Edge, Chrome and Opera) the stream just looks perfectly fine:
Screenshot 1:
![image](https://github.com/AlexxIT/WebRTC/assets/96210479/e60c3819-d9d1-4322-9e32-576210a3b32d)

Configuration (left stream): 

```
type: custom:webrtc-camera
entity: camera.kamera_aussen_stream_1
```

Configuration (right stream):
```
type: custom:webrtc-camera
url: rtsp://username:password@192.local.ip.adress/stream1
```

When I open the Stream thorugh the newest available Home Assistant Ios app, the Stream look weird and gets som kind of green border, attached you'll see my screenshot (same page, same code configuration):
![IMG_1087](https://github.com/AlexxIT/WebRTC/assets/96210479/8eebc4d5-5160-44b9-91c6-e875a933b026)

Any Idea what could be the cause for this, or any ideas how I could Investigate here?

Best regards from Germany :)

**Comment by Basti256** [comment]
> There are probably some kind of stream issues. I need access to the streams to investigate the problem. https://github.com/AlexxIT/go2rtc/wiki/Tunnel-RTSP-camera-to-Intenet You can find my contacts on my github profile.

Thanks for your very quick answer. 
Unfortunately I think i am unable to provide such kind of access here since this instance is currently only running locally without a permanent Internet connection. Is there any other way how I could provide additional informations?

**Comment by Basti256** [comment]
Maybe I can provide something from myself:
I've opened the Stream via VLC and these are the Codec and Statistic Informations which were provided so far:
Statistics:
![image](https://github.com/AlexxIT/WebRTC/assets/96210479/d38b7233-2c17-4cec-8e21-e8b7a64ab38c)
Codec:
![image](https://github.com/AlexxIT/WebRTC/assets/96210479/38899b44-a161-49ae-9158-65a2e9e8b490)

I still look forward for any support from you @AlexxIT and of course the rest of the community. :)

**Comment by AlexxIT** [comment]
Most likely the developers of a cheap no-name camera made mistakes when implementing the h265 codec. This is a very common situation.

There's a small chance I can fix it. But without access to the stream, it's impossible.

**Comment by Basti256** [comment]
> Most likely the developers of a cheap no-name camera made mistakes when implementing the h265 codec. This is a very common situation.
> 
> There's a small chance I can fix it. But without access to the stream, it's impossible.

Okay, then I have another Idea... I've got the same camera at home. I will grant you access the way you described and forward these informations to you. then you can have access the camera for around 1 week without any problems.

**Comment by douglas-srs** [comment]
I am also facing this issue, any news on this? 😅

**Comment by AlexxIT** [comment]
Nothing changed. Without access to stream can't help.

**Comment by douglas-srs** [comment]
I can give you access to my HA, how can we proceed? Where should I send you the login details?

**Comment by AlexxIT** [comment]
Your can find contact info in the GitHub profile

**Comment by AlexxIT** [comment]
Thanks to @douglas-srs for help with debugging. The problem as usual with wrong RTSP realisation from cheap cameras.
Solution described in readme: https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-rtsp

```
If the stream from your camera is glitchy, try using ffmpeg source.
```

Camera doesn't send codec params in SDP. So go2rtc should use random ones. This works fine for all modern browser. Problem only with Safari.

```
v=0
o=- 1109162014219182 0 IN IP4 0.0.0.0
s=HIK Media Server V4.71.111
i=HIK Media Server Session Description : standard
e=NONE
c=IN IP4 0.0.0.0
t=0 0
a=control:*
b=AS:2058
a=range:npt=now-
m=video 0 RTP/AVP 96
i=Video Media
a=rtpmap:96 H265/90000
a=control:trackID=video
b=AS:2048
m=audio 0 RTP/AVP 0
i=Audio Media
a=rtpmap:0 PCMU/8000
a=control:trackID=audio
b=AS:10
a=Media_header:MEDIAINFO=494D4B48020100000400050010710110401F000000FA000000000000000000000000000000000000;
a=appversion:1.0
```
