### ISSUE TITLE
Non-Issue / Question : Are WebRTC streams securely authenticated ?

### ISSUE THREAD

**Issue by PaleoW** [AlexxIT/WebRTC#728]
Hi !

This is more a question than an issue. I couldn't find a clear answer in the documentation. 

Are WebRTC streams secure, or could someone hit the public endpoint of go2rtc and be able to capture the streams ?

I am running go2rtc as an Home Assistant addon, and I've forwarded the WebRTC listen port on my firewall, but I'm now worried this could potentially mean I'm now streaming publically. 

Thanks in advance for any clarifications on that matter !

**Comment by AlexxIT** [comment]
If you talking about 8555 port, no one can use it for any purpose. It's just media data transfer port.
The connection is established via Hass API and protected by Hass auth (multi-factor if you set it).
