### ISSUE TITLE
Missing Custom Card

### ISSUE THREAD

**Issue by bjaurelio** [AlexxIT/WebRTC#729]
I installed WebRTC via HACS, restarted HA, and added the integration, but I do not have the option for a custom card for WebRTC when I go to add a card in my dashboard. I even tried adding it manually, and I receive the following error:

"Configuration errors detected:
Custom element not found: webrtc-camera" 

I have tried multiple restarts of HA as well as deleting and re-adding the WebRTC integration. The custom card will not appear. My log contains no mention of WebRTC.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/issues/260
