### ISSUE TITLE
FR: Merge multiple RTSP cameras into one WebRTC stream

### ISSUE THREAD

**Issue by scstraus** [AlexxIT/WebRTC#73]
Hi,

A lot of people, including myself, are bumping up against the limits of how many WebRTC sessions we can have going in a single browser window. One thing that would really make this the "ultimate" camera option for hass would be if we could somehow merge those camera stream into one WebRTC stream. I think this would alleviate most of the issues people have about displaying multiple cameras. A google search returned this as a starting point:
https://stackoverflow.com/questions/59320085/record-multiple-rtsp-streams-into-a-single-file#59324096
What do you think?

**Comment by AlexxIT** [comment]
I think it may be big CPU overhead on server. I prefer to make an online video on demand.
But if someone makes an addon that merges together the video and outputs RTSP - it can be connected to WebRTC component.

**Comment by scstraus** [comment]
Problem with 1 WebRTC stream per camera is that there will always be a hard limit to how many you can display on an endpoint (for me it's 3-4). A single stream would solve that. Unfortunately I've found nothing that can easily merge streams yet.

If there's no chance to implement it, you can close it.

**Comment by duy-nv** [comment]
I'm facing with the same problem. 
Have you found the way to merge multi merge multi webrtc stream into one from server? @scstraus

**Comment by scstraus** [comment]
No not really. Nothing easy enough for me to implement quickly at least.

**Comment by RyanEwen** [comment]
I'm extremely interested in this as well. I actually have no issue streaming 4 at once but when doing so to a Chromecast Ultimate, the frame rate drops into the single digits and sometimes the hardware overheats as locks up. Heh.

I'm trying to find a docker-based solution to combining 4 RTSP streams into 1. If I come up with something I'll report back. Please do the same.

**Comment by ahmadnbl** [comment]
Hi, I found the same concept on this docker project
https://hub.docker.com/r/migoller/live555proxyserverdocker
I think we can do like what it implement

**Comment by scstraus** [comment]
> Hi, I found the same concept on this docker project https://hub.docker.com/r/migoller/live555proxyserverdocker I think we can do like what it implement

This won't merge the streams into a single stream, it just proxies them so that multiple endpoints can access the stream without opening individual streams to the original source. I actually use it in my camera setup.

**Comment by whinis** [comment]
https://github.com/aler9/rtsp-simple-server This is used by frigate to proxy streams out and it has an HTTP api to switch the streams. This may be what is needed

**Comment by AlexxIT** [comment]
Check my new project. It has integration with ffmpeg:
https://github.com/AlexxIT/go2rtc

And ffmpeg can join multiple streams to one output:
https://trac.ffmpeg.org/wiki/Create%20a%20mosaic%20out%20of%20several%20input%20videos%20using%20xstack

Unfortunately, I don't have the time to make the right command myself.

**Comment by whinis** [comment]
I think the goal is less mosaic and more a switchable output but only 1 stream

**Comment by AlexxIT** [comment]
Well. You may create different Hass tabs and switch them. So only one stream will be simultaneously.

**Comment by scstraus** [comment]
Thanks AlexIT. The FFMPEG option may work for me. It is indeed a mosaic I need as I want to watch 4 streams on my Fire tablets around the house but they aren't strong enough to open 4 WebRTC cards at once. I think one big one with all 4 streams will be better. I don't want to switch between them, that would be worse than the FFMPEG streams that already work. Thanks

**Comment by AlexxIT** [comment]
Could you provide working command when you get it? I'll add it to docs :)

**Comment by scstraus** [comment]
I'll be honest, it's a bit of a big job so I'm not sure I will get to it very soon as I'm still working okay with my ffmpeg camera approach, despite acknowledging that this solution is likely superior in many ways.

**Comment by RyanEwen** [comment]
I'm very interested in this idea. If someone manages to get it working please share

**Comment by iscofield** [comment]
Also interested in doing this as well to have a babycam with two streams merged.  It looks like the above solution though only deals with video?  I'm using Frigate and trying to have a view of both rooms with audio playing simultaneously for both, but it appears that's not possible.

Found a similar thread of someone trying to do the same: https://old.reddit.com/r/frigate_nvr/comments/1el4mw7/014_live_view_as_babycam/
