### ISSUE TITLE
Rename "service" to "action"?

### ISSUE THREAD

**Issue by g1za** [AlexxIT/WebRTC#736]
Following HA 2024.8 release and renaming of "services" into "actions", should "service" be replaced by "action" for consistency with the new configuration?

At the moment if I replace "service" with "action" in my code, the PTZ control is not displayed, while HA shows the same invoked service as an action now.

https://github.com/AlexxIT/WebRTC/wiki/PTZ-Config-Examples

Thanks

Ref: https://www.home-assistant.io/blog/2024/08/07/release-20248/#goodbye-service-calls-hello-actions-

**Comment by AlexxIT** [comment]
This project has not migrated to the new logic and there are no plans to do so in the near future. The project should support older versions of Hass as much as possible.

**Comment by g1za** [comment]
Sure.
Thank you
