### ISSUE TITLE
Custom Card no Audio

### ISSUE THREAD

**Issue by tovdave** [AlexxIT/WebRTC#737]
Hello, 

I have a eufy tilt and pan camera, I have set up go2rtc and can access the camera stream including audio there. If I add a generic camera integration I have picture and sound. But if I add a custom card I only see the picture and have no sound. I also tried running it via ffmpeg but that didn't work either.

**Comment by AlexxIT** [comment]
You should:
- check camera's audio codec (for example in the go2rtc WebUI)
- check viewing technology (also named mode in this custom card
- compare results with this table https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#codecs-madness

**Comment by tovdave** [comment]
THX with MSE MODE it works very fine now thx.
Is there a way to change position for the fullscreen button?
I have tried some things but for me it was ony possible to change the position of the record button and not the UI Position.

**Comment by AlexxIT** [comment]
You can change UI via `styles` param. You should know CSS or ask someone who knows it.
