### ISSUE TITLE
[Feature request] Ability to use camera in automatisation

### ISSUE THREAD

**Issue by zuzuman** [AlexxIT/WebRTC#74]
In general:
My camera's audio codec is pcm_mulaw. So only with this integration I can get audio working. 
I have a lot of automatisations (ex. video record on movement) and it will be super cool to be able to use somehow record stream with audio.

**Comment by AlexxIT** [comment]
ffmpeg can handle any audio codec

**Comment by zuzuman** [comment]
> ffmpeg can handle any audio codec

Was not able to integrate my camera. Home Assistant service "camera.record" accepting only AAC codec, or I'm wrong?

**Comment by AlexxIT** [comment]
Should be fixed in v3
