### ISSUE TITLE
PTZ controls per stream

### ISSUE THREAD

**Issue by didster** [AlexxIT/WebRTC#749]
I'm trying to figure out the best way to have multiple cameras shown on a dashboard using WebRTC card.  Obviously multiple cards works fine but takes a lot of space.  I tried using swiper-card to host the cards within a single swiper element and that sort of works but the PTZ controls don't work within the swiper and more importantly 50% of the time the swiper doesn't even load.  Since that card seems abandoned not updated since 2022 I am looking for alternatives.

Using a single WebRTC card with each camera as a defined stream works great.  But my trouble now is all the cameras have PTZ enabled within the card and that config is global to the card itself, not per stream, so I can only configure one of the three cameras PTZ controls to work.  Is it possible to either:

a) Some how get the active stream name from the configuration so I can pass this to a script and use it to trigger the correct PTZ action
b) Configure PTZ controls in place per-stream?

Thanks

**Comment by AlexxIT** [comment]
I don't like the idea of complicating the logic of this card with linking PTZ settings to streams.
Better look for some custom card that can switch multiple WebRTC cards in one place.

**Comment by didster** [comment]
Understood. I have tried several and none of them work very well sadly. They either block the ptz controls all together or in the case of custom swipe card seem so buggy and don't load half the time.
But I understand your decision.
Could you just confirm for me if there is any way at all I could get the active stream name in yaml in a way I could pass it to a service?

**Comment by AlexxIT** [comment]
I'll think about what I can do

**Comment by didster** [comment]
Ok thank you!

One idea might be to add configuration for a helper name to the stream section

`stream_storage: my_helper`

And when given, have the card write to that helper the name of the stream when it changes.  Then the helper name could then be easily passed to a script and read from there.  As an added bonus it could also be used so the card itself could automatically switch to the last active stream when reloaded.

Just a thought
