### ISSUE TITLE
WARNING: Function will be removed in 2025.7 

### ISSUE THREAD

**Issue by garfield1964** [AlexxIT/WebRTC#754]
Got this warning this morning:

Detected that custom integration 'webrtc' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/webrtc/embed", "/config/custom_components/webrtc/www/embed.html", True)])`; This function will be removed in 2025.7 at custom_components/webrtc/__init__.py, line 74: hass.http.register_static_path("/webrtc/embed", str(path / "embed.html")), please create a bug report at https://github.com/AlexxIT/WebRTC/issues

**Comment by AlexxIT** [comment]
#722
