### ISSUE TITLE
WebRTC always muted by default on iphone?

### ISSUE THREAD

**Issue by totalitarian** [AlexxIT/WebRTC#756]
Just noticed that the audio is always muted on my iPhone using the following. Is this a known issue?

```
type: custom:webrtc-camera
url: doorbell
mode: webrtc

```

**Comment by AlexxIT** [comment]
This article not about Safari. But every browser has crazy policy for autoplay video with audio.
https://developer.chrome.com/blog/autoplay?hl=en

Safari also has crazy policy for autoplay webrtc video.
https://developer.apple.com/documentation/webkit/delivering_video_content_for_safari/
