### ISSUE TITLE
WebRTC in macOS Desktop Companion App

### ISSUE THREAD

**Issue by wojciechpolak** [AlexxIT/WebRTC#76]
Hi, WebRTC Camera works perfectly fine for me when viewing HA in a browser, but it doesn't work in Home Assistant Companion App for MacOS Desktop: https://apps.apple.com/us/app/home-assistant/id1099568401
I'm using version 2021.5 (2021.150).

(I also checked the mobile companion app on iOS, but it also works just fine)

Is it a bug or a known issue with the desktop app? If the latter, then please update README/FAQ about it. Thanks!

**Comment by errandwolfe** [comment]
Same issue, using Home Assistant Companion 2021.6 (2021.158).  Have verified that it is connecting with the local URL.  Not sure if this would be an issue in the WebRTC or an issue on the HAC app, but google search brought me here, so here I post.  Works perfectly in browsers and in iOS itself.

**Comment by AlexxIT** [comment]
Sorry. The macOS application does not support WebRTC and MSE.

**Comment by wojciechpolak** [comment]
Wow, that was one of the most impressive responses I've ever seen for a submitted issue. Waiting the whole 60 days for it was worth everything. Very detailed description, explanation, and so on. Thank you very much!

But seriously, you could at least mention about this limitation (any why) in the README/FAQ, no?

**Comment by AlexxIT** [comment]
I only discovered this yesterday while researching your issue. And spent more than an hour looking for the problem.
