### ISSUE TITLE
Telegram bot action: Send photo - Can't send file with kwargs

### ISSUE THREAD

**Issue by tOOmki** [AlexxIT/WebRTC#764]
I try to send a screenshot using the Telegram bot action: Send photo.
Every time in the HA logs I have:
```
Can't send file with kwargs: {'authentication': 'digest', 'parse_mode': 'html', 'url': 'http://192.168.1.228:1984/api/frame.jpeg?src=camera.garaz_brama_profile000_mainstream'}
Can't send file with kwargs: {'url': 'http://192.168.1.228:1984/api/frame.jpeg?src=camera.garaz_brama_profile000_mainstream'}
Can't send file with kwargs: {'url': 'http://192.168.1.228:1984/api/frame.jpeg?src=camera.garaz_brama_profile000_mainstream', 'authentication': 'bearer_token'}
```
I tried frame.mp4 and frame.jpeg - no difference.

Camera Reolink E1 Pro

**Comment by AlexxIT** [comment]
Are you sure you has this camera in the go2rtc config?

**Comment by tOOmki** [comment]
![obraz](https://github.com/user-attachments/assets/32547076-cef5-45b3-9033-71abd0ebb485)

**Comment by AlexxIT** [comment]
Maybe your Hass can't get this url, but your browser can

**Comment by tOOmki** [comment]
Camera preview in the tab works.

**Comment by AlexxIT** [comment]
Don't understand what you mean

**Comment by tOOmki** [comment]
I mean that the camera preview works on the tab.
What did you mean: "Hass can't get this url"?

**Comment by AlexxIT** [comment]
Perhaps Hass can't get this URL: `http://192.168.1.228:1984/api/frame.jpeg?src=camera.garaz_brama_profile000_mainstream`.
Or you are writing the service call incorrectly.

**Comment by tOOmki** [comment]
Onwif integration helped.
Sending a photo directly to Telegram doesn't work either.
That's why I save the snapshot to disk and then send it.
