### ISSUE TITLE
WEBRTC Camera not working after latest go2rtc update

### ISSUE THREAD

**Issue by bkr1969** [AlexxIT/WebRTC#766]
Just updated to go2rtc 1.9.5 and none of my rtsp feeds work now.  Just stuck on "Loading..."

**Comment by RIKWEBB** [comment]
> Just updated to go2rtc 1.9.5 and none of my rtsp feeds work now. Just stuck on "Loading..."

Same here...

**Comment by vk2him** [comment]
Same here - I get the following error in logs

```
Logger: homeassistant.components.camera
Source: components/camera/__init__.py:937
integration: Camera (documentation, issues)
First occurred: 11:44:02 AM (1 occurrences)
Last logged: 11:44:02 AM

Error handling WebRTC offer: Timeout talking to RTSPtoWebRTC server
```

Here's one of the cards that fail:

```
type: custom:webrtc-camera
url: rtsp://192.168.1.121:554/s0
mode: webrtc
muted: true
ui: true
```

**Comment by Vegas3T** [comment]
Same

**Comment by PhilippFelber** [comment]
Same error on my side. After update of go2rtc 1.9.5 there is no connection to any devices.

**Comment by barackca1** [comment]
Same here

**Comment by ChipMIK1** [comment]
Ditto

**Comment by vkogan2005** [comment]
Same here

**Comment by odolmach3** [comment]
Same...

**Comment by andker87** [comment]
same here, back to 1.9.4 is working fine

**Comment by bkr1969** [comment]
> same here, back to 1.9.4 is working fine

How did you roll back? I can’t seem to find a link to 1.9.4

**Comment by andker87** [comment]
> > same here, back to 1.9.4 is working fine
> 
> How did you roll back? I can’t seem to find a link to 1.9.4

I'm running it in docker, so the rollback was easy
`docker pull alexxit/go2rtc:1.9.4`
https://hub.docker.com/r/alexxit/go2rtc/tags

**Comment by Perimec** [comment]
Same here too

**Comment by Perimec** [comment]
I did restore from a backup and that solved the issue to restore the an older version

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.6

**Comment by SyrSkies** [comment]
> https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.6

really appreciate your work and effort!

**Comment by RIKWEBB** [comment]
Excellent  - confirmed v1.9.6 is working after update
