### ISSUE TITLE
FR: Camera entity that will dashcast url

### ISSUE THREAD

**Issue by amosyuen** [AlexxIT/WebRTC#770]
Thanks for great integration, I find that dashcast is vastly superior than the normal HA behavior for playing a camera.

I'm a big user of Google home and google assistant to integrate voice commands. One nice feature is to be able to expose camera entities to google assistant and make a voice command like [play baby camera] and have the stream play on the correct device.

I think it would be great if there was a configurable camera entity that users can configure with a url, and it could dashcast the url instead of using HA's default way of playing an HLS stream. Unsure how feasible this is.

**Comment by AlexxIT** [comment]
Your request not related to this integration.
It's related to this core integration https://www.home-assistant.io/integrations/google_assistant/
It's probably using the HLS format now. But Google Home is able to support the WebRTC protocol.
I don't have expertise in Google's API. To me, they are incredibly complex and confusing.

Perhaps in the future this will be possible. Considering that WebRTC is added to HA in the latest release
https://www.home-assistant.io/blog/2024/11/06/release-202411/
