### ISSUE TITLE
mse: streams: wrong response on DESCRIBE

### ISSUE THREAD

**Issue by mario-rossi78** [AlexxIT/WebRTC#776]
Hi, I have a Tapo C200 cam that I use in HA with "Tapo: camera control integration". I would like to try the webRTC integration and I think I've been set it right, but It doesn't work. 

![image](https://github.com/user-attachments/assets/a635a324-a5ef-4772-aa2c-8e02b00de829)

I also try to change user:pass with the username and the password of my Tapo account, but it doesn't work.
I already check the issues but I didn't find any solution.
Can someone help me?

Tnx

**Comment by AlexxIT** [comment]
Maybe your camera overloaded? You can check your rtsp link in desktop player, ex. VLC.

**Comment by mario-rossi78** [comment]
I tried without changing user:pass and changing it with TAPO_USER and TAPO_PASS. VLC says 

live555 error: Failed to connect with 
satip error: Failed to setup RTSP session

this are the VLC logs

[VLC log.log](https://github.com/user-attachments/files/17790341/VLC.log.log)

tnx

**Comment by AlexxIT** [comment]
Well. If VLC doesn't work for you - this integration won't work either. It is better to discuss your problem on the forums for your camera.
