### ISSUE TITLE
HA connection via Nabu Casa extremely unstable after adding WebRTC 

### ISSUE THREAD

**Issue by clandestine-avocado** [AlexxIT/WebRTC#78]
For about the last 24 hours, my external  connection via NC has been dropping in and out, after being rock solid since I started the service maybe a year ago. HA remains _locally_ accessible via IP. 

The only thing I changed was I added the WebRTC to help with poor camera streaming. WebRTC worked _pretty_ well, with almost zero lag (though I could not get streams displayed on Tablet running Fully Kiosk, but that's a separate issue.

Before I went to bed last night, I disabled WebRTC, and did not drop external access all night. Has anyone had similar a issue? When I would lose connections, I scoured the logs, but didn't see anything that jumped out of at me. I'd like to provide more helpful/diagnostic information, but unsure what else to do.

**Comment by AlexxIT** [comment]
This is know issue. NC limit external data. If WebRTC can connect to cameras with WebRTC protocol - such data will not be counted in NC traffic. But if WebRTC protocol won't work - component will use MSE protocol and this traffic will be counted.

Here was user with same problem

https://community.home-assistant.io/t/realtime-camera-streaming-without-any-delay-webrtc/258216

**Comment by clandestine-avocado** [comment]
Ok, thank you - I had read that, but assumed the integration just wouldn't work, rather than the NC external access dropping off. Can I assume that WebTRC was not working, so it defaulted to MSE, and limited out my NC external data limit? Or would setting `webrtc: false` help me out here?

**Comment by AlexxIT** [comment]
`mse: false` will helps you. You can't see stream remotely, but NC will work. Or check how to fix remote access to WebRTC protocol
https://github.com/AlexxIT/WebRTC#webrtc-external-access

**Comment by clandestine-avocado** [comment]
Ok, I finally had time yesterday to add the `mse: false` - but unfortunately, NC still drops off, same as it did without `mse: false`

I was going to give the "Medium tech way" a shot this morning, but unsure where to forward the UDP range, when you say "_forward this UDP port range on your router_"

Do I forward the UDP range to another range, or another single port? And does it matter what that/those destination ports are? Thanks!

**Comment by AlexxIT** [comment]
With `mse: false` option NC should not drops.

You should forward same port range as you set in integration options.
