### ISSUE TITLE
I cannot enable two-way audio on my sonoff camera

### ISSUE THREAD

**Issue by Narutojoy** [AlexxIT/WebRTC#784]
I want to enable two-way audio in my camera. It can achieve this function within its own application.My configuration is as follows
`type: custom:webrtc-camera
streams:
  - url: rtsp://rtsp:12345678@192.168.31.31:554/av_stream/ch0
mode: webrtc
media: microphone`
However, the web page reported an error, showing“webrtc/offer: streams: codecs not matched: H264, PCMA error”
My device is Raspberry Pi 4B, running the latest ha core and webrtc intergretion.
I have consulted a lot of information, but couldn't find a solution to my problem. Could you please help me? Thank you very much!

**Comment by AlexxIT** [comment]
Sonoff cameras don't support two way over open protocol standards.
