### ISSUE TITLE
How to add an entity for Tapo C120 camera to be able to add it to an automation setup in Home Assistant? 

### ISSUE THREAD

**Issue by susinths** [AlexxIT/WebRTC#786]
I've finally got sound on my Tapo C110 and C120 cams thanks to this fantastic project.
Now i wonder how i can setup an automation to capture video with sound and i am still missing an entity for the cams with sound.

Any help?

**Comment by AlexxIT** [comment]
You can use https://frigate.video/ project. Or you can use go2rtc addon. In both cases, you will need to set up transcoding the audio to AAC format. It is the only one supported in the records. And it is not in your camera by default.
And none of this is related to this project.
