### ISSUE TITLE
MSE Question

### ISSUE THREAD

**Issue by tunerooster** [AlexxIT/WebRTC#79]
I am running the `Allwiner-v2 yi-hack` on a `Xiaomi Mi Outdoor 1080p `camera.  I am running `Android Chrome` (actually `HA Companion` on Android which uses Chrome Webkit) on the client end, and version `2021.5.3 hass` server.  I can see from the video icon that I am connected via `WebRTC` (not MSE).

It is my understanding that this camera outputs only `AAC LC` audio.  It is also my understanding that WebRTC *does not* support AAC, but that MSE *does*.  Please correct me if I am mistaken.

My question is:

- How can I force it to connect via MSE (which should then provide audio) right?

I am not using `configuration.yaml` as, if I recall correctly, I just installed/configured using `HACS`.

Would/should I delete the integration and reinstall?  I.e., is there an option to select MSE in the installation procedure?

Please confirm that I should be able to get audio through this camera/browser combination.  Thanks a ton!

P.S., I could not find how to `tag` this as a *question* (since I am still new at this).

**Comment by weitheng** [comment]
Please refer here https://github.com/AlexxIT/WebRTC#config . Enter `webrtc: false` in the Lovelace card should force the video to be streamed over MSE

**Comment by AlexxIT** [comment]
@weitheng thanks

**Comment by tunerooster** [comment]
Thank you, I should have seen that!  I got confused thinking configuration.yaml was where I needed to set it.  My apologies and thanks again.

I am now having some issues the audio stream, but I will open a new issue when my testing is compete.  Still love this integration though!
