### ISSUE TITLE
Error during setup of component webrtc

### ISSUE THREAD

**Issue by olijouve** [AlexxIT/WebRTC#82]
Hi,

I used HACS to update component/card and it fail to setup with this error : 

`

Logger: homeassistant.setup
Source: custom_components/webrtc/__init__.py:77
First occurred: 15:21:22 (1 occurrences)
Last logged: 15:21:22
Error during setup of component webrtc

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 77, in async_setup
    version = hass.data['integrations'][DOMAIN].version
AttributeError: 'Integration' object has no attribute 'version'

`

Any Idea ?

**Comment by AlexxIT** [comment]
You using very old component version on very old Home Assistant version
