### ISSUE TITLE
Audio Muted by Default

### ISSUE THREAD

**Issue by tunerooster** [AlexxIT/WebRTC#83]
This may not be something WebRTC has any control over but...

In Android Home Assistant Companion (and in Google Chrome on Android), the WebRTC video which comes up is `muted by default`.

Why this matters:
- I am running a HA Dashboard (on the wall).
- When the front doorbell rings, I navigate to a WebRTC  live view of the front door.
- By speaking, I can initiate a dialog with the visitor, and would like to be able to hear their reply/replies without having to walk over to the dashboard to `unmute` the video.

_Does anyone have a suggestion/solution for this?_

Thanks for any help!

**Comment by tunerooster** [comment]
Yikes!  I don't know how I missed it.  The `muted` flag does exactly what I am asking for.  My apologies for missing it before posting.

Great work!  ...and thanks!

**Comment by tunerooster** [comment]
Ah!  I remember...

When I read it originally, it said `muted: false` was the default.  So I assumed that it was a browser thing...

I checked, and even though it says `muted: false` is the default, unless it is specifically set to `false` in the lovelace card config, it defaults to `muted: true`.  So it may be a bug that the code is not really defaulting to false.

**Comment by tunerooster** [comment]
I think I am not paying attention...

I am wrong, the default _IS_ `muted: true`.  I was misreading the "full" example and assumed the values specified were the defaults.  My bad...

**Comment by idoaflalo** [comment]
This is the funniest thing I ever read.
