### ISSUE TITLE
Reolink RLC-520

### ISSUE THREAD

**Issue by gitbeg** [AlexxIT/WebRTC#85]
Hi,
thanks for this beautiful project.
How can I use this component with Reolink 520?
I tried creating a generic camera with rtsp URL for reolink, h264_Preview... but I can't stream fluent.

Tips?

Thanks so much

**Comment by AlexxIT** [comment]
All tips in FAQ

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc
