### ISSUE TITLE
EZVIZ URL and Type confirmation

### ISSUE THREAD

**Issue by MrTheoW** [AlexxIT/WebRTC#86]
I would like to confirm it works with the following 3 cameras.

- C3WN
- C3W
- C6T (RF Edition)

I'm also using a bit more simple url to show the stream.
**/h264_stream**
rtsp://admin:[Verification Code]@IP.ADDR.ESS:554/h264_stream

`
type: custom:webrtc-camera
url: rtsp://admin:EIDUFV@192.168.1.111:554/h264_stream

`

**Comment by MessieAss** [comment]
MrTheoW : Thanks a lot! This was the information i was looking for. EZVIZ isn't too generous with information about the technical shenanigans. Runs wonderfully!
Any idea if / how i can shorten the 30 second delay in live stream?
:+1:

**Comment by MrTheoW** [comment]
To be honest I must say that I'm using a different approach now. I've got a nice little server that runs Proxmox. On that I've installed a Ubuntu setup with Docker and a container that runs Frigate that also contains object / person recognition. To get the videostream inside my Home Assistant I'm currently using MotionEye. I was having some rebuffering issues with WebRTC that I just couldn't solve. (Probably due to misconfiguration) Once my eye infection is over and I can see properly again I will go and reconfigure it to WebRTC because it's way faster.

**Comment by giosud** [comment]
Hi, i'm using a Ezviz C3W cam but i can't integrate it on WebRtc.
I tried many kinds of urls but no one seems to work.
rtsp://admin:XXXXXXXXXXXXXX@192.168.1.7:554/h264_stream
rtsp://admin:XXXXXXXXXXXXXX@192.168.1.7:554/h264
rtsp://admin:XXXXXXXXXXXXXX@192.168.1.7:554/h.264
rtsp://admin:XXXXXXXXXXXXXX@192.168.1.7:554/h.265
and many others

![c3w](https://user-images.githubusercontent.com/82643347/155946986-e39a5378-1b4e-4fda-9c06-9d2b1b4ed5f7.PNG)

Can anyone help me?
Thanks.
Giorgio

**Comment by MrTheoW** [comment]
I am using the lines described below and that works for me.
On the settings page of the EZVIZ App the Image Encryption is even on so maybe there are some network issues.

Although I must say I do often see the same error message passing by every now and then. It does solves itself after a refresh most of the time. Check if you can enter full screen mode and see if the error still pops up.

```
type: custom:webrtc-camera
url: rtsp://admin:PasswordLocatedOnTheDevice@10.0.0.242:554/h264_stream
```

**Comment by giosud** [comment]
Are you using the last version of WebRtc integration (v. 2.2.0)? 
Did you update the c3w firmware to the last version available (V5.2.7 build 210721)?  

I tried to show this cam by entity pictures card but with no success, but my C6N cam is shown both in webrtc and pictures card. The difference is codec version: C6N -> H.264; C3W -> H.265.

**Comment by MrTheoW** [comment]
Currently running:

- WebRTC Camera v2.2.0
- C3W (CS-CV310-A0-3C2WFRL) V5.2.7 build 210721

Like I mentioned above I used the custom intergration from HACS and did not try a entity picture card.
Do you get an image with VLC using the provided url?

**Comment by giosud** [comment]
>Do you get an image with VLC using the provided url?
Yes, every url i try, it is shown with VLC

**Comment by giosud** [comment]
> Do you see the demo video that is predefined when you add the custom card? 

Yes

> You could always do a reinstall of the HACS Intergration.

I tried it :(

**Comment by NeillHerbst** [comment]
@giosud were you able to fix the problem? 
I also have the exact same issue.

**Comment by giosud** [comment]
Hi @NeillHerbst. Yes i did.
The problem is that C3W uses H265 stream whitch is not supported by HA. It is possible change default and use H264, supported by HA, by Ezviz Studio software that you can download from Ezviz's website and then follow instructions shown in the attached files.

[How to visit the advanced setting of Ezviz Studio_1.pdf](https://github.com/AlexxIT/WebRTC/files/8230131/How.to.visit.the.advanced.setting.of.Ezviz.Studio_1.pdf)
![settings on studio](https://user-images.githubusercontent.com/82643347/157826344-2148db70-9d0e-443f-9e3a-185d88e02da2.png)

**Comment by NeillHerbst** [comment]
Thanks it worked perfectly

**Comment by AlexxIT** [comment]
Thanks for info!
