### ISSUE TITLE
Unable to maximize WebRTC streams in lovelace

### ISSUE THREAD

**Issue by HITChris** [AlexxIT/WebRTC#87]
Worked fine prior to the latest release. HA error -

![a](https://user-images.githubusercontent.com/34664460/121421269-9bd6e900-c933-11eb-80bf-69ce62e711e7.PNG)

**Comment by maxcanna** [comment]
Duplicate of #84

**Comment by Zagor4** [comment]
I have the same problem !

**Comment by maxcanna** [comment]
> I have the same problem !

please @Zagor4 avoid to answer with "me too". Just +1 the OP so the maintainer can know it affects multiple people 🙂

**Comment by Zagor4** [comment]
> > I have the same problem !
> 
> please @Zagor4 avoid to answer with "me too". Just +1 the OP so the maintainer can know it affects multiple people 🙂

Sorry... :(
What i have to do, to put +1 ?

**Comment by maxcanna** [comment]
> Sorry... :(
> What i have to do, to put +1 ?

No worries, just put a 👍🏻  reaction as you just did. But in the original issue since this is even a duplicate 😉

**Comment by AlexxIT** [comment]
Thanks @idoaflalo! Fixed in latest release
