### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by Yamaha0014** [AlexxIT/WebRTC#94]
Hi 
I have this error in log HA
Stream camera working ok in web site and ios, all is ok, but in log is this error?
Is it possible repair this?
Logger: frontend.js.latest.202106030
Source: components/system_log/__init__.py:190
First occurred: 15:41:50 (31 occurrences)
Last logged: 15:41:59

https://zzzzzzz.duckdns.org/webrtc/webrtc-camera.js?v2.0.2:88:0 InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable

**Comment by hellcry37** [comment]
same for me but mine was 1800 times :)

**Comment by midnight1979** [comment]
Logger: frontend.js.latest.202107070
Source: components/system_log/__init__.py:190
First occurred: 21 июля 2021 г., 11:52:21 (62808 occurrences)
Last logged: 0:26:42

http://192.168.0.97:8123/webrtc/webrtc-camera.js?v2.0.2:88:34 Uncaught QuotaExceededError: Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.
http://forahass.webrelay.io/webrtc/webrtc-camera.js?v2.0.2:88:34 Uncaught InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.

**Comment by Xaket** [comment]
2021-08-22 07:32:10 ERROR (MainThread) [frontend.js.latest.202108090] https://ha.hellohome.keenetic.link/webrtc/webrtc-camera.js?v2.0.2:88:0 InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable

**Comment by xekil** [comment]
hello, same error

**Comment by conorlap** [comment]
Same issue here

**Comment by Yamaha0014** [comment]
> Same issue here

no, I have still errors in my HA

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc

**Comment by AlexxIT** [comment]
Should be fixed in v3
