### ISSUE TITLE
Fullscreen doesn't work with Chrome 

### ISSUE THREAD

**Issue by smmoroz** [AlexxIT/WebRTC#95]
Hi, AlexxIT,

First of all, thanks for your great job with this component. 

Fullscreen doesn't work for me with Chrome browser. Here is the error I have:

```
webrtc-camera.js?v2.0.2:257 Uncaught TypeError: this.requestFullScreen is not a function
    at HTMLElement.fullscreen.onclick (webrtc-camera.js?v2.0.2:257)
fullscreen.onclick @ webrtc-camera.js?v2.0.2:257
```
![image](https://user-images.githubusercontent.com/64163706/122059771-a5f65d00-cdf5-11eb-896b-1244b8ffb43e.png)

I'm ready to help debugging it further.

**Comment by sansillusion** [comment]
same issue here, also does not work in android app and firefox.

http://192.168.1.193:8123/webrtc/webrtc-camera.js?v2.0.2:257:56 Uncaught TypeError: this.requestFullScreen is not a function

**Comment by smmoroz** [comment]
Thanks @idoaflalo. I didn't find similar issues. If needed, I can close this issue.

**Comment by AlexxIT** [comment]
Thanks @idoaflalo. Fixed in latest release
