### ISSUE TITLE
No Cards on the list 

### ISSUE THREAD

**Issue by BobslejSmart** [AlexxIT/WebRTC#96]
I don't see card on teh list cards.
Ofcourse i restarted HA and add manually file to resources and still i don't see card.
I tried add in xml Type and url from example bunny and i  have information about invalid type.
![2021-06-18 16_51_41-](https://user-images.githubusercontent.com/82237489/122580012-cde3fb80-d055-11eb-90e8-41510c63d0bc.png)

Of course i have instled integration on Hacs and integration in HA

**Comment by AlexxIT** [comment]
Install from HACS. Add to integrations. Clear browser cache
