### ISSUE TITLE
Uncaught QuotaExceededError in logs

### ISSUE THREAD

**Issue by marcob79** [AlexxIT/WebRTC#98]
Plugin version 2.2.1

Logger: frontend.js.latest.202106030
Source: components/system_log/__init__.py:190
First occurred: 7:58:31 AM (58 occurrences)
Last logged: 7:58:41 AM

https://xxxxxxxxxcc.duckdns.org:8123/webrtc/webrtc-camera.js?v2.0.2:88:34 Uncaught QuotaExceededError: Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.

**Comment by johntdyer** [comment]
I am seeing this too

**Comment by rover1955** [comment]
I am seeing something very similar.
https://xxxxxx.duckdns.org/webrtc/webrtc-camera.js?v2.0.2:88:34 Uncaught InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.

It shows up  thousands of times.

**Comment by AlexxIT** [comment]
This problem may be fixed in latest master version

**Comment by olylak** [comment]
I'm facing the same issue.

2021-09-14 12:02:15 ERROR (MainThread) [frontend.js.latest.202108300] https://******************/webrtc/webrtc-camera.js?v2.0.2:88:34 Uncaught QuotaExceededError: Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is ful

Any updates on that?

Thanks.

**Comment by AlexxIT** [comment]
Fix still present in master version

**Comment by trancer86** [comment]
Can anyone trace where this error comes from and whether it can be fixed plss😦

 Logger: frontend.js.latest.202108300 Source: components / system_log / __ init__.py:190 First occurred: 17 September 2021, 11:11:56 pm (3 occurrences) Last logged: 7:34:57 h. https: //*************.duckdns.org/lovelace/0: 0: 0 Uncaught 

Version core-2021.9.6
 Installation Type Home Assistant OS Development false 
Supervisor true 
Docker true 
User root Virtual Environment false 
Python Version 3.9.6 
Operating System Family Linux
 Operating System Version 5.10.62 CPU Architecture x86_64 
Timezone Europe / Sofia

**Comment by dermotduffy** [comment]
As per [last update](https://github.com/AlexxIT/WebRTC/issues/98#issuecomment-919687564) this is already fixed.

**Comment by trancer86** [comment]
> As per [last update](https://github.com/AlexxIT/WebRTC/issues/98#issuecomment-919687564) this is already fixed (just not released).

Thank you for the quick answer! 🙂🍻

**Comment by marcob79** [comment]
Any draft plan for the release of the fix?
Thanks

**Comment by DT00689** [comment]
Any update on the release?

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc

**Comment by marcob79** [comment]
Thanks for your feedback. 
Surely i'll have a try by migrating my configuration to this new project. 
I'll keep you posted

**Comment by AlexxIT** [comment]
Should be fixed in v3
