### ISSUE TITLE
Implement PTZ into yicam?

### ISSUE THREAD

**Issue by ranrinc** [AlexxIT/WebRTC#99]
Does anyone have help on lovelace PTZ implementation for YiCam that supports PTZ? Thanks

**Comment by olijouve** [comment]
Does your cam integration provide PTZ services through HomeAssistant ?
If the answer is yes the follow webRTC doc about ptz and adapt it with the real name/parameters of ptz service.
If not, then your stucked.

**Comment by ranrinc** [comment]
> Does your cam integration provide PTZ services through HomeAssistant ?
> If the answer is yes the follow webRTC doc about ptz and adapt it with the real name/parameters of ptz service.
> If not, then your stucked.

yeah.. I got that part.. but since my PTZ only has zoom and focus only.. Can I only show 4 buttons for zoom and focus only?

**Comment by AlexxIT** [comment]
Duplicate #101
